### ISSUE TITLE
Does this support video + sound with WebRTC?

### ISSUE THREAD

**Issue by albinekb** [oney/react-native-webrtc#1]
Sorry for this question, i want to use this in a project :+1:

**Comment by oney** [comment]
Yes, it does.
Please try the demo https://github.com/oney/RCTWebRTCDemo, and you can see how it works. Please tell me if you have any question.

**Comment by albinekb** [comment]
@oney, cool testing now! Does it work on iOS9? Arm64 support? (needed for appstore)

**Comment by oney** [comment]
Yes, I have used it in my app, and it is in App Store.

**Comment by albinekb** [comment]
Awesome! Demo works fine. Just needed to change the three linked files
![image](https://cloud.githubusercontent.com/assets/5027156/10158868/00da1000-6695-11e5-80a0-d8ecc90fbc61.png)
to .dylib version!

**Comment by oney** [comment]
Cool! So, I am wondering why did it need to change to dylib in your computer? Because of iOS or Xcode version?

**Comment by albinekb** [comment]
I don't know, it didn't find the other files. So changing them to dylib was the only solution i could find

**Comment by oney** [comment]
OK, I figure it out. It should be related to Xcode 7. Thank you for this info. I close it now.
