### ISSUE TITLE
Connecting with Kurento and debugging black screen issue.

### ISSUE THREAD

**Issue by sbaar** [oney/react-native-webrtc#100]
We've been converting the js in the demo project to send the semantics that the kurento media server is expecting, and have gotten to the point where we can observe from the browser two iphones both connect to a group call and transmit audio and video. However, we are having no luck displaying the RTCView and seeing video. Some of the time it is a black screen, and other times it is not rendered at all (can still see container background). There is no audio either. We are using 0.8.0.

onaddstream is being called on both the self peer connection and the other peer connection and streams are being added to the remotelist and RCTview is being rendered sometimes. (The goal is not to have loopback, but not adding ourselves to the remotelist makes no difference). 

In xcode RTCSetMinDebugLogLevel(kRTCLoggingSeverityInfo) or verbose prints out many logs with no obvious errors. Based on the logs and network monitor tab of xcode we are fairly, but not entirely sure that we are receiving data for the streams. RTCVideoManager.m seems to be working properly when stepping through it.

At this point we are unsure what direction to take to narrow down or diagnose the problem, or at which layer of the stack the problem could be. Any help or ideas would be appreciated.

**Comment by zxcpoiu** [comment]
have you successfully run demo app on both iphones which you have problems?

as my understanding, kurento acts like a b2bua server, so it can do whatever they want with the media stream, include transcoding/mixing and so on.

I think the first thing you should do is to verify:

**does the problem occurs only when media server involved?**
**or it occurs even when peer to peer call?**

keep factors as less as possible

**Comment by sbaar** [comment]
Before setting our app up with kurento, using the example heroku page one phone was able to stream and receive from browser page, yes. We were also able to get two phones communicating using the sample app itself.

The changes we had to make for kurento were all the socket.send(). I needed to use WebSocket directly and change the semantics of the json sent to the server. Basically translating the signaling server messsages to the ones used [in these two js files](https://github.com/Kurento/kurento-tutorial-java/tree/master/kurento-group-call/src/main/resources/static/js)

**Comment by sbaar** [comment]
We haven't had any luck today. We're going to investigate differences in control flow based on the fact that we're making a group call and pulling video from the server rather than just using the server for signaling. Has anyone used this library for something like that?

**Comment by zxcpoiu** [comment]
sorry, I don't have any experiences with kurento.
It seems more like a integration issue.

you may try to eliminate factors like:

1. force kurento use OPUS only
2. or set it to passthrough only ( do not let it involved with transcoding )
3. make sure RTP connection established on both of your clients.
4. investigate RTP packets if needed

**Comment by sbaar** [comment]
1. We've confirmed that both offers/answers are using vp8/opus, so we don't think that the issue.
2. We're pretty sure it's not doing any transcoding, due to inspecting the sdps, and the fact that it's not supposed to.

We have narrowed down the symptom, but not the problem.

Our own peer connection that we send media through is working fine. However, in the peer connection to the other person, after sending/receiving ice, after about a minute it goes from checking to failed. This is curious, since it is connected to the server on another peer connection, so you'd think it would definitely be possible on peer connection 2.

So now we are trying to figure out why ice state is going to fail (ice gathering is completed in both connections), but we can't get any visibility on that. Could there be a conflict in our peer connections?  Changing the ios code createOffer to include the constraints OfferToReceiveAudio/Video doesn't help. We're working off of .8, but .9 didn't make a difference nor did applying patch PR #88 

Any ideas what to try next? We know it's possible on ios, since https://github.com/nubomediaTI/Kurento-iOS works.

**Comment by sbaar** [comment]
After some more experimenting we got it working with Kurento. It looks like it was a matter of not sending the messages in the right order. We're still having trouble with the ice connection state constantly flipping between completed and disconnected causing the video to be very unstable, but that is outside of the scope of the library.

**Comment by zxcpoiu** [comment]
thanks for updated!

**Comment by halilb** [comment]
Hi @sbaar!

I'm also trying to make this library work with Kurento, but having similar problems. Would sharing your solution possible? I'm stuck with black screens here :)

**Comment by sbaar** [comment]
I don't have access to that code anymore, unfortunately, sorry.

**Comment by davidperrenoud** [comment]
I also got Kurento working with react-native-webrtc. If I remember correctly the trick was to add the ice candidates after the SDP was received. Here is an extract from my code:

```js
onIceCandidate(pc: RTCPeerConnection, candidate: {}) {
    const iceCandidate = new RTCIceCandidate(candidate);

    if (pc) {
        pc.addIceCandidate(iceCandidate);
    }

    // We save the ice candidate for later when we receive the SDP
    this.iceCandidates.push(iceCandidate);
};

onSdpAnswer(pc: RTCPeerConnection, sdpAnswer: {}) {
    const sessionDescription = {
        type: 'answer',
        sdp: sdpAnswer
    };

    pc.setRemoteDescription(new RTCSessionDescription(sessionDescription), () => {
        // After receiving the SDP we add again the ice candidates, in case they were forgotten (bug)
        this.iceCandidates.forEach((iceCandidate) => {
            pc.addIceCandidate(iceCandidate);
        });
    }, this.onError);
};
```

So to debug be sure to print logs on each ICE candidate, SDP an ICE connection state change and check the order.

@halilb Would you also need a log of a successful connection? I have a Kurento server running where I could extract that.

**Comment by halilb** [comment]
Awesome! Thanks a lot @davidperrenoud. This looks like an answer to my problems.

I can also benefit from logs of a successful connection. Could you e-mail them to me? My e-mail address is on my profile.

**Comment by davidperrenoud** [comment]
@halilb Here is a log of our signalling implementation using socket.io. You can see in red that the ICE candidates (`receiveIceCandidate`) are received before and after the SDP answer (`receive`) which I don't think is normal:

![kurento-server-log](https://user-images.githubusercontent.com/639875/27649802-2653b60c-5c33-11e7-878e-0a953268bff8.png)

**Comment by jlameiro87** [comment]
I'm trying to use kurento with react-native-webrtc in order to record the video calls and later be able to see it, can anyone share the configuration to point react-native-webrtc to kurento server?

**Comment by xoapit** [comment]
Do you have any solutions @jlameiro87 ?

**Comment by davidperrenoud** [comment]
For reference, we changed our signalling server to send the SDP answer **before** any other ICE candidate is sent. This is cleaner than fixing it on the React Native side and it seems that most implementations expect this order, including Google Chrome.
![webrtc-complete-diagram](https://user-images.githubusercontent.com/639875/50895435-60542f80-1406-11e9-9f2c-f2db29ded22d.png)
[Source](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Connectivity#The_entire_exchange_in_a_complicated_diagram)

**Comment by alindzon** [comment]
so how would you fix group-call tutorial to do this?  I am experimenting with group-call and I am having inconsistent connection issues when adding the third or fourth user to a call.  When it fails the ice state goes from checking to disconnected.
