### ISSUE TITLE
Black screen at getUserMedia for subsequent video calls

### ISSUE THREAD

**Issue by mavenave** [oney/react-native-webrtc#101]
For the 1st time it works, however when you do `this.navigator.pop()` to exit away from the call, and rerender the RTCView, it shows a black screen for the local stream.

This is how I kill all local streams when componentWillUnmount is called

``` javascript
this.localStream.getTracks().forEach(track => track.stop());
this.localStream.release();
this.localStream = null;
```

I checked within getUserMedia, and the stream is there. Taking a closer look, it looks like the videoSource (internally, Android source) has changed?

**Comment by oney** [comment]
After you call `this.localStream.release();`, do you recreate localStream from getUserMedia?

**Comment by mavenave** [comment]
Yes I call `getUserMedia` every time in `componentDidMount` which is called when the scene is rendered.

**Comment by mavenave** [comment]
@oney I can confirm that there is a bug for subsequent `VideoCapturerAndroid.create`. https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L517-522 An error message `Camera can not be started.` will be printed out.

You can reproduce it by popping away from a route and going back to it.

**Comment by mobileDevNativeCross** [comment]
+1 Switching doesn't work

**Comment by kononenko-a-m** [comment]
does anyone checked this bug with https://github.com/pristineio/webrtc-build-scripts ?
I mean twice get the stream, and checks if it's corrupted after second try?

**Comment by pmachowski** [comment]
I experience the same bug on iOS. Is someone working on it?

**Comment by zxcpoiu** [comment]
folks, please try #123 to see if it works.

**Comment by dev-hamid** [comment]
+1

**Comment by saghul** [comment]
A lot has changed since the original report, so I'm closing this. Please open a new issue with as many details as possible if you are still seeing this.
