### ISSUE TITLE
upgrade webrtc library to latest stable release 51/52

### ISSUE THREAD

**Issue by zxcpoiu** [oney/react-native-webrtc#103]
track this with a new issue.

folks, I created a branch `upgrade-webrtc-51` which upgraded webrtc core library to correspond release version 51 branch.

I only tested simple audio part and it looks fine without any slow problems on android.

Since I don't have enough time to test whole stuffs like video or data channel yet, I wish someone whi have problems on the old library can git it a try to see if it solves your problem or makes PR to that branch.

once the branch have been fully tested, we can merge it into the master branch.

for version related discussions, see #79 
cheers

**Comment by zxcpoiu** [comment]
51 branch revision is 12700 ( Stable )
52 branch revision is 13039 ( Beta )

**Comment by zxcpoiu** [comment]
**NOTE:**

I have some problems when uploading large library files several times. ( seems my ip get blocked for a while)

thus, in these two new branch 51 and 52, I stored library files on [Git Large File Storage (LFS)](https://git-lfs.github.com/). I'm not sure but if you have problems when clone branch, try install `git-lfs` first, it has a handy command for installation on website.

**Comment by sbaar** [comment]
The only problem with lfs is that npm does not currently support it, so I can't specify a lfs repo as a package.json dependency. I'll just try to merge the 52 branch into my fork and remove lfs manually.

**Comment by zxcpoiu** [comment]
ah, forgot to mentioned. my bad.

you can just specify `install from github` by change your `package.json` like: 

`"react-native-webrtc": "git+https://git@github.com/oney/react-native-webrtc.git#upgrade-webrtc-52"`

or you can clone this repo, said, to the previous level of your project's directory ( `../react-native-webrtc` ), and manually checkout `react-native-webrtc` to the branch you want, then edit your project's `package.json` to:

`"react-native-webrtc": "file:../react-native-webrtc"`

finally, `npm install` will install the branch you specified

**Comment by sbaar** [comment]
Hm, I was doing that for a fork but running into git lfs issues I just removed lfs and it worked fine. I'll try that tomorrow. In any case, 52 works fantastically. It dropped the ICE connection time from 30-60 seconds to 5-10 seconds.

**Comment by mobileDevNativeCross** [comment]
@zxcpoiu thanks for your work!
 does this version fixed bugs with camera switching and black screen?

**Comment by zxcpoiu** [comment]
@mobileDevNativeCross

I'm not sure, my use case only involved audio for now, totally no idea with video. :scream: 
That's why I invited you guys to test on newer version of webrtc to see if it fixed or improved.

**Comment by zxcpoiu** [comment]
0.10.0 released with branch 52 stable.
It seems not differences between beta and stable, but just in case, I still recompiled again and including it in master.
