### ISSUE TITLE
Demo application not working in iPhone 6 + iOS version 9.3.3

### ISSUE THREAD

**Issue by reformer** [oney/react-native-webrtc#105]
Hi,
I run your demo code on iPhone 6s Plus with Firefox browser but remote video doesn't show both side. I debug code but not found any difference between iPhone 5s (Same thing working with iPhone 5s) and iPhone 6s plus with firefox.

**Comment by zxcpoiu** [comment]
Are you on master branch? If so, try branch 51 or branch 52 first.
If I recall it correctly, the older version of webrtc has some incompatible issues on arm64 devices.

**Comment by zxcpoiu** [comment]
My experiences are, some of my iphone works and some have problems --- but they are all have the same iOS version with same device modal. very strange. still debugging.

**Comment by jakkra** [comment]
Any news on this issue?

**Comment by zxcpoiu** [comment]
It may related #35 
you may want to check my observation:

https://github.com/oney/react-native-webrtc/issues/35#issuecomment-236424076
https://github.com/oney/react-native-webrtc/issues/35#issuecomment-237201028

please let me know if you find any solutions

**Comment by saghul** [comment]
No follow-up, closing.
