### ISSUE TITLE
run-ios broken?

### ISSUE THREAD

**Issue by Qard** [oney/react-native-webrtc#106]
After following the install directions, I now seem to only be able to build the project in XCode. If I try to run with `react-native run-ios` I get this:

https://gist.github.com/Qard/ba38733f5abbc678cfaf5f1061166646

**Comment by zxcpoiu** [comment]
I'm not sure but by a quick glance, it is more like a react-native/environment issue rather than webrtc.

which messages in your log indicating it's a webrtc's problem ?

**Comment by Qard** [comment]
It worked fine before I tried to install react-native-webrtc. I did exactly what the instructions said, and now it's broken. Something in that install process broke it. I'm guessing some sort of library conflict, but I'm not really sure yet.

**Comment by zxcpoiu** [comment]
I would suggest to fallback to previous version ( either react-native or webrtc ), do the process again to see if it works and try to spot which versions/part it occurs.
