### ISSUE TITLE
Any way to control sound output target?

### ISSUE THREAD

**Issue by Qard** [oney/react-native-webrtc#107]
My Android phone seems to output sound from the larger speaker, rather than the headset speaker, while my iPhone does the opposite.

I'd like to be able to do *both* programmatically somehow. I had a quick look at the code and it seems like streamURL is currently the only property accepted by RTCView, unless I'm missing something.

**Comment by zxcpoiu** [comment]
use [react-native-incall-manager](https://github.com/zxcpoiu/react-native-incall-manager) for audio control.
we split into a different module because audio control is another complex stuff.
