### ISSUE TITLE
data channel support

### ISSUE THREAD

**Issue by benoitc** [oney/react-native-webrtc#11]
When it's planned the data channel support? Is there any other lib that could allow it?

**Comment by oney** [comment]
What device do you want to use on? iOS or Android? And what feature do you want to implement?

**Comment by benoitc** [comment]
I don't follow. I'm just asking if the [webrtc datachannesl](http://www.html5rocks.com/en/tutorials/webrtc/datachannels/) support is planned. Obviously for all but it all depends on your timeline. I need it to do a true P2P exchange between apps and browsers instead of relying on websockets.

**Comment by oney** [comment]
Got it. I only use audio and video communication in my project. I think this module should support data channel, but I don't have time to do it now.

**Comment by bnolan** [comment]
What would be involved in adding data channel support? I'd be interesting in using it also.

**Comment by philikon** [comment]
I'm working on this, will have a PR ready today or tomorrow.
