### ISSUE TITLE
libjingle_peerconnection.so.jar is corrupted

### ISSUE THREAD

**Issue by kononenko-a-m** [oney/react-native-webrtc#112]
Hello,

Try to run an app with webrtc, but build process fails with following messages:

```
error: error reading /Users/Peter/work/evisit-mobile-app/android/app/build/intermediates/exploded-aar/EVisit/WebRTCModule/unspecified/jars/libs/libjingle_peerconnection.so.jar; error in opening zip file
error: error reading /Users/Peter/work/evisit-mobile-app/android/app/build/intermediates/exploded-aar/EVisit/WebRTCModule/unspecified/jars/libs/libjingle_peerconnection.so.jar; error in opening zip file
```

I did configuration exactly how it described in install section.

Do you have any idea why files are corrupted, and how it can be fixed?

Thanks!

**Comment by zxcpoiu** [comment]
1. please install `git lfs` follow the instruction in README.
2. `rm -rf node_modules/react-native-webrtc`
3. `npm install react-nattive-webrtc`
4. check binaries in `node_modules/react-native-webrtc` had been actually downloaded. ( should more than 10 mb on android, 7x mb on iOS )

**Comment by zxcpoiu** [comment]
let me know if it works for you

**Comment by kononenko-a-m** [comment]
it works now, thanks!
