### ISSUE TITLE
Issue installing (RN 0.31)

### ISSUE THREAD

**Issue by vinalys** [oney/react-native-webrtc#113]
Hello,

I am reporting this here as I am unsure whether this is a bug or if I am doing something wrong: I am using iOS with RN 0.31 at this time and tried the steps to install the library.
However at compilation of the project I do get a few errors generated on the file RTCVideoViewManager.m:

> `Implicit declaration of function objc_getAssociatedObject`
> `Declaration of objc_getAssociatedObject must be imported from module ObjectiveC.runtime before it is required`
> `Conflicting types for objc_getAssociatedObject`

And the same for objc_setAssociatedObject.

The first time I went a bit fast assuming a rnpm link would do, then I actually tested again following strictly the steps to ensure all was made correctly.

I tried however the demo provided and it worked fine (I noticed however the setup of the project may be slightly different).

One more note: In the installation steps, there is a screenshot showing the libWebRTC.a added onto the Link Binary with Libraries but the step above does not mention to add it. Should it be added or not (it does not however change the issue I am facing)?

If anyone ever faced this issue or got some clue on what I may be missing during my setup could you provide me with some hints?
Or if this is an actual open issue with RN 0.31 please let me know.

**Comment by vinalys** [comment]
FYI I did fix this issue by adding an import on top of the RTCVideoViewManager.m file
`#import <objc/runtime.h>`

It does compile from there and I can have the video streams working properly.

**Comment by zxcpoiu** [comment]
nice job, thanks!
I'm not using  RN31 yet, will look into it while I'm at it.

**Comment by zxcpoiu** [comment]
thanks @vinalys @ianlin

**Comment by vinalys** [comment]
Thanks for the fix @ianlin and release @zxcpoiu !

**Comment by MicronXD** [comment]
Can anyone confirm that it works on Android? I'm also running RN31, but when I followed the instructions in AndroidInstallation.md, I got the following errors:

```
micronxd$ react-native run-android
JS server already running.
Running /Users/micronxd/Library/Android/sdk/platform-tools/adb reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/micronxd/GitHub/MyApp/android/build.gradle' line: 14

* What went wrong:
A problem occurred evaluating root project 'MyApp'.
> Could not find method compile() for arguments [project ':WebRTCModule'] on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@5e746d37.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.339 secs
```

Like @vinalys, I'm not totally sure if it's a bug or something I did wrong. I noticed the installation doc was 5 months old, so I think maybe there are other steps I should have taken to install.

**Comment by zxcpoiu** [comment]
@MicronXD 

Yeh, I can confirm it works on android with RN31, at least audio part.
the only difference after 0.10.0 is we are using git lfs for storing large library.
please fellows README or comments at https://github.com/oney/react-native-webrtc/issues/112#issuecomment-239620173 to see if it works.

**Comment by MicronXD** [comment]
Thanks for pointing me in the right direction! I'll report back with my findings.
