### ISSUE TITLE
One to Many - Media Servers

### ISSUE THREAD

**Issue by rainbowhat** [oney/react-native-webrtc#117]
Would anyone be able to advice how I can go about peer-to-server model (peer-to-media server-to-all other peers)
With perhaps XirSYS/TokBox? Possible?

**Comment by sbaar** [comment]
Try Kurento. Red5 also just came out with a webrtc beta but i think you have to be a paying subscriber to use it.

**Comment by lyubomir** [comment]
You may want to look at the following projects of the Jitsi community:
1. https://github.com/jitsi/jitsi-meet-react

A React Native/mobile app which is in its early stages of development, yet allows one to join multiparty conferences.

2. https://github.com/jitsi/jitsi-videobridge

The media router/SFU which does the magic of routing video to multiple participants.

3. https://github.com/jitsi/jitsi-meet

The mature Web counterpart of https://github.com/jitsi/jitsi-meet-react. (The former predates the latter by years.) Both 1. and 3. use https://github.com/jitsi/lib-jitsi-meet.

**Comment by atyenoria** [comment]
Janus gateway works well with this. I made a simple example https://github.com/atyenoria/react-native-janus-webrtc-video-chat
