### ISSUE TITLE
web-rtc demo project is not working in android

### ISSUE THREAD

**Issue by shaikhussian** [oney/react-native-webrtc#118]
Hai, i tried the demo project which where there in documentation, It was working fine in IOS but the problem is with Android, I already posted an issue for this in demo project repo, Please give me suggestion that how can i solve this problem, Here is the issue link of demo Project
https://github.com/oney/RCTWebRTCDemo/issues/24, Any one please help me

**Comment by zxcpoiu** [comment]
tracked at https://github.com/oney/RCTWebRTCDemo/issues/24
