### ISSUE TITLE
merge with jitsi forked

### ISSUE THREAD

**Issue by zxcpoiu** [oney/react-native-webrtc#122]
@lyubomir @oney 

I think it didn't make any scene to have separate repositories does the same thing.
It's a good idea to have this repostory merged:  https://github.com/jitsi/react-native-webrtc/

@lyubomir 

thanks for all your awesome works and point the commit specifically :+1: 

I'd like to merge it, but need your advise.

do you think is it a good idea that we merge/rebase from https://github.com/jitsi/react-native-webrtc/ master branch directly into this one and see if it work?

or is there any part may conflict I should know?

**Comment by zxcpoiu** [comment]
or should I merge branch `lib-jitsi-meet` ?

**Comment by oney** [comment]
@lyubomir Are you willing to be a collaborator of this repo? Let's merge jitsi/react-native-webrtc to oney/react-native-webrtc, and you can contribute code to this repo directly. Does it sound good to you?

**Comment by zxcpoiu** [comment]
Sounds like a extremely good idea to me :tada:

**Comment by zxcpoiu** [comment]
just created a PR #123 which directly merged from https://github.com/jitsi/react-native-webrtc/tree/lib-jitsi-meet

**Comment by lyubomir** [comment]
@zxcpoiu, yes, the branch lib-jitsi-meet is what I'd like to have merged into upstream. Thank you! (The master branch tracks the point in upstream's master at which the branch lib-jitsi-meet is forked.)

**Comment by oney** [comment]
@lyubomir I just invited you to join collaborators. Thanks for the contribution before and after.
