### ISSUE TITLE
getting an error like Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by shaikhussian** [oney/react-native-webrtc#124]
Hai, i followed the repo and installation step by step, I am getting an error like this while run in xcode please give me suggestions that how to resolve it
![fftyf](https://cloud.githubusercontent.com/assets/11956308/18027096/8dcedb92-6c77-11e6-81e3-6534a84a8bc6.png)

**Comment by shaikhussian** [comment]
@zxcpoiu please respond i am facing this error from last two days i added $(inherited) in other linker flags, But still facing the error, please give me suggestions that how to resolve it

**Comment by shaikhussian** [comment]
Please respond,give me suggestions that how to resolve it

**Comment by zxcpoiu** [comment]
I'm not always online, and not an expert neither, sorry about that.

I guess you should unlink all webrtc library on your xcode, and fellow instructions to get latest 0.10+ library. ( especially get it via git lsf )

a `Product` -> `Clean` may help.

**Comment by zxcpoiu** [comment]
when I encounter similar problems, I would try:

1. unlink all webrtc library on xcode
2. delete all `react-native-webrtc` folder in `node_module`
3. follow instructions to get webrtc lib via npm install and git lfs
4. a `Product` -> `Clean` in xcode may help.

**Comment by zxcpoiu** [comment]
please try #123 to see if it works.
