### ISSUE TITLE
Cannot render multiple RTCViews on Android

### ISSUE THREAD

**Issue by lyubomir** [oney/react-native-webrtc#126]
In React Native, the framework instructs react-native-webrtc in accord with the respective JSX to initialize a new RTCView which is a GLSurfaceView for an RTCMediaStream. In the Android WebRTC API, there's a single, static VideoRendererGui (i.e. a singleton) which works with a single GLSurfaceView and renders multiple RTCMediaStreams in different areas of the GLSurfaceView. Currently, RTCView works with VideoRendererGui disregarding its singleton nature. Consequently, it is not currently possible to render multiple RTCViews.

**Comment by lyubomir** [comment]
I personally see two approaches to dealing with this problem:

1. Have a single GLSurfaceView and render multiple RTCMediaStreams into it using org.webrtc.VideoRendererGui. The problem with this approach is that it's not clear where the GLSurfaceView should be "mounted" within the UI hierarchy of the app. In Google's examples, the app declares the GLSurfaceView in XML and then VideoRendererGui is initialized with that view retrieved by ID. But react-native-webrtc is a library so I don't feel immediately comfortable with the idea that the library should rely on the app creating the GLSurfaceView. Additionally, it's kind of tricky to determine the percent location and size of the "views" within that GLSufraceView where the respective RTCMediaStream is to be rendered.

2. Don't use org.webrtc.VideoRendererGui and, thus, have multiple GLSurfaceViews (RTCView extends GLSurfaceView). The problem with this approach is that we have to implement the rendering that org.webrtc.VideoRendererGui does.

**Comment by lyubomir** [comment]
The approach that I'll be trying out first is 2: copy org.webrtc.VideoRendererGui into com.oney.WebRTCModule.VideoRendererGui, remove the singleton nature of that and than use it to render multiple RTCViews.

**Comment by lyubomir** [comment]
Well... It was easy to remove the singleton nature of VideoRendererGui. Unfortunately, it doesn't look like I can reliably have multiple intersecting GLSurfaceViews drawing appropriately. I guess the tearing in the window that GLSurfaceView does is the reason why VideoRendererGui is a singleton. Approach 2 is a no-go then.

I'll think about approach 1 tomorrow. Having multiple WebRTCViews and a single GLSurfaceView sounds like needing considerable thought and substantial coding.

**Comment by zxcpoiu** [comment]
wow! what a valuable research! :+1: :100: 

Have you check the implementation of [openwebrtc](http://www.openwebrtc.org/)?
They ( [Ericsson Research](https://www.ericsson.com/research-blog/) ) follow the webrtc API spec closely but with a different implementation using `GStreamer`
you may have interest to look at: [openwebrtc github](https://github.com/EricssonResearch/openwebrtc/)

it's a shame that I couldn't help much here.

**Comment by lyubomir** [comment]
There's another approach:

3. Use org.webrtc.SurfaceViewRenderer instead of GLSurfaceView + VideoRendererGui. An advantage of this approach is that SurfaceViewRenderer is not limited to one View instance like VideoRendererGui. Among the disadvantages are that the implementation of SurfaceViewRenderer appears to not have very good logic related to layouts, has a deadlock fixed after v52.

**Comment by lyubomir** [comment]
Eventually, I ended up implementing the 3rd approach i.e. using SurfaceViewRenderer. Now multiple videos can be rendered (at the same time) and they can overlap (for a total of 3 layers which is a limitation of OpenGL). Additionally, I've implemented mirroring (commonly used for the user-facing camera) in RTCView on Android because CSS-based mirroring doesn't work with RTCView on Android (which works on iOS applied to a parent View). I just need to figure out the support for object-fit (cover and content like I did them on iOS).

**Comment by lyubomir** [comment]
This issue is fixed in https://github.com/jitsi/react-native-webrtc/commit/a5a469282b9f7cd040cfd570a8c4a8479c29b7f3. Once https://github.com/oney/react-native-webrtc/pull/123 is merged, I'll either create a PR for the specified commit or I'll push it into master myself. The following is the message of the specified commit:

VideoRendererGui is a singleton and, consequently, multiple RTCViews
would not render. Implements RTCView using SurfaceViewRenderer instead
in order to render multiple RTCView at a time.

Introduces zOrder in RTCView in order to allow control over how multiple
RTCViews overlap.

Introduces mirror in RTCView in order to allow control over whether
RTCView mirrors the video it renders. Commonly used for the user-facing
camera.

Implements objectFit in RTCView in order to allow control how the video
is displayed in the rectangle of RTCView while preserving the aspect
ratio. The feature was previously implemented on iOS.

**Comment by zxcpoiu** [comment]
excellent!

I had manually added https://github.com/jitsi/react-native-webrtc/commit/a5a469282b9f7cd040cfd570a8c4a8479c29b7f3 to #123 and get it merged.

it is really a huge improvement, big thanks to @lyubomir
