### ISSUE TITLE
undefined is not an object(evaluating 'container.setState')

### ISSUE THREAD

**Issue by shaikhussian** [oney/react-native-webrtc#128]
Hai, I run your demo project,and check in device it working fine, But in index.ios.js, i added the some code for navigator, added some form code init.when click on signIn button i want to show the webRtc screen for that screen i just copied the main.js file code in RTcWebdemo project and added in my code, here is my code
**index.ios.js**

```
if (!window.navigator.userAgent) {
  window.navigator.userAgent = "react-native";
}
'use strict';
import React,{Component} from 'react';
var SignIn = require('./SignIn');
import {
  AppRegistry,
  StyleSheet,
  Navigator,
  AsyncStorage,
} from 'react-native';
class RCTWebRTCDemo extends Component {
  render() {
    return (
            <Navigator
                initialRoute={{
                  component:SignIn  //component declaration
                }}
                configureScene={(route) => ({
                  ...Navigator.SceneConfigs.HorizontalSwipeJump,
                  gestures: false
                })}
                renderScene={(route, navigator) =>{
                  return <route.component navigator={navigator} {...route.passProps} />;
                }}/>
        );
  }
};
```

**signIn.js**

```
onSignin(){
    this.props.navigator.push({
      component: main
    })
}
```

When click on signIn button of the below image calling the above function in main component i added the main.js file code
![simulator screen shot 31-aug-2016 3 09 28 pm1](https://cloud.githubusercontent.com/assets/11956308/18124263/1ee35cc4-6f8f-11e6-85af-9afa6dca54f0.jpg)

but when i run project before clicking on signIn button, It shows some error like this
![error](https://cloud.githubusercontent.com/assets/11956308/18124333/69278cd8-6f8f-11e6-842d-065473be5115.png)

please give me suggestions that how to resolve this

**Comment by zxcpoiu** [comment]
make sure you set `container = this` in the main `WebRTCDEMO Component`'s `ComponentDidMount`.

my suggestion would be:  try to understand demo `main.js` logic, and applied it in to your own logic.

**Comment by rohitgupta87410** [comment]
Hi  @shaikhussian  
I am also facing same issue . If u find the solution of this issue then please help me  to resolve this . 

Thanks

**Comment by davidperrenoud** [comment]
Would someone have the time to write the demo using `React.Component` instead of `React.createClass` and make it easier to understand? [The official examples from OpenWebRTC are pretty good.](https://github.com/EricssonResearch/openwebrtc-examples/blob/master/android/NativeCall/app/src/main/java/com/ericsson/research/owr/examples/nativecall/NativeCallExampleActivity.java)

**Comment by rohitgupta87410** [comment]
@davidperrenoud  
Have you worked on this . if yes then pls provide solution to above issue. 
Thanks

**Comment by davidperrenoud** [comment]
Yes, the easiest solution (not the best one) would be to build your app like the RCTWebRTCdemo with `React.createClass`:
https://github.com/oney/RCTWebRTCDemo/blob/master/main.js#L232

As @zxcpoiu said, you can then map the `container` variable to `this` in `componentDidMount`:
https://github.com/oney/RCTWebRTCDemo/blob/master/main.js#L247

(A prettier solution would be to put the sockets and WebRTC functions in two separate files and the `React.Component` in another file.)

**Comment by rohitgupta87410** [comment]
Yes, i did same .

"

Yes, the easiest solution (not the best one) would be to build your app
like the RCTWebRTCdemo with React.createClass:
https://github.com/oney/RCTWebRTCDemo/blob/master/main.js#L232

As @zxcpoiu <https://github.com/zxcpoiu> said, you can then map the
container variable to this in componentDidMount:
https://github.com/oney/RCTWebRTCDemo/blob/master/main.js#L247

"


but still getting same issue when i started app .

**Comment by zxcpoiu** [comment]
It simply means you did not set it correctly.
it's a JS/react-native coding syntax issue.

as @davidperrenoud
you may want to try export your component, maybe as a singleton, and manipulate it in another file ( your main app.js with main logic )

**Comment by swaroopa94** [comment]
Hi
I am also getting the same issue.
Please tell how to solve this one..

**Comment by rohitgupta87410** [comment]
Put your code "socket.on" into componantdidMount function .

**Comment by LoseTheQuit** [comment]
this is how I solved the problem: https://stackoverflow.com/questions/40109937/undefined-is-not-an-object-evaluating-container-setstate/40974201#40974201

**Comment by zxcpoiu** [comment]
thanks for the link @LoseTheQuit 

for anyone who interest in app structure, see #167 as well

**Comment by saghul** [comment]
Nothing actionable for the plugin itself, closing.
