### ISSUE TITLE
WebRTC v53

### ISSUE THREAD

**Issue by lyubomir** [oney/react-native-webrtc#129]
Now that Chrome 53 is in stable, update to WebRTC v53 because v52 has a known issue which crashes the library (and the respective app, of course) upon removal of MediaStream (e.g. the remote endpoint leaves the call).

**Comment by zxcpoiu** [comment]
I'm on it :smile:

**Comment by zxcpoiu** [comment]
finally, after a chaos  of build process...

anyway,
I had published `0.11.0` to npm including latest improvements from jitsi branch
and a 0.12.0 is a pre-release on master and not publish to npm yet, with latest webrtc 53 build

PR is #131
