### ISSUE TITLE
 Error setting property 'streamURL' of RTCVideoView

### ISSUE THREAD

**Issue by jcgertig** [oney/react-native-webrtc#13]
I just go this set up and started testing it but I am getting this msg any ideas?

```
[warn][tid:main][RCTUIManager.m:956] Error setting property 'streamURL' of RTCVideoView with tag #65: 
Exception thrown while executing UI block: -[RTCVideoTrack copyWithZone:]: unrecognized selector sent to instance 0x14e051050
```

**Comment by oney** [comment]
What React Native version are you testing?
Can you test [Demo project](https://github.com/oney/RCTWebRTCDemo) to see whether the same error happened?

**Comment by jcgertig** [comment]
I'm on 0.17.0. And I can try

**Comment by jcgertig** [comment]
I does not happen with the demo project I will test updating it to 0.17.0

**Comment by jcgertig** [comment]
Same issue once I updated the example

**Comment by jcgertig** [comment]
?

**Comment by jcgertig** [comment]
any progress?

**Comment by camwhite** [comment]
I'm seeing some strange behavior on latest version as well. Any update or help would be greatly appreciated, thanks.

**Comment by oney** [comment]
Sorry for the delay.

I have tested demo project with RN 0.17.0 and react-native-webrtc 0.2.7 on iOS on real device. No error happened.
@jcgertig Are you sure the issue happens on demo project? Please make sure to update demo project and test it.

**Comment by oney** [comment]
The problem happen when the app just launch? Or when connect to other peer?

**Comment by camwhite** [comment]
@oney I'm seeing this when attempting to set the `streamURL` prop on RTCView component.

Also maybe you could provide some insight on why I'm able to connect to my socket server when running in the simulator on `localhost`, but not on my iOS device. I **have** pointed the socket.io `connect()` method towards my machines LAN IP address..

**Comment by jcgertig** [comment]
I am using ngrok @camwhite to tunnel my local server and it allows connection to be made

**Comment by oney** [comment]
@camwhite Did you try setting streamURL to RTCView on device and the error still happened?

**Comment by camwhite** [comment]
@oney yea I did.. Like i mentioned the stream object only contains `_streamId: 0`. Should I expect to see something different?

Thanks! @jcgertig I hadn't thought of that :+1:

**Comment by camwhite** [comment]
Honestly what I really like to do is be able to use [react-native-video](https://github.com/brentvatne/react-native-video) and send the `stream.toURL()` into the source prop.

**Comment by jcgertig** [comment]
I could really get behind that idea @camwhite

**Comment by jcgertig** [comment]
No configuration needed really download [ngrok](https://ngrok.com/) and run it like so

**Comment by jcgertig** [comment]
if you don't know thats `App Transport Security Settings` -> `Exception Domains` in the `Info.plist` needs to be a dictionary with `NSIncludesSubdomains` : Yes, `NSTemporaryExceptionAllowsInsecureHTTPLoads' : Yes, `NSThirdPartyExceptionRequiresForwardSecrecy` : No

**Comment by camwhite** [comment]
Dude @jcgertig thanks so much!

Would you like to spend some time trying to debug the issue at hand? I'm curious what your code looks like and also what the stream object contains for you.

In my case `stream.toURL()` returns `0`

**Comment by oney** [comment]
It is totally correct that `stream` is `{ _streamId: 0}` and `stream.toURL()` is `0`.
We are not in real browser, so `stream` is not `MediaStream` of browser.
I don't think this module can work together with `react-native-video`. `stream` is mapped to `RTCMediaStream.h` in Objective-C, and there is no `RTCMediaStream.h` in  `react-native-video`.

**Comment by camwhite** [comment]
Ok got the local stream up and running it's was an error on my end, sigh.. Still having trouble getting an authenticated socket connection from my device.

@jcgertig I followed your guidance, but still have no luck either from the device or the simulator. Here's a screenshot of my configuration..

<img width="491" alt="screen shot 2016-01-28 at 1 37 10 pm" src="https://cloud.githubusercontent.com/assets/6933346/12654986/acd058a4-c5c4-11e5-9518-c37949bafc8c.png">

I'd be happy to lend you a hand getting your stream going if you could help me out here!

**Comment by jcgertig** [comment]
@camwhite Sorry could not get back to you. What version of ios are you building for? Im building for 9.2 may be thats where the error is?

**Comment by camwhite** [comment]
No worries @jcgertig I'm building 9.2 as well.. So I don't think that's your issue. What my problem was is I had a typo buried in my altjs store that was preventing the stream from being set on the state. 

I'd be down to share some code with you if you want to see how I've gotten the local video stream :100:

**Comment by jcgertig** [comment]
@camwhite that would be great

**Comment by camwhite** [comment]
Hope this helps @jcgertig 

```
// Import proper components
import WebRTC, {RTCView, RTCMediaStream} from 'react-native-webrtc';

// A method for for grabbing the stream 
getLocalStream() {
    let promise = new Promise((resolve, reject) => {
      navigator.getUserMedia({audio: true, video: true, videoType: 'front'}, (stream) => {
        resolve(stream);
      }, (err) => {
        reject(err);
      });
    });
    return promise;
}

componetDidMount() {
  this.getLocalStream().then((stream) => {
    // do something with stream
  });
}
 ```

I dispatch my stream into a store via an action once the promise is resolved. Also I don't render the `RTCView` unless `this.state.localStream != null`

**Comment by jcgertig** [comment]
I have something very similar :|

```
getLocalStream().then((stream) => {
      this.setState({ stream }, () => {
          join(this, this.state.roomID);
      });
});
```

**Comment by camwhite** [comment]
Could it be that you are rendering the `RTCView` before the stream has been resolved? Bc I was seeing the error while evaluating the prop `streamURL` with a null value..

**Comment by jcgertig** [comment]
```
local = stream !== null ? <RTCView style={styles.myVideoView} streamURL={stream.toURL()} /> : <View style={styles.myVideoView} ></View>;
```

**Comment by camwhite** [comment]
@jcgertig the stream would be on the state, no?

**Comment by jcgertig** [comment]
yes I have `let { stream } = this.state;` above that

**Comment by camwhite** [comment]
I see. I'm having a thought it may be due placing the stream object inside another object whilst setting it on the state. Try `this.setState(stream)` with no encapsulating object?

**Comment by jcgertig** [comment]
hmm i have more in the state then just that

**Comment by jcgertig** [comment]
I could make a wrapping component and try that

**Comment by camwhite** [comment]
Also I am calling `stream.toURL()` when setting it on the state not is the render method, maybe try that?

**Comment by camwhite** [comment]
And @jcgertig wouldn't you need a key like `this.setState({ stream: stream })`?
not `this.setState({ stream })`

**Comment by jcgertig** [comment]
I will try that

**Comment by jcgertig** [comment]
yeah it auto pulls out if you do `let { varName } = object;`

**Comment by jcgertig** [comment]
I got this working but now I get 
2016-02-25 15:18:13.576 Peep[436:40445] Failed to make complete framebuffer object 8cd6
2016-02-25 15:18:13.609 Peep[436:40445] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x13f8f9c10> to GL_RENDERBUFFER 1

**Comment by rbholeraj** [comment]
@jcgertig  yeah i facing same issue .. i write up my query on stackoverflow (http://stackoverflow.com/questions/36419884/failed-to-bind-eagldrawable-in-webrct-react-native) please let me know if anybody know about same.
