### ISSUE TITLE
Cannot git clone current HEAD 

### ISSUE THREAD

**Issue by inspiraluna** [oney/react-native-webrtc#132]
Hello, 

i just tried cloning with the following result: 

git clone https://github.com/oney/react-native-webrtc.git
Cloning into 'react-native-webrtc'...
remote: Counting objects: 1159, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 1159 (delta 16), reused 0 (delta 0), pack-reused 1119
Receiving objects: 100% (1159/1159), 38.36 MiB | 730.00 KiB/s, done.
Resolving deltas: 100% (548/548), done.
Checking connectivity... done.
git-lfs smudge 'android/libs/libjingle_peerconnection.so.jar': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: android/libs/libjingle_peerconnection.so.jar: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Is it just me or is there something wrong inside?

**Comment by zxcpoiu** [comment]
> git-lfs: command not found

have you install `git-lfs` locally?
if not, follow the readme in `prerequisite` section to install it first then try again

**Comment by inspiraluna** [comment]
Perdon! - was new to me!

**Comment by zxcpoiu** [comment]
no worries, all were new to me, too :smile:

**Comment by zxcpoiu** [comment]
`0.13.0` have get rid of annoying `git-lfs` already.
my bad for using `git-lfs` in it's so early stage.
