### ISSUE TITLE
Long delay on Android device

### ISSUE THREAD

**Issue by elad-softimize** [oney/react-native-webrtc#138]
Hi,
When running the demo and connecting to the demo server I get a really long delay (about 1.5 sec) in the video stream.
If I connect to the same room from a web browser on the same device I see the same stream with minimal delay.

Any idea how I can begin to understand this issue?

Thanks!

**Comment by zxcpoiu** [comment]
Do you mean:

1. `connection establishment time` delay
or
2. stream has a latency around 1.5 seconds compares to reality?

**Comment by elad-softimize** [comment]
Thanks for the reply.

The latency of the stream is 1.5 seconds compared to reality.
Both peers are connected to the same wifi network.

**Comment by zxcpoiu** [comment]
Hmm... I don't have any clues now. it needs tons of experiments and has tons of factors.
Does it occurs on some popular high-end devices as well?

**Comment by wumke** [comment]
I'm also seeing this issue in the android demo app of this project: the remote video seems to display delayed and slower than expected (when using (internal or external)stun- and (internal)turnserver).
The iOS version of the demo app displays both streams real time, no matter if connected by stun results or via turn server...

I've played with native WebRTC videocall apps between the same devices and there was no noticeable delay there. So I don't think mid-range devices are the problem.

**Comment by wumke** [comment]
@elad-softimize Take a look at [https://github.com/oney/react-native-webrtc/issues/267](https://github.com/oney/react-native-webrtc/issues/267) to resolve this issue.
I've modified the max constraints and both the delay and slow speed are good now!

**Comment by zxcpoiu** [comment]
You can not `fix` that due to the nature of p2p ice under different networks.
But you can `optimize` it with some trade off, for example, you can always include only TURN server's candidate in the sdp. ( just an example )

This is a complex issue and the answer depends on your use case, which point you care the most and the resources you have.
