### ISSUE TITLE
'RTCVideoView' has no propType for native prop 'RTCVideoView.onLayout' of native type 'boolean'

### ISSUE THREAD

**Issue by wmjbyatt** [oney/react-native-webrtc#14]
I'm getting the above error when I run the demo app, as well as when I try to re-implement a minor variation of the demo app as a component in an existing app.

This is with ReactNative 0.17.0.

Please let me know if providing any more information will help.

**Comment by oney** [comment]
Are you using on Android?

**Comment by wmjbyatt** [comment]
Yes I am.

I was able to resolve the issue by making the following change in `RTCView.js`:

```
...
var v = requireNativeComponent('RTCVideoView', RTCView, {nativeOnly: {
  ...
  onLayout: true // <= Added this line
}});
...
```

I don't really understand why that was necessary, though, so it feels rather ad hoc and I'd love to understand why that needed to be done or see a real fix.

**Comment by wmjbyatt** [comment]
Huh. I just saw the PR fixing this issue the same way. I guess I should have checked there first. My mistake.
