### ISSUE TITLE
Unsupported Architectures

### ISSUE THREAD

**Issue by besarthoxhaj** [oney/react-native-webrtc#141]
When I try to submit the bundle to the TestFlight I get this error.

```
[Transporter Error Output]: ERROR ITMS-90087: "Unsupported Architectures. The executable for NativeRTC.app/Frameworks/WebRTC.framework contains unsupported architectures '[x86_64, i386]'."
[13:44:54]: [Transporter Error Output]: ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'NativeRTC.app/Frameworks/WebRTC.framework/WebRTC' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
[13:44:54]: [Transporter Error Output]: ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
[13:44:54]: [Transporter Warning Output]: WARNING ITMS-90080: "The executable 'Payload/NativeRTC.app/Frameworks/WebRTC.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."
[13:44:55]: Transporter transfer failed.
[13:44:55]: WARNING ITMS-90080: "The executable 'Payload/NativeRTC.app/Frameworks/WebRTC.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."
```

I'm looking at this [stackoverflow question](http://stackoverflow.com/questions/30547283/submit-to-app-store-issues). Any help much appreciated :)

**Edit 1:**

As far as I can see **x86_64** architecture is for iPad simulators while **i386** is for iPhone simulators, both are 32 and 64bit compatible.

**Edit 2:**

[Here](http://stackoverflow.com/questions/26190693/xcode-6-01-archive-validation-error-invalid-segment-alignment) they talk about _Archive validation error: Invalid Segment Alignment_ and one of the answers refers to:

> In my case I was submitting an app that include a framework I had built that was a universal framework - created using lipo (for use with both device and simulator).
> 
> After replacing the universal compiled framework with device compiled framework, validation was successful.

**Edit 3:**

Using `lipo --info`, you can see `WebRTC.framework/WebRTC` have multiple architectures indeed `i386 x86_64 armv7 arm64`.

```
> lipo -info NativeRTC.xcarchive/Products/Applications/NativeRTC.app/Frameworks/WebRTC.framework/WebRTC
Architectures in the fat file: NativeRTC.xcarchive/Products/Applications/NativeRTC.app/Frameworks/WebRTC.framework/WebRTC are: i386 x86_64 armv7 arm64
```

**Edit 4.**

From [this article](http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/) looks like https://github.com/oney/react-native-webrtc/blob/master/ios/WebRTC.framework/WebRTC has been complied with `i386 x86_64 armv7 arm64` architectures. You can see it by cloning it and running `lipo -detailed_info ios/WebRTC.framework/WebRTC`.

I'm gonna try to remove `i386 x86_64`.

**Edit 5.**
Running:

```
cd node_modules/react-native-webrtc/ios/WebRTC.framework/
lipo -remove i386 WebRTC -o WebRTC && lipo -remove x86_64 WebRTC -o WebRTC
```

Solves the problem. I'm gonna test however if it still works on simulators.

**Edit 6.**
Nope! I get the following error:

```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_RTCConfiguration", referenced from:
      objc-class-ref in libRCTWebRTC.a(RCTConvert+WebRTC.o)
blabla
```

**Edit 7.**

So clearly there some issues, at least on my side. Is anyone experiencing the same problems?

**Edit 8.**

Apparently is an app store submission bug http://www.openradar.me/radar?id=6409498411401216

**Edit 9.**

I created this little script which helps me jump between architectures during dev and app store release.

``` js
'use strict';

const fs = require('fs');
const exec = require('child_process').execSync;

const WEBRTC_BIN_PATH = `${__dirname}/node_modules/react-native-webrtc/ios/WebRTC.framework`;
const ARCH_TYPES = ['i386','x86_64','armv7','arm64'];

if(process.argv[2] === '--extract' || process.argv[2] === '-e'){
  console.log(`Extracting...`);
  ARCH_TYPES.forEach(elm => {
    exec(`lipo -extract ${elm} WebRTC -o WebRTC-${elm}`,{cwd:WEBRTC_BIN_PATH});
  });
  exec('cp WebRTC WebRTC-all',{cwd:WEBRTC_BIN_PATH});
  console.log(exec('ls -ahl | grep WebRTC-',{cwd:WEBRTC_BIN_PATH}).toString().trim());
  console.log('Done!');
}

if(process.argv[2] === '--simulator' || process.argv[2] === '-s'){
  console.log(`Compiling simulator...`);
  exec(`lipo -o WebRTC -create WebRTC-x86_64 WebRTC-i386`,{cwd:WEBRTC_BIN_PATH});
  console.log(exec('ls -ahl | grep WebRTC',{cwd:WEBRTC_BIN_PATH}).toString().trim());
  console.log('Done!');
}

if(process.argv[2] === '--device' || process.argv[2] === '-d'){
  console.log(`Compiling device...`);
  exec(`lipo -o WebRTC -create WebRTC-armv7 WebRTC-arm64`,{cwd:WEBRTC_BIN_PATH});
  console.log(exec('ls -ahl | grep WebRTC',{cwd:WEBRTC_BIN_PATH}).toString().trim());
  console.log('Done!');
}
```

**Comment by aleclarson** [comment]
Did you follow [this guide](https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md) to a T?

I was having similar issues, and I think setting `Enable Bitcode` to `NO` will help you.

**Comment by besarthoxhaj** [comment]
@aleclarson thanks for you reply. Yes I did.

I set `Dead Code Stripping` to `No`` and `Enable Bitcode` to No, both on my main xcode project as well as in `RCTWebRTC.xcodeproj`. Still same problem.

However to avoid possible caching problem I will start a new brand project and let you know.

**Comment by jakkra** [comment]
The stackoverflow question you linked to solved it for me. I just followed the first answer.

**Comment by zxcpoiu** [comment]
make documents clearer in #174

**Comment by 8enmann** [comment]
I also had to use the stackoverflow script. Please add instructions to the readme!

**Comment by zxcpoiu** [comment]
@8enmann 

added in fcfa9d1bd3cc3178a88ec4e8588d8f900654704c
thanks

**Comment by 8enmann** [comment]
Thanks!

**Comment by davidperrenoud** [comment]
Even after doing `lipo -remove i386 WebRTC -o WebRTC && lipo -remove x86_64 WebRTC -o WebRTC`, my build is disappearing from TestFlight without any error or warning. Do you have a solution?

**Comment by bkonkle** [comment]
I was having this same issue, even after trying the script included here. (Thanks for that, though!) The tiny script in this post fixed the arch issue reliably without having to run anything manual, and resolved all of the other validation issues I was having (!!!): http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

Thanks for this library, by the way!

**Comment by anhtuank7c** [comment]
I have a question?

Where do i have to put your script?

Have problem with iOS 10.2

```

ld: warning: object file (/Users/anhtuank7c/Desktop/Live/ios/build/Build/Products/Debug-iphonesimulator/libRCTWebRTC.a(RTCVideoViewManager.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/anhtuank7c/Desktop/Live/ios/build/Build/Products/Debug-iphonesimulator/libRCTWebRTC.a(WebRTCModule.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/anhtuank7c/Desktop/Live/ios/build/Build/Products/Debug-iphonesimulator/libRCTWebRTC.a(WebRTCModule+RTCPeerConnection.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/anhtuank7c/Desktop/Live/ios/build/Build/Products/Debug-iphonesimulator/libRCTWebRTC.a(WebRTCModule+RTCMediaStream.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/anhtuank7c/Desktop/Live/ios/build/Build/Products/Debug-iphonesimulator/libRCTWebRTC.a(RCTConvert+WebRTC.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/anhtuank7c/Desktop/Live/ios/build/Build/Products/Debug-iphonesimulator/libRCTWebRTC.a(WebRTCModule+RTCDataChannel.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: framework not found WebRTC for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rayhuang** [comment]
Here is what I think the correct execution order to get archive right:

1. run the script with -e
2. run the script with -d
3. remove all generated bundle other than WebRTC under node_modules/react-native-webrtc/ios WebRTC.framework/
4. do  the archiving.
5. validate or upload.

For myself it just do fine.

**Comment by siemya** [comment]
@besarthoxhaj 

After executing your script with the order -e and -d, and creating the .ipa file, when i try to upload to app store, other than my app these are also listed.

![gg](https://cloud.githubusercontent.com/assets/1944945/23615484/9d3543e4-0297-11e7-8e7f-ec103e757874.png)

When i upload i get errors similar to

> "nvalid Bundle Structure - The binary file 'MyApp.app/Frameworks/WebRTC.framework/WebRTC-i386' is not permitted. Your app can't contain standalone executables or libraries, other than the CFBundleExecutable of supported Bundles.

**Comment by liudongpu** [comment]
@siemya 
remove all generated bundle other than WebRTC under node_modules/react-native-webrtc/ios WebRTC.framework/

**Comment by siemya** [comment]
@liudongpu That solved it thanks!

However i have a new problem #223

**Comment by RedkoVO** [comment]
In terminal: cd react-native-webrtc/tools/ && ./downloadBitcode.sh

It helped me.

**Comment by danwhite-ipc** [comment]
Anyone ran the script in a Microsoft App Center build?
