### ISSUE TITLE
Android 4.1 (API 16)

### ISSUE THREAD

**Issue by davidperrenoud** [oney/react-native-webrtc#142]
Has anyone tried using this module on Android 4.1? I get the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoSuchMethodError: com.oney.WebRTCModule.WebRTCView.isInLayout
   at com.oney.WebRTCModule.WebRTCView.requestSurfaceViewRendererLayout(WebRTCView.java:317)
```

I think we should add some Android Support Library.

**Comment by davidperrenoud** [comment]
So, just some small changes were needed in `WebRTCView.java`:
```java
import android.support.v4.view.ViewCompat;
```

In `requestSurfaceViewRendererLayout`:

```java
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
            if (!isInLayout()) {
                onLayout(
                    /* changed */ false,
                        getLeft(), getTop(), getRight(), getBottom());
            }
        }
```

Indeed, `ViewCompat.isInLayout()` does not seem to exist with build tools < 24.0.0 and the method would anyway return `false` for API level < 18.

In `tryAddRendererToVideoTrack`:

```java
    private void tryAddRendererToVideoTrack() {
        if (videoRenderer == null
                && videoTrack != null
                && ViewCompat.isAttachedToWindow(WebRTCView.this)) {
```

**Comment by davidperrenoud** [comment]
I now get:
```
E/dalvikvm: Could not find class 'android.opengl.EGLConfig[]', referenced from method org.webrtc.EglBase14.getEglConfig
```

Strange...

@lyubomir Shouldn't EglBase in `SurfaceViewRenderer.java` automatically fall back to EglBase10 on Android 4.1?

**Comment by rajsinghUSA** [comment]
I would very much appreciate help on this issue as well.

**Comment by lyubomir** [comment]
@davidperrenoud, I don't think I'll have the time to look into Android 4.1 any time soon, I'm sorry. Besides, I don't have access to an Android 4.1 device. If Android 4.1 becomes a target for our app, I guess I'll have to look into that but I don't have high hopes. Anyway, if WebRTC supports Android 4.1, you can look at its source code and figure out how it deals with the related differences.

**Comment by lyubomir** [comment]
@rajsinghUSA, the isInLayout and isAttachedToWindow should be taken care of now in the latest master (and, if I'm not mistaken, in the latest release).

@davidperrenoud, I'll try to work on falling back to EglBase10 now. Will you be available for testing because I don't have devices on which to reproduce it?

**Comment by davidperrenoud** [comment]
Yes, for which devices do you need testing? We have devices with Android 4.1.2, 4.3, 4.4.2 and 4.4.4.

**Comment by lyubomir** [comment]
@davidperrenoud, could you please test https://github.com/jitsi/react-native-webrtc/commit/9ff876faf71db7852e1c572f4f7e20cded2c5a93 for the fallback from EglBase14 to EglBase10?
