### ISSUE TITLE
RTCView mirroring on iOS

### ISSUE THREAD

**Issue by davidperrenoud** [oney/react-native-webrtc#143]
@lyubomir Thanks for the new `mirror` property on `RTCView`! Do you already have iOS support for `mirror` in some branch?

If not, we could try adding something along the lines of:
```objective-c
CGAffineTransform transform = CGAffineTransformMakeScale(-1.0, 1.0);
[view setTransform:transform];
```

**Comment by lyubomir** [comment]
No, @davidperrenoud, I don't have it for iOS in any branch. (The way we mirror on iOS is my a CSS transform of the container/parent of RTCView. I did an implemented mirror on Android because that approach doesn't work on Android and WebRTC API had it implemented anyway.)

**Comment by davidperrenoud** [comment]
Thanks @lyubomir!

For someone looking for the solution:
```javascript
<RTCView
  streamURL={this.props.selfViewSrc}
  mirror={true}
  style={{ transform: [{ scaleX: (Platform.OS === 'ios') ? -1 : 1 }] }}
/>
```
