### ISSUE TITLE
Missing keys in getUserMedia

### ISSUE THREAD

**Issue by ndarilek** [oney/react-native-webrtc#145]
I previously used this library and had code like the following:

```
    MediaStreamTrack.getSources((sources) => {
      const source = sources.find((s) => s.kind == "video")
      const constraints = {audio: true, video: {optional: [{sourceId: source.id}]}}
      getUserMedia(constraints, getUserMediaSuccess, console.error)
    })
```

However, in the latest build I get an error telling me my constraints are missing key `mandatory`. I add that key, and then am told I'm missing another.

None of the examples include these keys. Am I missing something? I'm just trying to put together a quick tutorial so am not interested in sophisticated camera-selection code. Seems like maybe a dependency isn't being hard-pinned and now requires additional fields?

My code is here: https://github.com/ndarilek/react-native-janus-echotest

Thanks.

**Comment by tezqa** [comment]
Hello,

I think the demo available at https://github.com/oney/RCTWebRTCDemo is outdated.

Here is what you should pass to make this capricious getUserMedia happy :)

```
getUserMedia({
      audio: true,
      video: {
        mandatory: {
          minWidth: 240, // Provide your own width, height and frame rate here
          minHeight: 300,
          minFrameRate: 30
        },
        facingMode: 'user',
        optional: [{ sourceId: source.id }]
      }
    }, getUserMediaSuccess, console.error);
```

**Comment by zxcpoiu** [comment]
@skeie so after you applied @tezqa 's example, the problem solved, right?

**Comment by skeie** [comment]
Yes. I haven't had the time to submit a pr to fix the issue yet...

**Comment by zxcpoiu** [comment]
cool, thanks!
