### ISSUE TITLE
Audio feedback / echo cancellation?

### ISSUE THREAD

**Issue by amccloud** [oney/react-native-webrtc#148]
Is there any way to prevent audio feedback? Seems sorta odd to playback audio captured by the mic.

Looks like this is usually accomplished by muting the local video element. I'm not certain how I would accomplish the same with this library.

**Comment by zxcpoiu** [comment]
this library enables lots of echo cancellation options on android ( I'm not sure about iOS ), maybe you can try to find out which is the best combination for your use case.

note: high-end devices usually has hardware EC embedded, it works well even you don't use any of software EC.


I' not sure about your case, but if you want to mute local stream, you can try something like:

```javascript
let tracks = localMediaStream.getTracks();
if (tracks.length > 0) {
    tracks.forEach((element, index, array) => {
        element.enabled = false;
    })
}
```

**Comment by amccloud** [comment]
I've tried. My application actually only sets enabled to true while you are
holding a button - like a walkie talkie. When enabled is false the audio is
no longer sent to remote peers but it still seems to playback for the local
peer which causes a feedback loop.

**Comment by zxcpoiu** [comment]
You can try **turn mic off** as well while you disabling track. This beyond the scope of this project, you can check source code in **react-native-incall-manager**, if I recall it correctly, there is a function doing that.

assuming both of your clients are **speaker on** like walkie-talkie, from my limited experiences, it is unavoidable if two clients close enough to each other (B party's mic can hear sound from A party's speaker )

**Comment by amccloud** [comment]
Ignoring the second client/device, your suggestion would still mean
feedback when the mic is enabled. Is there ever a case where the audio
recorded by the mic should come through the speakers? The only audio that I
expect be playing out of the speakers is that from a remote peer.

**Comment by zxcpoiu** [comment]
>The only audio that I
expect be playing out of the speakers is that from a remote peer.

I agree, but I never experience feedback when there is only one device.
Does this occurs on iOS?

webrtc handles it's own media player, (maybe per stream one player ?)
usually, I only have one PeerConnection and have one Stream.

I don't have any theories for now but few factors we should consider:
( for android only )

* try on one local stream / remote stream only and see what it does.
* try on high-end devices to see if it occurs on some devices
* try combination of [echo cancellation options at L349](https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L349)
* monitor some thing like `AudioFocus` `AudioRouteChanged` events on android to spot the source.

currently, I think the best workaround is using:
`InCallManager.setMicrophoneMute(true)` with `track.enable = false`
