### ISSUE TITLE
Android: Build failed with an exception.

### ISSUE THREAD

**Issue by swaroopa94** [oney/react-native-webrtc#152]
Hi 
I am using your module and integrated this in my application .
In IOS its working fine but in android the build id failed and giving an exception as follows:
![screen shot 2016-10-19 at 3 31 50 pm](https://cloud.githubusercontent.com/assets/19324363/19515626/e01ec818-9615-11e6-95d2-f19b34b5522c.png)

Don't know what the issue is tried this:
`compile('com.googlecode.json-simple:json-simple:1.1.1') {
    exclude group: 'org.webrtc'
}`

But it did not work for me 
Please help in solving this.

**Comment by zxcpoiu** [comment]
make sure you clean all build cache and intermediate files, and try again.

**Comment by swaroopa94** [comment]
@zxcpoiu Yes I Tried but no use..

Showing same error

**Comment by zxcpoiu** [comment]
then I can help much here, sorry for that,
I think it's more like a android build issue and should be asked on StackOverflow

but feel free to post here how you solve it once you got the solution

**Comment by swaroopa94** [comment]
@zxcpoiu  ok sure 

Thanks
