### ISSUE TITLE
setLocalDescription crashes app

### ISSUE THREAD

**Issue by fmtoffolo** [oney/react-native-webrtc#153]
When running
`
peerConnection.createOffer((desc) => {
             peerConnection.setLocalDescription(desc, function () {
        console.log('setLocalDescription', pc.localDescription);
      });
        }, function (e) {
            console.log(e)
        });
`

It crashes de app.

**Comment by fmtoffolo** [comment]
fixed adding this to manifest
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

**Comment by zxcpoiu** [comment]
thanks for paste your solutions!

**Comment by zxcpoiu** [comment]
@fmtoffolo thanks
added it into docs in https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md
