### ISSUE TITLE
Android - createOffer always returns with video channel 

### ISSUE THREAD

**Issue by ganeshagrawal** [oney/react-native-webrtc#155]
I have setup the  getUserMedia with video set to false, and calling createOffer. 
getUserMedia({ "audio": true, "video": false }, (stream) => {

All is good on iOS and I do get an offer with sdp in description with audio only, but on android I get an offer back with video in it. Is there something wrong on the android side of implementation.

this.connection.createOffer((desc) => {

**Comment by tezqa** [comment]
Hello,

And does it really create a video stream? A simple reason to prove it: it willl dramatically drain you battery ;)

Here is my code to get (or not) user's streams, if it helps: 

```
function getLocalStream(audioEnabled, videoEnabled, isFront, callback) {
  let videoConfig = false;

  if (videoEnabled) {
    MediaStreamTrack.getSources(sourceInfos => {
      log('SourceInfos', sourceInfos);
      let videoSourceId;
      let sourceInfo;
      for (let i = 0; i < sourceInfos.length; i++) {
        sourceInfo = sourceInfos[i];
        if (sourceInfo.kind == 'video' && sourceInfo.facing == (isFront ? 'front' : 'back')) {
          videoSourceId = sourceInfo.id;
          break;
        }
      }

      videoConfig = {
        mandatory: {
          minWidth: 240,
          minHeight: 300,
          minFrameRate: 30
        },
        facingMode: 'user',
        optional: [{sourceId: videoSourceId}]
      };

      _getUserMedia();
    });
  } else {
    _getUserMedia();
  }

  function _getUserMedia() {
    getUserMedia({
      audio: audioEnabled,
      video: videoConfig
    }, stream => {
      log('Stream', stream);
      callback(stream);
    }, logError);
  }
}
```

**Comment by zxcpoiu** [comment]
@ganeshagrawal 

I have similar issue like you that noticed even though pass `video: false` in, but the sdp always contains video candidates.

It's because `react-native-webrtc` doesn't support customized constraints well.

I only have audio use cases currently, so my workaround is just set `OfferToReceiveVideo = false`

**see:**

https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L70

https://github.com/oney/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule%2BRTCPeerConnection.m#L124

**Comment by ganeshagrawal** [comment]
Thanks @zxcpoiu. Setting the value to false in above constraints fixes the issue where the offer is not returned back with video offer.

**Comment by zxcpoiu** [comment]
It has been changed to js side.

https://github.com/oney/react-native-webrtc/blob/c0e8fe233486a3772525ed297f65d6d4dc685d58/RTCPeerConnection.js#L127-L130

Pass constraints as `options` arguments directly into `createOffer` or `createAnswer` at JS side with `OfferToReceiveVideo = false`.

Something like:

```js
const options = {
  mandatory: {
    OfferToReceiveAudio: true,
    OfferToReceiveVideo: false,
  },
};
```
