### ISSUE TITLE
Android: Media device stream not released

### ISSUE THREAD

**Issue by stwiname** [oney/react-native-webrtc#158]
Trying to dispose of the local media stream doesn't seem to work correctly.
I am calling:

``` js
localStream.getTracks().forEach(t => t.stop());
localStream.release();
```

But signs are pointing to it still being used.
- I can see camera related logging (`org.webrtc.Logging: CameraStatistics: Camera fps: 30`) continuing on my main device (Nexus 5X, Android 7.1.1) and similar behaviour on another device (Samsung Tablet, Android 5.1.1).
- Device continues to feel hot.
- Battery stats show the usage for the app continues to use the camera.

I think https://github.com/oney/react-native-webrtc/issues/101 might be related to this.

**Comment by zxcpoiu** [comment]
@stwiname which react-native-webrtc version you are using?

**Comment by stwiname** [comment]
Version 0.35. Ill have a quick look to see if i can get it working with 0.36 when i get the chance.

**Comment by zxcpoiu** [comment]
Oh, I mean the version of this library

**Comment by stwiname** [comment]
Ah. Sorry.

We are using the latest master branch

**Comment by zxcpoiu** [comment]
thanks, but I don't have any clue currently.
maybe you should close peerConnection as well?

**Comment by stwiname** [comment]
It seems to be happening even if I don't add the stream to the peer connection.

**Comment by maximovicd** [comment]
I got the same problem and it seems to be happening due to the fact that VideoCapturer is never saved so it can be stopped at later time. Can you guys confirm that that's the root cause of the problem?

**Comment by zxcpoiu** [comment]
@maximovicd 
What do you mean by saved VideoCapturer?
And did you found a solution or workaround?

**Comment by maximovicd** [comment]
I mean in WebRTCModule.java, `VideoCapturer` is created and reference to it is not stored. It has `stopCapture` method, that I tried and successfully used to release the camera capture. I think it's a solution for the problem. Let me know if you need more details.

**Comment by stwiname** [comment]
@maximovicd I have managed to reproduce your solution.

`stopCapture` only exists on `VideoCapturerAndroid` so the `VideoCapture` instance needs to be cast back.

@zxcpoiu This is the `VideoCapturer` reference that needs to be kept and have `stopCapture` called on.
https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L323 

It also seems to fix https://github.com/oney/react-native-webrtc/issues/101 for me.

I will try and find the time to get a PR together. I need to get a better understanding of `WebRTCModule.java` and when `stopCapture` should be called first.

**Comment by zxcpoiu** [comment]
ping @lyubomir 

he has much more solid knowledges than me

**Comment by maximovicd** [comment]
@stwiname I didn't have to cast anything in my case, but yeah, it is pretty hard to assume if you will be able to create multiple tracks for one capturer because I think it will fail if camera is already used.

My guess would be to have capturer paired with track, so when the track is released, you can release the capturer as well. Other than that, it might be possible to create multiple tracks from one capturer, in which case when all tracks are dropped, we should drop the main capturer.

**Comment by lyubomir** [comment]
I'll have the time to look into this issue next week.
