### ISSUE TITLE
React Native 0.20

### ISSUE THREAD

**Issue by JoeLogan1981** [oney/react-native-webrtc#16]
Hi,

I have tried to implement this in React Native 0.20 and cannot get anything aside from a blank `RTCView.  navigator.getUserMedia()` appears to work properly, and the camera activates on Android (haven't tested iOS yet).  `getUserMedia()` returns a RTCMediaStream object, seemingly correctly, which contains a `_streamID`.  However, I cannot seem to be able to produce any video from it.  Any ideas?  Is this just not compatible yet with RN 0.20?

**Comment by JoeLogan1981** [comment]
Hello again,

OK so I seem to have narrowed down the problem....

1)  I have built and run the demo app on an Android phone, which aside from adding the `onLayout: true` fix mentioned in other posts, ran without a hitch.

2)  I have run the demo app on the phone, and opened the https://react-native-webrtc.herokuapp.com/ app in Chrome.  In chrome, the local and remote streams render fine.

3)  On the phone, the `RTCView` renders a black box only.

Is anybody else having similar issues?  A fix would be awesome..!

**Comment by voidvoxel** [comment]
Hey Joe,

Did you set RTCView's streamURL?

**Comment by JoeLogan1981** [comment]
Hey,

Yes, `RCTView`'s `streamURL` is set to the the output of `RCTMediaStream.toURL()` 

Joe

**Comment by voidvoxel** [comment]
@JoeLogan1981 
Two possible issues I can think of are
1. setting streamURL with wrong RTCMeidaStream. Are you getting RTCMediaStream from the event generated by onaddsteram?
2. everything is working except the UI isn't updating. Instead of setting streamURL directly. Save stream.toURL() to a state and set streamURL = {this.state.xyz}. This way the UI will re-render when stream.toURL() updates.

**Comment by JoeLogan1981** [comment]
@voidvoxel 

`RTCMediaStream` is being generated correctly, basically as per the demo app code.  The media stream is delivered fine through Websockets, and the stream can be viewed (and heard) on a browser client.

The issue does indeed seem to relate to the UI not rendering correctly.  I am setting the `stream.toURL()` to the state correctly, and setting the `streamURL = {this.state.videoURL}`.  

I have also build and run the demo app which gives exactly the same result.  The camera activates correctly, transmits the stream perfectly, but does not render either the remote or local stream in the `RTCView`.  

The only errors I had during the build was during npm install, where `bufferutil` and `utf-8-validate` were unable to be built due to the lack of an explicit libgcc compiler, which seems to be a known issue since Xcode Command Line Tools was updated.....

**Comment by liangmicha** [comment]
Hi @JoeLogan1981 I am also running into the same issue. Were you able to get it to work?

**Comment by JoeLogan1981** [comment]
@liangmicha Unfortunately not.  It's probably some kind of incompatibility with the original implementation of `react-native-webrtc` in Android and the current protocol implemented by the WebRTC group.  Seems to relate to the `RTCView` component.  I am not an Android developer by any stretch, and I reckon we could use some input from somebody who is able to debug Android builds (in Android Studio?) and offer some pointers.

**Comment by reactor81** [comment]
+1 Also seeing a similar result. Just gray / blank video rendered locally on Android. Have not tried sending the feed out, just want to get local stream working first.

**Comment by JoeLogan1981** [comment]
@reactor81 hopefully someone should get this resolved soon. I will try and debug it tomorrow and at least get some idea of where the issue lies.

**Comment by liangmicha** [comment]
@JoeLogan1981  was this working with previous versions of react-native? If so, which one?

**Comment by reactor81** [comment]
@liangmicha This was working on ios and android on version 0.1.5

**Comment by oney** [comment]
I just update 0.3.0. Please try to see whether the problem is fixed. You can also try Demo project. It should work with RN 0.20.0 on iOS and Android.

**Comment by JoeLogan1981** [comment]
@oney tested on RN 0.20.0 and working on both Android and iOS.  Closing now.
