### ISSUE TITLE
app died, no saved state

### ISSUE THREAD

**Issue by snsekar** [oney/react-native-webrtc#160]
Hi,
I am trying to run https://github.com/oney/RCTWebRTCDemo on Android 4.2.2
App closes automatically after few seconds

Following issue occurred 

> I/ActivityManager( 1961): Process com.rctwebrtcdemo (pid 22833) (adj 0) has died.
> D/DisplayManagerService( 1961): Display listener for pid 22833 died.
> W/ActivityManager( 1961): Force removing ActivityRecord{42ca1a70 u0 com.rctwebrtcdemo/.MainActivity}: app died, no saved state

**Comment by snsekar** [comment]
@oney Can you help me?

**Comment by zxcpoiu** [comment]
I updated RCTWebRTCDemo to use master branch of `react-native-webrtc` now
please try again to see if it works

**Comment by snsekar** [comment]
https://github.com/oney/RCTWebRTCDemo/issues/35

**Comment by snsekar** [comment]
@zxcpoiu i checked the demo with updated to use master. Now getting following error

> 
> E/rtc     (17596): # Fatal error in ../../webrtc/api/android/jni/androidnetworkmonitor_jni.cc, line 212
> E/rtc     (17596): # last system error: 22
> E/rtc     (17596): # Check failed: !jni()->ExceptionCheck()
> E/rtc     (17596): # Error during CallVoidMethod
> E/rtc     (17596): #

**Comment by snsekar** [comment]
https://github.com/oney/RCTWebRTCDemo/issues/36#issuecomment-259669625
