### ISSUE TITLE
No Next keys for keyIterator in WebRTCModule.java

### ISSUE THREAD

**Issue by skeie** [oney/react-native-webrtc#161]
When I run https://github.com/oney/RCTWebRTCDemo/pull/33

I'll get an error [here]
(https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L239)
telling that there are no next keys. So if I add the if-sentence bellow to line 238. The RCTWebRTCDemo works. Is this a problem with RCTWebRTCDemo or react-native-webrtc?

```java
if(keyIterator.hasNext()) {
..

```

**Comment by zxcpoiu** [comment]
thanks @skeie 
I add checks before get `nextKey()`
fixed in 76e299a86681c80133bc72a80e92b2f06123d703
