### ISSUE TITLE
Info.plist in WebRTC.framework is invalid for store submission

### ISSUE THREAD

**Issue by jeffgorder** [oney/react-native-webrtc#162]
The current CFBundleVersion is set to 1.0._branch54 which causes the submission to the app store to fail. Should be 1.0.54

**Comment by zxcpoiu** [comment]
thanks @jeffgorder , I had changed CFBundleVersion.

just curious, is the submission failure an automatic process or rejected by guys from apple?

**Comment by jeffgorder** [comment]
Thanks for fixing that. The failure is an automatic check that happens when you try and submit your bundle, well before anyone sees it.
