### ISSUE TITLE
[Android] Crash when joining a room

### ISSUE THREAD

**Issue by twhit093** [oney/react-native-webrtc#163]
I am seeing this crash when trying to join a room on Android.

```
# Fatal error in ../../webrtc/api/android/jni/androidnetworkmonitor_jni.cc, line 212
# last system error: 88
# Check failed: !jni()->ExceptionCheck()
# Error during CallVoidMethod
#
Fatal signal 6 (SIGABRT), code -6 in tid 1336 (network_thread )
```

Here are some logs from the react-native side of things before it crashes.
```
join ["JigY-zYuEZydgeGSAAIk"]
state: {info: "Please enter or create room ID", status: "ready", roomID: "test", isFront: true, selfViewSrc: "e06b025e-f7cd-46f3-846b-7d60dabc7713"…}
RTCPeerConnection {signalingState: "stable", iceGatheringState: "new", iceConnectionState: "new", _remoteStreams: Array[0], _dataChannelIds: Set…}
onnegotiationneeded
createOffer RTCSessionDescription {sdp: "v=0↵o=- 4584367344462272542 2 IN IP4 127.0.0.1↵s…8931 label:39ba638f-f679-4df9-a8e7-52f741e52a64↵", type: "offer"}
onsignalingstatechange have-local-offer
```

And then it crashes on the Android side with the above exception. Before I try to join the room I can see my local video. Anyone have any ideas?

Thanks!

**Comment by twhit093** [comment]
Problem was the same as https://github.com/oney/react-native-webrtc/issues/153

Needed to add network state permission in the manifest

`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>`

**Comment by zxcpoiu** [comment]
thanks @twhit093 

added it into docs in https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md
