### ISSUE TITLE
Remote view is not loading

### ISSUE THREAD

**Issue by swaroopa94** [oney/react-native-webrtc#165]
Hi,
I am using your module 
I am not getting the remote view  even though peer has joined.
Its showing "One Peer Joined" in my log but no remote view.

Here is my log when there is no remote view:

> 11-07 18:21:04.528 22318-24038/com.roger I/org.webrtc.Logging: VideoCapturerAndroid: isVideoStabilizationSupported: false
11-07 18:21:04.528 22318-24038/com.roger I/org.webrtc.Logging: VideoCapturerAndroid: Start capturing: 640x480@[1000:30000]
11-07 18:21:04.828 22318-22499/com.roger I/ReactNativeJS: **'join', [ 'rl0R7PTJcY5pkEUPAAK-' ]**
11-07 18:21:04.858 22318-24038/com.roger D/com.oney.WebRTCModule.WebRTCModule: CameraEventsHandler.onFirstFrameAvailable
11-07 18:21:04.958 22318-22500/com.roger D/com.oney.WebRTCModule.WebRTCModule: addStreamtrue
11-07 18:21:04.958 22318-22499/com.roger I/ReactNativeJS: onnegotiationneeded
11-07 18:21:04.958 22318-22500/com.roger D/com.oney.WebRTCModule.WebRTCModule: RTCPeerConnectionCreateOfferWithObjectID start
11-07 18:21:04.958 22318-22500/com.roger D/com.oney.WebRTCModule.WebRTCModule: RTCPeerConnectionCreateOfferWithObjectID end
11-07 18:21:08.738 22318-22499/com.roger I/ReactNativeJS**: JOINOne peer join!**
11-07 18:21:08.738 22318-24249/com.roger I/ACodec: [OMX.qcom.video.encoder.vp8] setupVideoEncoder succeeded
11-07 18:21:08.748 22318-24249/com.roger D/ACodec: onStart
11-07 18:21:08.748 22318-24249/com.roger D/ACodec: [OMX.qcom.video.encoder.vp8] Now Loaded->Idl
11-07 18:21:12.688 22318-22499/com.roger I/ReactNativeJS: 'exchange candidate', { to: 'uWNmGhA0zPOSJwoeAAK9',
                                                            candidate: 
                                                             { candidate: 'candidate:4041122834 1 udp 1686052607 106.51.5.67 49238 typ srflx raddr 192.168.1.98 rport 49238 generation 0',
                                                               sdpMLineIndex: 0,
                                                               sdpMid: 'audio' },
                                                            from: 'rl0R7PTJcY5pkEUPAAK-' }
11-07 18:21:12.698 22318-22500/com.roger D/com.oney.WebRTCModule.WebRTCModule: peerConnectionAddICECandidate() start
11-07 18:21:12.698 22318-22500/com.roger D/com.oney.WebRTCModule.WebRTCModule: peerConnectionAddICECandidate() end
11-07 18:21:14.648 22318-24038/com.roger I/org.webrtc.Logging: VideoCapturerAndroid: Camera fps: 20.
11-07 18:21:16.648 22318-24038/com.roger I/org.webrtc.Logging: VideoCapturerAndroid: Camera fps: 20.
11-07 18:21:18.148 22318-22318/com.roger V/MediaPlayer[Native]: constructor
11-07 18:21:18.148 22318-22318/com.roger V/MediaPlayer[Native]: setListener
11-07 18:21:18.158 22318-22318/com.roger D/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
11-07 18:21:18.158 22318-22318/com.roger W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
11-07 18:21:18.168 22318-22318/com.roger I/MediaPlayer[Native]: reset
11-07 18:21:18.168 22318-22318/com.roger I/MediaPlayer[Native]: reset
11-07 18:21:18.168 22318-22318/com.roger D/MediaPlayer: setDataSource by uri
11-07 18:21:18.168 22318-22318/com.roger D/MediaPlayer: Couldn't open file on client side, trying server side
11-07 18:21:18.168 22318-22318/com.roger D/MediaPlayer: setDataSource by path
11-07 18:21:18.168 22318-22318/com.roger D/StreamingPolicy: libstreamingpolicy v1.1.0.32.b6cc69e
11-07 18:21:18.178 22318-22318/com.roger V/MediaPlayer[Native]: setDataSource
11-07 18:21:18.188 22318-22318/com.roger V/MediaPlayer[Native]: setVideoSurfaceTexture
11-07 18:21:18.188 22318-22318/com.roger V/MediaPlayer[Native]: prepareAsync
11-07 18:21:18.208 22318-22335/com.roger E/MediaHTTPConnectionEx: MediaHTTPConnectionEx contructor
11-07 18:21:18.208 22318-22335/com.roger D/MediaHTTPConnectionEx: current Package Name:com.roger
11-07 18:21:18.208 22318-22335/com.roger **E/MediaHTTPConnectionEx: connect
11-07 18:21:18.208 22318-22335/com.roger E/MediaHTTPConnectionEx: disconnecting
11-07 18:21:18.208 22318-22335/com.roger E/MediaHTTPConnectionEx: disconnected**
11-07 18:21:18.208 22318-22335/com.roger D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= LG-H345/V10j Player/LG Player 1.0 for Android 5.1.1 (stagefright alternative)
11-07 18:21:18.208 22318-22334/com.roger E/MediaHTTPConnectionEx: getMIMEType
11-07 18:21:18.208 22318-22334/com.roger E/MediaHTTPConnectionEx: [seekToEx] offset:0/mCurrentOffset:-1
11-07 18:21:18.208 22318-22334/com.roger D/libc-netbsd: [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
11-07 18:21:18.208 22318-22334/com.roger D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=4; ai_family=0
11-07 18:21:18.208 22318-22334/com.roger D/MediaHTTPConnectionEx: proxy null port 0

Can anyone help me to solve this.

**Comment by zxcpoiu** [comment]
Make sure both of your client on the same lan
Or have stun /turn server supports

You can check #102 first
