### ISSUE TITLE
Get stuck at initialising state..

### ISSUE THREAD

**Issue by swaroopa94** [oney/react-native-webrtc#167]
Hi,

I am using your module for video calling in my application.
when I start the room for first time its showing one peer join and remote view is getting very lately.
In my app i have a back icon when I click on that I am leaving the room by calling leave(socketId) function.
My issue is when i click on the back icon and again going to start the room its showing initialising only but it is not connecting.
 I tried  leave(socketId) and 
` socket.on('disconnect', function(socketId){
          console.log("on back disconnect");
        // leave(socketId)
        });`

 but they did not work and showing same as initialising
Can anyone tell me how to solve this issue.

Thanks.

**Comment by zxcpoiu** [comment]
Check my comments in #116 
It may related
You need to control your instance cleanly

**Comment by swaroopa94** [comment]
After clearing my instance if again I join the room it working fine.
But when I click my back button and again want to join then its get stuck in initialising state.
How can I control when I click on my back button?

**Comment by zxcpoiu** [comment]
you can try release/clean all `Track/Stream/PeerConnection` when press back button.
( and you may need to `unmount` your "vidio" view, so make sure you see: `ComponentWillUnmout` when press back button)
and re-initialize them once you go to "video" view.

this may related to #116 #158

**Comment by swaroopa94** [comment]
I wrote like this when i click my back button:
`if(this.state.socketId!=null){
          leave(this.state.socketId)
        }`
I tried this also:
` socket.on('leave', function(socketId){
        console.log("backleave");
        leave(socketId);
})`
Both of them did not work for me.
Can You tell me how can I release or clean them ?

**Comment by zxcpoiu** [comment]
maybe you should try release localStream ( leave() function does not release localStream )
see: https://github.com/oney/RCTWebRTCDemo/blob/master/main.js#L265

```
      if (localStream) {
        for (const id in pcPeers) {
          const pc = pcPeers[id];
          pc && pc.removeStream(localStream);
        }
        localStream.release();
      }
```

**Comment by swaroopa94** [comment]
I Tried this but still getting  the same.

**Comment by zxcpoiu** [comment]
can you try applying solutions in #158 to see if it work?

**Comment by swaroopa94** [comment]
Tried this also but getting same issue.

**Comment by zxcpoiu** [comment]
I thought you are referring to `react-native-webrtc` module itself.
but seems you are referring to `RCTWebRTCDemo` instead. is that correct?

if so, then it is the app structure issue instead library itself.

`RCTWebRTCDemo` is just a demo showing very basic usage, and I don't think you can apply into your app as an page without any modification.

for example, the demo use heroku server which every folks who testing demo would use the same server instance. we don't know what's going on on the server. you should implement your signaling part to exchange sdp based on your logic.

**about debugging direction**

it is more like a react-native's life-cycle/instance-holding issue.

1. You can try put logs on the first line in every functions, and you will know what functions are expected to be executed which it doesn't.

2. post full application source code and logs you ran into error on stackoverflow.

**Comment by swaroopa94** [comment]
We Used our own server not heroku but getting the same issue.I will just email you my source code can you tell me where exactly the issue is.

**Comment by zxcpoiu** [comment]
If it's improper to post your source code, then it's improper that you send to anyone.

webrtc can be used in lots of different ways, we are not able to debug app for everyone.
besides I'm still learning these stuff as well.

the common approach for your question, usually, is you create a simple `repository` which can reproduce your issue,  then go to website such as `stackoverflow` for helps ( be sure tag it as `react-native`).

**Comment by zxcpoiu** [comment]
in my guess, you should print logs in `ComponentDidMount()` and `_press()` function ( in `RCTWebRTCDemo` ) to check if they are executed after you go back to the same page again.

**Comment by swaroopa94** [comment]
ok thank you @zxcpoiu

**Comment by swaroopa94** [comment]
In my scenario I kept log in every function but when I click back button again want to enter room then its showing only initialization but its not going to the connecting.
`
socket.on('connect', function(data) {
  console.log('connecting again');
  getLocalStream(true, function(stream) {
    localStream = stream;
    _this.setState({selfViewSrc: stream.toURL()});
    _this.setState({status: 'ready', info: 'Please enter or create room ID'});
     _this.setState({status: 'connect', info: 'Connecting'});
        join(_this.state.roomID);
  });
});`
console.log is not printing for the second time

**Comment by zxcpoiu** [comment]
yes, that's what I was guessed. it's a `app structure`/`instance holding` issue.
when you go to that page the second times, socket doesn't connect again thus the rest of code which initialing webrtc was not called.

you can try either:

1. manually execute `io.connect()` and `getLocalStream` after you back to the page.
2. don't use global object, which means you put every creation logic in `ComponentDidMount()`
    and clean them in `ComponentWillUnmount`
   then you only have to worry about components's lifecycle

**Comment by swaroopa94** [comment]
@zxcpoiu  thanks for the reply i just wrote as you said but when i go back in ComponentWillUnmount I cleared up everything by calling:
`  socket.on('leave', function(socketId){
      leave(socketId);
    });`
But for the response its taking much time.

**Comment by zxcpoiu** [comment]
`socket.on` is an setting an event after you create socket, you can't call it directly.

check https://github.com/socketio/socket.io-client for how to use `socket.io`

#### you should clean in `ComponentWillUnmount`:

1. leave room ( `leave()` )
2. close pc (peer connection)
3. close socket ( something like `socket.close`  )

#### you should create everything in `ComponentDidUnmount`:

something like

```
// --- create/connect socket
const socket = io.connect(xxxx)

// --- set events
socket.on(xxx)
socket.on(xxx)
```

**Comment by swaroopa94** [comment]
Hi,
I said now its came to  connecting state but:

First Case: Its getting connected but for one user its showing only self view and for other user its showing only remote view.

Some times its showing only Connecting....
This is what i have written in componentWillUnMount()

`  if(this.state.socketId!=null){
         pc.close()
    }

    delete pcPeers[this.state.socketId];

    const remoteList = this.state.remoteList;
    delete remoteList[this.state.socketId]
    this.setState({
      remoteList: remoteList,
      selfViewSrc:null
    });
    this.setState({info: 'One peer leave!'});
    console.log("LEAVE"+'One peer leave!')
   if (localStream) {
      for (const id in pcPeers) {
        const pc = pcPeers[id];
        pc && pc.removeStream(localStream);
      }
    }
     localStream.release();
     _this.setState({socketId:'',roomID:''});`

**Comment by zxcpoiu** [comment]
I don't have any video experiences, so at this stage, I can't help in further debug here now.

and I'll find time to rewrite demo to make it clearer.
and of course, if you have better structure, please make a PR to demo project

**Comment by swaroopa94** [comment]
@zxcpoiu Can you tell me how to create a PR

**Comment by zxcpoiu** [comment]
1. **fork** upstream repository you want to improve
2. create a branch and make changes based on newest upstream source code on your repo
3. commit and push to **your own forked repo**

then the rest of it is google stuff, check guides below:

https://help.github.com/articles/creating-a-pull-request/
https://yangsu.github.io/pull-request-tutorial/

**Comment by saghul** [comment]
Nothing actionable for the plugin itself AFAIS, closing.
