### ISSUE TITLE
App crashed. Not working on Android 4.2.2 & 4.4.4

### ISSUE THREAD

**Issue by snsekar** [oney/react-native-webrtc#168]
Hi,
I request the authors/contributors to add supported versions on both platforms Android/IOS
I tested on Android 4.2.2 & 4.4.4. Simply app crashed while opening

**Comment by davidperrenoud** [comment]
I described some changes in the following link. I think it works at least for Android >4.3:
https://github.com/oney/react-native-webrtc/issues/142

**Comment by snsekar** [comment]
@davidperrenoud Thanks for pointing the issue. However it is not working in 4.4.4 
I am getting following 2 fatal errors

> W/AppOps  ( 1041): Bad call: specified package qcamera under uid 1013 but it is really -1
> E/AndroidRuntime(21911): FATAL EXCEPTION: mqt_native_modules
> E/AndroidRuntime(21911): Process: com.rctwebrtcdemo, PID: 21911
> E/AndroidRuntime(21911): com.facebook.react.modules.core.JavascriptException: undefined is not an object (evaluating 'container.setState'), stack:
> E/AndroidRuntime(21911): <unknown>@1698:10
> E/AndroidRuntime(21911): <unknown>@1547:9
> E/AndroidRuntime(21911): <unknown>@87132:16
> E/AndroidRuntime(21911): __invokeCallback@7493:15
> E/AndroidRuntime(21911): <unknown>@7368:24
> E/AndroidRuntime(21911): guard@7307:3
> E/AndroidRuntime(21911): invokeCallbackAndReturnFlushedQueue@7367:6
> E/AndroidRuntime(21911): 
> E/AndroidRuntime(21911): 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:94)
> E/AndroidRuntime(21911): 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
> E/AndroidRuntime(21911): 	at java.lang.reflect.Method.invokeNative(Native Method)
> E/AndroidRuntime(21911): 	at java.lang.reflect.Method.invoke(Method.java:515)
> E/AndroidRuntime(21911): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
> E/AndroidRuntime(21911): 	at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
> E/AndroidRuntime(21911): 	at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
> E/AndroidRuntime(21911): 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
> E/AndroidRuntime(21911): 	at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
> E/AndroidRuntime(21911): 	at android.os.Handler.handleCallback(Handler.java:733)
> E/AndroidRuntime(21911): 	at android.os.Handler.dispatchMessage(Handler.java:95)
> E/AndroidRuntime(21911): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
> E/AndroidRuntime(21911): 	at android.os.Looper.loop(Looper.java:136)
> E/AndroidRuntime(21911): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
> E/AndroidRuntime(21911): 	at java.lang.Thread.run(Thread.java:841)
> W/AppOps  ( 1041): Bad call: specified package qcamera under uid 1013 but it is really -1
> W/AppOps  ( 1041): Bad call: specified package qcamera under uid 1013 but it is really -1
> W/ActivityManager( 1041):   Force finishing activity com.rctwebrtcdemo/.MainActivity
> W/AppOps  ( 1041): Bad call: specified package qcamera under uid 1013 but it is really -1

....
....

> E/rtc     (23495): # Fatal error in ../../webrtc/api/android/jni/androidnetworkmonitor_jni.cc, line 212
> E/rtc     (23495): # last system error: 22
> E/rtc     (23495): # Check failed: !jni()->ExceptionCheck()
> E/rtc     (23495): # Error during CallVoidMethod
> E/rtc     (23495): #
> F/libc    (23495): Fatal signal 6 (SIGABRT) at 0x00005bc7 (code=-6), thread 23520 (network_thread)

**Comment by snsekar** [comment]
Finally. Issue fixed
https://github.com/oney/RCTWebRTCDemo/issues/36

@davidperrenoud Thanks for your help on Android < 4.3
