### ISSUE TITLE
iOS mute microphone

### ISSUE THREAD

**Issue by voidvoxel** [oney/react-native-webrtc#17]
I'm trying to implement a button that mutes the microphone. iOS doesn't seem to have any API to do this so I cannot create a Native Module for this purpose.

**Comment by voidvoxel** [comment]
Solution: pc.removeStream(localStream)

**Comment by davidperrenoud** [comment]
You can now disabled an audio track to mute it:

```javascript
localStream.getAudioTracks().forEach((track) => {
  track.enabled = false;
});
```
