### ISSUE TITLE
Having difficulty with MediaStreamTrack.getSources

### ISSUE THREAD

**Issue by hawaiikaos** [oney/react-native-webrtc#170]
Hi I posted a question on Stackoverflow a few days ago about an issue I've been having trying to use react-native-webrtc. I haven't had any responses so I thought I'd link it here (so not an issue with react-native-webrtc per se):

http://stackoverflow.com/questions/40595830/simple-example-for-accessing-the-camera-via-webrtc-in-react-native-android

Basically, I'm new to React and Android studio, and I'm trying to port an augmented reality app over from a web-based app I created (I'd prefer to try to use react-native-webrtc rather than just straight up importing my existing code to see if there's a performance gain). I thought it would be fairly simple to just get the video stream, but alas no. I was just wondering if anyone here could help out.

**Comment by zxcpoiu** [comment]
answered on Stackoverflow
