### ISSUE TITLE
default codecs in the library (regarding library size)

### ISSUE THREAD

**Issue by zxcpoiu** [oney/react-native-webrtc#177]
this library is for resource-limited mobile devices.
regarding the library size, should we:

* remove codecs that are not wildly used?
* keep default settings, and let folks compile themselves if needed?

( I'm not sure if add/remove a codec makes a significant change on size. )

All suggestions are welcome.

**Comment by sagivo** [comment]
@zxcpoiu my 2 cents - you want to keep it as lean and small as possible with no extra code. 
i'll optimize for the 80/20 rule. also we can add each codec as a plugin so users can easily decide what plugins they want. similar to what express.js does with middleware.

**Comment by bennyguitar** [comment]
@sagivo is it even possible to do what you suggest? As far as I know, codecs have to be compiled with webrtc - meaning that the framework offered with this library would change depending on what codecs were installed. I don't know if you can add a codec after the fact.

**Comment by zxcpoiu** [comment]
@sagivo 
I'm not sure if we can use plugin way to include codec though like @bennyguitar  said, all codecs are compiled into the `.so` file.

@bennyguitar 
do you know some good ways to include/strip codecs from the library ( both iOS and andoird )?

**Comment by bennyguitar** [comment]
Only one I have experience with is VP9 for iOS. That was an easy change to include/exclude. My guess is that you'll have to dive down into the source more to include/exclude other codecs. The creators of the build scripts that come with webrtc made it really easy to include VP9.

**Comment by zxcpoiu** [comment]
@bennyguitar 

thanks, seems it's the only way :scream:

**Comment by saghul** [comment]
I'm going to go ahead and close this. It's a lot more trouble than it's worth, really.
