### ISSUE TITLE
Robotized audio

### ISSUE THREAD

**Issue by Gcampes** [oney/react-native-webrtc#178]
Hi, After some fiddling around I could finally manage to get this thing to work with my signaling server. Video works fine, I can see a webcam video using both, iOS and Android devices, and I can see the video on iOS emulator aswell.
Audio on the other hand is robotized when I run in my iOS simulator, and when I run on either iOS or android devices audio doesn't work at all.
This is similar to the case I encountered when running your demo app, but when I do run the demo app, neither the simulators or devices have any audio. 

Any idea of what could be causing this issue?

**Comment by zxcpoiu** [comment]
are you talking to a remote server? ( the other side is a server / a none-webrtc client or running with different webrtc version )
if so, reduce all your codes as simple as possible and modify sdp codec priority accordingly.

but if both side of your clients run with same version of webrtc, then I have no idea.

**Comment by Gcampes** [comment]
We figured out the issue. It was actually a problem with the sdp format, we were parsing it incorrectly, and audio and video candidates were messed up. After fixing up the candidates everything went ok, still figuring other issues out, Thanks!

**Comment by zxcpoiu** [comment]
thanks for the feedback @Gcampes
