### ISSUE TITLE
No Video appearing on Android (also in demo)

### ISSUE THREAD

**Issue by reactor81** [oney/react-native-webrtc#18]
Please see issue in demo app https://github.com/oney/RCTWebRTCDemo/issues/7

Also have issue when using react-native-webrtc core library in 2 other apps I tested.

**Comment by JoeLogan1981** [comment]
+1 on this.  Still trying to find a solution, and debugging in Android Studio did not help pinpoint the problem.  FYI, I also tried another library for Cordova, `phonertc` which gave a similar result on Android.  Both `phonertc` and `react-native-rtc` appear to use the same WebRTC build scripts by pristine.io

**Comment by oney** [comment]
I just update 0.3.0. Please try to see whether the problem is fixed. You can also try Demo project. It should work with RN 0.20.0 on iOS and Android.

**Comment by zxcpoiu** [comment]
please verify it on the latest version again.
feel free to reopen if the problem still occurs.
