### ISSUE TITLE
Error with WebRTCModule:prepareComFacebookFrescoDrawee0110Library when I try to build.

### ISSUE THREAD

**Issue by LoseTheQuit** [oney/react-native-webrtc#181]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':WebRTCModule:prepareComFacebookFrescoDrawee0110Library'.
> Could not expand ZIP '/Users/clxxxii/.gradle/caches/modules-2/files-2.1/com.facebook.fresco/drawee/0.11.0/7c8a4d211b2334b6d52b9de614b52423b16f7704/drawee-0.11.0.aar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 18.492 secs

**Comment by zxcpoiu** [comment]
does webrtc use `fresco` !?
I guess it is not related to `webrtc` but `react-native`

can you try **CLEAN PROCESS** described in https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

then try it again
