### ISSUE TITLE
Where does remote stream attach to devices speakers?

### ISSUE THREAD

**Issue by IvRRimum** [oney/react-native-webrtc#182]
We are in need to attach/deattach remote streams to different output devices. Where does that happen? How can one do that?

**Comment by IvRRimum** [comment]
For example only audio stream?

**Comment by zxcpoiu** [comment]
`webrtc` seems has it's own audioplayer ( it will initiate it automatically. ) this is the most confused part compares to web audio elements.

I use `react-native-incall-manager`, it listens devices plug/unplug event and make sure the audio type during flow changes.

But I don't know if you can force audio stream goes through specific devices.

**Comment by saghul** [comment]
Nothing actionable, closing.
