### ISSUE TITLE
default iOS architecture library 

### ISSUE THREAD

**Issue by zxcpoiu** [oney/react-native-webrtc#183]
according to discussion in #141 ( thanks to @besarthoxhaj )
current iOS native webrtc framework includes 4 arch:

* arm / armv7
* arm64
* x64 / x86_64 ( seems for iPad simulators )
* x86 / i386 ( seems for iPhone simulators )

currently, if you want to submit your app to AppStore, you may need to strip x86 and x64 manually before submission via script provided in #141 

**Question:**
is it necessary to include x64/x86 archs in the iOS library?
or just have arm/arm64 included?

**Comment by davidperrenoud** [comment]
If `i386` and `x86_64` aren't included in the framework, we need to make sure that we don't call a method from this framework, otherwise it won't compile for the simulator. Weak linking could help but I don't think it's needed.

You can add compiler macros in order to leave out methods:

```objective-c
#if !(TARGET_IPHONE_SIMULATOR)
    RTCDataChannelConfiguration *init = [RTCDataChannelConfiguration new];
#endif
```

**Comment by zxcpoiu** [comment]
@davidperrenoud 

thanks for mentioned that, though I don't have any idea on it. :cry: 
would you please tell me where should I add those macros?

and what is your opinion about exclude `i386` and `x86_64`?

my current thinking is,
we should make this library prodution ready means that we exclude supports for simulators by default in order to reduce size and avoid any bugs when submission to apple store

**Comment by saghul** [comment]
I move for close. The simulator is useful for testing, stripping the unneeded architectures is trivial and already documented.
