### ISSUE TITLE
libd_unnamed_symbol538$$WebRTC - EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by m59peacemaker** [oney/react-native-webrtc#186]
My iOS app has been working until recently. I made no changes from last I ran it successfully from Xcode. Now the app is crashing every time it tries to make a WebRTC connection. I've tried clearing caches, reinstalling node modules, and repeated the webrtc installation steps. I've also tried on multiple devices. I get the same crash. Any ideas?
![screenshot 2016-12-29 13 47 37](https://cloud.githubusercontent.com/assets/4369247/21558740/8d696d18-ce04-11e6-84bd-2e29dce865f8.png)

**Comment by m59peacemaker** [comment]
Correction: it crashes when I call `close()` on the peer connection. The app was encountering a situation where the desired behavior is to abort the peer connection, though it was just getting setup. When it tries to cleanup by calling `close()` it crashes.

**Comment by zxcpoiu** [comment]
no ideas currently.

not sure about if it is related, but I always test react-native app without xcode. ( press `stop` after install apps )

I noticed xcode would stops app sometimes, but I don't know why.

**Comment by saghul** [comment]
No follow-up, closing. Please update to the latest version and report back if you still get issues.
