### ISSUE TITLE
build errors for arm

### ISSUE THREAD

**Issue by jjdp** [oney/react-native-webrtc#195]
if i build using separate cpu architecture i got this error for arm:

`java.io.FileNotFoundException: ..\react-native-webrtc\android\build\intermediates\bundles\release\jni\lib\armeabi-v7a\libjingle_peerconnection_so.so (The system cannot find the path specified)
`

is arm not supported? -EDIT- even building for single cpu architecture it still errors

i also have found that the demo uses RN 0.29 and in build.gradle 
it uses `com.android.tools.build:gradle:1.3.1` while mine is `2.1.0` not that i know if this matters.
-EDIT- setting it back to `1.3.1` compiles on a newly tested project but my old one requires `2.1.0` because of [one signal](https://github.com/geektimecoil/react-native-onesignal)

im also using RN 0.39 and v0.54.6 for webrtc

**Comment by jjdp** [comment]
apparently it conflicts with the one signal package. version 2.1.0 or 1.3.1 is fine regardless 

the fix is this in /build.gradle

```
android {
    ...
    defaultConfig {
        ...
        multiDexEnabled true
    }
}
```

**Comment by zxcpoiu** [comment]
thanks for sharing!
