### ISSUE TITLE
How to release camera usage when my app is backgrounded?

### ISSUE THREAD

**Issue by EdmundMai** [oney/react-native-webrtc#197]
I notice in the Android log that `SurfaceViewRenderer: No surface to draw on` prints out nonstop when I have the localStream and I background the app.

Is there anything I can do to stop it from trying to draw when the app is backgrounded?

**Comment by zxcpoiu** [comment]
you may check #158 and #172

they uses `videoCapturer.stopCapture()` to stop it.
but I'm not sure if there is an API to `pause` it and can be resumed.


And I think it may related to #179 as well if you want to pause a remote stream

**Comment by EdmundMai** [comment]
Is there an example of `videoCapturer.stopCapture()`? I don't have any references to videoCapturer in my code.

I noticed that if I don't release the localStream while the app is in the background, the camera totally stops working and I have to restart the phone

**Comment by EdmundMai** [comment]
this seems to work, however it causes the peer to see a black screen when the app is active again:

```
  componentDidMount() {
    AppState.addEventListener('change', (state) => { this.handleAppStateChange(state) });
  }

  handleAppStateChange(state) {
    if (state === "background") {
      // stop camera usage when app is backgrounded.
      // local stream breaks after a few minutes if we don't do this
      if (localStream) {
        localStream.getTracks().forEach(t => t.stop());
        localStream.release();
      }
    }


```

**Comment by saghul** [comment]
You will need to create and add a track again.

**Comment by estebanprimost** [comment]
@saghul  Sorry to back to this but how exactly you do this process of add new tracks (with react-native-webrtc)? 
It is not enough to request the local stream again?
I'm having same @EdmundMai issue...

Thanks and sorry for my english!
