### ISSUE TITLE
Get error 404

### ISSUE THREAD

**Issue by igala** [oney/react-native-webrtc#199]
When sending the iOS app to background , configured background mode to support audio but still it disconnects , maybe there is some kind of override in the code ?

**Comment by zxcpoiu** [comment]
what do you mean by `error 404` and `disconnect` ?

if you enable `background audio` in your app.
the behavior is ( my experience ) :

1. you can NOT start and play a audio session while app is in background.  

2. if your audio session **starts when app is in foreground**, it will continue to play after app goes to background.

**Comment by saghul** [comment]
@zxcpoiu is correct. Also note that React Native won't run timers (setTimeout, setInterval) so might need to polyfill them with https://github.com/ocetnik/react-native-background-timer
