### ISSUE TITLE
Sound on iPhone comes from the ear piece instead of speaker

### ISSUE THREAD

**Issue by darkrishabh** [oney/react-native-webrtc#2]
Just wanna know, is this a bug or is there a config for that ?

BTW, nice work. looks great. just need to work on performance a bit. kind of heats up the phone.

**Comment by oney** [comment]
You can switch ear piece and speaker by those codes.
```objective-c
AVAudioSession* session = [AVAudioSession sharedInstance];
[session overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker error:nil]; \\ speaker
[session overrideOutputAudioPort:AVAudioSessionPortOverrideNone error:nil]; \\ ear piece
```
Currently, this is not implemented in this module.

About performance, I use libWebRTC.a to implement WebRTC connection. It seems its performance is not good enough.
