### ISSUE TITLE
Question about getting remoteSrc url

### ISSUE THREAD

**Issue by wandonye** [oney/react-native-webrtc#200]
Using the `toURL` method of my remote stream, I got something like `{1c56a73d-6fdd-43f6-a494-6dcc0acb783b}`. Is it right? Or should it be like `blob:http://localhost:3000/1c56a73d-6fdd-43f6-a494-6dcc0acb783b` or `1c56a73d-6fdd-43f6-a494-6dcc0acb783b`.

To clarify, I'm not using the demo server. I'm using Rocket.Chat's server. So the format of the stream might be different. But I'm not sure what is the expected input for RTCView in the remote case. For local stream, set streamURL=the token string is working well.

What is the underlying mechanism for the RTCView to find the stream with the URL?

**Comment by saghul** [comment]
It's just an ID to find the right stream to render in the EGL view, it's not like a the blob URL browsers use.
