### ISSUE TITLE
iOS: Questions about default CPU usage

### ISSUE THREAD

**Issue by HongSeokHwan** [oney/react-native-webrtc#202]
I am performing a performance test using iPhone 5s. After starting a video chat, the CPU usage rises to about 150%. It gets hot after a few minutes. :)

Maybe I'm making a mistake, but I wonder what the default CPU usage is.

And let me know if you have any tips on solving high CPU usage issue.

**Comment by saghul** [comment]
By default you will be using VP8, which is not hardware accelerated, and that yields a higher CPU usage. You could try using H264, which uses the builtin hardware so it should use less CPU.

**Comment by ramneekhanda** [comment]
@saghul how does one change codec?

**Comment by HongSeokHwan** [comment]
Is there an option? Or do I have to implement it myself?

**Comment by saghul** [comment]
Sorry @ramneekhanda I missed your reply! @HongSeokHwan yes, the only way to do it is to munge the SDP.

**Comment by ramneekhanda** [comment]
@saghul example please?

**Comment by saghul** [comment]
I don't have one handy, but it boils down to using [sdp-transform](https://github.com/clux/sdp-transform) to alter the order of the codec payload types in the m=video line.

**Comment by georgewwindsor** [comment]
Yeah I would just change the camera parameters to something low like 240x160. This significantly reduced my CPU usage. resplved by PR #288

**Comment by bsiddiqui** [comment]
@georgewwindsor I tried mocking your configuration
```js
          video: {
            mandatory: {
              maxWidth: 240,
              maxHeight: 160,
              maxFrameRate: 10
            },
            facingMode: 'user',
            optional: frontSourceId ? [{ sourceId: frontSourceId }] : []
          }
```

This didn't seem to have a major affect on cpu. Is there something else you did?

**Comment by ramneekhanda** [comment]
@saghul following is the answer sdp generated by one of iphones when we were testing two iphones..

Question - I just need to reorder and bring h264 on the top if i want it to be used?

how does the device know that the h264 can be decoded by other phone? is that based on answer sdp?

`{
  "version": 0,
  "origin": {
    "username": "-",
    "sessionId": "1161114873153247190",
    "sessionVersion": 2,
    "netType": "IN",
    "ipVer": 4,
    "address": "127.0.0.1"
  },
  "name": "-",
  "timing": {
    "start": 0,
    "stop": 0
  },
  "groups": [
    {
      "type": "BUNDLE",
      "mids": "audio video"
    }
  ],
  "msidSemantic": {
    "semantic": "WMS",
    "token": "1D33F700-B9F6-4C31-A6B0-492E1DF42C0B"
  },
  "media": [
    {
      "rtp": [
        {
          "payload": 111,
          "codec": "opus",
          "rate": 48000,
          "encoding": 2
        },
        {
          "payload": 103,
          "codec": "ISAC",
          "rate": 16000
        },
        {
          "payload": 104,
          "codec": "ISAC",
          "rate": 32000
        },
        {
          "payload": 9,
          "codec": "G722",
          "rate": 8000
        },
        {
          "payload": 102,
          "codec": "ILBC",
          "rate": 8000
        },
        {
          "payload": 0,
          "codec": "PCMU",
          "rate": 8000
        },
        {
          "payload": 8,
          "codec": "PCMA",
          "rate": 8000
        },
        {
          "payload": 106,
          "codec": "CN",
          "rate": 32000
        },
        {
          "payload": 105,
          "codec": "CN",
          "rate": 16000
        },
        {
          "payload": 13,
          "codec": "CN",
          "rate": 8000
        },
        {
          "payload": 110,
          "codec": "telephone-event",
          "rate": 48000
        },
        {
          "payload": 112,
          "codec": "telephone-event",
          "rate": 32000
        },
        {
          "payload": 113,
          "codec": "telephone-event",
          "rate": 16000
        },
        {
          "payload": 126,
          "codec": "telephone-event",
          "rate": 8000
        }
      ],
      "fmtp": [
        {
          "payload": 111,
          "config": "minptime=10;useinbandfec=1"
        }
      ],
      "type": "audio",
      "port": 9,
      "protocol": "UDP/TLS/RTP/SAVPF",
      "payloads": "111 103 104 9 102 0 8 106 105 13 110 112 113 126",
      "connection": {
        "version": 4,
        "ip": "0.0.0.0"
      },
      "rtcp": {
        "port": 9,
        "netType": "IN",
        "ipVer": 4,
        "address": "0.0.0.0"
      },
      "iceUfrag": "lGNc",
      "icePwd": "ld2+P6xUuc8c1EeWh0D7LZpT",
      "iceOptions": "renomination",
      "fingerprint": {
        "type": "sha-256",
        "hash": "19:65:BC:C2:E4:9B:D2:AA:14:96:A8:48:27:9C:2F:10:92:C4:10:F6:01:34:38:57:CB:92:0D:DD:E8:B3:38:84"
      },
      "setup": "actpass",
      "mid": "audio",
      "ext": [
        {
          "value": 1,
          "uri": "urn:ietf:params:rtp-hdrext:ssrc-audio-level"
        }
      ],
      "direction": "sendrecv",
      "rtcpMux": "rtcp-mux",
      "rtcpFb": [
        {
          "payload": 111,
          "type": "transport-cc"
        }
      ],
      "ssrcs": [
        {
          "id": 1331749219,
          "attribute": "cname",
          "value": "2fwfNUAcEpVDr5dT"
        },
        {
          "id": 1331749219,
          "attribute": "msid",
          "value": "1D33F700-B9F6-4C31-A6B0-492E1DF42C0B 24FE2172-F7B2-40E5-B8A7-D964811CCC2E"
        },
        {
          "id": 1331749219,
          "attribute": "mslabel",
          "value": "1D33F700-B9F6-4C31-A6B0-492E1DF42C0B"
        },
        {
          "id": 1331749219,
          "attribute": "label",
          "value": "24FE2172-F7B2-40E5-B8A7-D964811CCC2E"
        }
      ]
    },
    {
      "rtp": [
        {
          "payload": 96,
          "codec": "VP8",
          "rate": 90000
        },
        {
          "payload": 98,
          "codec": "VP9",
          "rate": 90000
        },
        {
          "payload": 100,
          "codec": "red",
          "rate": 90000
        },
        {
          "payload": 127,
          "codec": "ulpfec",
          "rate": 90000
        },
        {
          "payload": 125,
          "codec": "H264",
          "rate": 90000
        },
        {
          "payload": 97,
          "codec": "rtx",
          "rate": 90000
        },
        {
          "payload": 99,
          "codec": "rtx",
          "rate": 90000
        },
        {
          "payload": 101,
          "codec": "rtx",
          "rate": 90000
        },
        {
          "payload": 124,
          "codec": "rtx",
          "rate": 90000
        }
      ],
      "fmtp": [
        {
          "payload": 125,
          "config": "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f"
        },
        {
          "payload": 97,
          "config": "apt=96"
        },
        {
          "payload": 99,
          "config": "apt=98"
        },
        {
          "payload": 101,
          "config": "apt=100"
        },
        {
          "payload": 124,
          "config": "apt=125"
        }
      ],
      "type": "video",
      "port": 9,
      "protocol": "UDP/TLS/RTP/SAVPF",
      "payloads": "96 98 100 127 125 97 99 101 124",
      "connection": {
        "version": 4,
        "ip": "0.0.0.0"
      },
      "rtcp": {
        "port": 9,
        "netType": "IN",
        "ipVer": 4,
        "address": "0.0.0.0"
      },
      "iceUfrag": "lGNc",
      "icePwd": "ld2+P6xUuc8c1EeWh0D7LZpT",
      "iceOptions": "renomination",
      "fingerprint": {
        "type": "sha-256",
        "hash": "19:65:BC:C2:E4:9B:D2:AA:14:96:A8:48:27:9C:2F:10:92:C4:10:F6:01:34:38:57:CB:92:0D:DD:E8:B3:38:84"
      },
      "setup": "actpass",
      "mid": "video",
      "ext": [
        {
          "value": 2,
          "uri": "urn:ietf:params:rtp-hdrext:toffset"
        },
        {
          "value": 3,
          "uri": "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time"
        },
        {
          "value": 4,
          "uri": "urn:3gpp:video-orientation"
        },
        {
          "value": 5,
          "uri": "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"
        },
        {
          "value": 6,
          "uri": "http://www.webrtc.org/experiments/rtp-hdrext/playout-delay"
        }
      ],
      "direction": "sendrecv",
      "rtcpMux": "rtcp-mux",
      "rtcpRsize": "rtcp-rsize",
      "rtcpFb": [
        {
          "payload": 96,
          "type": "ccm",
          "subtype": "fir"
        },
        {
          "payload": 96,
          "type": "nack"
        },
        {
          "payload": 96,
          "type": "nack",
          "subtype": "pli"
        },
        {
          "payload": 96,
          "type": "goog-remb"
        },
        {
          "payload": 96,
          "type": "transport-cc"
        },
        {
          "payload": 98,
          "type": "ccm",
          "subtype": "fir"
        },
        {
          "payload": 98,
          "type": "nack"
        },
        {
          "payload": 98,
          "type": "nack",
          "subtype": "pli"
        },
        {
          "payload": 98,
          "type": "goog-remb"
        },
        {
          "payload": 98,
          "type": "transport-cc"
        },
        {
          "payload": 125,
          "type": "ccm",
          "subtype": "fir"
        },
        {
          "payload": 125,
          "type": "nack"
        },
        {
          "payload": 125,
          "type": "nack",
          "subtype": "pli"
        },
        {
          "payload": 125,
          "type": "goog-remb"
        },
        {
          "payload": 125,
          "type": "transport-cc"
        }
      ],
      "ssrcGroups": [
        {
          "semantics": "FID",
          "ssrcs": "571867238 1367778039"
        }
      ],
      "ssrcs": [
        {
          "id": 571867238,
          "attribute": "cname",
          "value": "2fwfNUAcEpVDr5dT"
        },
        {
          "id": 571867238,
          "attribute": "msid",
          "value": "1D33F700-B9F6-4C31-A6B0-492E1DF42C0B 63B63D06-C0CA-4392-A837-B8AABB4051CE"
        },
        {
          "id": 571867238,
          "attribute": "mslabel",
          "value": "1D33F700-B9F6-4C31-A6B0-492E1DF42C0B"
        },
        {
          "id": 571867238,
          "attribute": "label",
          "value": "63B63D06-C0CA-4392-A837-B8AABB4051CE"
        },
        {
          "id": 1367778039,
          "attribute": "cname",
          "value": "2fwfNUAcEpVDr5dT"
        },
        {
          "id": 1367778039,
          "attribute": "msid",
          "value": "1D33F700-B9F6-4C31-A6B0-492E1DF42C0B 63B63D06-C0CA-4392-A837-B8AABB4051CE"
        },
        {
          "id": 1367778039,
          "attribute": "mslabel",
          "value": "1D33F700-B9F6-4C31-A6B0-492E1DF42C0B"
        },
        {
          "id": 1367778039,
          "attribute": "label",
          "value": "63B63D06-C0CA-4392-A837-B8AABB4051CE"
        }
      ]
    }
  ]
}`

**Comment by zxcpoiu** [comment]
A Party's `SDP Offer` contains available codec preference of A.
B Party will replys `SDP Answer` contains available codec preference of B.

See RCF to know further negotiation detail and the priority. There are different algorithm depends on what your client/server used.

If it didn't match, one side will return `Not Acceptable` then failed.

you can remove unwanted `rtp` codecs and related params from your object then re-construct a new sdp.
For this party, you should read related codecs spec for SDP to know which param in sdp is related to specific codec.

**Comment by aditya6992** [comment]
How do I add a new codec? A new experimental video codec for example? I am aware that webrtc only supports 3 right now. But is it possible to do that?

**Comment by Utkarsh3441** [comment]
> By default you will be using VP8, which is not hardware accelerated, and that yields a higher CPU usage. You could try using H264, which uses the builtin hardware so it should use less CPU.

Thanks, it solved my problem

**Comment by Proxy08** [comment]
@Utkarsh3441 how did you implement it ?
