### ISSUE TITLE
To enable bitcode in iOS

### ISSUE THREAD

**Issue by tpisto** [oney/react-native-webrtc#205]
Currently the documentation instructs to disable bitcode for projects that include react-native-webrtc. I think that having bitcode enabled has it's merits, so I was thinking that has there been effort to check if we could enable it?

https://bugs.chromium.org/p/webrtc/issues/detail?id=5085
https://blog.andyet.com/2015/10/20/building-webrtc-with-bitcode/

**Comment by saghul** [comment]
I wouldn't do that until it's absolutely mandatory. 

https://lowlevelbits.org/bitcode-demystified/
https://medium.com/@FredericJacobs/why-i-m-not-enabling-bitcode-f35cd8fbfcc5#.27w9tnowk

**Comment by saghul** [comment]
No, sorry.
