### ISSUE TITLE
It is in connecting state only when the devices are in same network

### ISSUE THREAD

**Issue by swaroopa94** [oney/react-native-webrtc#208]
Hi,
 I am using this module for video calling.
I am having two devices when they are connected with the different wifi networks the video calling is working fine and I am getting the both remote and the self view.

My issue is that when my devices are connected withe the same wifi network then it showing only connecting state and not connecting at all.

Can anyone tell me how to make it work with same network.

**Comment by vinh1503** [comment]
the same error

**Comment by saghul** [comment]
No follow-up, closing.
