### ISSUE TITLE
about 3 seconds freezing when calling getUserMedia(front camera) more than twice in iOS

### ISSUE THREAD

**Issue by atyenoria** [oney/react-native-webrtc#209]
I came across to the strange phenomenon that freezing happens when calling getUserMedia(facemode: user...) in iOS, and that network connection disconnect. This happens only if you choose front camera. The back camera works perfectly. And, first calling for  front camera is no problem.  I'm using janus-gateway as WEBRTC SFU. Does anyone know how to solve it(deleting strange freezing)?  This happens in Xcode device release mode(not in device debug mode)

**Comment by dguillamot** [comment]
I have also experienced this issue and have traced it into the Objective-C getUserMedia call. It seems to happen even without a peer connection and can be reproduced just with the getUserMediaCall when trying to swap cameras. 

From what I saw, it happened every second-time calling getUserMedia. (every even call, but not odd)

**Comment by seb0zz** [comment]
I've got the same issue :-(

**Comment by atyenoria** [comment]
Yes, even call triggers this freezing. So, in order to delete this, I insert the fake getUserMedia(back) before getUserMedia(front). This solves this problem. But, it is not the good solution.

**Comment by seb0zz** [comment]
We could fix this by doing the following:

```javascript
localStream.getTracks().forEach((t) => {
  localStream.removeTrack(t);
});
localStream.release();
```

**Comment by atyenoria** [comment]
Nice! This solves this problem perfectly!

**Comment by lenglengiOS** [comment]
hello ， where should i write this code :
```
 localStream.getTracks().forEach((t) => {
  localStream.removeTrack(t);
});
localStream.release();
```

**Comment by ivmos** [comment]
@lenglengiOS you need to save such reference somewhere and do that cleanup in a phase where makes sense, e.g before toggling camera, or when leaving "room" so that next getUserMedia is fast... 
In my case I reproduced 8seconds (iphoneSE) constant freeze from second getUserMedia compared to first one which is less than one second. I checked with instruments and no CPU/Mem pike in that interval, finally I found this issue :)
