### ISSUE TITLE
com.facebook.react.uimanager.annotations not found  in android

### ISSUE THREAD

**Issue by zhenlovezhen2012** [oney/react-native-webrtc#21]
Error in Android:
node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/RTCVideoViewManager.java:12: 错误: 程序包com.facebook.react.uimanager.annotations不存在
import com.facebook.react.uimanager.annotations.ReactProp;

node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/RTCVideoViewManager.java:42: 错误: 找不到符号
  @ReactProp(name = "streamURL", defaultInt = -1)
   ^
  符号:   类 ReactProp
  位置: 类 RTCVideoViewManager

node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java:424: 错误: 找不到符号
                Window window = getCurrentActivity().getWindow();
                                ^
  符号: 方法 getCurrentActivity()

-----------------------------------
My react native version is 0.20.0.

**Comment by zhenlovezhen2012** [comment]
I solved this problem;
In Android/build.gradle,chang compile 'com.facebook.react:react-native:0.13.+'   to compile 'com.facebook.react:react-native:0.20.+'.

Then it works fine,but I don't know why.

**Comment by oney** [comment]
Oh, it's my mistake. I will fix it in latest version.

**Comment by philikon** [comment]
This seems to be fixed now. Can we close this?

**Comment by oney** [comment]
Yes, we should close it.
