### ISSUE TITLE
Issues with TURN

### ISSUE THREAD

**Issue by JamesToohey** [oney/react-native-webrtc#217]
Hi,

Firstly - thank you very much for this library.

We're designing an application that allows web-to-web and web-to-mobile video communication. We have implemented a TURN server and tested it by tethering a laptop to 4G and doing a web-to-web video, so our TURN server is definitely working.

We cannot establish a connection web-to-mobile over a 4G connection with TURN config, however it works fine on wifi.

Any ideas?

```
configuration = {
    'iceServers': [
        {
            'url': 'turn:domain:port',
            'username': 'username',
            'credential': 'password',
        },
    ],
};

this.peerConn = new RTCPeerConnection(configuration);
```

**Comment by JamesToohey** [comment]
For anyone looking in the future, this was an issue with me not correctly passing ice candidates to the server

**Comment by bsiddiqui** [comment]
@JamesToohey what were you doing incorrectly that allowed for wifi but didn't allow for cellular?

**Comment by JamesToohey** [comment]
I didn't have a method to handle the iceCandidates coming in

```
        this.peerConn.addIceCandidate(new RTCIceCandidate(data.candidate));
```

**Comment by JamesToohey** [comment]
@bsiddiqui I think it would only work on the same Wifi, so it was effectively cheating a connection
