### ISSUE TITLE
Question: Is it possible to pass the stream to a <WebView/>?

### ISSUE THREAD

**Issue by Enijar** [oney/react-native-webrtc#218]
Is this out of the scope of this project or is it possible to do?

**Comment by davidperrenoud** [comment]
No, you can only send a string to the WebView (through [onMessage](https://facebook.github.io/react-native/docs/webview.html#onmessage)).

You could however overlay the stream on top of a WebView. There is an example on how to pass messages between a WebView and React Native at the bottom of the WebView documentation [in the MessagingTest class](https://facebook.github.io/react-native/docs/webview.html#examples).

**Comment by Enijar** [comment]
So it's not possible to create, for example, a video from the stream.toURL() string?

**Comment by saghul** [comment]
stream.toURL is just an internal identifier, not something generic APIs can use. Closing since there is nothing actionable here.

**Comment by saket424** [comment]
@saghul ,
Is it possible to use react-native-webrtc to handle only the <video>/<audio> tags of the Webview as a native overlay and let Webview handle the rest of the webcode.  Similar to what is being done in this project https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc/blob/master/src/PluginMediaStreamRenderer.swift line 39

Any code sample on how one may go about achieving this more cordova like idea where we delegate only the webrtc media parts to react-native and let the rest be handled in the standard webview ?

Thanks in advance

**Comment by saghul** [comment]
That's not the goal of this project. The cordova plugin is implemented that way because all you have is a webview, but in React Native, everything is implemented as a native component.
