### ISSUE TITLE
android error:addPackage(new WebRTCModulePackage(this))

### ISSUE THREAD

**Issue by zhenlovezhen2012** [oney/react-native-webrtc#22]
android/app/src/main/java/com/showmyscreen/MainActivity.java:31: 错误: 无法将类 WebRTCModulePackage中的构造器 WebRTCModulePackage应用到给定类型;
                .addPackage(new WebRTCModulePackage(this))
                            ^
  需要: 没有参数
  找到: MainActivity
  原因: 实际参数列表和形式参数列表长度不同

My react native version is 0.20.0.

When I change to " .addPackage(new WebRTCModulePackage())",it build success.

I don't know whether it will cause other problems. Please fix it.

**Comment by oney** [comment]
Sorry about that. I forgot updating the Readme.
Please see https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

**Comment by zhenlovezhen2012** [comment]
Thanks.

**Comment by philikon** [comment]
Seems like we can close this?
