### ISSUE TITLE
Direct call using react native.

### ISSUE THREAD

**Issue by reformer** [oney/react-native-webrtc#221]
Hi, 
Current functionality is when both party must enter room id manually then webcall established, But now i want direct call to my client so we both no need to enter room id manually.  How i can do it using webRTC. Welcome, If any idea share here.

**Comment by RangerMauve** [comment]
Have every person listen on a unique channel for "incoming calls" When person A wants to call person B, person A will send a "call" event to person B's channel with a unique room ID. Person A will then join the channel. Person B will get some sort of notification on their phone to tell them to accept the call. Once they accept, they join the room too.

**Comment by saghul** [comment]
I'm closing this, since it's outside of the scope of the plugin itself, applications should take care of the rendezvous in any way they deem appropriate.
