### ISSUE TITLE
xcode setup vs RNPM

### ISSUE THREAD

**Issue by quadsurf** [oney/react-native-webrtc#222]
will there be support in the near for simply running `react-native link react-native-webrtc` to avoid all that xcode setup, or is xcode config the only way? (assuming ios)

**Comment by sagivo** [comment]
@quadsurf we should add it as the xcode setup is not trivial, would you like to suggest a PR for it?

**Comment by saghul** [comment]
I don't think it's possible, due to the embedded framework. If anyone knows a way around it, please feel free to open a PR. Cheers!
