### ISSUE TITLE
How do you configure the audio stream's output?

### ISSUE THREAD

**Issue by deqyd** [oney/react-native-webrtc#225]
Hey @oney,

How do you configure the webrtc audio stream (RTCView component) to output audio to the device's main speaker instead of the receiver speaker?

**Comment by saghul** [comment]
This package doesn't provide APIs for that. You can take a look at https://github.com/zxcpoiu/react-native-incall-manager

**Comment by deqyd** [comment]
Thanks @saghul. I will try to use it again and post back why it may not be working for my specific project.

**Comment by deqyd** [comment]
This worked well. Thanks again.

**Comment by thedevxen** [comment]
I am still not able to figure out how to do it? Can anyone tell me please.... I am wasting hours to make a call from one phone to another, but it's not working...
