### ISSUE TITLE
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/oney/WebRTCModule/BuildConfig;

### ISSUE THREAD

**Issue by nickkapoor** [oney/react-native-webrtc#227]
I am wondering if someone has run into this issue.  Where the build on the android (which was working till yesterday) is now giving me an error.  I had installed the react-native-permissions library, react-native-maps(which I removed because it was causing problems in the build too. Unlinked it with the react-native unlink command).  

I have cleaned the cache, removed the webrtc and re-installed it.  At a total loss. 
If someone has run into this issue and has been able to resolve it, would greatly appreciate the help.

Thanks

**Comment by jjdp** [comment]
try adding:

    android {
      ...
      defaultConfig {
        ...
        multiDexEnabled true

**Comment by zxcpoiu** [comment]
@nickkapoor 

does adding support for multiDex solves your problem?

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by nickkapoor** [comment]
I do have multidex set to true. Given up on using react native for android. Too many issues with memory being freed up for a highly image based solution.

**Comment by montao** [comment]
I have the same issue. 

`Multiple dex files define Lcom/oney/WebRTCModule/WebRTCModulePackage`

**Comment by montao** [comment]
_does adding support for multiDex solves your problem?_

No. The error persists. I checked that the module is included only once in the code.
