### ISSUE TITLE
In android,when set RTCView full screen,and setState to change render,the screen is black.

### ISSUE THREAD

**Issue by zhenlovezhen2012** [oney/react-native-webrtc#23]
In android,when set RTCView full screen,and setState to change render,the screen is black.

When I changed windowWidth to 200 rather than Dimensions.get('window') and changed windowHeight to 200 rather than Dimensions.get('window'),it works fine.

But in iOS，it also works fine.

Is this a bug in android？

The code is:
```javascript
	constructor() {
		super();
		this.state = {
			desktopShareSocketId: null,
			videoURL: null,
			showBackButton: true,
			showDesktopShare: false,
			windowWidth: Dimensions.get('window').width,
			windowHeight: Dimensions.get('window').height
		};
	}

	render() {
		return (
			<View style={stylesGlobal.container}>
				{ this.state.showDesktopShare == true ? (<TouchableHighlight
					onPress={ this._onPressShareScreen.bind(this) }
					underlayColor="#ff00ff00"
				>
					<RTCView style={{width: this.state.windowWidth, height: this.state.windowHeight}}
					         streamURL={this.state.videoURL}/>
				</TouchableHighlight>) :  (<View></View>) }
				{ this._renderBackButton() }
			</View>
		);
	}
```
When I stop desktopShare and setState to change render:
```javascript
that.setState({
    videoURL: null,
    desktopShareSocketId: null,
    windowWidth:0,
    windowHeight:0,
    showBackButton: true,
    showDesktopShare: false
});
```
The screen is change to black;
There are some pictures.

Before setState:

![screenshot_2016-03-01-16-34-55_com showmyscreen](https://cloud.githubusercontent.com/assets/6262638/13421854/eb2a0b42-dfcb-11e5-9fce-13c6058c71e2.png)

After setState:
![screenshot_2016-03-01-16-35-47_com showmyscreen](https://cloud.githubusercontent.com/assets/6262638/13421891/2da1d202-dfcc-11e5-869e-9898918d6fc7.png)

**Comment by oney** [comment]
Please change to
```javascript
windowWidth: Dimensions.get('window').width,
windowHeight: Dimensions.get('window').height
```

**Comment by zhenlovezhen2012** [comment]
Sorry,I have used this，it also not work.

**Comment by oney** [comment]
Can you print it?
```javascript
console.log(Dimensions.get('window'));
```

**Comment by zhenlovezhen2012** [comment]
The following is the console:
``javascript
Dimensions.get('window'): Object {width: 360, height: 640, scale: 3, fontScale: 3}
``

**Comment by oney** [comment]
Still not solved?

**Comment by zxcpoiu** [comment]
please verify it on the latest version again.
feel free to reopen if the problem still occurs.
