### ISSUE TITLE
audio only communication

### ISSUE THREAD

**Issue by zxcpoiu** [oney/react-native-webrtc#24]
Hi Oney,

I'm trying to get audio only communication to work and having no lucks now.
Since every examples are all video based, my question is:

* should audio-only rendering use RTCView or use some components like react-native-audio?
* if `mediaConstraints={"audio": true, "video": false}` then it should not include video related ice info in sdp right?

If it needs to do some PR, please shed some light on it, i'd like to do that.
Thanks for the great job.

**Comment by oney** [comment]
Yes, it support audio-only.
You can just use PeerConnection and don't set stream's URL to a RTCView

**Comment by zxcpoiu** [comment]
Thanks! I'll try it!

**Comment by jeremyong** [comment]
Sorry to comment on an old issue but the resolution wasn't clear to me. If we aren't supposed to use an RTCView, what should we use instead? For an audio only stream the toURL method returns just the id of the stream.

**Comment by zxcpoiu** [comment]
yeh, it's weird at the first glance. ( to me, still even now )

You can treat it like:

webrtc native library invoke native audio player for you after connection established and stop when the connection finished.

so all you have to do is to make sure connection is successfully established. ( set sdp description and exchange signals )

**Comment by edolix** [comment]
Hi! Sorry but the resolution is not clear to me too.
I not able to obtain an SDP **without** video informations. 
The first call to _peer.createOffer_ returns a SDP with video even if i didn't load stream before. (I do not use "getUserMedia" at all!)

Thanks for this project and support!

**Comment by zxcpoiu** [comment]
The default constraints is both enable audio and video.

if you want a audio only sdp, be sure to pass `OfferToReceiveVideo: false` (see: https://github.com/oney/react-native-webrtc/blob/master/RTCPeerConnection.js#L44-L50)
when creating peer connection and/or create offer

and `{video: false}` constraints when `getUserMedia`

**Comment by edolix** [comment]
Ok @zxcpoiu, thank you!

**Comment by quangvinh2080** [comment]
Hi. Sorry because I have the same issue and the resolution still not work for me. 
I'm trying to find a way to play media got from the `peerConnection.onaddstream`. Currently, its callback got a stream after I send invite but I still can't hear any stream media

My peer.onaddstream handler
```
peer.onaddstream = function(event) {
     var remoteStream = event.stream;
     var tracks = remoteStream.getTracks();
     peer.getStats(tracks[0]).then((stats) => {
        console.log(stats, 'stats');
     });
     setStream(remoteStream.toURL());
};
```
The setStream will change state of RTCView's streamURL props. I already tried to remove it but still not work

```
sip.invitecontext.sessionDescriptionHandler | SessionDescriptionHandlerOptions: {"constraints":{},"peerConnectionOptions":{}}
sip.invitecontext.sessionDescriptionHandler | initPeerConnection
sip.invitecontext.sessionDescriptionHandler | New peer connection created
sip.invitecontext.sessionDescriptionHandler | acquiring local media
sip.invitecontext.sessionDescriptionHandler | acquired local media streams
sip.invitecontext.sessionDescriptionHandler | createOffer
sip.invitecontext.sessionDescriptionHandler | resetIceGatheringComplete
sip.invitecontext.sessionDescriptionHandler | Setting local sdp.
sip.invitecontext.sessionDescriptionHandler | sdp is v=0
o=- 3327275265645139439 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS E548D7C5-50FD-4374-A092-3179C3982A11
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:W2/u
a=ice-pwd:UO6aSo88KPivxArCyDan6ryy
a=ice-options:trickle renomination
a=fingerprint:sha-256 10:A3:47:04:68:1F:33:CC:E7:9A:A3:4D:82:96:8C:58:54:94:AC:99:CC:E3:25:B8:37:85:58:50:C2:84:F6:BD
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1153752113 cname:LztCtlZcGUG6q611
a=ssrc:1153752113 msid:E548D7C5-50FD-4374-A092-3179C3982A11 B72DE834-233B-482F-BBAD-32F0E5EE4277
a=ssrc:1153752113 mslabel:E548D7C5-50FD-4374-A092-3179C3982A11
a=ssrc:1153752113 label:B72DE834-233B-482F-BBAD-32F0E5EE4277
sip.invitecontext.sessionDescriptionHandler | waitForIceGatheringComplete
sip.invitecontext.sessionDescriptionHandler | ICE is not complete. Returning promise
sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: gathering
sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:917273023 1 udp 2122260223 192.168.10.19 64106 typ host generation 0 ufrag W2/u network-id 1 network-cost 10
sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3085205259 1 udp 1686052607 1.53.3.242 64106 typ srflx raddr 192.168.10.19 rport 64106 generation 0 ufrag W2/u network-id 1 network-cost 10
sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2016380239 1 tcp 1518280447 192.168.10.19 51465 typ host tcptype passive generation 0 ufrag W2/u network-id 1 network-cost 10
sip.invitecontext.sessionDescriptionHandler | ICE candidate gathering complete
sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: complete
sip.invite-dialog | INVITE dialog mnp2ka5v4stt2vfa9djg84mttrpge3rgp04aXK3jreS constructed
sip.invitecontext.sessionDescriptionHandler | ICE Connection State changed to iceConnectionChecking
sip.invite-dialog | INVITE dialog mnp2ka5v4stt2vfa9djg84mttrpge3rgp04aXK3jreS sending ACK request
sip.invite-dialog | INVITE dialog mnp2ka5v4stt2vfa9djg84mttrpge3rgp04aXK3jreS received BYE request
sip.inviteclientcontext | closing INVITE session mnp2ka5v4stt2vfa9djg84mttrpge3
sip.invitecontext.sessionDescriptionHandler | closing PeerConnection
sip.invitecontext.sessionDescriptionHandler | resetIceGatheringComplete
sip.invite-dialog | INVITE dialog mnp2ka5v4stt2vfa9djg84mttrpge3rgp04aXK3jreS destroyed
sip.invitecontext.sessionDescriptionHandler | ICE Connection State changed to iceConnectionClosed
```

Thanks so much for all the support !

**Comment by RamanSB** [comment]
I'm slightly confused by the proposed solution in this Issue... On the web, HTML AudioElements can handle the remoteStream URL and can play audio. We can detect when this audio starts by leveraging event handlers like "`onplay`"...

How do we achieve this on mobile? As @quangvinh2080 pointed out invoking .toURL() on the remoteStream and trying to create a sound with suppose 'expo-av' will not result in the correct output, as expo-av requires a network URL not one from WebRTC, still confused about how to go about this, anyone got a proposed solution?

Ideally I want to be able to track the duration of time the remoteStream is playing on one of my peers.

**Comment by saghul** [comment]
It's currently not possible to do that. Remote audio is played automatically.
