### ISSUE TITLE
INVITE sdp does not include any ICE candidates

### ISSUE THREAD

**Issue by elbow** [oney/react-native-webrtc#242]
Hi,

We're trying to make a test Android app using React Native and jssip.  (We had to slightly modify jssip to work against react-native-webrtc).

I'm finding that the SDP sent by our client app does not include any ICE candidate lines (a=candidate). By contrast the SDP coming from Chrome includes candidate lines for the expected addresses.

The client is calling to a Freeswitch system which rejects the call, presumably since it can't perform ICE with no candidates.

The test phone is on a private IP address in case that it relevant.  There is no NAT between the phone and the Freeswitch system.

We added a log message to the icecandidate event listener and we do get events for the expected ICE candidates but the a=candidate lines don't get added to the generated SDP.

Do we need to do something different with react-native-webrtc ? In the Chrome client we didn't do anything special to have this work.

I'm looking for some pointers as to how to investigate this.

Thanks,
Steve

**Comment by michaelstephendavies** [comment]
So I did some more investigating and it seems JsSIP has nothing to do with it. If I run this in a browser:

```js
navigator.getUserMedia({audio: true, video: false}, um => {
  let rpc = new RTCPeerConnection();
  rpc.addStream(um);
  rpc.addEventListener("icecandidate", cand => {
    console.log(cand);
    console.log(""+rpc.localDescription.sdp);
  });
  rpc.createOffer(desc => {
  	console.log(desc.sdp);
    rpc.setLocalDescription(desc, () => {}, () => {});
  }, () => {}, {
      mandatory: {
          OfferToReceiveAudio: 'true',
          OfferToReceiveVideo: 'false'
      }
  });
}, () => {});
```
Then it logs some SDP without any ICE candidates, then after they come in it logs the same SDP but now with the ICE candidates.

Running the same code in react-native:

```js
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from "react";
import {AppRegistry, StyleSheet, Text, View, Button} from "react-native";

import WebRTC, {RTCPeerConnection, RTCIceCandidate, RTCSessionDescription, MediaStream, MediaStreamTrack, getUserMedia} from 'react-native-webrtc';

//import JsSIP from "./jssip";

export default class HelloWorld extends Component {
  constructor() {
    super();
    this.state = {connected: false, failed: false, timer: 0};
  }

  componentDidMount() {
    getUserMedia({audio: true, video: false}, um => {
      let rpc = new RTCPeerConnection();
      rpc.addStream(um);
      rpc.addEventListener("icecandidate", cand => {
        console.log(cand);
        console.log(""+rpc.localDescription.sdp);
      });
      rpc.createOffer(desc => {
        console.log(desc.sdp);
        rpc.setLocalDescription(desc, () => {}, () => {});
      }, () => {}, {
          mandatory: {
              OfferToReceiveAudio: 'true',
              OfferToReceiveVideo: 'false'
          }
      });
    }, () => {});
  }

  render() {
    return <View><Text>hello</Text></View>;
  }
}

AppRegistry.registerComponent("HelloWorld", () => HelloWorld);
```
And in the debug console, the SDP never contains any ICE candidates.

This is running react-native-webrtc as of commit `cbe0c73` (latest as of 6 days ago).

**Comment by saghul** [comment]
Do you see the icecandidate event firing? ICE candidates may come later, if you need an SDP with them all you can wait until you get a null candidate (signal of end) and get the SDP. It will contain them at that time.

**Comment by michaelstephendavies** [comment]
Yes, I do get icecandidate events. JsSIP does wait for the null candidate. But in react-native I'm finding that the SDP does not contain ice candidates even after the null candidate signal.

**Comment by zxcpoiu** [comment]
You must invoke `createOffer` or `createAnswer`  AGAIN AFTER all ice candidates has been gathered

**Comment by michaelstephendavies** [comment]
Okay. Is it necessary to `setLocalDescription` with the new SDP from the second `createOffer`?

**Comment by zxcpoiu** [comment]
you don't have to call `setLocalDescription` again after second `createOffer`

**Comment by thenewvu** [comment]
@elbow , @michaelstephendavies: Could you guys share modifications for jssip that make it work on react-native-webrtc ? I'm also working on these technologies, hope to have some help from you. Thank you.

**Comment by allcomsh** [comment]
what modifications you made for jssip to use with react-native-webrtc? @elbow @michaelstephendavies @thenewvu

**Comment by thenewvu** [comment]
@allcomsh: You can see my patches here: https://github.com/thenewvu/JsSIP/tree/v0.7.11-react-native

**Comment by murugancmi** [comment]
@thenewvu  jssip work with react native ?

**Comment by thenewvu** [comment]
@murugancmi Yes

**Comment by murugancmi** [comment]
where i can find the code

**Comment by thenewvu** [comment]
@murugancmi I can't share the code from the project I'm working on, but for patches that needed to make JsSIP runnable, you can see in:
* https://github.com/thenewvu/JsSIP/tree/v0.7.11-react-native
* https://github.com/thenewvu/react-native-webrtc/tree/brekeke

**Comment by murugancmi** [comment]
@thenewvu  i am getting codec INCOMPATIBLE_DESTINATION in freeswitch,Can i now react-native-webrtc suport codecs

**Comment by thenewvu** [comment]
@murugancmi I never worked on freeswitch before, sorry, I'm not sure.

**Comment by murugancmi** [comment]
react-native-webrtc support codecs?

**Comment by murugancmi** [comment]
@thenewvu  Thanks for your good time :+1:

**Comment by allcomsh** [comment]
@murugancmi not work for freeswitch, check the ways you collect candidates and how to send them to freeswitch.

**Comment by TimMeade** [comment]
@murugancmi INCOMPATABLE_DESTINATION on Freeswitch most likely is a CODEC issue.   Check your codecs on both legs of the call.

**Comment by seven1240** [comment]
You need to add apply-candidate-acl to sofia profile to make it work in FreeSWITCH, check verto.conf.xml for reference.

**Comment by AdilSoomro** [comment]
@thenewvu I tried your ports, JsSIP fails to find the webrtc. What can be wrong?

I added JsSIP and rn-webrtc through npm and replaced both of node modules with yours ports. JsSIP registers fine through SIP. But when placing or receiving call, JsSIP produces an error saying webrtc not found.

**Comment by manuquentin** [comment]
Hi @zxcpoiu,
Just for information, why do you need to do another `createOffer` again after ice candidates are gathered ?
Is it specific to `react-native-webrtc` ?

Thanks !

**Comment by zxcpoiu** [comment]
@manuquentin

Because ice gathering is asynchronous, every time an candidates gathered will be stored in to local ice agent. When you call `crateOffer`, it just return `currently gathered` ice candidates stored in memory.

So if you want to includes all ice candidates once in a sdp, either you collect every ice candidates from events and inject it into your sdp, or you can just wait till ice gathering finished ( and it stored in ice agent internally ) then call `createOffer` again.

webrtc acts as `ice trickling` by default, if I recall it correctly, earlier version of chrome do wait for all ice candidates for you ( or is pre-gathered, I don't know. ) when you call craeteOffer.

Both js and native implementation of webrtc may be vary between mobile and web.

**Comment by fukemy** [comment]
@zxcpoiu , hi, did u mean i need wait some second to setLocalDesc after createAnswer?

**Comment by fukemy** [comment]
hi @zxcpoiu , i have same problem with remote peerConnection. I dont know why only remote peer got Ice failed:
 Here is my code:
 
 ```
let joinResponse = await this.sendAsync({
        request: "join",
        room: this.roomID,
        pin: this.pin,
        ptype: "subscriber",
        feed: publisher.id,
        private_id: privateID,
      });
      
      console.log('receive => joinResponse')

      if (
        joinResponse &&
        joinResponse.plugindata &&
        joinResponse.plugindata.data &&
        joinResponse.plugindata.data.videoroom === "attached"
      ) {
      }

      const remote = {
        sdp: joinResponse.jsep.sdp,
        type: joinResponse.jsep.type,
      }
      
      try{
        await this.pc.setRemoteDescription(remote);
        this.isRemoteDescriptionSet = true;
        console.log('set other user remoteDesc success')
      }catch(error){
          console.log('setRemoteDescription error', error)
      }

      let answer = await this.pc.createAnswer({
        offerToReceiveAudio: audio,
        offerToReceiveVideo: video,
      });

      await this.pc.setLocalDescription(answer);

      console.log('receive setLocalDescription succes')
      for (const candidate of this.cachedCandidates) {
        await this.pc.addIceCandidate(candidate);
      }
      this.cachedCandidates = [];

      const startResponse = await this.sendAsyncWithJsep(
        {
          request: "start",
          room: this.roomID,
        },
        {
          type: answer.type,
          sdp: answer.sdp,
        }
      );
      console.log('receive => startResponse', this.cachedCandidates)
```

When create remote peer, i saw this candidate sdpMid = '0', can u help me to explain? I really dont know why

**Comment by saghul** [comment]
This issue is years old, please don't post further comments. Specially if you keep asking the same question across multiple issues.

**Comment by fukemy** [comment]
thanks, i created new issues already
