### ISSUE TITLE
Is there a way to watch the stream with only one user?

### ISSUE THREAD

**Issue by LoseTheQuit** [oney/react-native-webrtc#245]
I have it working in a way that allows me to watch myself if i'm the first one in the room, anyone who joins to watch the stream from a different phone will see a video of the first person in the room recording. The way that it works now is that two people have to be in a room for the stream/video to start - my question is, how can one watch the stream by himself - not needed two people in a room for the stream to start>?

**Comment by saghul** [comment]
That fully depends on your application. If you requested video from the user you already have a video track which you can render using a RTCView. Doing that for local or remote video streams is up to your application, there is nothing specific about it in this plugin.

**Comment by LoseTheQuit** [comment]
it only shows a video if two people are in the room - I want to see the video of myself when i stream, when i'm the first one in the room. There is no video track produced when you begin the stream by yourself, care to see my code>?
