### ISSUE TITLE
Prepare M57 release

### ISSUE THREAD

**Issue by saghul** [oney/react-native-webrtc#248]
I think we should make the M57 release in npm. Google just announced M58 is in beta: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/13BE3fbHcLU/bQJWNBihBgAJ so I'll get a M58 build sometime soon.

I'll land https://github.com/oney/react-native-webrtc/pull/247 later today, and we should be set for it.

@zxcpoiu what do you think?

**Comment by zxcpoiu** [comment]
sounds great, ping me once you merged all necessary PRs.
then I will release to npm with some release note.

**Comment by zxcpoiu** [comment]
I didn't test any beta version before.
would it be hard to maintain if we use webrtc beta version in master, or beta version is relatively stable enough?

**Comment by saghul** [comment]
> I didn't test any beta version before.
> would it be hard to maintain if we use webrtc beta version in master, or beta version is relatively stable enough?

I was thinking on creating a M58 branch for people to start playing with. Then once it hits stable / we are comfortable with it, we would merge to master.

**Comment by saghul** [comment]
> sounds great, ping me once you merged all necessary PRs.
> then I will release to npm with some release note.

Awesome, will do!

**Comment by saghul** [comment]
@zxcpoiu I landed #247. Go ahead with the release when you have time. Thanks a lot!

**Comment by saghul** [comment]
@zxcpoiu I updated the wiki and readme.

**Comment by zxcpoiu** [comment]
thanks mate!
released!

**Comment by saghul** [comment]
Excellent! Thanks a lot! 👏 🎉
