### ISSUE TITLE
On android set RTCView streamUrl error

### ISSUE THREAD

**Issue by zhenlovezhen2012** [oney/react-native-webrtc#25]
If only get audio and set the RTCView streamUrl error:

![screenshot_2016-03-07-17-12-05_com showmyscreen](https://cloud.githubusercontent.com/assets/6262638/13566503/e0185d2a-e490-11e5-8383-4e4b7c5f8035.png)

```javascript

navigator.getUserMedia({
			"audio": true,
			"video": false
		}, function (stream) {
                        this.setState({localMediaStream: stream});
		}, function (err) {
			console.log("createAudioStream err: ", err);
		});
	}

<RTCView style={{width: 150, height: 150}} streamURL={this.state.stream}/>

```

On componentDidMount:

```javascript

this.setState({
			stream:this.state.localMediaStream.toURL()
		});

```

**Comment by oney** [comment]
If you only use audio, do not set a stream to RTCView. It will still have audio connection.
