### ISSUE TITLE
Recoding and streaming audio to external server

### ISSUE THREAD

**Issue by cayasso** [oney/react-native-webrtc#255]
Hi, I would like to create a voice command app, using https://api.ai for this I am thinking on something very similar to Whatsapp voice messages feature where user press button recording starts and when user release button then recording stops and audio is sent (in my case would be send to a NodeJS server or directly to API.ai). My plan is to stream the audio via SocketIO.
What would be the best way to accomplish the above using `react-native-webrtc`? specially the streaming part, sending chunks as they are recorded?

The approach is similar to this https://subvisual.co/blog/posts/39-tutorial-html-audio-capture-streaming-to-node-js-no-browser-extensions

Or to this (but with NodeJS) https://dzone.com/articles/record-audio-using-webrtc

Any help would be much appreciated. Thanks!

**Comment by zxcpoiu** [comment]
at least in current library, recording API is not implemented/tested yet.

so if you want to streaming real time audio, either your node server or API.ai supports establish audio streaming via ICE negotiate. ( mock as another peer )

once negotiated, on your media server or mocked peer proxy, you can forward your RTP packets to anywhere you want.

**Comment by HeroSony** [comment]
Hi @cayasso, Now it's 2019. Did you find solutions?
