### ISSUE TITLE
Crash in android 7.0

### ISSUE THREAD

**Issue by swaroopa94** [oney/react-native-webrtc#257]
Hi,

In android 7.0 my app getting crash immediately after entering into the room
It showing an error as shown in below screenshot:
![screen shot 2017-04-18 at 2 25 17 pm](https://cloud.githubusercontent.com/assets/19324363/25122980/77fd869e-2444-11e7-9048-24ac7fbaa9c6.png)

Please tell me how to resolve it.
Thank you

**Comment by zxcpoiu** [comment]
it does't seem like a webrtc issue.

have you tried to remove webrtc and see if the problem exist?

**Comment by swaroopa94** [comment]
no I will try it

**Comment by saghul** [comment]
The crash seems to happen in some orientation module, not WebRTC. Closing.
