### ISSUE TITLE
dyld: Symbol not found: _AVCaptureSessionInterruptionReasonKey

### ISSUE THREAD

**Issue by kangshaojun** [oney/react-native-webrtc#259]
dyld: Symbol not found: _AVCaptureSessionInterruptionReasonKey
  Referenced from: /private/var/mobile/Containers/Bundle/Application/BCA15B8F-E2B1-495B-83BB-26C17DA84A38/CloudWebRTC.app/Frameworks/WebRTC.framework/WebRTC (which was built for iOS 9.0)
  Expected in: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 in /private/var/mobile/Containers/Bundle/Application/BCA15B8F-E2B1-495B-83BB-26C17DA84A38/CloudWebRTC.app/Frameworks/WebRTC.framework/WebRTC

when i  use ios8 debug the  rn webrtc  will trace this error,you can compile the webrtc library remove this render.

my qq is:283796665

**Comment by saghul** [comment]
We only support iOS >= 9, if you try to use it in iOS 8 problems are expected as it's an unsupported version.

**Comment by kangshaojun** [comment]
ok ， thank you for  your answer

**Comment by tuanhm93** [comment]
@kangshaojun you can use master branch with ios 8 by replace webrtc.framework of branch rn-less-40 and change #import <WebRTC/RTCLegacyStatsReport.h> to #import <WebRTC/RTCStatsReport.h>
in WebRTCModule+RTCPeerConnection.m. Hope this help
