### ISSUE TITLE
Success is not a function

### ISSUE THREAD

**Issue by camwhite** [oney/react-native-webrtc#26]
![img_2342](https://cloud.githubusercontent.com/assets/6933346/13625759/a46dbf28-e5ed-11e5-8595-7caa8b4cfc52.PNG)

Only appears on the device of the user who initiated the call.. And once dismissed a successful connection is made. Any ideas?

**Comment by zhenlovezhen2012** [comment]
Hello,you can see the 60 lines in your node_modules/react-native-webrtc/RTCPeerConnection.js,
you should use setLocalDescription like:
```javascript

pc.setLocalDescription(session_desc, ()=> {
                                      //success callback
					},()=>{
                                      // failed callback
});

```

**Comment by camwhite** [comment]
You're right I was missing the error cb on setting the local description! However, I am still seeing the same error on the initiating device..
