### ISSUE TITLE
Cannot establish connect after submitted to TestFlight 

### ISSUE THREAD

**Issue by wandonye** [oney/react-native-webrtc#260]
I'm using version ^0.54.3.

It works well when I run the app on my iPhone with Xcode, but once I submit it to TestFlight and download it from there, I cannot get connected. Any idea?

Is it related to entitlement? Because when I upload it to TestFlight, the entitlement of WebRTCframework is 0. But I was able to upload without any warn or error

<img width="535" alt="screen shot 2017-04-22 at 3 54 15 pm" src="https://cloud.githubusercontent.com/assets/7805834/25308140/45d9210e-2774-11e7-892c-c77b8e47f69c.png">

**Comment by saghul** [comment]
No idea. Do you see anything in the logs? Are you using HTTP instead of HTTPS?

**Comment by wandonye** [comment]
I eventually figured out the problem: 
Microsoft CodePush is the one to blame.
