### ISSUE TITLE
Calling _switchCamera freezes video

### ISSUE THREAD

**Issue by thehappycoder** [oney/react-native-webrtc#264]
When I call track._switchCamera(), video freezes for both sender and receiver.

Is it normal or there is some step I am missing? Couldn't find any example code that uses this method.

**Comment by saghul** [comment]
It's a custom API to toggle cameras, but it shouldn't cause any freeze. What platform are you on? We use in on [Jitsi Meet](https://github.com/jitsi/jitsi-meet/) to toggle cameras.

**Comment by thehappycoder** [comment]
@saghul Thanks! I will check out Jitsi Meet source code next week.

It freezed for me when I ran an app on iOS and switched the camera.

**Comment by saghul** [comment]
I can't reproduce that, I'm afraid :-S Works here...

**Comment by thehappycoder** [comment]
@saghul It's works for me too. I'll reopen this if freeze occurs again.

Thanks for your help, mate!

Jitsi Meet looks nice by the way! :-)
