### ISSUE TITLE
High level differences between this project and Janus

### ISSUE THREAD

**Issue by hamsal** [oney/react-native-webrtc#265]
This is not an issue but I needed a way to ask so I posted here.

I am curious to hear how this compact solution contrasts with the more heavyweight Janus and why someone would use Janus over this when Janus is much more complicated? A few use cases or examples to aid explanation would be great.

**Comment by zxcpoiu** [comment]
the best place to ask this sort of questions is ask on StackOverflow.

here are the short answer:

webrtc simply helps you to achieve the following things on devices/machines:

1. get media from device
2. gathering network info
3. generates SDP and render media accordingly.

the exchange of sdp ( signal ) leaves up to you --- you may use any kind of protocol even invented by yourself.

if you want to achieve more high level / abstract functionalities such as conference / call forward / pstn/ss7 bridging / voicemail / virtual ippbx extension manageents... etc. you need to implement all the signal / authentication parts on both client and server.

there are lots of frameworks. and again, you can treat webrtc is a media helper which generates sdps and negotiating for you to the remote party according to what you feed it.
