### ISSUE TITLE
How to toggle video on and off during a call?

### ISSUE THREAD

**Issue by EdmundMai** [oney/react-native-webrtc#268]
I want to allow my users to toggle the video stream on and off (while keeping the audio stream).
Is this possible? Also is there a way to detect this from the peer's end (the 2nd person)?

P.S. I'm not referring to `getUserMedia({ video: false })`. I want to toggle the video on and off after the call is established.

**Comment by thehappycoder** [comment]
Did you try MediaStreamTrack.enable method?

**Comment by EdmundMai** [comment]
Looks like this should do the job: https://github.com/oney/react-native-webrtc/blob/793143ba68e720388d4d5e69011fc472d32f87ca/MediaStream.js#L76

But is there a way to detect from the other person's end that the videoTrack has been disabled? (like a callback on Person B's end that Person A has shut off their camera?)

I don't want to just show a black screen when this happens

**Comment by thehappycoder** [comment]
Actually, it's a property, not a method. My mistake.

When I disabled a track, peer sees frozen video in my case.

**Comment by EdmundMai** [comment]
Yea I want to be able to respond to that event so that I can update the UI for Person B. Seeing a frozen video isn't very user friendly

**Comment by EdmundMai** [comment]
I eventually used a dataChannel for this.
