### ISSUE TITLE
Can't build iOS after 

### ISSUE THREAD

**Issue by kralcifer-ms** [oney/react-native-webrtc#271]
Simplest repro I have is to follow the React Native steps for pulling the 2048 repo and getting it running with React Native, then following your steps here: https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md but it immediately can't compile because WebRTCModule.m can't find 'React/RCTBridge.h'.  If I do a new (rather than existing iOS) via 'react-native init foo' I notice that it generates the proper include paths in '<root>/ios/build/Build/Products/Debug-*' but I'm not sure why the CocoaPods way of including React Native isn't doing this for me.

**Comment by saghul** [comment]
Are you using CocoaPods? If so, how does your Podfile look like?

**Comment by kralcifer-ms** [comment]
I am and React Native is in there but I was doing the manual dependency steps you guys mentioned, mostly because it talks about "instead of steps 2 through 5, but you might still have to do step 6 above" but there's only 4 steps so it was unclear to me what your pod would do.  I'll try to do yours as a pod and see what happens.  Here's my current Podfile:

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'swift-2048' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  target 'swift-2048Tests' do
    inherit! :search_paths
  end

end

**Comment by saghul** [comment]
@kralcifer-ms So, after you do `pod install`, what error do you get? How are you building your application?

**Comment by kralcifer-ms** [comment]
Just doing a 'Build and run the current scheme' default when opening the xcworkspace of swift2048.

/Users/kralferch/source/react/RN2048-2/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m:3:9: 'React/RCTBridge.h' file not found

**Comment by kralcifer-ms** [comment]
I did a version with react-native-webrtc brought in to clean swift2048 (with working React Native, no Native Modules) via cocoa pods and getting the same error.  Here's what that pod file looks like (had to change target to '9.0':

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'swift-2048' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  target 'swift-2048Tests' do
    inherit! :search_paths
  end

end
```

**Comment by saghul** [comment]
Ah, I think I know. When using `use_frameworks` the headers are not copied to the right place. Do you have anything in your ios/Pods/Headers/ directory?

**Comment by kralcifer-ms** [comment]
iOS/Pods/Headers directory is empty.

I commented out use_frameworks but now the Swift code that integrates React Native fails on 'import React' saying "No such module 'React'".

Now I need to figure out how to get the two to work together.  Commenting out generates the headers but fails in Swift and uncommenting fails headers but succeeds with Swift.

```
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
```

Some progress though!  Any more ideas?

**Comment by kralcifer-ms** [comment]
Any chance you can look into getting your stuff to work with use_frameworks for swift apps?

I pursued a script that copies the React headers like mentioned in this link: https://github.com/CocoaPods/CocoaPods/issues/4605

named it 'copy_react_headers.sh':

```
#!/bin/bash

cd Pods/Headers

rm -rf Public/React
mkdir -p Public/React
cd Public/React
for f in ../../../../../node_modules/react-native/React/**/*.h
do
    ln -s $f
done
for f in ../../../../../node_modules/react-native/Libraries/**/*.h
do
    ln -s $f
done


cd ../..
rm -rf Public/Yoga
mkdir Public/Yoga
cd Public/Yoga
for f in ../../../../../node_modules/react-native/ReactCommon/yoga/yoga/*.h
do
    ln -s $f
done
```

and I'm now getting linker errors:

Undefined symbols for architecture x86_64:
  "_RCTRegisterModule", referenced from:
      +[RTCVideoViewManager load] in RTCVideoViewManager.o
      +[WebRTCModule load] in WebRTCModule.o
  "_OBJC_CLASS_$_RCTConvert", referenced from:
      objc-class-ref in RCTConvert+WebRTC.o
      l_OBJC_$_CATEGORY_RCTConvert_$_WebRTC in RCTConvert+WebRTC.o
      objc-class-ref in RTCVideoViewManager.o
  "_OBJC_CLASS_$_RCTViewManager", referenced from:
      _OBJC_CLASS_$_RTCVideoViewManager in RTCVideoViewManager.o
  "_OBJC_METACLASS_$_RCTViewManager", referenced from:
      _OBJC_METACLASS_$_RTCVideoViewManager in RTCVideoViewManager.o
  "__RCTLogNativeInternal", referenced from:
      +[RCTConvert(WebRTC) RTCSessionDescription:] in RCTConvert+WebRTC.o
      +[RCTConvert(WebRTC) RTCIceCandidate:] in RCTConvert+WebRTC.o
      +[RCTConvert(WebRTC) RTCIceServer:] in RCTConvert+WebRTC.o
      +[RCTConvert(WebRTC) RTCConfiguration:] in RCTConvert+WebRTC.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kralcifer-ms** [comment]
search for "use_frameworks! linker error _RCTRegisterModule" resulted in https://github.com/CocoaPods/CocoaPods/issues/4792 which seems similar.

Not seeing any solution that will help me yet.

**Comment by kralcifer-ms** [comment]
These links describe our situation as well I think:
https://github.com/facebook/react-native/issues/579
https://github.com/facebook/react-native/pull/1228

**Comment by saghul** [comment]
Yep, I ran into those too. My conclusion was to not use CocoaPods if using Swift. If you manage to figure it out, a PR would be more than welcome!

**Comment by saghul** [comment]
I'm closing this since it's not an issue this plugin can address, but a wider one in CocoaPods.
