### ISSUE TITLE
borderRadius does not work on Android

### ISSUE THREAD

**Issue by EdmundMai** [oney/react-native-webrtc#272]
I'm trying to add a borderRadius to my RTCView and it's not working. Even worse, when I try to work around it by wrapping it in a View that has a borderRadius, it ignores it and stays squared.

```
const styles = StyleSheet.create({
  remoteVideoContainer: {
    borderRadius: 50,
    height: 100,
    marginBottom: 20,
    width: 100,
    overflow: 'hidden',
    backgroundColor: 'green',
  },
  video: {
    flex: 1,
    resizeMode: 'cover',
    backgroundColor: 'blue',
  },
});

export default VideoView = ({
  videoURL,
}) => {
  return (
    <View style={styles.remoteVideoContainer}>
      <RTCView
        style={styles.video}
        streamURL={videoURL}
        mirror={true}
        objectFit="cover"
      />
    </View>
  );
};
```

**Comment by EdmundMai** [comment]
This could be a react native issue. I don't think borderRadius works on android as of RN 0.44

**Comment by zyofeng** [comment]
Border Radius works as of 0.51
However applying it to RTCView does not have any effect, please advise

**Comment by vinh-smartdev** [comment]
I have exactly same issue

**Comment by khushal87** [comment]
Me too having the same issue

**Comment by 8BallBomBom** [comment]
Are you by any chance rendering an RTCView on top of another RTCView?
If so, things like border radius won't work correctly at least on Android without extra work.

**Comment by khushal87** [comment]
What kind of extra work might fix it? Were you able to fix it somehow? @8BallBomBom

**Comment by 8BallBomBom** [comment]
You'd essentially have to implement your own native view using something like TextureView.
Best to look into how SurfaceView works before hand.

This might be fixed at some point with a re-implementation due to the new RN ARCH and Module handling but i can't really say as of yet as i'm unsure of the future road map.

**Comment by Bayramito** [comment]
> You'd essentially have to implement your own native view using something like TextureView. Best to look into how SurfaceView works before hand.
> 
> This might be fixed at some point with a re-implementation due to the new RN ARCH and Module handling but i can't really say as of yet as i'm unsure of the future road map.

is there any example of this method ? as of 2024 still the issue exists

**Comment by 8BallBomBom** [comment]
Haven't found any decent examples but did come across [this](https://github.com/ibitcy/react-native-hole-view) recently.
It might not work, unsure as I've not tested.
Worth a shot.

If it does work, maybe we could do something similar.
