### ISSUE TITLE
The lastest webrtc  can't work with jitsi-videobridge

### ISSUE THREAD

**Issue by richmonkey** [oney/react-native-webrtc#273]
WebRTC.framework can't contains x86 code when submit to appstore.
I used the latest webrtc(commitid:144475b3286f4de5059e0333044a72faf5d0171c) source to compile my webrtc.framework(only contains arm code)
but it can't work with jitsi-videobridge
my fork is https://github.com/richmonkey/react-native-webrtc

**Comment by richmonkey** [comment]
jitsi videobridge commit id:c65f68acd7046b1a517a985d2dc0a75186bb855b

**Comment by richmonkey** [comment]
jicofo commit id:0676b569277fec9d05fc14e386bf83026a1c67ab

**Comment by saghul** [comment]
This has nothing to do with the Jitsi Video Bridge. This plugin has always had x86 in it, for the Simulator to work. 

You can follow the instructions [here](https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md#app-store-submission) to remove non-arm architectures when submitting to the store. Or use lipo by hand, whatever suits you.

If you make your own builds you should make them from the same commits we do (see commit logs).
