### ISSUE TITLE
iOS: crash when locking + unlocking phone

### ISSUE THREAD

**Issue by philikon** [oney/react-native-webrtc#274]
Locking the phone and unlocking it after a short while seems to lead to random crashes immediately or within a few seconds of unlocking. The problem is intermittent and can't always be reproduced, but it definitely occurs fairly frequently. I can reproduce this with https://github.com/oney/RCTWebRTCDemo as well as my own apps. WebRTC's native sample app (AppRTCMobile) does not have this problem.

Has anyone else run into this? Any ideas?

**Comment by zxcpoiu** [comment]
is it related to this in https://github.com/oney/react-native-webrtc/pull/249#issuecomment-301212802 ?

**Comment by zxcpoiu** [comment]
based on your commit in https://github.com/oney/RCTWebRTCDemo/pull/52/commits/f01cc5cfdafc327d440bb7567f81bb2b42f85b4c
> The latest commit appears to be a workaround for oney/react-native-webrtc#274, but the underlying issue is not solved.

what do you mean by underlying issue?

my personal use case is an **audio only** app and had set `UIBackgroundModes` with `audio/voip` from the beginning, from my perspective, `UIBackgroundModes` with `audio/voip` is necessary to webrtc-based app (except you only using data channel) rather than a workaround.

not sure the reason, but seems [jitsi-meet has set `UIBackgroundModes` with `audio/voip` as well](https://github.com/jitsi/jitsi-meet/blob/master/ios/app/Info.plist#L69)

**Comment by philikon** [comment]
> what do you mean by underlying issue?

That WebRTC will very likely crash when you lock and unlock the phone.

> `UIBackgroundModes` with audio/voip is necessary to webrtc-based app (except you only using data channel) rather than a workaround.

Well, right, if you're using only datachannels or one-way audio/video that does not need survive when you background the app, I think there should be a way to make that work. But it seems that WebRTC provides no such way. One cannot even close any PeerConnections that are active because such an operation would be asynchronous and there's not enough time allowance from iOS.

It seems you are right in the sense that any WebRTC application is *required* to declare `audio` and `voip`.

**Comment by zxcpoiu** [comment]
yep, those background operations always makes me headache :(

if webrtc does not provide a way for self-closing-without-crash, one possible way might be closing all webrtc object in app events when it move to background.

**Comment by saghul** [comment]
> is it related to this in #249 (comment) ?

Those had nothing to do with background operation.

**Comment by saghul** [comment]
@philikon What kind of crash do you get? Is your app allowed to run in the background as per Apple's rules?

**Comment by philikon** [comment]
I get SIGPIPE. I specifically want to avoid the `voip` and `audio` background modes.

I'm fairly confident this is a WebRTC bug. I filed https://bugs.chromium.org/p/webrtc/issues/detail?id=7686. For now, the work around is to disable all SIGPIPE signals for the process (see my comment in the WebRTC bug.)

**Comment by saghul** [comment]
I see. I'm going to go ahead and close this since there is nothing actionable for us until WebRTC fixes it. Please holler once a fix lands so we can include it in the next build (though I try to keep track).

**Comment by jjdp** [comment]
seems fixed https://bugs.chromium.org/p/webrtc/issues/detail?id=7686

**Comment by saghul** [comment]
Thanks for the heads up, I'll cherry-pick it for the next build.
