### ISSUE TITLE
Detect if the user is speaking or not

### ISSUE THREAD

**Issue by atyenoria** [oney/react-native-webrtc#276]
Is it possible to detect if the user is speaking or not?
In the web, hark.js ( https://github.com/otalk/hark ) enables this.
Does anyone has some clues about this?

**Comment by saghul** [comment]
That's not going to work with this plugin, since there is no AudioContext available, and even if there was, it wouldn't work with our MediaStream objects.

See https://github.com/oney/react-native-webrtc/issues/10

**Comment by jadbox** [comment]
@saghul why is it not possible to get an AudioContext?

**Comment by saghul** [comment]
@jadbox Because the execution environment (React Native) doesn't provide one. Of course one could go all-in and implement it, but I don't think that's in the scope of this project.

**Comment by jadbox** [comment]
It seems like react-native is a dead end for us then. I've even thought about just using a webview to do webrtc so that I can monitor the audio, but video permissions on the webview is also an issue.
https://github.com/facebook/react-native/issues/11610

**Comment by saghul** [comment]
@jadbox I don't want to sound condescending, but that's how it should be done, except when you want to show the local volume, for example. We (Jitsi) do audio levels server side, and so does Janus now. This makes sense because you can normalize the values there.

As for local metering of the stream, you can do it with getStats too, but alas, calling it very often is a performance killer on react-native due to the excessive ping-ponging across threads and the cost of serialization.

**Comment by jadbox** [comment]
@saghul thanks for the heads up, appreciated. Can you point me where Jitsi exposes audio levels (or better, detects talking) on the server side?

**Comment by sagark1510** [comment]
@jadbox  @saghul @atyenoria Any updates or solution on this issue?

**Comment by kostiantyn-solianyk** [comment]
Also interested.

**Comment by LukaGotcha** [comment]
This should do the trick. Implementation in react

` 
const [abortRecording, setAbortRecording] = useState<any>();
const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    const speechEvents = hark(stream);

    // When speech starts
    speechEvents.on("speaking", () => {
      console.log("Speaking");
    });

    // When speech stops
    speechEvents.on("stopped_speaking", () => {
      setAbortRecording(
        setTimeout(() => {
          //Do something
        }, 1000)
      );
    });`
    
    Where setAbortRecording resets timeout everytime user starts to speak again.

**Comment by LukaGotcha** [comment]
This should do the trick. Implementation in react

    
    const [abortRecording, setAbortRecording] = useState<any>();
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    const speechEvents = hark(stream);

    // When speech starts
    speechEvents.on("speaking", () => {
      console.log("Speaking");
    });

    // When speech stops
    speechEvents.on("stopped_speaking", () => {
      setAbortRecording(
        setTimeout(() => {
          //Do something
        }, 1000)
      );
    }); 
    
    
Where setAbortRecording resets timeout everytime user starts to speak again.

**Comment by xuergo** [comment]
> This should do the trick. Implementation in react. With the usage of **hark** library you can detect if user is speaking or not
> 
> ```
> const [abortRecording, setAbortRecording] = useState<any>();
> const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
> const speechEvents = hark(stream);
> 
> // When speech starts
> speechEvents.on("speaking", () => {
>   console.log("Speaking");
> });
> 
> // When speech stops
> speechEvents.on("stopped_speaking", () => {
>   setAbortRecording(
>     setTimeout(() => {
>       //Do something
>     }, 1000)
>   );
> }); 
> ```
> 
> Where setAbortRecording resets timeout everytime user starts to speak again.

This is react native
