### ISSUE TITLE
Issue with DataChannel between browser

### ISSUE THREAD

**Issue by rockwotj** [oney/react-native-webrtc#277]
Hello, I'm trying to establish a webrtc connection between a browser and this library over a data channel but get the following failure on the browser:

```
Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Data channel type mismatch. Expected RTP, got SCTP..
```

Which is odd, but I'm using the same config to create them, both taken from [this article](http://www.justgoscha.com/programming/2014/03/07/simple-webrtc-datachannel-establishment-for-dummies.html). Are there any recommendations for debugging? Thanks!

**Comment by saghul** [comment]
That article recommends using RTP data channels, which is deprecated, and not supported by this plugin. Remove `{'RtpDataChannels': true }` from your code and it should work.

I would also recommend you look at a more recent example, such as this one: https://webrtc.github.io/samples/src/content/datachannel/basic/
