### ISSUE TITLE
Can you add this method for stream object?

### ISSUE THREAD

**Issue by zhenlovezhen2012** [oney/react-native-webrtc#28]
This would allow the voice mute，I really need this method，Thank you very much.
```javascript

localMediaStream.getAudioTracks()[0].enabled = false;

```

**Comment by oney** [comment]
I have plan to support it. Maybe 1 week later.

**Comment by voidvoxel** [comment]
@zhenlovezhen2012 pc.removeStream(localStream) works for muting for me.

**Comment by zhenlovezhen2012** [comment]
@voidvoxel Thanks voidvoxel .Actually I also thought about this solution，but I think this is not the best solution.If we use "localMediaStream.getAudioTracks()[0].enabled = false",the pc only emit an event of onicecandidate.If the scene is many-to-many,if we use "removeStream" method ,we must remove  pc's localStream from every pc object.
Thank you again.
My English is not  good, I hope you can understand. ~.~

**Comment by voidvoxel** [comment]
@zhenlovezhen2012 yeah, that makes sense. I didn't even think about that because my app only allows one-to-one. Thanks for the issue; this would be very helpful in the future :)

**Comment by dguillamot** [comment]
Hi, is this (ability to enable/disable individual tracks) under development?

**Comment by oney** [comment]
Not yet.

**Comment by dguillamot** [comment]
Thanks. I dont mind to create  PR for it myself but I think I need access to RTCMediaStream.m
