### ISSUE TITLE
Broadcasting and Bandwidth problem

### ISSUE THREAD

**Issue by VinZenTz1989** [oney/react-native-webrtc#282]
I'd like to live stream via camera from the mobile as CCTV that anyone can watch via their mobile phone. But, I'm curious that how much bandwidth I need to use? 

Can I use bandwidth just single set and everyone can see the same content?

**Comment by saghul** [comment]
You are going to need a server for the broadcasting part. With this library you can send a stream of WebRTC video somewhere, but supporting multiple connected clients should probably be handled with a server side component. An HD video stream will take about 2mbps.
