### ISSUE TITLE
Vidyo.io (or any PaaS solution) integration

### ISSUE THREAD

**Issue by ethan605** [oney/react-native-webrtc#287]
Hi, my primary need is to use some existing services to handle all the backend stuffs (STUN, TURN, ICE, Data channels stuffs,...), so I have some options (Vidyo, OpenTok,...). But can we integrate such PaaS solutions to our WebRTC client?

As what I've read in their [documents](https://developer.vidyo.io/documentation/4-1-13-4/getting-started), they support Javascript (for web browsers only), native iOS & Android. I doubt that there's no straight way to connect `react-native-web-rtc` to their endpoint servers.

Do you have any other way that can solve this problem? Thanks

**Comment by TheChuckster** [comment]
If they support WebRTC, there isn't much they can really do to _break_ WebRTC support.

**Comment by ethan605** [comment]
@TheChuckster doesn't really understand your point, what do you mean exactly?

**Comment by TheChuckster** [comment]
Start hacking. First thing I would try is setting the STUN and TURN servers manually to theirs. If that doesn't do it, take a look at the browser WebRTC calls being made in their example code, and sniff the SDP packets.

**Comment by TheChuckster** [comment]
Whatever they're doing has GOTTA be WebRTC under the hood, so it's just a question of how much finagling it will take to get it to work.

**Comment by saghul** [comment]
@ethan605 React Native is not quite like a browser, but you may make it look enough like one so you can use the JavaScript API. We pretty much do that with Jitsi Meet.

At any rate, integrating with any PaaS is out of the scope of this plugin, so I'm going to go ahead and close this.
