### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by dangnelson** [oney/react-native-webrtc#290]
Are you familiar with Expo? Would it be possible to run a version of this using Expo's existing audio and video components?

[https://docs.expo.io/versions/v17.0.0/sdk/audio.html](https://docs.expo.io/versions/v17.0.0/sdk/audio.html)

[https://docs.expo.io/versions/v17.0.0/sdk/video.html](https://docs.expo.io/versions/v17.0.0/sdk/video.html)

**Comment by saghul** [comment]
I don't think those components can be used. Since we use WebRTC a regular video player won't do, we provideo our own view which can render WebRTC streams.
