### ISSUE TITLE
WebRTC support in iOS 11

### ISSUE THREAD

**Issue by idibidiart** [oney/react-native-webrtc#291]
Does WebRTC support in iOS 11 mean that iOS itself now has public APIs for WebRTC or will we have to use a WebView and run JS in it to get to it? I'm asking in case it's possible to leverage the new support in iOS 11 for WebRTC to simplify this library. Asking naively...

**Comment by saghul** [comment]
No. WebRTC is exposed in Safari and possibly the WebView (I haven't tested the latter). But native applications will continue needing to provide their own SDK.

WebRTC got integrated into WebKit, not as a system framework.

**Comment by davidperrenoud** [comment]
Still, what are the advantages of react-native-webrtc instead of using a WKWebView on iOS 11?

And is it possible to make a call between an app using react-native-webrtc and Safari on iOS 11, as only the H.264 codec is supported?

**Comment by saghul** [comment]
> Still, what are the advantages of react-native-webrtc instead of using a WKWebView on iOS 11?

This plugin is **native**. A `WKWebView` is a web view, with all its advantages and limitations. This plugin is bound to be updated more frequently than iOS, for one. This plugin has VP8 support too.

> And is it possible to make a call between an app using react-native-webrtc and Safari on iOS 11, as only the H.264 codec is supported?

Yes. This plugin supports both H.264 and VP8 for video.
