### ISSUE TITLE
RTCVideoView has no propType for native prop RTCVideoView.nativeID of native type String

### ISSUE THREAD

**Issue by vuquangthinh** [oney/react-native-webrtc#292]
Yesterday, I tried react-native-webrtc with react-native:
This is my dependences:

		"react": "16.0.0-alpha.12",
		"react-native": "0.45.0",
		"react-native-webrtc": "^1.57.1",
		"socket.io-client": "^2.0.2"

I used js code in demo: https://github.com/oney/RCTWebRTCDemo
and install: https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

but i got error:
RTCVideoView has no propType for native prop RTCVideoView.nativeID of native type String

this is my screen of android (Android 6, Xiaomi 4 LTE):
![c3aalo8](https://user-images.githubusercontent.com/1710072/26924525-70093fc4-4c70-11e7-80c1-3dbac37d1e5d.png)

Thank you for reading

**Comment by telecmi** [comment]
I am also getting same error if i change my react and react-native version 

"react": "16.0.0-alpha.6",
"react-native": "0.44.0",

its works fine

**Comment by saghul** [comment]
I am not seeing this on 0.42.

**Comment by rafser01** [comment]
It works for me : 

> open this file "node_modules/react-native-webrtc/RTCView.js"
> Remove or comment Object "View" at line number 59-69;
> And add new Object "View" ; 
`const View = requireNativeComponent("RTCVideoView", RTCView, {
  nativeOnly: {
    testID: true,
    accessibilityComponentType: true,
    renderToHardwareTextureAndroid: true,
    accessibilityLabel: true,
    accessibilityLiveRegion: true,
    importantForAccessibility: true,
    onLayout: true,
    nativeID: true
  }
});`

**a prop types were missing "nativeID"**
