### ISSUE TITLE
setRemoteDescription Error

### ISSUE THREAD

**Issue by liberatomota-itcenter** [oney/react-native-webrtc#293]
Hello,

I'm getting this error on `setRemoteDescription`.
```
{
   message:"Failed to set remote offer sdp: Failed to create channels."
   name:"SetRemoteDescriptionFailed"
}
```

When the error occur the peer is closed and the call terminated.
This just happens when the call direction is android-->ios. The other way around never fails.

Spend all day searching for an answer but couldn't get it to work...

The code that calls the method:
```
function createAnswer() {
		console.log("--------> createAnswer", options);
		if (options.type != "answer") return;

		//options.offerSDP.sdp = addStereo(options.offerSDP.sdp);
		peer.setRemoteDescription(new RTCSessionDescription(options.offerSDP), onSdpSuccess, onSdpError);
		peer.createAnswer(function (sessionDescription) {
				sessionDescription.sdp = serializeSdp(sessionDescription.sdp);
				peer.setLocalDescription(sessionDescription, () => {}, () => {});
				if (options.onAnswerSDP) {
					options.onAnswerSDP(sessionDescription);
				}
			},
			onSdpError);
	}
```

Thank you

**Comment by saghul** [comment]
Can you paste the failing SDP? Do you manually mangle it in any way?

**Comment by liberatomota-itcenter** [comment]
Here are the two sdp,

android->ios, ERROR:
```
"v=0
o=FreeSWITCH 1496980496 1496980497 IN IP4 192.168.1.138
s=FreeSWITCH
c=IN IP4 192.168.1.138
t=0 0
a=msid-semantic: WMS 1pxwJINGfhoRimWwKjD5G0jZCN4bfQ77
m=audio 16386 RTP/SAVPF 102 0 8
a=rtpmap:102 opus/48000/2
a=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=fingerprint:sha-256 E8:FA:E9:99:BE:C3:B9:4E:82:C1:65:55:CA:85:AC:D3:E5:D6:E3:FD:43:3F:0F:B9:E2:A5:5B:6E:38:DF:7D:9D
a=setup:actpass
a=rtcp-mux
a=rtcp:16386 IN IP4 192.168.1.138
a=ssrc:1531022306 cname:5utE27a8eoQmBCJb
a=ssrc:1531022306 msid:1pxwJINGfhoRimWwKjD5G0jZCN4bfQ77 a0
a=ssrc:1531022306 mslabel:1pxwJINGfhoRimWwKjD5G0jZCN4bfQ77
a=ssrc:1531022306 label:1pxwJINGfhoRimWwKjD5G0jZCN4bfQ77a0
a=ice-ufrag:Lc6i3g7vU2xZIuWD
a=ice-pwd:Og8Hd9GhomuPO4Rq6OyZVwlF
a=candidate:0226448714 1 udp 659136 192.168.1.138 16386 typ host generation 0
a=candidate:0226448714 2 udp 659136 192.168.1.138 16386 typ host generation 0
a=silenceSupp:off - - - -
a=ptime:20
a=sendrecv
"
```

ios->android, SUCCESS:
```
"v=0
o=FreeSWITCH 1496980567 1496980568 IN IP4 192.168.1.138
s=FreeSWITCH
c=IN IP4 192.168.1.138
t=0 0
a=msid-semantic: WMS sAl5xwefA5aszPc1HmrwifUmi3Egh7AA
m=audio 16418 RTP/SAVPF 102 0 8
a=rtpmap:102 opus/48000/2
a=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=fingerprint:sha-256 E8:FA:E9:99:BE:C3:B9:4E:82:C1:65:55:CA:85:AC:D3:E5:D6:E3:FD:43:3F:0F:B9:E2:A5:5B:6E:38:DF:7D:9D
a=setup:actpass
a=rtcp-mux
a=rtcp:16418 IN IP4 192.168.1.138
a=ssrc:1531022409 cname:yMvV8A1zw1SWGUNe
a=ssrc:1531022409 msid:sAl5xwefA5aszPc1HmrwifUmi3Egh7AA a0
a=ssrc:1531022409 mslabel:sAl5xwefA5aszPc1HmrwifUmi3Egh7AA
a=ssrc:1531022409 label:sAl5xwefA5aszPc1HmrwifUmi3Egh7AAa0
a=ice-ufrag:65AeblrjeVplTQMh
a=ice-pwd:s83ryURVMzHjkknggOlhZCq3
a=candidate:7074839340 1 udp 659136 192.168.1.138 16418 typ host generation 0
a=candidate:7074839340 2 udp 659136 192.168.1.138 16418 typ host generation 0
a=silenceSupp:off - - - -
a=ptime:20
a=sendrecv
"
```

**Comment by saghul** [comment]
> android->ios, ERROR:

Wait, we don't generate the SDP here, FreeSWITCH is. So the problem is not Android calling iOS, it's FreeSWITCH calling iOS, right?

One thing you could try is to remove this line:

```
a=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40
```

Does that help?

**Comment by liberatomota-itcenter** [comment]
Even without that line the sdp failed.
I also tested with an ipad to see if the problem could be device specific but the error still occurs.

Can you advise me how to debug this?

Really need to start receiving call in apple devices :)

**Comment by saghul** [comment]
> Can you advise me how to debug this?

I wish there was a better way, but alas, there isn't. Take an SDP generated by the device and look at the differences.

This line should also go, FWIW: 

```
a=rtcp:16418 IN IP4 192.168.1.138
``` 

And there doesn't seem to be BUNDLE

**Comment by liberatomota-itcenter** [comment]
What I tested,

- removing all the `a=rtcp` lines: fails
- adding the BUNDLE line and `a=mid:audio` after `a=setup:actpass`: crashes the app
- change peer configuration (bundlePolicy and RTCRtcpMuxPolicy): fails

Tried a lot of combinations of the above 3 to no success.

I will keep trying...

**Comment by allcomsh** [comment]
I have the same problem, it works on Android (receiving incoming freeswitch call) but it does not work on any IOS.  any progress?
Some thing must be wrong or not compatible in the IOS libRTCWebRTC.a. If any one have the debug version of libRCTWebRTC.a should be able to debug it. What the version of libRTCWebRTC.a of IOS? 
 @oney

**Comment by allcomsh** [comment]
@liberatomota-itcenter @oney 
can you compile a new version of libRTCWebRTC.a for IOS or debug the libRTCWebRTC.a to see what's wrong with sdp from freeswitch?
because Android works, IOS does not.

**Comment by allcomsh** [comment]
on IOS setRemoteDescription failed on this sdp: 
v=0
o=FreeSWITCH 1498632779 1498632780 IN IP4 192.168.0.134
s=FreeSWITCH
c=IN IP4 192.168.0.134
t=0 0
a=msid-semantic: WMS 0YrTR4MfqCsdSbLzYe5msbl1hiOSZHOQ
m=audio 22880 RTP/SAVPF 0 8
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=fingerprint:sha-256 64:87:C3:D9:F6:04:F9:5E:32:45:32:4F:B3:57:D5:EC:10:D9:74:1A:D2:FF:0B:CF:0F:9C:CC:86:FD:55:3F:2D
a=setup:actpass
a=rtcp-mux
a=rtcp:22880 IN IP4 192.168.0.134
a=ssrc:2035809883 cname:v5zc0bigEBkmDWLr
a=ssrc:2035809883 msid:0YrTR4MfqCsdSbLzYe5msbl1hiOSZHOQ a0
a=ssrc:2035809883 mslabel:0YrTR4MfqCsdSbLzYe5msbl1hiOSZHOQ
a=ssrc:2035809883 label:0YrTR4MfqCsdSbLzYe5msbl1hiOSZHOQa0
a=ice-ufrag:1HDjJPaQYPzNmetH
a=ice-pwd:aSJ0US7pjiBM5d3WLx5kc610
a=candidate:2261573942 1 udp 659136 192.168.0.134 22880 typ host generation 0
a=candidate:2261573942 2 udp 659136 192.168.0.134 22880 typ host generation 0
a=silenceSupp:off - - - -
a=ptime:20
a=sendrecv

**Comment by zxcpoiu** [comment]
@allcomsh 

you can use build scripts in tools to rebuild

**Comment by zxcpoiu** [comment]
if you guys are using something like FreeSwitch / Asterisk, I think you should do:

* set webrtc constraints `bundlePolicy` to `balanced` in java and objc. I guess it is because android and ios has different default `bundlePolicy` value in c++ library. 

or 

* make sure your server send SDP with `a=group BUNDLE xxx` before `m` line and `a=mid xxx` in each m line 


let me know if it works

**Comment by allcomsh** [comment]
the second works, thanks a lot. @zxcpoiu @liberatomota-itcenter 
I thought I tried the first method before and it does not work.

**Comment by liberatomota-itcenter** [comment]
Mounting a app test to validate. 
@allcomsh can you past the success SDP sended from the server?

**Comment by allcomsh** [comment]
a=group:BUNDLE audio
m=audio 30592 RTP/SAVPF 0 8 3 9
a=mid:audio

**Comment by allcomsh** [comment]
just as @zxcpoiu said

**Comment by liberatomota-itcenter** [comment]
Can confirm that it worked although now I have no sound...
But this bug can be closed because the error no longer appears.
Thanks  to all for the feedback

**Comment by denyspozniak** [comment]
Hello!
Can you explain why it is important to have a=group:BUNDLE/a=mid, without it webrtc side answers SIP 488 ?

**Comment by zxcpoiu** [comment]
@denyspozniak 

because webrtc native library uses [Negotiating Media Multiplexing Using the Session Description Protocol
                                 (SDP)](https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-39)

**Comment by denyspozniak** [comment]
What about legacy endpoint support?
https://webrtcstandards.info/sdp-bundle/
_Note that max-compat is the most likely to be backwards compatible with non-BUNDLE-aware legacy devices._

**Comment by zxcpoiu** [comment]
I'm not familiar with it, so I can not be sure if it works in your use case, sorry.
This plugin is a wrapper of native webrtc and pass your constraints like bundle policy into it.
I believe webrtc-discuss forum is a better place to get help for your question.

**Comment by denyspozniak** [comment]
Ok. Thank you very much!
