### ISSUE TITLE
Is it currently possible to record the audio in a call?

### ISSUE THREAD

**Issue by marcusegues** [oney/react-native-webrtc#294]

**Comment by saghul** [comment]
Nope, the media recorder API (which I'm not sure if the SDK exposes) is not implemented.

**Comment by saghul** [comment]
Given how mobiles work, I think the best way to accomplish this is by recording the audio at the system level, not in this plugin.

**Comment by machester4** [comment]
@saghul  you have an idea how I can record the system audio with React Native?

**Comment by xoapit** [comment]
I am trying to record the audio. I use react-native-audio-record the audio. It works for me on iOS but Android is not able to. Do you have other solutions?

**Comment by alexivaner** [comment]
@xoapit I want to make sure, does it work as well using react-native-audio-record for remote audio? Is it only for recording local audio track? Thanks

**Comment by saghul** [comment]
I don't know if that will work.
