### ISSUE TITLE
Enable/disable individual local tracks

### ISSUE THREAD

**Issue by jmesquita** [oney/react-native-webrtc#299]
I'm trying to implement a mute/unmute function and I'm having a hard time getting the local tracks as getLocalTracks() is not implemented. How would one get the tracks being used in order to be able to set enable/disable? Is there a way with the current implementation?

**Comment by zxcpoiu** [comment]
If you are referring to mute the local stream.
below is an example

```javascript
setMute(mute, localMediaStream) {
    let tracks = localMediaStream.getTracks();
    // --- you might want to check is it an audio or video
    if (tracks.length > 0) {
        tracks.forEach((element, index, array) => {
            element.enabled = mute; // --- enable/disable local track
        })  
        InCallManager.setMicrophoneMute(mute); // --- use incall manager to turn on/off mic
    }   
}   
```

**Comment by jmesquita** [comment]
I am referring to that indeed but rather how do I get access to the stream
from the peerconnection object. There you are passing the localMediaStream
object on the function. Do you save a reference to that object instead of
fetching it from peerconnection?

**Comment by zxcpoiu** [comment]
Yes, I save a stream object reference currently.
