### ISSUE TITLE
Error: 'document is not defined' from JSONPPolling.prototype.doPoll - socket.io.js:1085

### ISSUE THREAD

**Issue by wzywno** [oney/react-native-webrtc#30]
Hi,
I wanted to add webrtc to my project. I successfully started demo app, it was great.
Now when I try to copy implementation from demo I get error:

<img width="292" alt="screen shot 2016-03-15 at 18 28 13" src="https://cloud.githubusercontent.com/assets/1249754/13787304/b6c124f6-eadb-11e5-8114-444a1b6f65ff.png">

Any clue will be helpful

**Comment by wzywno** [comment]
it happens both on ios and android

**Comment by parthi82** [comment]
This article might help https://medium.com/@ekryski/how-to-actually-use-socket-io-in-react-native-39082d8d6172#.xlyiaqjvf

**Comment by zhenlovezhen2012** [comment]
@parthi82 You are right.

**Comment by wzywno** [comment]
Thank you.
The problem was with user agent (it must be set to 'react native'). When I was debugging in chrome, user agent was set automatically to chrome user agent. When I disabled debugging it started working.
