### ISSUE TITLE
Wrong documentation for iOS installation

### ISSUE THREAD

**Issue by Kenjirou** [oney/react-native-webrtc#301]
How can I make this library work on iOS using Cocoapods?
In your documentation I've found the following:

```
You can use the included podspec in your podfile to take care of all dependencies
instead of manually adding files to the project (instead of steps 2 through 5,
but you might still have to do step 6 above).
```

but _above_ is only 4 steps...

My actions to reproduce the issue:

1. `yarn add react-native-webrtc`
2. add podspec to Podfile in ios folder
3. `cd ios && pod install`
4. `cd .. && react-native link`
5. try to build project in Xcode -> the error appears: `clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by saghul** [comment]
Can you paste the full error?

**Comment by Kenjirou** [comment]
@saghul sure:

```
Apple Mach-O Linker Error Group:
    Linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by saghul** [comment]
That's not the full error. It should give the reason under. You may need to right click and pick "reveal in log file".

**Comment by Kenjirou** [comment]
@saghul here is the screenshot:
![screen shot 2017-06-23 at 16 46 38](https://user-images.githubusercontent.com/13053189/27484985-c02fb43c-5833-11e7-9423-6ace946e94c3.png)

**Comment by saghul** [comment]
The error is "Duplicate symbols for architecture x86_64". Check if you are linking with WebRTC.framework twice.

**Comment by Kenjirou** [comment]
@saghul yeah, you're right - it happens because of `react-native link` command. So, with Cocoapods we don't need to use it after pods have installed.
Thank a lot for your help!
