### ISSUE TITLE
when open the app on Android, there is no video until you input <TextInput> 

### ISSUE THREAD

**Issue by laozhuxinlu** [oney/react-native-webrtc#302]
When i open the app, the video should appear because of:
socket.on('connect', function(data) {
  console.log('connect');
  getLocalStream(true, function(stream) {
    localStream = stream;
    container.setState({selfViewSrc: stream.toURL()});
    container.setState({status: 'ready', info: 'Please enter or create room ID'});
  });
});

Actually, there is no video. But if you focus on <TextInput> , the video will appear.

Why? could everyone help me?

**Comment by saghul** [comment]
Please only report issues relevant to the plugin itself.

**Comment by laozhuxinlu** [comment]
HI all, 


    Why do you think this issue is not relevant to the plugin?


First, I npm install react-native-webrtc from github, and add this plugin to my project, and found the issue that i have reported: when open the app on Android, there is no video until you input <TextInput>


Second, I download the Demo (RCTWebRTCDemo) from github, and also found this issue on this project.


Finally, you can download the project from my GitHub: ReactNative_WebRTC_Demo . It is so simple that just press Connect Button after you install it on your device.


Very sorry to bother all of you. And thank you very much. 






At 2017-06-23 02:24:33, "Saúl Ibarra Corretgé" <notifications@github.com> wrote:


Please only report issues relevant to the plugin itself.

**Comment by zxcpoiu** [comment]
@laozhuxinlu 

This library `react-native-webrtc` is purely a library without any `TextInput / UI element` and will not start automatically, it's like how you use `webrtc` in the browser.

for start a local video, you should invoke `getUserMedia` then render video stream in RTCView.

you will need to invoke it manually based on your app's logic, DEMO app is just one way to demonstrate how it might work.

So what are are asking is more likely a `RCTWebRTCDemo` issue which should be opened there, or a `How to use` issue which should better asked on somehting like StackOverflow.

If you are trying `RCTWebRTCDemo`, you can delete all the codes just focus on

1. how to use `getUserMedia`
2. how to get media stream and render it on `RTCView`

invoke them properly in `ComponentDidMount` then you will have video immediately
