### ISSUE TITLE
Can't work with RN 0.45.1

### ISSUE THREAD

**Issue by LionelWoody** [oney/react-native-webrtc#305]
`RTCVideoView` has no propTypes for native prop `RTCVideoView.nativeID` of native type `String`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync.
Updating both should make this error go away.

verifyPropTypes.js:67:22
requireNativeComponent.js:108:6
RTCView.js:60:36
require.js:174:12

**Comment by LionelWoody** [comment]
back to RN 0.44.x
no error.

**Comment by saghul** [comment]
This was fixed in https://github.com/oney/react-native-webrtc/commit/1b3270f56bb1d4f42d57481ae60b68f3e650906b. Please test using master.
