### ISSUE TITLE
Audio is one way only 

### ISSUE THREAD

**Issue by Jerameel** [oney/react-native-webrtc#307]
Tested on Android Device to Android Emulator, I'm only getting audio from the emulator and receiving it on my android device but is not capable on doing the other way around. Shouldn't it be a two way communication?

**Comment by saghul** [comment]
Yes it should. I suggest you try on a real device, this is known to work properly.

**Comment by Jerameel** [comment]
I have tried on real device, still the same result.

**Comment by zxcpoiu** [comment]
you might want to try:

1. test both side on real device
2. both devices are under the same and simple local wifi
3. configure STUN or TURN if needed
4. exam your sdp

**Comment by Jerameel** [comment]
I tried using a different device, my other device seems to just loop the audio data. Its all working now well with the same unit of phone.
