### ISSUE TITLE
UI freezes

### ISSUE THREAD

**Issue by bsiddiqui** [oney/react-native-webrtc#309]
Once I have established a peer connection the UI freezes. I still see the video stream but buttons either don't receive callbacks or the callbacks are very delayed.

Using latest version.

**Comment by saghul** [comment]
What OS? Are you calling getStats? Was this happening with older versions?

**Comment by bsiddiqui** [comment]
@saghul iOS, `react-native` 0.44.1` - I haven't used previous versions of `react-native-webrtc`

I'm not calling `getStats`. Everything appears to be working correctly. I receive the peer connection, the video and audio streams come through, but all UI interactions outside of the video stream are slow.

This is the function I call when the component mounts to start the connection.
```js
  async beginConnection () {
    const token = encodeURIComponent(`Bearer ${this.props.token}`)

    const peer = this.peer = new RTCPeerConnection({
      iceServers: config.ICE_SERVERS
    })

    const socket = this.socket = io(config.WEBSOCKET_API, {
      query: `authorization=${token}`
    })

    // We already have the peer and socket configured, time to check for
    // the status for the first time
    this.checkStatus()

    socket.on('connect', this.checkStatus)

    peer.onaddstream = event => {
      console.log('adding stream')
      this.setState({ remoteStreamUrl: event.stream.toURL() })
    }

    peer.oniceconnectionstatechange = this.checkStatus
    peer.onsignalingstatechange = this.checkStatus

    this.localStream = await this.getLocalStream()

    this.setState({
      selfStreamUrl: this.localStream.toURL()
    })

    peer.onicecandidate = event => {
      if (event.candidate) {
        socket.emit('candidate', {
          roomId: this.props.appointmentId,
          ...event.candidate
        })
      }
    }

    socket.on('error', capture)

    socket.on('exception', data => {
      capture(new Error('WebRTC signaling exception'), data)
      this.quit(data.message)
    })

    socket.on('initiate', () => {
      peer.createOffer(desc => {
        peer.setLocalDescription(desc, () => {
          socket.emit('offer', {
            roomId: this.props.appointmentId,
            sdp: peer.localDescription
          })
        }, capture)
      }, capture)
    })

    socket.on('offer', data => {
      peer.setRemoteDescription(new RTCSessionDescription(data.sdp), () => {
        peer.createAnswer(desc => {
          peer.setLocalDescription(desc, () => {
            socket.emit('answer', {
              roomId: this.props.appointmentId,
              sdp: peer.localDescription
            })
          }, capture)
        }, capture)
      }, capture)
    })

    socket.on('answer', data => {
      peer.setRemoteDescription(new RTCSessionDescription(data.sdp), noop => noop, capture)
    })

    socket.on('candidate', data => {
      peer.addIceCandidate(new RTCIceCandidate(data))
    })

    socket.on('connect', () => {
      socket.emit('join', {
        roomId: this.props.appointmentId
      })
    })

    socket.on('leave', socketId => {
      console.log('leaving socket: ', socketId)
    })

    socket.on('quit', () => this.quit('The appointment has ended'))

    peer.addStream(this.localStream)
    InCallManager.start({ media: 'video' })
  }
```

**Comment by bsiddiqui** [comment]
More info: upgrading to `react-native` 0.45.1 seems to help when running in Release mode, but still laggy in Debug mode

**Comment by renanpupin** [comment]
@bsiddiqui could you paste your checkStatus function code?

**Comment by bsiddiqui** [comment]
@renanpupin 

```js
  checkStatus = () => {
    const socketIsConnected = this.socket.connected
    const iceConnectionState = this.peer.iceConnectionState
    const connectingStates = ['have-remote-offer', 'stable', 'checking']

    if (!socketIsConnected) {
      return this.setState({ text: 'Joining the session' })
    } else if (iceConnectionState === 'new' || iceConnectionState === 'failed') {
      return this.setState({ 
        text: `Waiting for ${this.props.remoteClientName} to join the Session`
      })
    } else if (connectingStates.includes(iceConnectionState)) {
      return this.setState({
          text: `Connecting you to ${this.props.remoteClientName}`
      })
    } else if (iceConnectionState === 'disconnected') {
      return this.setState({
          text: 'Uh oh, it looks like you\'re experiencing some connection issues. We\'re attempting to reconnect you!'
      })
    } else {
      this.setState({ text: null })
    }
  }
```

**Comment by saghul** [comment]
@bsiddiqui Since you are in iOS I suggest you use Xcode's Instruments a run a CPU profile (https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/MeasuringCPUUse.html). That should give you more insight as for where the issue is.

**Comment by 8BallBomBom** [comment]
#202
I was experiencing something similar as well.
What i did was use [sdp-transform](https://github.com/clux/sdp-transform) as suggested by @saghul to re-order the default video codecs to prefer h264 which then reduced the load quite a bit, no need to set resolutions lower, 720p minimum runs great.

**Comment by bsiddiqui** [comment]
@8BallBomBom so you parse the sdp, change the rtp order, and then re-write it? Do you have a code sample?

**Comment by bsiddiqui** [comment]
@8BallBomBom @saghul I tried parsing the sdp and changing the video media rtp order so the `H265` is first but that didn't really change anything. Maybe I'm doing it wrong?

```js
peer.localDescription.sdp = transformSdp(peer.localDescription.sdp)

transformSdp = sdp => {
    let parsedSdp = transform.parse(sdp)

    parsedSdp.media = parsedSdp.media.map(media => {
      if (media.type === 'video') {
        const baseRtp = [media.rtp.find(rtp => rtp.codec === 'H264')]
        media.rtp = baseRtp.concat(media.rtp)
      }

      return media
    })

    return transform.write(parsedSdp)
}
```

**Comment by saghul** [comment]
make sure you compare ignoring the case, I've seen H264 and h264.

**Comment by 8BallBomBom** [comment]
@bsiddiqui Sorry not been about.
Try applying `string.toLowerCase(` rtp.codec ) === 'h264'`

**Comment by bsiddiqui** [comment]
@saghul I tried ignoring case - still 80-100% cpu usage on iPhone 6 and 7+. Is that normal?

**Comment by saghul** [comment]
Have you verified you are using H.264? You can check that by using a browser on the other end, and checking with chrome://webrtc-internals.

In addition, you might want to give the master branch a try, it has HW accelerated codecs enabled now.

**Comment by bsiddiqui** [comment]
@saghul I'll try verifying in chrome

On master it looks like HW is enabled for android. Is it also enabled for iOS?

**Comment by bsiddiqui** [comment]
@saghul definitely better on master but still uses quite a bit of battery (~1% / minute). I'll close for now and re-open if I'm not using H264 when testing in browser
