### ISSUE TITLE
Using width, height property for RTCView, stretches or shrinks the video. doesn't maintain the original aspect ratio of the video

### ISSUE THREAD

**Issue by parthi82** [oney/react-native-webrtc#31]
Is there a way to set the size of the local and remote video based on the aspect ratio of the video stream so that the video doesn't appear stretched or shrunk

**Comment by zhenlovezhen2012** [comment]
@parthi82  I solved this problem. If you get stream on ios or android, you should send "width:Dimensions.get('window').width,height: Dimensions.get('window').height" to other.Others can scaling  video width and height.

If you get stream in the browser like:
```javascript
this.getUserMedia.call(navigator, {
      audio: false,
      video: true
    }, function (stream) {
      that.localVideoStream = stream;
      var o = document.createElement('video');
      o.autoplay = 'autoplay';
      o.style.width = "500px";
      o.src = URL.createObjectURL(stream);
      document.getElementById('room-wrapper').appendChild(o);
      o.onloadeddata = function () {
        callback(null,stream,o.offsetWidth,o.offsetHeight);
        var _parentElement = o.parentNode;
        if(_parentElement){
          _parentElement.removeChild(o);
        }
      };
    },

```

**Comment by parthi82** [comment]
It would be nice if the video stream could be made to fit in RTCView keeping the original aspect ratio. I think the size of the remote or local video view needs to be recalculated based on the frame size from video stream received. The video view can be animated to a new size, found something like that here:
https://github.com/ISBX/apprtc-ios/blob/master/AppRTC/ARTCVideoChatViewController.m#L205

**Comment by parthi82** [comment]
Or may be something similar to the CSS object-fit: cover 
https://groups.google.com/forum/#!searchin/discuss-webrtc/fit/discuss-webrtc/FnSOHqvFbEw/muRYUaEPOosJ

**Comment by oney** [comment]
It's hard for me to support it now. I will keep it in mind. PRs are welcome.

**Comment by m59peacemaker** [comment]
@oney What is the aspect ratio from getUserMeda? To handle portrait and landscape orientation, is it best to calculate the width and height of the RTCView based on the screen dimensions and that aspect ratio?

**Comment by lyubomir** [comment]
I have aspect preservation (both Android and iOS) and objectFit (iOS and possibly next week Android) in the fork of the Jitsi community: https://github.com/jitsi/react-native-webrtc/commits/lib-jitsi-meet.

**Comment by m59peacemaker** [comment]
@lyubomir Cool. What's the point of the fork? Is there a hope to merge these two repositories? Is the fork published on npm?

**Comment by lyubomir** [comment]
@m59peacemaker, the point of the fork is to allow us - the Jitsi community and Atlassian - to move at our own pace. We have the desire to have our modifications in upstream. Unfortunately, priorities and lots of urgent work don't always allow me to create PRs. I recently asked @oney to please take a look at our commits and cherry-pick whatever he finds useful because I'm swamped with work.

**Comment by lyubomir** [comment]
The property objectFit on RTCView is implemented on both iOS and Android now in https://github.com/jitsi/react-native-webrtc/commit/a5a469282b9f7cd040cfd570a8c4a8479c29b7f3. It allows choosing how the video is to be displayed while preserving the aspect ratio. It follows the specifications for the HTML video element and the CSS property object-fit.

**Comment by lyubomir** [comment]
https://github.com/oney/react-native-webrtc/commit/da9ddf418bf51d7ec55cba3f6613566b7f5bd1b5 and https://github.com/oney/react-native-webrtc/commit/0ce332c9d7099a802343f192d02bf4d2cc5463d7 follow the `HTMLVideoElement` specification as closely as possible and preserve the aspect ratio on iOS and Android, respectively. Additionally, these two commits implement an `objectFit` property on `RTCView` which allows one to control how the video fills the rectangle of `RTCView` similarly to the CSS `object-fit` property:
- `cover` fills the `RTCView`'s width and height, possibly cropping the parts of the video that don't fit in;
- `contain` completely fits the video inside the `RTCView`, possibly leaving horizontal or vertical transparent bars
