### ISSUE TITLE
Very Confused with iOS installation process

### ISSUE THREAD

**Issue by EsdrasEtrenne** [oney/react-native-webrtc#312]
Ok, so I started my project using Expo so I detatched to ExpoKit. That part is fine, but I am taking a look at the step one installation for iOS and I am so confused. It says to right click libraries in Xcode but I dont see that in my project. Libraries in my project so I am concerned I am importing these files to the wrong place. 

Step 4 says I should end up with a certain kind of file structure but my file structure looks nothing like that either. The project I have looks similar to the file structure in step 3, but where am I to find the Xcode file that I am supposed to have open for step one?

In my my_project/ios there is a my_project.xcworkspace that I am told to open in order to run my iOS simulations on the ExpoKit documentation page (see step 3 in following link): https://docs.expo.io/versions/v16.0.0/guides/expokit.html

That is where I tried to do the import of the libraries but I just dont see any Library folder there when the .xcworkspace file is open i just see a my_project folder as well as a Pods folder

<img width="255" alt="screen shot 2017-07-06 at 7 07 00 pm" src="https://user-images.githubusercontent.com/24880491/27937665-5a87f748-627e-11e7-8d2a-289a12419117.png">

This is what my file structure looks like when I follow step one and I'm pretty sure that is wrong

And then lastly, for that script in step 6, where do I copy paste that?

help please

**EDIT:** 

I watched a youtube video and it had step by step instructions. I did not run `react-native-link`. After that the Libraries folder showed up. Here is the video I watched to help install:

https://www.youtube.com/watch?v=1Bm6qoYp8qQ

I still don't understand step 6 though? Where would I paste that script? And would I need to tweak that script at all?

**Comment by zxcpoiu** [comment]
it's nice to see there is an awesome video.

> I still don't understand step 6 though? Where would I paste that script? And would I need to tweak that script at all?

alright, I have ios document updated.
now we have step1 ~ step4 and two appendix

are you referring to appendix B ? please check new document again to see if it solves your problem

https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md

**Comment by EsdrasEtrenne** [comment]
Thank you! yes the update clears the rest up. I was referring to appendix B. I have never had to run a script for this before so I just wasn't sure.

**Comment by zxcpoiu** [comment]
hooray!

**Comment by saghul** [comment]
@zxcpoiu Thanks for doing that! What do you think about putting that script in the "tools/" directory? That way users don't need to copy and paste...

**Comment by zxcpoiu** [comment]
yes sure, will do it soon!

**Comment by zxcpoiu** [comment]
done!

**Comment by saghul** [comment]
Thanks!
