### ISSUE TITLE
Loud Speaker Support

### ISSUE THREAD

**Issue by Jerameel** [oney/react-native-webrtc#314]
Is this supported ? How can we increase the gain from the stream to output to device speaker? 

#### Platform information

* **OS**: Android / iOS

**Comment by saghul** [comment]
It's not supported and I don't think anyone is working in adding support for it.

**Comment by 8BallBomBom** [comment]
I'm currently using this.
https://github.com/zxcpoiu/react-native-incall-manager

Then when a video call gets connected i use this.
`InCallManager.setForceSpeakerphoneOn( true );`
Would use setSpeakerphoneOn instead but it seems iOS doesn't like that.

**Comment by Jerameel** [comment]
I believe force speaker just routes audio to speaker. Im already using the speaker, what i want is a louder volume. 

Normally the volume is just equivalent to an ordinary  telephone call.

**Comment by 8BallBomBom** [comment]
Ahh sorry misunderstood.
I'd suggest looking around, there might be a module for it already >> https://js.coach/
But using a volume beyond the typical limit would normally result in distorted audio and possibly damage to the device speaker over time.

**Comment by Jerameel** [comment]
Or maybe you're right? Is it a different hardware for the normal speaker and the loudspeaker function? for example in common phone calls.

**Comment by saghul** [comment]
Increasing the system volume beyond its limits is definitely out of the scope of this plugin. I'm closing this.
