### ISSUE TITLE
Compilation error when including react-native-webrtc as pod 

### ISSUE THREAD

**Issue by mahmoud-cliqz** [oney/react-native-webrtc#315]
When I try to include react-native-webrtc into my iOS project using CocoaPods, I got compilation errors that the compiler could not find specific files (all files that exist in react core)

#### Expected behavior
Project should compile successfully 

#### Observerd behavior
```/react-native-webrtc/ios/RCTWebRTC/RCTConvert+WebRTC.m:1:
/node_modules/react-native-webrtc/ios/RCTWebRTC/RCTConvert+WebRTC.h:1:9: fatal error: 'React/RCTConvert.h' file not found
#import <React/RCTConvert.h>
        ^
1 error generated.
```
#### Steps to reproduce the problem
Here is my pod file
```
use_frameworks!
target 'Client' do
    
    pod 'React', :path => './node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    ]
    pod 'Yoga', :path => './node_modules/react-native/ReactCommon/yoga'
    pod 'RNFS', :path => './node_modules/react-native-fs'
    pod 'react-native-webrtc', :path => './node_modules/react-native-webrtc'
end
```

**Comment by saghul** [comment]
Is that your entire Podfile?

**Comment by mahmoud-cliqz** [comment]
I have updated the issue (only `Yoga` was missing)

**Comment by saghul** [comment]
Not only. You are using "use_frameworks!", which doesn't work because headers are not copied to the right place. Do you really need that?

**Comment by mahmoud-cliqz** [comment]
I am using  `use_frameworks!` because my app is written using Swift so it is much easier to import React as a framework i.e. I just use `import React` in the top of my swift class

btw I managed to have it working now without removing `use_frameworks!` by modifying `react-native-webrtc.podspec` to add dependency as the following
`s.dependency 			'React/Core'`

Would that be a correct fix?

**Comment by saghul** [comment]
Interesting! Can you make a PR with that? I'll give it a test then.

**Comment by mahmoud-cliqz** [comment]
I did it
Thanks

**Comment by saghul** [comment]
PR landed, closing!
