### ISSUE TITLE
WebView and RTCView playing audio at the same time?

### ISSUE THREAD

**Issue by Jonovono** [oney/react-native-webrtc#318]
#### Expected behavior

I want to have the audio from the WebView and RTCView play at the same time.

#### Observerd behavior

I have a WebView and a RTCView that both play audio. When I render the WebView the audio from the RTCView stops

#### Platform information

* **React Native version**:
0.43.0
* **Plugin version**:
"^1.58.1
* **OS**: 
ios

**Comment by saghul** [comment]
You need to configure the AVAudioSession with the "mixing with others" option.
