### ISSUE TITLE
Android RTCView add  transform style , RTCView is black but ios works fine;

### ISSUE THREAD

**Issue by zhenlovezhen2012** [oney/react-native-webrtc#32]
Android RTCView add  transform style  , RTCView is black but iOS works fine;
Please see the following code:
```javascript
<RTCView
          style={{ width: 300, height: 300, transform: [{rotate: '90deg'}] }}
          streamURL={ this.state.videoURL }
        />
``` 
If remove the transform it works ok：
```javascript
<RTCView
          style={{ width: 300, height: 300}}
          streamURL={ this.state.videoURL }
        />
``` 
I think this is a bug for android RTCView.
If it is not difficult，please fix it.Thank you very much.

**Comment by mgreer** [comment]
This is a bug in React Native: https://github.com/facebook/react-native/issues/3491 and others

**Comment by zxcpoiu** [comment]
thanks @mgreer
