### ISSUE TITLE
[Question] How do I know react-native-webrtc for iOS is use the H264 hardware encoder/decoder?

### ISSUE THREAD

**Issue by starcwl** [oney/react-native-webrtc#323]
I have created a video communication use react-native-webrtc successful. I know it use H264. but I want to know if it is use hardware encoder/decoder.   So how could I check it use hardware or software 
encoder/decoder. 

* **React Native version**: 0.44.3
* **Plugin version**:1.54.7
* **OS**:  iPhone7
* **OS version**:

**Comment by saghul** [comment]
If you are using the current master branch you will be using H264 with HW acceleration, not otherwise. There is no way to check this at runtime AFAIK.
