### ISSUE TITLE
Ready for a new release?

### ISSUE THREAD

**Issue by AaronVasquez** [oney/react-native-webrtc#329]
I see some commits that fixes some of the errors I'm seeing. 

Specifically:
* https://github.com/oney/react-native-webrtc/commit/22e4a3aae252fbe01f8305b4f113f900573d42cd
* https://github.com/oney/react-native-webrtc/commit/1b3270f56bb1d4f42d57481ae60b68f3e650906b

Can we bump the version and have a new release? Is it ready? Thanks!

**Comment by saghul** [comment]
I'm fine with that. @zxcpoiu can you please cut a release when you can? Thanks!

**Comment by zxcpoiu** [comment]
yes of course, I was just not sure if it is stable yet.

done!
