### ISSUE TITLE
Error "Property 'modules' not found on object of type 'RCTBridge *' " when building on RN 0.22.2

### ISSUE THREAD

**Issue by RuRios** [oney/react-native-webrtc#33]
Tried to build a project created using RN 0.22.2 and was not able to build it. Seems like I'm hitting this issue:

RTCVideoViewManager.m:54:40: Property 'modules' not found on object of type 'RCTBridge *'

Any thoughts on how to fix this?

Thanks!

**Comment by HungTran92** [comment]
Same problem!

**Comment by dhrrgn** [comment]
Someone asked about this error in the React Native Community Group on Facebook, and while I don't use this package, I did a little digging, and here is some helpful info:

The `modules` property on `RCTBridge` was deprecated back in November 2015, and removed about 3 weeks ago, hence why this is just now popping up.

Here is the commit that deprecated the property: https://github.com/facebook/react-native/commit/060664fd3d9331f062696e68179bac9cd4544a06

Here is the relevant excerpt from the commit message:

> This diff introduces a better API that will allow modules to be initialized lazily as they are needed, and deprecates `bridge.modules` (modules that use it will still work, but should be rewritten to use `bridge.moduleClasses` or `-[bridge moduleForName/Class:` instead.

**Comment by vespakoen** [comment]
Thanks for the pointer, this seems to work:

```
WebRTCModule *module = [self.bridge moduleForName: @"WebRTCModule"];
```

**Comment by zxcpoiu** [comment]
thanks @vespakoen 
I think the commit is #27

thanks for pointed it out.
seems it doesn't release on npm yet.

cc @oney

**Comment by RuRios** [comment]
Finally had a chance to look into this... closing now. Thanks for your help guys!

**Comment by oney** [comment]
@zxcpoiu I will release it now.
