### ISSUE TITLE
Using ios_arch.js script to switch back to simulator architectures

### ISSUE THREAD

**Issue by bsiddiqui** [oney/react-native-webrtc#330]
I've been using this script to prepare for app store submission and it works well: 
https://github.com/oney/react-native-webrtc/blob/master/tools/ios_arch.js

Whenever I try and run in the simulator after extracting and re-packaging using the script, though, I get an `Undefined symbols for architecture` error.

I tried re-running the script with `--extract` and then `--simulator` but neither commands work.

When I run `--extract` I get this error:
`i386 specified but fat file: WebRTC does not contain that architecture`

I can solve the problem but un-installing and re-installing the `react-native-webrtc` package but it's pretty annoying to have to do that every time after I submit a release to the app store.

**Comment by zxcpoiu** [comment]
All you have to do, is to back up all archs somewhere generated by `--extract`
when you want to repackage, just copy these backup files into the same directory that it was extracted.

let's say the original `WebRTC_orig` binary contains two arch: `arm` and `x86`

after you `--extract`, the script will extract all archs out of binary
then you `--package`, the script will use extracted arch to repackage a new `WebRTC_new`

so if you `--extract` again on `WebRTC_new` which already contains ONLY 1 arch, thus, you can NOT recovery the original `WebRTC_orig` with 2 archs.

**Comment by zxcpoiu** [comment]
Since we never know user's file system structure and user's preference to back up or not. it's not suitable to implement it on script.

Another method you can do without re-install, is to just copy `WebRTC` binary from github as `WebRTC_orig`, then replace your `WebRTC_new`

**Comment by Stas-Buzunko** [comment]
@zxcpoiu 
1. i still don't understand how to achieve this with shell scripts, could you write an example?
2. why isn't it documented in docs?

**Comment by zxcpoiu** [comment]
It's in the ios installation doc

https://github.com/react-native-webrtc/react-native-webrtc/blob/dfe222b2114c7765f837fcdf88cecccb9ac9450a/Documentation/iOSInstallation.md#appendix-b---apple-store-submission
