### ISSUE TITLE
HW acceleration is working, but the HW encoder not use texture surface 

### ISSUE THREAD

**Issue by jiangjianping** [oney/react-native-webrtc#331]
Hi,

The HW acceleration is working now on my two  android devices. I wonder why the HW encoder did not use texture surface, while decode could render to surface?

**Comment by jiangjianping** [comment]
camera1Enumerator is created with "capturetotexture" to false

**Comment by saghul** [comment]
Camera 2 does use textures though. I guess we could set that to true now though.
