### ISSUE TITLE
RTCView is falling behind other RTCView?

### ISSUE THREAD

**Issue by JoostVermeulen11** [oney/react-native-webrtc#337]
I encountered this problem, on Android only. When I create a container over the rtcView, it's ok, but when I put some RTCViews in that container, they're falling behind the other RTCView. Did anyone experienced this to? And does anyone have a solution for this? It's strange, because this only happens when i'm running my app on Android. On iOS it is all ok. You can see at the left of the picture, some stream is shown partially, the rest is falling behind the other RTCView.

![screenshot_20170825-101351](https://user-images.githubusercontent.com/9720909/29705774-d0a5f36c-897f-11e7-8f8b-a4f29d612603.png)

**Comment by lyubomir** [comment]
I think I solved the order by adding a zIndex property on RTCView and, if I remember correctly, that was needed because of Android. Please read the source code of RTCView for details.

**Comment by JoostVermeulen11** [comment]
Thanks! This solved my problem! :)
Needed to add a zOrder property to my RTCViews.
