### ISSUE TITLE
RTCMediaStream.release() doesn't work

### ISSUE THREAD

**Issue by Lichwa** [oney/react-native-webrtc#34]
I've tried this on Android. After using localStream.release() method, it doesn't get dispatched and keeps streaming video from camera.

**Comment by zxcpoiu** [comment]
Does [https://github.com/oney/RCTWebRTCDemo](https://github.com/oney/RCTWebRTCDemo) works?

try it and print some logs at `pc.onremovestream`

**Comment by Lichwa** [comment]
I ran demo project, and it doesn't work either. This is most likely problem with stream itself, I tried changing camera BEFORE establishing any peer connection and stream just stops.

I changed code a little so that I can swap between all created streams. 
After starting application, first stream has an `_id = 1`, upon clicking at `Switch camera` button it gets replaced by new stream with `_id = 2` which is completely blank and when i swapped back to the first stream `id = 1`, it turns out it didn't get dispatched and keeps streaming video from camera.

**Comment by zxcpoiu** [comment]
Oh I see.

MediaStream.release() is just remove the stream from an array hold on native module.
If you really want to stop rendering RTCView, maybe should implement some callback to disable RTCVideoViewManager ( this also need a stop function. )


btw, on android, it doesn't implement peerConnectionRemoveStream yet.

**Comment by oney** [comment]
As @zxcpoiu said, if you want to disconnect the stream and the peer connection, please use `peerConnection.removeStream(stream);`
The purpose of `RTCMediaStream.release()` is releasing the stream that is generated by `getUserMedia`. The reason is that native side can't know when to release the stream. There is no destructor method on Javascript.
```javascript
var localStream;
getUserMedia({"audio": true, "video": true}, function (stream) {
  localStream = stream;
}, logError);
function releaseLocalStream() {
  localStream.release();
  localStream = null;
}
```

I will implement peerConnectionRemoveStream on Android ASAP.

**Comment by zxcpoiu** [comment]
implemented

**Comment by mobileDevNativeCross** [comment]
Could you show example how to switch camera?

**Comment by zxcpoiu** [comment]
Please check https://github.com/oney/RCTWebRTCDemo

**Comment by mobileDevNativeCross** [comment]
@zxcpoiu I tried to switch camera from face to back and video just stuck, in https://github.com/oney/RCTWebRTCDemo project.
I tried on Android.

**Comment by nickkapoor** [comment]
Wondering if the switching of the camera was resolved?  When I switch the camera, it returns a blank screen to the peers.  Additionally, I wanted to know how I can restart the stream if I pause it with   localStream.release();
