### ISSUE TITLE
Compression and Encryption

### ISSUE THREAD

**Issue by Jerameel** [oney/react-native-webrtc#340]
How can we achieve this? I can't figure out where is the actual stream.

**Comment by saghul** [comment]
Achieve what exactly? Audio / video are encoded using different codecs which already compress media and this media is encrypted using DTLS-SRTP.

**Comment by Jerameel** [comment]
I'm pertaining to third party encryption and compression rather than the codec's default. Is it possible to capture the audio stream before transmission and before generating output to speaker?

**Comment by saghul** [comment]
Not at the API level we are using libwebrtc. You would need to modify WebRTC itself. I'm closing this since it's out of the scope of the project, sorry.

**Comment by savaliyap** [comment]
> Not at the API level we are using libwebrtc. You would need to modify WebRTC itself. I'm closing this since it's out of the scope of the project, sorry.

Hi @saghul , how'd I implement DTLS-SRTP.? any leads would be appreciated

**Comment by saghul** [comment]
It's already implemented and used by default. There is no way to use WebRTC without it.

**Comment by savaliyap** [comment]
So it uses SRTP by default?

**Comment by saghul** [comment]
Yes, it's mandatory in WebRTC.

**Comment by savaliyap** [comment]
Ok, thanks for the clarification.
