### ISSUE TITLE
How to make rounded RTCView?

### ISSUE THREAD

**Issue by wack17s** [oney/react-native-webrtc#341]
It's not issue, sry, but is it possible to make video in circle?

`<RTCView streamURL={this.state.videoURL} style={{ width: wind.width, height: wind.width, backgroundColor: 'red', borderRadius: wind.width / 2 }} />`

![issue](https://user-images.githubusercontent.com/14200710/30072409-de927f58-9272-11e7-838e-327ca5bd22bc.jpeg)

**Comment by 8BallBomBom** [comment]
Try adding objectFit={'cover'} to your RCTView.
Found here -> https://github.com/oney/react-native-webrtc/blob/cbd06d7107b93bb12131a6ddf99ea2093867d51b/android/src/main/java/com/oney/WebRTCModule/RTCVideoViewManager.java#L52

Haven't tried it myself but worth a shot.

**Comment by tuomohopia** [comment]
@wack17s  How are you getting that RTCView clipped in a circle like that? I can't get the borderRadius to work, and Android doesn't seem to support clipping the video via a View parent with borderRadius.

**Comment by amberv0** [comment]
Possibly the simplest solution is to put a png on top of the view. Keep transparent whatever you want to be visible, and the rest should have background's color

**Comment by ShaubertIlya** [comment]
Hello. Have you managed this issue? Is yes, could you share your realization, please?

**Comment by amberv0** [comment]
@ShaubertIlya , I needed a custom shape so I did create a png and put it on top. It works for sure :) and another solution, if only circle is needed, is to put the component inside of the view, for which to set borderRadius and overflow:'hidden'. Without hidden overflow somehow doesn't always apply, I didn't check why.
