### ISSUE TITLE
Android vs android audio is too low

### ISSUE THREAD

**Issue by khanghyxda** [oney/react-native-webrtc#345]
We're using React Native WebRTC in an Android and Web app at the moment
Android vs Web audio when the test does not have any problems
But Android vs Android Simulator Audio is too low, really very too low
`return getUserMedia({
      audio: true,
      video: {
        mandatory: {
          minWidth: 500, 
          minHeight: 300,
          minFrameRate: 30
        }
      }
    });`
Does the audio stream have more options?  Or use the default speaker is loudspeaker?

React Native version: 0.47.2
Plugin version: 1.58.2
OS: Android Simulator Samsung S6 vs Samsung S7 Android 6.0 vs Android 7.0

**Comment by saghul** [comment]
This plugin does not manage sound volume. It must be an artifact of whatever emulation / translation the simulator is doing. As you already verified, it works well on real devices. We use the earpiece by default.
