### ISSUE TITLE
Sending slices of an ArrayBuffer causes entire underlying buffer to be sent

### ISSUE THREAD

**Issue by jd20** [oney/react-native-webrtc#347]
When using react-native-webrtc, I noticed I was getting extraneous bytes on the data channel, compared to electron-webrtc. Digging deeper, it seems to be a bug in send(), for which I've submitted PR #346.

#### Expected behavior
The data sent on data channel should be exactly what is sent to send().

#### Observerd behavior
If you pass a subarray `data` to send(), it will send the contents of the entire underlying buffer (`data.buffer`).

#### Steps to reproduce the problem
```
let chan = <get a RTCDataChannel>
let buffer = new ArrayBuffer(8)
let x = new Uint8Array(buffer, 2, 2)
chan.send(x) // Verify on other side of data channel, that 8 bytes are sent instead of 2
```

#### Platform information

* **React Native version**: 0.48.2
* **Plugin version**:
* **OS**: iOS
* **OS version**: OSX 10.12.6

**Comment by zxcpoiu** [comment]
#346 merged! thanks!
