### ISSUE TITLE
[iOS] Add Permission on info.plist

### ISSUE THREAD

**Issue by Jerameel** [oney/react-native-webrtc#348]
The documentation for iOS doesn't indicate that this is needed. 

```
<key>NSCameraUsageDescription</key>
<string>Camera</string>
<key>NSMicrophoneUsageDescription</key>
<string>Microphone</string>
```

I believe this is necessary since iOS 10 is out.

**Comment by saghul** [comment]
Yes, that is indeed required! Mind sending a documentation PR? Thanks!
