### ISSUE TITLE
In ocassions i can't see friend stream

### ISSUE THREAD

**Issue by jlameiro87** [oney/react-native-webrtc#353]
In ocassions I only see my local video, i put several logs thinking that the problem was that I not get friend remote video, but the stream has data, why can't I see friend video?

**Comment by CandyOgre** [comment]
@jlameiro87 have you tried a [demo](https://github.com/oney/RCTWebRTCDemo) ?

**Comment by CandyOgre** [comment]
@jlameito87 I have this bug too, don't know how to fix it

**Comment by zxcpoiu** [comment]
you might want to try to deploy STUN/TURN first to see if it works.

**Comment by CandyOgre** [comment]
@zxcpoiu can you provide a link for some free STUN/TURN if there are any?

**Comment by zxcpoiu** [comment]
@CandyOgre 

I don't advocate for services that I haven't tried.
But for open source project, [coturn](https://github.com/coturn/coturn) seems awesome
