### ISSUE TITLE
Production STUN server

### ISSUE THREAD

**Issue by CandyOgre** [oney/react-native-webrtc#358]
Do I need to deploy own STUN server if I want to use this technology in production?

I have issue that I can\`t see other peer sometimes. Don`t know how to fix it

**Comment by zxcpoiu** [comment]
STUN and TURN is used to for traversal NAT / firewall.
so it's depends on your use case.

there are tons of STUN/TURN open source / services / tutorials out there
just google it and you will find the best solution for your need :)
