### ISSUE TITLE
Can't change volume

### ISSUE THREAD

**Issue by vugtis** [oney/react-native-webrtc#362]
Changing the hardware volume doesn't have any effect. Raising , lowering, muting don't have any effect. The streamed audio is still the same.

#### Expected behavior
Raising / Lowering volume using volume button will change the volume

#### Observed behavior
Sound didn't change at all.

#### Steps to reproduce the problem
2 people joined in chatroom

#### Platform information

* **React Native version**: 0.44
* **Plugin version**: newest
* **OS**: Android
* **OS version**: 4.4.2 and 5.0.1

**Comment by Jerameel** [comment]
Have you tried changing all volumes? (master, call, media, alarm) depending on your device. 

Or you can route the audio to main speakers with [https://github.com/zxcpoiu/react-native-incall-manager](url)

**Comment by cristiantx** [comment]
Having the same issue.

**Comment by yxwandroid** [comment]
Having the same issue.

**Comment by yxwandroid** [comment]
The App currently USES the headset to not switch the speaker. How do you switch to the speaker

**Comment by saghul** [comment]
Do you see the volume bar when using the hardware buttons?

**Comment by saghul** [comment]
> The App currently USES the headset to not switch the speaker. How do you switch to the speaker

See https://github.com/zxcpoiu/react-native-incall-manager

**Comment by yxwandroid** [comment]
@saghul 

   I   mean  at  iphone   run     react-native-webrtc   Voice is from telephone receiver    ,
   I want to know  How to switch to telephone speaker

**Comment by zxcpoiu** [comment]
@yxwandroid 

This library does not handle audio routing.

https://github.com/zxcpoiu/react-native-incall-manager is designed to use with this library that helps you to choose your audio route, or you can implement your logic in your own app.
