### ISSUE TITLE
WebRTC can't connect

### ISSUE THREAD

**Issue by renanpupin** [oney/react-native-webrtc#366]
I'm having a problem starting the WebRTC call. Sometimes the call simply fails and neither the picture nor the video is transmitted. However, this is something that occurs on some occasions and sometimes does not.
Is there a problem related to ICE and STUN server? Should I add some kind of specific treatment to try to reconnect? How to detect this type of problem?

**Comment by renanpupin** [comment]
The code is available through the link.
https://pastebin.com/8LpUxFYq

**Comment by Jerameel** [comment]
If you encounter the same issue when on the same network, it should not be related to **Stun** and **Turn** server.

Also, you might be confusing **ICE** with **Turn**
