### ISSUE TITLE
How to stream an MP3 Audio file instead of recorded audio?

### ISSUE THREAD

**Issue by sridharswain** [oney/react-native-webrtc#367]
* **react-native-cli: 2.0.1
react-native: 0.44.3**:
* **OS**: Android
* **OS VERSIOn**: 5.0.2

**Comment by Jerameel** [comment]
User kurento media server and add a Player End Point.

**Comment by sridharswain** [comment]
I want it to be true p2p, without any server in between

**Comment by saghul** [comment]
That's out the scope of this plugin.
