### ISSUE TITLE
LocalStream is required when creating PeerConnection

### ISSUE THREAD

**Issue by jerameel** [oney/react-native-webrtc#368]
**Expected Behavior**
The peerconnection should start negotiation even without localstream

* **React Native version**: Latest
* **OS**:Android / iOS

**Comment by saghul** [comment]
I don't think you can negotiate a PC without any stream. Does this work in a browser?

**Comment by cristiantx** [comment]
It does, if you create the offer with `offerToReceiveVideo` or `offerToReceiveAudio` flags on.

**Comment by saghul** [comment]
That's correct @cristiantx. I can't confirm if this is still a problem, but a lot has changed since about a year ago...

**Comment by cristiantx** [comment]
Ok, I will test it when I have the time so we can close this if it's already set

**Comment by saghul** [comment]
Gracias!

**Comment by ibc** [comment]
...

**Comment by saghul** [comment]
@ibc Have you tested this? I know OfferToReceiveVideo works fine, so maybe we can close this...

**Comment by ibc** [comment]
Honestly I don't remember. I may have tested it (do SDP O/A without local stream in the `pc`) but I don't remember it know.

Anyway: **zero** reasons come to my mind for it not to work.
