### ISSUE TITLE
App crashes on Android Nougat, Kitkat and Jellybean. Also on IOS 9 and 8

### ISSUE THREAD

**Issue by jayspirits** [oney/react-native-webrtc#369]
I was trying to implement a peer to peer video call. I got it working even cross platforms but it has an issue regarding with the platform versions.
I tried to debug and found out where it crashes. By the time i call getUserMedia it crashes, not if I remove the video from the object constraint parameter and leave just the audio.
For example:
_working:_
`getUserMedia({
      audio: true
    })`

_not working:_
`getUserMedia({
      audio: true,
      video: {
        mandatory: {
          minWidth: width,
          minHeight: height,
          minFrameRate: 30,
        },
        facingMode: 'user'
      }
    })`

#### Expected behavior
Successfully sends and receives video requests. can do peer to peer video call.

#### Observered behavior
App crashes upon sending video request and also upon receiving.

#### Steps to reproduce the problem
Start the call process or receive the call.

#### Platform information

* **React Native version**: RN v 0.47.0
* **Plugin version**: 1.58.3
* **OS**: Android
* **OS version**: Nougat 7.0, Kitkat 4.4, Jellybean 4.3
* **OS**: IOS
* **OS version**: 9, 8

**Comment by Jerameel** [comment]
Because you need to handle the permissions.

**Comment by jayspirits** [comment]
@Jerameel So you're saying there's a different permission to handle with those android and ios versions that aren't working? 
I already added those permissions as docs instructed. And as what Ive said I made it work on some versions for example on android marshmallow and lollipop and on ios 10 and 11.

**Comment by Jerameel** [comment]
Yes, android has changed their policy since marshmallow, as for iOS I'm not quite sure with 8 and 9 since I'm working fine with the latest version.

Try this out,  https://github.com/yonahforst/react-native-permissions

**Comment by jayspirits** [comment]
@Jerameel Sorry for bothering you with this. I should have known this thing :). I'm gonna check the link you shared and see what I can do. Thanks for your time.

**Comment by Jerameel** [comment]
@jayspirits  No problem, you may now close the issue . :D

**Comment by jayspirits** [comment]
@Jerameel I just want to clarify that the crashing issue that i encountered has nothing to do with the permission thing. It was the getUserMedia constraint i set for the video. I provided too much height and width that causes the crashing.
But the permission work around you suggested solved a different issue i encountered after i solved the crashing problem.
Thanks a lot!
