### ISSUE TITLE
RTCView rendering problem.

### ISSUE THREAD

**Issue by rbholeraj** [oney/react-native-webrtc#37]
I trying your code from https://github.com/oney/react-native-webrtc. I  got error ,
```
Failed to bind EAGLDrawable: <CAEAGLLayer: 0x14790930> to GL_RENDERBUFFER 1
Failed to make complete framebuffer object 8cd6
```
I also write query on stackoverflow http://stackoverflow.com/questions/36419884/failed-to-bind-eagldrawable-in-webrct-react-native
Can you help me correct way why camera not rendering on RTCView?

Thanks

**Comment by parthi82** [comment]
I had the same problem. It happens if you are not setting height and width for RTCView

**Comment by rbholeraj** [comment]
@parthi82  hi i set frame to RTCView but given me same problem. My updated code is like,
import React, {
  AppRegistry,
  Component,
  StyleSheet,
  Text,
  TouchableHighlight,
  View
} from 'react-native';

var WebRTC = require('react-native-webrtc');
var {
  RTCPeerConnection,
  RTCMediaStream,
  RTCIceCandidate,
  RTCSessionDescription,
  RTCSetting,
  RTCView
} = WebRTC;


var configuration = {"iceServers": [{"url": "stun:stun.l.google.com:19302"}]};
var pc = new RTCPeerConnection(configuration);
navigator.getUserMedia({ "audio": true, "video": true }, function (stream) {
  pc.addStream(stream);
});
pc.createOffer(function(desc) {
  pc.setLocalDescription(desc, function () {
    // Send pc.localDescription to peer
  }, function(e) {});
}, function(e) {});
pc.onicecandidate = function (event) {
  // send event.candidate to peer
};


var container;

var RCTWebRTCDemo = React.createClass({
  getInitialState: function() {
    return {videoURL: null};
  },
  componentDidMount: function() {
    container = this;
  },
  render: function() {
    return (
      <View style={styles.container}>
        <RTCView streamURL={this.state.videoURL}/>
      </View>
    );
  }
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: 400,
    width: 400,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});

AppRegistry.registerComponent('RCTWebRTCDemo', () => RCTWebRTCDemo);

**Comment by zxcpoiu** [comment]
great
