### ISSUE TITLE
Local Stream Not working on iOS 9.3.5 (iPhone 4s)

### ISSUE THREAD

**Issue by iSuperMan** [oney/react-native-webrtc#377]
RTCView Not working on iPhone 4s (iOS 9.3.5)
I just get blank view without any errors.

Note: Same app is working perfect on iPhone 7.

**Comment by iSuperMan** [comment]
My code of component
```javascript
import React, { PureComponent } from 'react';
import { View, Dimensions } from 'react-native';

import {
  RTCView,
  getUserMedia,
} from 'react-native-webrtc';

const { height, width } = Dimensions.get('window');

class WebRTC extends PureComponent {
  constructor(props) {
    super(props);

    this.state = {
      localStreamUrl: null,
    };
  }

  componentDidMount() {
    getUserMedia({
      audio: true,
      video: {
        mandatory: {},
        facingMode: 'user',
      },
    },
      (stream =>
        this.setState({
          localStreamUrl: stream.toURL(),
        })),
      (error => console.error(`getUserMedia failed with error: ${error}`)),
    );
  }

  render() {
    return <View>
      <RTCView
        streamURL={this.state.localStreamUrl}
        style={{
          width,
          height,
          backgroundColor: 'grey',
        }}
      />
    </View>;
  }
}

export default WebRTC;

```

**Comment by iSuperMan** [comment]
I realized that the problem is not in `<RTCView />`, but in the local stream.
Because remote stream's video is working perfect, but when i run same code with local stream i get blank view without any errors.

**Comment by iSuperMan** [comment]
info about sources

```javascript
componentDidMount() {
    MediaStreamTrack.getSources((sourceInfos) => {
      console.log('sourceInfos: ', sourceInfos);
    });
}
```

<img width="561" alt="2017-11-12 18 28 16" src="https://user-images.githubusercontent.com/11515531/32700517-71b26fca-c7d7-11e7-8db2-6a23e88e70b8.png">

**Comment by iSuperMan** [comment]
info about stream
```javascript
    getUserMedia({
      audio: true,
      video: { facingMode: 'user' },
    }, (stream) => {
      console.log('stream: ', stream);
      this.localStream = stream;
      this.setState({ localStreamUrl: stream.toURL() });
      this.pc.addStream(stream);
    }, logError);
```
<img width="829" alt="2017-11-12 18 33 58" src="https://user-images.githubusercontent.com/11515531/32700607-691239a8-c7d8-11e7-9829-f604c8552d19.png">

**Comment by brunsy** [comment]
@iSuperMan, Local stream is displaying on our iPhone 4s test device (ios 9.3.5) - running from master 86cb6c9ac585015d9f08fa053e3acd7d9b5fa2a3.
If you are still having problems, try test a lower resolution - I can't remember off the top of my head but I think the default was too high for that phone.

**Comment by amberv0** [comment]
@brunsy , just faced the exact same issue with iPhone 4s and spent a couple of hours trying to find out what's going on. I'm using the latest version on npm - 1.58.3. Changing the resolution didn't help. 
What DID help though, was installing the module directly from the master branch. 
So maybe it would make sense to publish the current code to npm to save other people from the same trouble?
Thank you!

**Comment by tabvn** [comment]
It does not work on Iphone 4s. IOS: 9.35. Confirmed.

**Comment by amberv0** [comment]
@tabvn , did you install from the master branch?

**Comment by tabvn** [comment]
I just tested same code on master branch, i did install latest "react-native-webrtc" and use Pod install 
IOS 9.35, Iphone 4S that i issue when get local Media Stream . However working fine on Iphone 5s, Ios 10

screenshot error after get local Stream. 
<img src="https://firebasestorage.googleapis.com/v0/b/tabvn-fireshot.appspot.com/o/shots%2FQrC4k82w1uVqSO8ckTnvisBko7l1%2F-L81l08Y88zk8JDJYU2S.png?alt=media&token=cbb2adc5-2bec-4679-ab97-bee13280ec28" />

**Comment by tabvn** [comment]
One more note is: On Iphone 4s IOS if use IsFront (Front Camera) no error but display on rtc view is nothing. (Work fine on Iphone 5s IOS 10 both front and back camera).

If change camera mode to back, then on IPhone 4s crash. like screenshot above.

**Comment by tabvn** [comment]
Any Lucky  with Other on IOS 9.35 Iphone 4S ?

**Comment by tabvn** [comment]
[react-native-webrtc.zip](https://github.com/oney/react-native-webrtc/files/1863517/react-native-webrtc.zip)
Finally here is version worked on Iphone 4s IOS 9.35
