### ISSUE TITLE
sdp transform error

### ISSUE THREAD

**Issue by jjdp** [oney/react-native-webrtc#380]
I am rearranging the order of the codecs so that h264 is first but on android to ios calls im getting an encoding undefined error on one of the callbacks on RCTPeerConnection.

As I have seen in my logs, Is it because android does not have h264? @zxcpoiu @saghul

```
//check and replace for H264 codec
function preferH264(description) {
  let newDescription = description;
  let sdp = description.sdp;
  let parsedSdp = transform.parse(sdp);

  parsedSdp.media = parsedSdp.media.map(media => {
    if(media.type === 'video') {
      const baseRtp = [media.rtp.find(rtp => rtp.codec.toLowerCase() === 'h264')];
      media.rtp = baseRtp.concat(media.rtp);
    }

    return media;
  });

  newDescription.sdp = transform.write(parsedSdp);

  return newDescription;
}
```

**Comment by zxcpoiu** [comment]
One of the easiest way to see which codec it supports, is to create offer without any constraints then see the codec list in sdp in different platform.

**Comment by zxcpoiu** [comment]
I don't know if there are existing official api to choose now or any time soon. Mangling sdp is a sort of hack to me and should be do it careful --- because the format of webrtc generated sdp is not 100% the same, and if a format / attr is not supported by `sdp-transform` or your own mangling script, those format would be changed / ignored, different from the original one.

**Comment by jjdp** [comment]
Does not work like this? Say if one phone doesn't support this codec, shouldn't it move on to the next?
If that's the case, then the encoding error could be because the format is not the same on different platforms

**Comment by zxcpoiu** [comment]
you can see my comment [here](https://github.com/oney/react-native-webrtc/issues/202#issuecomment-341665265)

there is no other better way currently than dump sdp from both platform and compare :(

**Comment by brunsy** [comment]
@jjdp you are adding an undefined into the rtp list in cases where the codec is not found...

**Comment by jjdp** [comment]
oh now i see where the problem is
