### ISSUE TITLE
Unable to resolve dependency for ':@debug/compileClasspath': Could not resolve project

### ISSUE THREAD

**Issue by dmeij** [oney/react-native-webrtc#382]
Hello,

I'm trying to install the react-native-webrtc plugin. But i keep on getting the same errors when trying to implement WebRTCModule:

Unable to resolve dependency for ':@debug/compileClasspath': Could not resolve project :WebRTCModule. Open File Show Details
Unable to resolve dependency for ':@debugAndroidTest/compileClasspath': Could not resolve project :WebRTCModule. Open File Show Details
Unable to resolve dependency for ':@debugUnitTest/compileClasspath': Could not resolve project :WebRTCModule. Open File Show Details
Unable to resolve dependency for ':@release/compileClasspath': Could not resolve project :WebRTCModule. Open File Show Details
Unable to resolve dependency for ':@releaseUnitTest/compileClasspath': Could not resolve project :WebRTCModule. Open File Show Details

I followed the instructions on: https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md.

Build.gradle:

dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    implementation project(":CordovaLib")
    implementation project(':WebRTCModule')
    implementation 'com.github.nkzawa:socket.io-client:0.3.0'
    implementation "com.android.support:support-v4:24.1.1+"
}

Can someone help me please?

* **React Native version**: 16.0.0
* **Plugin version**: 1.58.3
* **OS**: Android

**Comment by zxcpoiu** [comment]
not sure but FWIW, I use `compile project(':react-native-webrtc')` instead `implementation`

**Comment by zxcpoiu** [comment]
`implementation` seems a breaking change at gradle 3 in replace of `compile`.
I'm using gradle 2...

Are you still using React Native 16 ? or it's a typo?

**Comment by saghul** [comment]
You seem to have opened the issue in the wrong project. This plugin is for React Native, not Cordova.

**Comment by tranvannhat** [comment]
I get same error :( 
I followed the instructions on: https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md.
