### ISSUE TITLE
TypeError: undefined is not an object (evaluating ‘WebRTCModule.peerConnectionlnit’)

### ISSUE THREAD

**Issue by krisana** [oney/react-native-webrtc#383]
## i'm already setting Xcode from document
[https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md](url)

<img width="336" alt="screen shot 2560-11-15 at 05 23 09" src="https://user-images.githubusercontent.com/14059115/32808557-1133b6c2-c9c6-11e7-9d6c-793ffd06217b.png">

## i try to test from this code

`
import React, { Component } from 'react';
// import { Platform } from 'react-native';
import {
    RTCPeerConnection,
    RTCMediaStream,
    RTCIceCandidate,
    RTCSessionDescription,
    RTCView,
    MediaStreamTrack,
    getUserMedia,
} from 'react-native-webrtc';

class VideoCall extends Component {
    // Initial state
    state = {
        videoURL: null,
        isFront: true
    }

    componentDidMount() {
        const configuration = { "iceServers": [{ "url": "stun:stun.l.google.com:19302" }] };
        const pc = new RTCPeerConnection(configuration);
        const { isFront } = this.state;
        MediaStreamTrack.getSources(sourceInfos => {
            console.log('MediaStreamTrack.getSources', sourceInfos);
            let videoSourceId;
            for (let i = 0; i < sourceInfos.length; i++) {
                const sourceInfo = sourceInfos[i];
                // I like ' than "
                if (sourceInfo.kind === 'video' && sourceInfo.facing === (isFront ? 'front' : 'back')) {
                    videoSourceId = sourceInfo.id;
                }
            }
            getUserMedia({
                audio: true,
                // THIS IS FOR SIMULATOR ONLY
                // In fact, you better test on real iOS/Android device
                // We just can test audio on simulator, so i set video = false
                // video: Platform.OS === 'ios' ? false : {
                video: {
                    mandatory: {
                        minWidth: 500, // Provide your own width, height and frame rate here
                        minHeight: 300,
                        minFrameRate: 30
                    },
                    facingMode: (isFront ? 'user' : 'environment'),
                    optional: (videoSourceId ? [{ sourceId: videoSourceId }] : [])
                }
            }, (stream) => {
                // use arrow function :)
                // (stream) or stream are fine
                console.log('Streaming OK', stream);
                this.setState({
                    videoURL: stream.toURL()
                });
                pc.addStream(stream);
            }, error => {
                console.log('Oops, we getting error', error.message);
                throw error;
            });
        });
        pc.createOffer((desc) => {
            pc.setLocalDescription(desc, () => {
                // Send pc.localDescription to peer
                console.log('pc.setLocalDescription');
            }, (e) => { throw e; });
        }, (e) => { throw e; });

        pc.onicecandidate = (event) => {
            // send event.candidate to peer
            console.log('onicecandidate', event);
        };

    }

    render() {
        return (
            <RTCView streamURL={this.state.videoURL} style={styles.container} />
        );
    }
}
const styles = {
    container: {
        flex: 1,
        backgroundColor: '#ccc',
        borderWidth: 1,
        borderColor: '#000'
    }
};

export default VideoCall;
`

* **React Native version**:
react-native-cli: 2.0.1
react-native: 0.49.3
* **Plugin version**:
"react-native-webrtc": "^1.58.3"
* **OS**: 
* **OS version**:
ios version 11.1

Thanks in advance for any help that you are able to provide.

**Comment by zxcpoiu** [comment]
This error seems due to not install module properly.
The installation process in document is not for expo but for pure react native.

You might need to check expo's documents for how to install native module, and feel free to add a section to docs for how to use it with expo, thanks!

**Comment by krisana** [comment]
@zxcpoiu Thank you so much for keyword about **native module** in Expo's Docs i'm just using `exp` CLI

**Comment by Uysim** [comment]
Did you managed to fix it?
