### ISSUE TITLE
upgrade webrtc to latest branch (M63)

### ISSUE THREAD

**Issue by gut4** [oney/react-native-webrtc#384]
Latest webrtc branch now is [M63](https://groups.google.com/forum/#!topic/discuss-webrtc/qDtSDxoNSII)
Any plans to upgrade? Anyone working on this?

**Comment by zxcpoiu** [comment]
@saghul said that to upgrade to M59 above might takes longer.
I don't have time and plan yet currently.

If I'm going to working on it or someone wants to do so, will create a WIP branch called MXX for everyone to test and review together :)

**Comment by atyenoria** [comment]
+1

**Comment by zxcpoiu** [comment]
+1 :smile:

**Comment by saghul** [comment]
Please stop it with the "+1". If you want it done send a pull request.

**Comment by sboily** [comment]
Hello, i opened a PR #410 from the @saghul and @paweldomas work from jitsi repo.

**Comment by reimertz** [comment]
Just want to tell you @saghul, @paweldomas and all others that I really all the work you put into this. You are awesome!

**Comment by saghul** [comment]
Done.
