### ISSUE TITLE
peer connection is not closed when call is end. app is running on background. how i can handle it.

### ISSUE THREAD

**Issue by ignivahermenpreet** [oney/react-native-webrtc#385]
function leave(data) {
  console.log('leave', data);
  const pc = pcPeers[data.user_id];
  if(pc)
  {
    const viewIndex = pc.viewIndex;
    pc.close();
    delete pcPeers[data.user_id];

    const remoteList = container.state.remoteList;
    delete remoteList[data.user_id]
    container.setState({ remoteList: remoteList });
  }
}
#### Platform information

* **React Native version**:0.44.0
* **Plugin version**:^1.58.3
* **OS**: 
* **OS version**:

**Comment by atyenoria** [comment]
+1

**Comment by saghul** [comment]
Can you please reword your question? I don't fully understand what the problem is. Note that, by itself, this plugin won't magically make your app run in the background, that's up to the application.

**Comment by zayedelfasa** [comment]
as me.. i have as question as you.. how to handle "disconnect" video call if i have an event listener to disconnect? i want to use "leave" method but i think that is incorrect.. please tell me how..

**Comment by krishnapsarthi** [comment]
@saghul 
I am also facing same issue.
I am using webrtc connection, when i logout from app peer connection is not closing. I can still hear audio from peers.
I have tried with close each peer connection but that cause different issue.
Also tried with RTCRtpTransceiver stop but it does'not supported in react-native-webrtc.
I am using version :- 
**React**: 16.6.0
**React-native**: 0.57.4
**react-native-webrtc**: 1.67.1

please give your thoughts on this?

**Comment by saghul** [comment]
> I am using webrtc connection, when i logout from app peer connection is not closing. I can still hear audio from peers.
> I have tried with close each peer connection but that cause different issue.

Well, what exactly are you doing so audio stops? What didn't work?

**Comment by krishnapsarthi** [comment]
When we left any peer to peer meeting audio of peers should stop playing. But it doesnot not stops. Means when we disconnect meeting RTCConnection should be close automatically or we need to close it manually?
I have tried with close each peer connection but throws an another exception..

**Comment by saghul** [comment]
> Means when we disconnect meeting RTCConnection should be close automatically or we need to close it manually?

You must close it, of couse.

> I have tried with close each peer connection but throws an another exception..

What exception?

**Comment by krishnapsarthi** [comment]
@saghul 
I have tried to close all peer connection before call disconnect.
I think it does not disconnecting properly, cause when i try to join same meeting just after disconnect without refresh it won't shows my the stream to other web peer.

What is the standard way to handle disconnect peer connection in this library?

**Comment by saghul** [comment]
The only "special" thing you need to do is call `.release()` on your local stream. The rest is the same as the as you would do on a browser: close the peer connection.

**Comment by krishnapsarthi** [comment]
@saghul 

I have added code to call .release() on localstream and then closed peer connection. Still i can hear audio from peer users.

**Comment by krishnapsarthi** [comment]
@saghul 

Actually i have created 2 RTC connections for Local and Remote. 

Here is the code:-
`const { localStream } = this.state;
       if (localStream) {
           localStream.getTracks().forEach(t => t.stop());
           localStream.release();
       }
      this.pc1LocalList[peerName].connection.close();
      delete this.pc1LocalList[peerName];`
It works for peer to peer connection. but when i exit from meeting and call above code, it redirects me to home screen still in the background i can hear auido from connected peer.

If i try to close remote connection as 
`this.pc1RemoteList[peerName].connection.close();`
Then i all peers get freeze including web peers.

**Comment by avspeed** [comment]
@krishnapsarthi did you ever find a solution to this ?
