### ISSUE TITLE
Camera orientation 90* off when rotating phone after pausing/unpausing camera

### ISSUE THREAD

**Issue by bighitbiker3** [oney/react-native-webrtc#387]
#### Expected behavior
The RTCView should know the correct orientation after pausing/unpausing the camera.

#### Observerd behavior
When rotating my phone after getting the local mediastream the view is calculated correctly. However if my phone is in portrait mode, and I pause and unpause the local stream using `track.enabled = {bool}` and then rotate my phone, goes from this:

![img_1776](https://user-images.githubusercontent.com/15604901/33619929-4a0ef8c8-d99b-11e7-9c6f-8298041a6d1f.PNG)

To this: 

![img_1777](https://user-images.githubusercontent.com/15604901/33619933-4bcc9e22-d99b-11e7-8c8d-c546eee1f6f9.PNG)
 
In the landscape wonky state above, if I then toggle the video tracks enabled state it'll then show correctly.

#### Steps to reproduce the problem
Toggle video `enabled` and then rotate phone. 

#### Platform information

* **React Native version**: 0.50.1
* **Plugin version**: 1.58.3
* **OS**:  iOS
* **OS version**: 11.1.2

**Comment by bighitbiker3** [comment]
I was able to fix this by building webrtc from source and adding it to my project instead of using the one bundled in this package.

**Comment by zxcpoiu** [comment]
are you doing what #220 says to lock orientation?

**Comment by bighitbiker3** [comment]
I’m not.  Originally I did and then figured I might as well try it without and I ended up not needing to lock the orientation

**Comment by zxcpoiu** [comment]
awesome, would you might indicating which part you did for anyone might have the same situation?

**Comment by bighitbiker3** [comment]
Sure! I just ended up following the Podfile instructions [here](https://webrtc.org/native-code/ios/). 

So `pod init` if you don't have a `Podfile` yet
Add the following to your Podfile ```  platform :ios, '9.0'
  pod 'GoogleWebRTC'``` 
`pod install`

Easy peasy!

Follow the instructions in #220 if you want to lock the orientation. To fix this issue that isn't needed though.

**Comment by zxcpoiu** [comment]
Thanks for sharing @bighitbiker3 !

But it's still a little bit weird to me that by adding a `Podfile` config solves this problem though. :confused: 

Going to close this, if anyone has the same issue, try the solution above :+1:
