### ISSUE TITLE
Video Stream freezing only the first time

### ISSUE THREAD

**Issue by jjdp** [oney/react-native-webrtc#388]
#### Expected behavior
Remote stream should continue
#### Observed behavior
Remote stream freezes after a set amount of time on my Asus Zenfone 5. Old phone I know but this happens only once your called.
Any calls after that it works fine. The mic/camera permission  is already accepted and checked

There could be some initialization that's causing this. 
#### Steps to reproduce the problem
Fresh install app
Receive call for the first time
Only the first call this happens
#### Platform information

* **React Native version**: 0.49
* **Plugin version**: 1.58.3
* **OS**:  Android
* **OS version**: 5.0

**Comment by saghul** [comment]
Please try the latest release.
