### ISSUE TITLE
Flash/torch support

### ISSUE THREAD

**Issue by ndarilek** [oney/react-native-webrtc#39]
Thanks for this module! I've been working with it for the past day or so and it's been an absolute joy to use Web RTC on my Android device. Some of my code has been an almost direct copy from the web implementation of my app.

One of my reasons for building a mobile app is better integration with native hardware. To that end, I'd really like to access the flash so the user can toggle it. I thought about implementing this in a separate module, but I think Android will give me grief if I share the camera with another module.

I've never seen anything in the Web RTC spec for flash support. Thoughts on how it might be done? If there's no way in the spec (such that it is) maybe we add a setting on RTCSetting? We'd also need a way to query whether the device even has a flash, and that probably wouldn't make sense on RTCSetting.

**Comment by zxcpoiu** [comment]
Yeah, I think WebRTC only defines audio/video stream related stuffs.
+1 for separated module.

by the way, I'm implementing a module that deals with audio routing, proximity sensor, screen locks...etc. basically designed for work together with this modules. The main idea is to handle any situations we encounter and any functions we need during a audio/video chat.

I think the flash light toggle function can be merged with my module.
will publish it maybe next week and tag you after then. :)

**Comment by ndarilek** [comment]
Cool. Yeah, I'm not fundamentally opposed to it being another 
module--would prefer that, in fact. I'm just not sure how camera access 
from multiple modules works. I know that for instance the older Android 
`Camera.open()` throws an exception if another component has camera 
access, which you need to toggle the flash.

But yeah, definitely keep me posted. Thanks!

**Comment by zxcpoiu** [comment]
@ndarilek 

module is published.
check https://github.com/zxcpoiu/react-native-incall-manager
and see if it suitable for your implementation

**Comment by ndarilek** [comment]
Looks really nice, thanks! Despite filing a couple issues I really do 
like the API and the thought you put into this. I was starting to 
realize how many corner cases I'd have to work around in my own 
implementation of A/V calls but you've created a good starting point, 
and a place to submit PRs when I start needing more features.

Thanks again.

**Comment by oney** [comment]
@zxcpoiu Awesome!!

**Comment by zxcpoiu** [comment]
track this issue at:
https://github.com/zxcpoiu/react-native-incall-manager/issues/5

**Comment by cmpayc** [comment]
Perhaps this is not the most elegant and beautiful solution at the moment, but I didn't find another. That's how I made the flashlight work on Android (on iOs you can use react-native-incall-manager). Tested on Nexus 5 (Andoid 6.0.1) and Nexus 6P (Android 8.0.0). Do not forget to backup the module!

1. First of all, you need to create a directory ```.../node_modules/react-native-webrtc/android/src/main/java/org/webrtc```
2. Than you need to take 5 src files from your WebRTC version commit (I take it from M58 commit here: https://chromium.googlesource.com/external/webrtc/+/branch-heads/58/webrtc/sdk/android - api and src folders):
```
Camera1Session.java
Camera2Session.java
CameraCapturer.java
CameraSession.java
CameraVideoCapturer.java
```
3. In ```CameraSession.java``` interface CameraSession add:
```java
public void setFlash(boolean enable);
```
4. In ```Camera1Session.java``` class Camera1Session add:
```java
@Override
public void setFlash(boolean enable){
	  android.hardware.Camera.Parameters parameters = camera.getParameters();
	  List<String> supportedFlashModes = parameters.getSupportedFlashModes();
	  if(supportedFlashModes != null) {
		if(supportedFlashModes.contains(android.hardware.Camera.Parameters.FLASH_MODE_TORCH)) {
			parameters.setFlashMode(android.hardware.Camera.Parameters.FLASH_MODE_TORCH);
		} else if(supportedFlashModes.contains(android.hardware.Camera.Parameters.FLASH_MODE_ON)) {
			parameters.setFlashMode(android.hardware.Camera.Parameters.FLASH_MODE_ON);
		} else {
			return;
		}
	  }else{
		  return;
	  }
}
```
5. In ```Camera2Session.java``` class Camera2Session  add :
```java
private CaptureRequest.Builder captureRequestBuilder;

@Override
public void setFlash(boolean enable){
	try {
		if (enable) {
			captureRequestBuilder.set(CaptureRequest.FLASH_MODE, CameraMetadata.FLASH_MODE_TORCH);
			captureSession.setRepeatingRequest(captureRequestBuilder.build(), null, null);
		}else{
			captureRequestBuilder.set(CaptureRequest.FLASH_MODE, CameraMetadata.FLASH_MODE_OFF);
			captureSession.setRepeatingRequest(captureRequestBuilder.build(), null, null);
		}
    } catch (CameraAccessException e) {
        return;
    }
}
```
And change method onConfigured of class CaptureSessionCallback:
```java
REPLACE:
final CaptureRequest.Builder captureRequestBuilder =
        cameraDevice.createCaptureRequest(CameraDevice.TEMPLATE_RECORD);
TO:
captureRequestBuilder = cameraDevice.createCaptureRequest(CameraDevice.TEMPLATE_RECORD);
```
6. In ```CameraCapturer.java``` class CameraCapturer add :
```java
@Override
public void setFlash(boolean enable) {
	if (currentSession != null) {
		currentSession.setFlash(enable);
	}
}
```
7. In ```CameraVideoCapturer.java``` interface CameraVideoCapturer add :
```java
public void setFlash(boolean enable);
```
8. Then edit ```.../node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java``` and in class GetUserMediaImpl add:
```java
void setFlash(String id, boolean enable){
	VideoCapturer videoCapturer = mVideoCapturers.get(id);
	if (videoCapturer != null) {
		CameraVideoCapturer cameraVideoCapturer = (CameraVideoCapturer) videoCapturer;
		cameraVideoCapturer.setFlash(enable);
        }
}
```
9. Edit ```.../node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java``` and in class WebRTCModule add:
```java
@ReactMethod
public void mediaStreamTrackSetFlash(final String id, boolean enable) {
    MediaStreamTrack track = mMediaStreamTracks.get(id);
    if (track != null) {
        getUserMediaImpl.setFlash(id, enable);
    }
}
```
10. Edit ```.../node_modules/react-native-webrtc/MediaStreamTrack.js``` and in class MediaStreamTrack add:
```javascript
_setFlash(enable) {
    if (this.remote) {
      throw new Error('Not implemented for remote tracks');
    }
    if (this.kind !== 'video') {
      throw new Error('Only implemented for video tracks');
    }
    WebRTCModule.mediaStreamTrackSetFlash(this.id, enable);
}
```
11. And finally, in order to ensure that there are no class conflict errors during the compilation, I did the following (maybe it's crazy, but it works).
Open ```.../node_modules/react-native-webrtc/android/libs/libwebrtc.jar``` with some archiver (I use 7z) and remove from it all the files that we added from WebRTC revision (all Camera1Session*.java, all Camera2Session*.java, all CameraCapturer*.java, all CameraSession*.java, all CameraVideoCapturer*.java).
And delete ```.../node_modules/react-native-webrtc/android/build``` directory.

Now you can use it in your project:
```javascript
let tracks = localStream.getVideoTracks();
for(var i in tracks){
    tracks[i]._setFlash(true); //or false
}
```
The flashlight turns on on the camera, which is now active.

I hope this helps you.

**Comment by patidars** [comment]
@zxcpoiu @ndarilek Do we have any solution for android?
I have tried react-native-incall-manager but it did not worked in android.

**Comment by patidars** [comment]
@cmpayc I have tried your solution but it gives error while npm-install
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout e2294c302bde944d40a7ef31d6451a78b624cc22
npm ERR! fatal: reference is not a tree: e2294c302bde944d40a7ef31d6451a78b624cc22
npm ERR!

Thanks
