### ISSUE TITLE
janus gateway streaming not work

### ISSUE THREAD

**Issue by NatChung** [oney/react-native-webrtc#391]
Hi 

I am using Janus gateway to streaming RTP to RTCView , but it only works in rn-less-40, like this sample: https://github.com/inspiraluna/JanusReact, but when I switch the newest version (1.58.3), it doesn't work and doesn't show any error message

**Comment by zxcpoiu** [comment]
Because that repo you posted is use RN-less 40.
Master only support higher version of RN.

So all you have to do is upgrade RN on that repo, or downgrade master to support RN less 40 ( maybe rebase or some cherrypicks )

Since there is nothing we can do on this libs.
I'm going to close this now,
