### ISSUE TITLE
WebRTC audio stopped after playing a video using react-native-video

### ISSUE THREAD

**Issue by GuangzheGao** [oney/react-native-webrtc#392]
Basically I am using `react-native-video` package to play a video, which stops the WebRTC audio streaming somehow.

I tried adding `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionMixWithOthers error:nil];` in AppDelegate.m
Doesn't seem to help.

I suspect it is due to the conflict between AVCaptureSession (from react-native-webrtc) and AVAudioSession (from react-native-video), as I search from google, this post seem to be most relevant (others I have tried but not work): https://stackoverflow.com/questions/42031076/no-audio-from-avcapturesession-after-changing-avaudiosession

My react module Objective C skill is really limited, so changing the module is pretty hard for me and I not sure if I am on the right track. Any help or direction is appreciated! Please let me know if more input helps or this is duplicate issue.

#### Expected behavior
Audio Mixes for the WebRTC audio (AVCaptureDevice captured?) and the AVPlayer played audio.

#### Observed behavior
Webrtc audio is preempted by AVPlayer played audio. Even when the video finished playing, there is still no audio for WebRTC. However, the WebRTC video plays fine.

#### Steps to reproduce the problem
1. Install `react-native-video`; directions are here: https://github.com/react-native-community/react-native-video

2. Start WebRTC audio streaming

3. Play a video as instructed in: https://github.com/react-native-community/react-native-video#usage

#### Platform information

* **React Native version**: 0.50.3
* **Plugin version**: 1.58.3
* **OS**: iOS
* **OS version**: 10.3.x

**Comment by saghul** [comment]
This is not going to work. There is a single AVAudioSession in iOS (it's a global thing) and both projects will configure it differently, in incompatible ways.

This project doesn't allow audio mixing by default. This is intentional, the same way audio from a regular phone call doesn't mix with other audio.

I'm afraid your only choice is to write your own module in ObjC which reconfigures the session when your application needs it.

**Comment by JLLLinn** [comment]
We are having this issue when we try to play a video during a video call. Is there a way to temporarily suspend the audio of webrtc but still keep the connection when the video plays, so we don't have to reconnect to webrtc after the video ends?

**Comment by zxcpoiu** [comment]
@JLLLinn 

You can try `audio_track.enable = false`
