### ISSUE TITLE
 video to display  at  no ssl certification 

### ISSUE THREAD

**Issue by yxwandroid** [oney/react-native-webrtc#393]
I use https://192.168.1.26:4443   for not SSL certification
Ios Release packaging  and  running app video does not display
But using https://react-native-webrtc.herokuapp.com for SSL certification
 ios Release packaging  RunIng  app video to display

Do you have to use HTTPS for SSL authentication when you call the Release app
react-native-cli: 2.0.1
react-native: 0.50.3
* **OS**:  iOS

**Comment by saghul** [comment]
Yes, SSL is mandatory. You can disable it for a specific domain using ATS and the NSTemporaryExceptionAllowsInsecureHTTPLoads key, but you need to do that in your app.

**Comment by yxwandroid** [comment]
thank you         @saghul 
I want to know how to remove SSL authentication logic code

**Comment by zxcpoiu** [comment]
This library basically not thing to do with your signaling logic ( XMPP/SIP/HTTP/WS... )

Apple has `App Transport Security` policy that forces all apps use SSL to connect. So SSL is mandatory to your signaling implementation.

It's unlikely that you can remove SSL authentication from iOS core on each user's device.
 `NSTemporaryExceptionAllowsInsecureHTTPLoads` is a config that tells iOS core to `allow` your app can make a insecure connection.
