### ISSUE TITLE
React/RCTConvert.h file not found

### ISSUE THREAD

**Issue by fuub** [oney/react-native-webrtc#394]
Hello, 

I'm trying to build for ios, followed the installation steps carefully but I'm getting this error when building:

React/RCTConvert.h not found

on the first line of RCTConvert+WebRTC.h file.

Any help please?

**Comment by saghul** [comment]
Did you use CocoaPods?

**Comment by fuub** [comment]
No, but I think what is the problem, I was adding react-native-webrtc in a
cordova project, but it needs react-native instead of cordova... total noob
at this..

**Comment by saghul** [comment]
Yes indeed, this is a React Native plugin.
