### ISSUE TITLE
evaluating stream.reactTag

### ISSUE THREAD

**Issue by yxwandroid** [oney/react-native-webrtc#395]
undefined is not an object  ( evaluating stream.reactTag) 

How to deal with the problem

thanks

#### Platform information

react-native-cli: 2.0.1
react-native: 0.50.3
* **OS**: iOS -->

**Comment by saghul** [comment]
Can you paste a traceback or something? Some steps to reproduce it? Something? Really, if you want people to help you, you need be as detailed as you possibly can.

**Comment by mazero** [comment]
I have the same error with Android. Any ideads why ? Thx

undefined is not an object (evaluating 'stream.reactTag')
addStream
    RTCPeerConnection.js:128:48
createPC
    VisioScreen.js:139:17
<unknown>
    VisioScreen.js:79:17
onack
    socket.js:312:14
onpacket
    socket.js:236:17
<unknown>
    index.js:21:20
emit
    index.js:133:25
ondecoded
    manager.js:332:12
<unknown>
    index.js:21:20
emit
    index.js:134:25
add
    index.js:246:16
ondata
    manager.js:322:19
<unknown>
    index.js:21:20
emit
    index.js:133:25
onPacket
    socket.js:451:18
<unknown>
    socket.js:268:18
emit
    index.js:133:25
onPacket
    transport.js:145:12
onData
    transport.js:137:16
onmessage
    websocket.js:146:16
dispatchEvent
    event-target.js:172:43
<unknown>
    WebSocket.js:148:27
emit
    EventEmitter.js:182:12
__callFunction
    MessageQueue.js:250:47
<unknown>
    MessageQueue.js:101:26
__guard
    MessageQueue.js:218:6
callFunctionReturnFlushedQueue
    MessageQueue.js:100:17

**Comment by andikare** [comment]
anyone can help me with this error ? 
rtcweb is connecting but i have some error like this,
undefined is not an object (evaluation 'stream.reactTag')

and the video don't show,,  
thank you

**Comment by andikare** [comment]
anyone can solve this error ? anyone please ?

**Comment by DevelopSmith** [comment]
@andikare did you find the solution? I am facing the same problem!

**Comment by andikare** [comment]
@DevelopSmith no dude ,
I switched to using Opentokvideo call and its works
