### ISSUE TITLE
RTCPeerConnection.getStats() returns a nested string blob

### ISSUE THREAD

**Issue by jd20** [oney/react-native-webrtc#396]
While trying to integrate simple-peer with react-native-webrtc, I've found that the output of getStats() is non-standard, which can cause problems with other libraries that expect a browser-like output.

#### Expected behavior
Calling RTCPeerConnection.getStats() should return an array of structured objects. For example:

```
(18) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
0: {id: "googLibjingleSession_7269088161857653593", type: "googLibjingleSession", timestamp: 1514770646094.905, values: Array(1)}
1: {id: "datachannel_0", type: "datachannel", timestamp: 1514770646094.905, values: Array(4)}
...
16: {id: "Conn-audio-1-4", type: "googCandidatePair", timestamp: 1514770646094.905, values: Array(21)}
17: {id: "Cand-00VNzHwh", type: "localcandidate", timestamp: 1514770646094.905, values: Array(6)}
length: 18
```

#### Observed behavior
Instead, it's returning a single element array, with a giant JSON string:

`["[{"id":"googLibjingleSession_7269088161857653593",…5"},{"portNumber":"54298"},{"transport":"udp"}]}]"]`

#### Steps to reproduce the problem
Create an instance of RTCPeerConnection, and then call getStats().

#### Platform information

* **React Native version**: 0.51.0
* **Plugin version**: ^1.58.3
* **OS**: iOS
* **OS version**: 9.0

#### Proposed Fix
In RTCPeerConnection.js:204, there's a long comment about how the getStats() data is passed across the bridge as a string, for performance reasons. However, the following check is `typeof stats === 'string'`, whereas what is coming across the bridge from WebRTCModule+RTCPeerConnection.m seems to always be an array with a single-element string, so that check is never matching. Not sure if the Android code has the same problem.

An easy fix would be to just check for an array with a single-element string, and convert it. I tried this and it worked OK for me locally, maybe there's a better solution, on the native side.

```javascript
        if (Array.isArray(stats) && stats.length === 1 && typeof stats[0] === 'string') {
          stats = stats[0]
        }
        if (typeof stats === 'string') {
          // Original code ...
        }
        return stats;
```

**Comment by saghul** [comment]
Sounds about right. Care to send a PR?

**Comment by jd20** [comment]
Sure, submitted #398.

**Comment by zxcpoiu** [comment]
@jd20 

merged, thanks :)
