### ISSUE TITLE
Using SIP.js and/or JsSIP for SIP Server

### ISSUE THREAD

**Issue by ostrichegret** [oney/react-native-webrtc#397]
Using this demo ( and installing latest react-native-webrtc ) and the demo server, it works
`https://github.com/oney/RCTWebRTCDemo`

when i try to use latest sip.js and jssip.
```
npm i --save sip.js
npm i --save jssip
```

On JsSIP
after add this on main.js
`var jssip = require('jssip');`

I got this error 
`error: bundling: Error: Couldn't find preset "env" relative to directory "D:\\RCTWebRTCDemo\\node_modules\\jssip"`

On sip.js

Using ws it works,
```
var configuration = {
      uri: '1000@xxx.com',
      ws_servers: 'ws://xxx.com:5066',
      authorizationUser: '1000',
      password: 'xxx$$$123'
    };

ua = new sip.UA(configuration);
```
While using wss, i got websocket error, connection closed
```
var configuration = {
      uri: '1000@xxx.com',
      ws_servers: 'wss://xxx.com:7443',
      authorizationUser: '1000',
      password: 'xxx$$$123'
    };

ua = new sip.UA(configuration);
```

using the ws option, while trying to do call i got 
```
ua.invite('5000@xxx.com', getLocalStream(true, function(stream) {
    localStream = stream;
    container.setState({selfViewSrc: stream.toURL()});
    container.setState({status: 'ready', info: 'Please enter or create room ID'});
  }));
```

`TypeError: Cannot read property 'getUserMedia' of undefined`

How to fix this? Thank you

**Comment by saghul** [comment]
This plugin does not pollute the global namespace, that is, there is no `window.getUserMedia`, you need to require this module early on and assign it yourself.

**Comment by ostrichegret** [comment]
@saghul 

Hi saghul, thank you very much for your help, also on iosrtc :)

I have this code 
```
import {
  RTCPeerConnection,
  RTCMediaStream,
  RTCIceCandidate,
  RTCSessionDescription,
  RTCView,
  MediaStreamTrack,
  getUserMedia,
} from 'react-native-webrtc';
```
and add this code just like you said
`window.getUserMedia = getUserMedia;`

when i use the call method:
 ```
 _callSIP(event){
    ua.invite('5000@xxx.com',getUserMedia({
      audio: true,
      video: {
        mandatory: {
          minWidth: 640, // Provide your own width, height and frame rate here
          minHeight: 360,
          minFrameRate: 30,
        },
        facingMode: ( "user"),
        optional: ([]),
      }
    }, function (stream) {
      console.log('getUserMedia success', stream);
    }, function (error) {
      console.log('getUserMedia err', error);
    }));
  },
```

i clear the console before running the call function and got this error:
```
getUserMedia success MediaStream {active: true, _tracks: Array(2), id: "ae51b069-e7d4-4c5d-8051-25c0fc36e6e6", reactTag: "ae51b069-e7d4-4c5d-8051-25c0fc36e6e6", Symbol(listeners): Object}
D:\RCTWebRTCDemo\node_modules\react-native\Libraries\ReactN…:71 Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'getUserMedia' of undefined
TypeError: Cannot read property 'getUserMedia' of undefined
    at i (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:56863:397)
    at r.i.defaultFactory [as sessionDescriptionHandlerFactory] (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:56865:18)
    at r.invite (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:56403:214)
    at o.<anonymous> (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:56639:15)
    at tryCallOne (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:16553:12)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:16639:15
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:6163:19
    at Object.callTimer (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5357:9)
    at Object.callImmediatesPass (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5443:27)
    at Object.callImmediates (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5453:30)
```

Here is the full main.js
[main.txt](https://github.com/oney/react-native-webrtc/files/1597382/main.txt)

Thank you

**Comment by zxcpoiu** [comment]
@ostrichegret

1. `getUserMedia` is a promise function, you should wait it for a stream then pass into `invite` instead pass a promise to `invite`

2. `sip.js` use lots of webrtc function internally, not just getUserMedia, you should inject this moduleinto sip.js in their `enviroment.js`. Unfotunately, this is not official supported in sip.js, but you can hack it yourself.

This injecting/Promise things is really out of scope of this module.
You might get better help on `sip.js` or StackOverflow

**Comment by ostrichegret** [comment]
@zxcpoiu 
oh  i see, so that's why it pop up error.
Thanks for the help and confirmation

**Comment by platonish** [comment]
@zxcpoiu Hi, unfortunately SIP.js have removed `environment.js` in [this commit](https://github.com/onsip/SIP.js/commit/47335b69d86acbfab1cb48f3c562b068246744fc), and so this is no longer possible, is there any other way of injecting this module? It looks like they don't intend to support React Native any time soon. 
[This thread](https://groups.google.com/forum/#!searchin/sip_js/react$20native|sort:date/sip_js/ZUP0FEZpz44/WiWvZ_diAAAJ) suggests that a custom SDH implementation would also be required, do you have any suggestions around that? Thanks!
