### ISSUE TITLE
Audio mediaStreamTrack lateness

### ISSUE THREAD

**Issue by Kornflexx** [oney/react-native-webrtc#399]
#### Expected behavior

In audio (only) session, microphone should record and send sound instantly when localstream is created and return (by promise).

#### Observerd behavior

Randomly, the audio capture start after more than 10 seconds.

#### Platform information

* **React Native version**: 0.51.0-rc.3
* **Plugin version**: 1.58.3
* **OS**: Android
* **OS version**: 7.1+

**Comment by saghul** [comment]
10 seconds after what? ICE negotiation can take a while depending on the network conditions, and audio will not be transmitted until that is done.

**Comment by Kornflexx** [comment]
This lateness append on some Samsung device when the proximity sensor was activated too fast (under a second). This behaviour is pretty strange.
