### ISSUE TITLE
Volume is controlled by the Android Call slider

### ISSUE THREAD

**Issue by Carlosarturo28** [oney/react-native-webrtc#402]
#### Expected behavior
Control the volume on Android with the native "media" slider.

#### Observerd behavior
The volume of the remote streaming is controlled by the "call" slider from Android.

#### Steps to reproduce the problem
Run the example, enter a room in the app and in the heroku server and try to move the volume control.

#### Platform information

* **React Native version**: 0.44
* **Plugin version**: 1.58.3
* **OS**: Android
* **OS version**: 6.1

**Comment by zxcpoiu** [comment]
isn't a call volume shouldn't be controlled by `call` slider? It's intended to use that `audio category` both in native webrtc. `incall-manager` does the same as well.

**Comment by nguyenanhthai** [comment]
I got same issue. My expected result is sound of webrtc should be in 'media' slider sound control.

**Comment by zxcpoiu** [comment]
Hmm...unfortunately, that is the default behavior of webrtc internally.
If you want to change slider controlled by `media` instead `call`, then you can set your `AudioMode` in your own app to override the default settings.

You can check `react-native-incall-manager` to know how to override it.

**Comment by nguyenanhthai** [comment]
I see. That's the default behavior of webrtc. Audio will pass to system as call-sound.
I have tried change audioMode to `MODE_NORMAL` instead of `MODE_IN_COMMUNICATION` in android but not work. It makes `react-native-incall-manager` not work and sound very small.

**Comment by zxcpoiu** [comment]
WebRTC may changes audio mode internally once the call established.
You can try set audio mode / stream AFTER call established.

Also, you can try `MODE_RINGTONE` as well.

**Comment by zxcpoiu** [comment]
And you try can set `getCurrentActivity().setVolumeControlStream(AudioManager.STREAM_MUSIC);`, I believe that determine the type of volume control

**Comment by saghul** [comment]
Closing since the behavior is internal to WebRTC and not something to be handled by this plugin.

**Comment by jjunk1989** [comment]
@nguyenanhthai I got same issue and after a lot of search I find this [Android audio playout in non-call media streams](https://groups.google.com/forum/#!searchin/discuss-webrtc/STREAM_MUSIC|sort:date/discuss-webrtc/OhdVmDsfhhM/jvog35cAAgAJ).
Just add `WebRtcAudioTrack.setAudioTrackUsageAttribute(AudioAttributes.USAGE_MEDIA);` before new peerconnection fix my problem. You can try it.

**Comment by jiantongc** [comment]
> @nguyenanhthai I got same issue and after a lot of search I find this [Android audio playout in non-call media streams](https://groups.google.com/forum/#!searchin/discuss-webrtc/STREAM_MUSIC%7Csort:date/discuss-webrtc/OhdVmDsfhhM/jvog35cAAgAJ).
> Just add `WebRtcAudioTrack.setAudioTrackUsageAttribute(AudioAttributes.USAGE_MEDIA);` before new peerconnection fix my problem. You can try it.

Where do you get `WebRtcAudioTrack`? Appreciate it

**Comment by kosmologist** [comment]
`WebRtcAudioTrack.setAudioTrackUsageAttribute(AudioAttributes.USAGE_MEDIA)` fixes issue.

**Comment by jf4444** [comment]
WebRtcAudioTrack.setAudioTrackUsageAttribute(AudioAttributes.USAGE_MEDIA) not work on 75
