### ISSUE TITLE
localStream render fails on reload

### ISSUE THREAD

**Issue by tuomohopia** [oney/react-native-webrtc#403]
The `localStream`'s render only shows blank after code reload, it does not appear to be rendering anything. `log-android` will report just the same stream specs, except a new ReactId tag.

I'm running the demo code, except upgraded React Native to the latest version:
https://github.com/oney/RCTWebRTCDemo

I've tried on Oneplus 5T running android 7.1.1 as well as Galaxy Note 3 running Android 5.0. Android Studio's Virtual Device won't render anything at all in any occasion in `<RTCView />` with the demo code. On the Virtual Device, the camera app actually crashes whenever I try to run it after I've installed and run the WebRTCdemo code on it once.

Running `react-native run-android` again seems to render the `localStream `video correctly again.

If I'm doing something wrong here, please help me understand how to use the module correctly.

#### Steps to reproduce the problem

1.  Fresh install
2. Upgrade RN
3. Launch app
4. Access in-app developer menu -> Reload

#### Platform information

* **React Native version**: 0.51.0
* **Plugin version**: 1.58.3
* **OS**: Android
* **OS version**: 5.0

**Comment by zxcpoiu** [comment]
Hmm...I don't think this is the issue to be fixed since your app are not going to `reload` in production. And you won't trigger a `code push` while your client is during a call.

If I need reload the app, usually I will force close the app after reload to make sure everything is cleaned to avoid this kind of issue.

**Comment by saghul** [comment]
This is a known limitation. There is a global EGL context which will be leaked with every reload. This does not occur on production builds, so restarting the app should do. Tedious, I know, but I couldn't find a way around it.

**Comment by tuomohopia** [comment]
Ok, thanks for letting me know it's not just a local problem at my setup! For some reason, I often fail to render the localStream even on the first time, but just trying again usually makes it work somehow at some point.
