### ISSUE TITLE
How to access the Remote Streaming only

### ISSUE THREAD

**Issue by Carlosarturo28** [oney/react-native-webrtc#404]
I'm playing with the demo and it actually works very well. But what I want to do is to receive the remote Streaming from the demo server on a device, without broadcasting my own device to the streaming, more or less like a security system. How can I achieve this? 

I tried to ignore the getUserMedia and getLocalStream without any succeed.

Thank you very much for the help!

**Comment by zxcpoiu** [comment]
In your should at least complete `offer/answer` to establish a workable connection. It does matter which side initiate the offer.

For local stream, I haven't tried though, but I think at least you can disable your local stream track once you've created. Not sure if it can totally be not created at all.

**Comment by saghul** [comment]
You still need to call getUserMedia and use the `offerToRecevieVideo` set of constraints.

**Comment by ibc** [comment]
> You still need to call getUserMedia and use the offerToRecevieVideo set of constraints.

Sorry, let me understand: why does the app need to call `getUserMedia` if it's not wishing to send its audio/video?

**Comment by Carlosarturo28** [comment]
I tried to use `offerToReceiveVideo: false` in the mandatory of the `getUserMedia` but it keeps showing the device camera.

**Comment by ibc** [comment]
> I tried to use `offerToReceiveVideo: false` in the mandatory of the `getUserMedia` but it keeps showing the device camera.

And why did you expect that such a constrain would work at all in `getUserMedia()`?

**Comment by Carlosarturo28** [comment]
> And why did you expect that such a constrain would work at all in getUserMedia()?

I don't know. I just tried. I think I misunderstood what saghul said. Do you have some idea of achieve the desired function? @ibc

**Comment by ibc** [comment]
Just search for `offerToReceiveVideo` in Google and you'll find the proper place to set it ;)

**Comment by Carlosarturo28** [comment]
> Just search for offerToReceiveVideo in Google and you'll find the proper place to set it ;)

That's what I'm doing ;)

> Sorry, let me understand: why does the app need to call getUserMedia if it's not wishing to send its audio/video?

So, you say I don't need to call getUserMedia since I don't want to send audio/video?

**Comment by ibc** [comment]
> So, you say I don't need to call getUserMedia since I don't want to send audio/video?

Yes. *Definitely*. Do not pay attention to @saghul, it's not the first time he says that calling `getUserMedia` is needed for receiving audio/video.
