### ISSUE TITLE
Issue with pixelated remoteStream

### ISSUE THREAD

**Issue by bsiddiqui** [oney/react-native-webrtc#407]
#### Expected behavior
Clear video

#### Observerd behavior
Often the video for one of the clients becomes all pixelated like this:
![img_2235](https://user-images.githubusercontent.com/2721959/34748316-c770138a-f550-11e7-8eec-2319dd748c4e.png)

Is there a reason the remoteStreamUrl would be a video that's all pixelated like this?

* **React Native version**: 0.49.3
* **Plugin version**: master
* **OS**: iOS

**Comment by saghul** [comment]
We've seen this happen on some devices with WebRTC M58, but upgrading to M63 fixes it. We are close to finishing the upgrade, so when that's ready the problem should go away.

**Comment by 25matt12** [comment]
@bsiddiqui Did you find a workaround ? I have the same issue and it's working properly, the image is always pixelated but it works just fine on Android.

**Comment by bsiddiqui** [comment]
@25matt12 no workaround yet - just waiting for M58

**Comment by eawwal** [comment]
I stumbled upon a quick fix, I am also in the same boat regarding this pixelated view on my project, but if I transfer to RCTWebRTCDemo, using the same exact code it works perfectly fine with no pixelation. I am testing on iPhone X and get pixelation issues only. All other devices fine, iPhone X remote stream quality pixelated on new build but seems to be working on old RCTWebRTC build? Any update on this, or which version of webrtc the demo is running? Help much appreciated.

**Comment by 25matt12** [comment]
Just so you know, I'm having the issue on iPhone X also and it works just fine with the demo too.
I have no clue about what could be the cause of the problem.

I'm also having an other issue on iOS, the first time I get the userMedia stream it's instant but if I close the view and try to get it again it takes 5 to 10 seconds to enter the callback...

**Comment by yaynick** [comment]
@saghul Seems like the jitsi fork has already upgraded to M63. For those of us looking to resolve the issues with iPhone 8/X, are there any major compatibility issues (other than promises) with simply switching over to the fork?

**Comment by TylerIlunga** [comment]
Any news on the upgrade from M58 to M63?

**Comment by zxcpoiu** [comment]
for M63 upgrade, please continue discussion in #449
