### ISSUE TITLE
Unable to install the project

### ISSUE THREAD

**Issue by AdrianHomeless** [oney/react-native-webrtc#408]
#### Expected behavior
Being able to run the app

#### Observerd behavior
npm install:
npm WARN react-native-webrtc@1.58.3 requires a peer of react-native@>=0.40.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-webrtc@1.58.3 No license field.

react-native run-android:
Command `run-android` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

After failed install:
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory

In the demo--> react-native -v (In 
react-native-cli: 2.0.1
react-native: 0.44.3

#### Steps to reproduce the problem
git clone https://github.com/oney/react-native-webrtc.git
cd react-native-webrtc
npm install

#### Platform information

* **React Native version**: with official demo says react-native: 0.44.3, so I guess that is the one.
* **Plugin version**: 1.58.3
* **OS**: 
* **OS version**:

**Comment by AdrianHomeless** [comment]
Hello. 
I´m sorry. I´m unable to install your project.
When I try npm install I get the following warns and the project is not installed.
I have no problem running the official demo.
I´m so sorry. Your project seems awesome and I tried to find a solution for days, but no luck.
Do you know what this could it be?
Thanks.

**Comment by saghul** [comment]
This project is just a library, not an app you can run. If you have trouble with a demo application, please open the issue there.
