### ISSUE TITLE
What's with the Foobar v. FoobarImpl stuff?

### ISSUE THREAD

**Issue by philikon** [oney/react-native-webrtc#41]
I don't quite see the point of `RTCPeerConnectionBase` deferring `someMethod()` to `someMethodImpl()` which is then implemented in `RTCPeerConnection`. This seems to be modeled on React Native's `WebSocketModule` implementation, which only does this so it can reuse the code for the websocket-based debugging stuff. What's the reasoning do introduce this complication in react-native-webrtc? Can we get rid of it?

**Comment by philikon** [comment]
(I'll be happy to do the work to simplify the code.)

**Comment by oney** [comment]
I don't actually know why react native core does that, I just try to model it. Let's keep it if it is harmless.

**Comment by philikon** [comment]
> I don't actually know why react native core does that,

Purely historical reasons. I am already fixing it in https://github.com/facebook/react-native/pull/6889.

> Let's keep it if it is harmless.

I disagree. I'd like to consolidate it to make the code much more readable and more easily maintainable. Will throw up a PR.

**Comment by oney** [comment]
No problem! I think it will be good.
