### ISSUE TITLE
Experiencing deadlock on disconnect.

### ISSUE THREAD

**Issue by mhashmi** [oney/react-native-webrtc#411]
#### Expected behaviour

When calling close on RTCPeerConnection, the connection should disconnect cleanly.

#### Observed behaviour

Randomly, we get a deadlock where the entire app becomes unresponsive. This behaviour is fairly easy to replicate (on our end), with 1 in 10 connections almost always deadlocking on peer disconnect. 

The following backtrace is available if we pause the app (after it deadlocks): 

> thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x0000000182c0c0f0 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x0000000182d22ce4 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$mp + 640
    frame #2: 0x0000000102070b7c WebRTC`rtc::Event::Wait(int) + 236
    frame #3: 0x0000000102103c48 WebRTC`webrtc::PeerConnectionProxyWithInternal<webrtc::PeerConnectionInterface>::Close() + 164
> frame #4: 0x0000000100692778 App`-[WebRTCModule(self=0x0000000102d8deb0, _cmd="peerConnectionClose:", objectID=(long)6) peerConnectionClose:] at WebRTCModule+RTCPeerConnection.m:223
    frame #5: 0x0000000183101cd0 CoreFoundation`__invoking___ + 144
    frame #6: 0x0000000182fe056c CoreFoundation`-[NSInvocation invoke] + 292
    frame #7: 0x0000000182fe501c CoreFoundation`-[NSInvocation invokeWithTarget:] + 60
    frame #8: 0x000000010071a6f8 App`::-[RCTModuleMethod invokeWithBridge:module:arguments:](self=0x00000001043bf700, _cmd="invokeWithBridge:module:arguments:", bridge=0x0000000102b8e000, module=0x0000000102d8deb0, arguments=1 element) at RCTModuleMethod.mm:519
    frame #9: 0x00000001007a8f18 App`facebook::react::RCTNativeModule::invokeInner(this=0x000000010441a380, methodId=9, params=0x000000011012d7e0) at RCTNativeModule.mm:96
    frame #10: 0x00000001007a8b64 App`facebook::react::RCTNativeModule::invoke(this=0x000000011012d7d0)::$_0::operator()() const at RCTNativeModule.mm:68
    frame #11: 0x00000001007a8b04 App`::___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke((null)=<unavailable>) at RCTNativeModule.mm:62
    frame #12: 0x0000000101ea52cc libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #13: 0x0000000101ea528c libdispatch.dylib`_dispatch_client_callout + 16
    frame #14: 0x0000000101ea9ea0 libdispatch.dylib`_dispatch_main_queue_callback_4CF + 1196
    frame #15: 0x00000001830a2544 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
    frame #16: 0x00000001830a0120 CoreFoundation`__CFRunLoopRun + 2012
    frame #17: 0x0000000182fbfe58 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #18: 0x0000000184e6cf84 GraphicsServices`GSEventRunModal + 100
    frame #19: 0x000000018c71467c UIKit`UIApplicationMain + 236
    frame #20: 0x0000000100683a54 App`main(argc=1, argv=0x000000016f7839f0) at main.m:16
    frame #21: 0x0000000182adc56c libdyld.dylib`start + 4
(lldb)

#### Steps to reproduce the problem

The issue is indeed quite random, and I've taken care to ensure that the close call from our PeerConnection instance is called only once. Additionally, the deadlock has been observed on the very first PeerConnection created -- i.e, where the ObjectID is 0. In the image attached (please see below), the deadlock occurred on the 6th disconnect. 

![rtc-deadlock-a](https://user-images.githubusercontent.com/1129805/35317151-31bc628c-00f7-11e8-8f30-55c950b4e4cf.png)

#### Platform information

* **React Native version**: 0.49.5
* **Plugin version**: 1.58.3
* **OS**: iOS
* **OS version**: 11.2.2

#### Additional notes

 - The remote stream coming in is from a Desktop Capture using Electron APIs.

 - When close is called on the RTCPeerConnection instance, the registered callback for ICE state change fires, with state set to 'closed'. The Remote peer (Electron side) also receives the disconnect and closes the connection on the remote end. However, it seems that the call to close from WebRTCModule+RTCPeerConnection.m simply never returns, locking the main thread. 

If anyone has any suggestions on how I can go about debugging this, it would be greatly appreciated. Also, if there is any additional information I can provide, please do let me know. 

Thanks.

**Comment by mhashmi** [comment]
Hi all, 

I closed this issue last night when we discovered a version of our app that wasn't deadlocking at all. Turns out, a modification to the generated SDP to switch to H264 was the cause. I'll reopen the issue with full details and perhaps a test case where it can be reproduced easily.

**Comment by andyryan** [comment]
Might be worth noting that this is happening on standard webrtc also (not just react-native-webrtc) I have a version of the webrtc.framework i have build myself from source and it is doing the same thing

**Comment by shaharmor** [comment]
Did you guys figure this out?
