### ISSUE TITLE
[Question] How to build exact same version of WebRTC?

### ISSUE THREAD

**Issue by cristiantx** [oney/react-native-webrtc#416]
I'm successfully building the latest versions of WebRTC but I want to build M58 with all the same cherry picks. But I'm not sure what all the version code means.
```
M58
commit
(16937)
(+21-18206)
```

Specially the `(+21-18206)` part. Does that means it's 21 commits after (16937)? 

If so, I'm not sure how to get the commit hash from the commit number. 

Thanks!

**Comment by cristiantx** [comment]
Dumb me, after spend the whole day with this I discovered [this document](https://github.com/oney/react-native-webrtc/blob/master/Documentation/BuildingWebRTC.md) which makes things a lot easier. 

I think it should be linked somewhere in the README.
Thanks.

**Comment by zxcpoiu** [comment]
sure, thanks!
