### ISSUE TITLE
Current Status of Media Constraints

### ISSUE THREAD

**Issue by cristiantx** [oney/react-native-webrtc#418]
On my app, I need to make sure that the video I'm recording is 16:9, but not necessary HD, some old devices give a poor framerate when streaming in HD. But does support a 16:9 aspect ratio with a smaller size.

What's the status of Media Constraints like `minAspectRatio` or `aspectRatio`?

I know that team has been working on them from what I saw in the commits and pull requests.

Right now seems to be ignoring it, but I'm not sure if it's because `react-native-webrtc` limitation or because WebRTC M58 doesn't have those.

If it's the first case I would like to help to implement this feature, but I need someone to update me on the current state since I couldn't figure it out from the code.

**Comment by saghul** [comment]
The current state is that only some of the constraints are implemented. The only way to know about which ones is to browse the source, sorry about that.

We (jitsi) have updated to M63, but need to merge back, which will be painful because Promise support was landed here without much testing and broke some things.

**Comment by cristiantx** [comment]
@saghul Do you mean that anything you put in the constraints it's passed to WebRTC library and it's up to what the library supports, right? I saw in `react-native-webrtc` code that it basically just translate the properties and pass them to WebRTC.

Off-topic: I'm really up to collaborate in the project but I'm not sure where to start and which are the most critical tasks to make it progress.

**Comment by zxcpoiu** [comment]
@cristiantx 

On js side, should follow spec as possible, but the current version of underlying webrtc lib is M58, a feature could really work or not largely depends on underlying version.

This libs implement js side api, and translate arguments into underlying webrtc lib, note that there may have differences between android and ios even the underlying lib in the same version.

Usually, I would check does a feature has been implemented in the underlying libs or not ( check webrtc source or their PSA ), compares api or argument between ios and android. Then check js spec to see if I can follow the spec as possible. Finally, write objc or java to translate/pass from js to underlying.

Current state is trying to merge M63, it may take a while. And during this period, it's better not to merge complex PR.

I think you can check spec and features based on M63 and jitsi's branch. Then have your PR or fixes stay on local branch, once M63 landed, it would be easier to migrate.

**Comment by zxcpoiu** [comment]
In short, check is a specific constraints supported in current version of underlying lib. If yes, write a translation from JS into the underlying if you find this lib doesn't pass it to.

**Comment by cristiantx** [comment]
Thanks! I'll get to it. 
One more question that might be off topic for this thread but I need it to do my tests. 
I'm using the script provided in `tools` folder to build my own WebRTC. But when I do I get a really slow FPS on the receiver (just on iOS). If I use the one pre-compiled provided it works just great.

I'm building it in a macOS machine, do you guys do something else in particular to build?

**Comment by cristiantx** [comment]
I'll get into it and see how that goes. Will send a PR when I see fit. Thanks!
