### ISSUE TITLE
Filling the Screen with an RTCView

### ISSUE THREAD

**Issue by briank621** [oney/react-native-webrtc#419]
In my application, I have a remote source whose dimensions I may not know in advance. I wish to fill the local screen so that the video goes to the screen edges.

I see two possibilities for the `objectFit` props, `contain` and `cover`. Is there something like a `fill` or `stretch`, that would fill the screen **without** preserving aspect ratio? Perhaps, any workarounds?

**Comment by saghul** [comment]
That would be cover, then wrap the RTCView in a View with the following style:

```
alignSelf: 'stretch',
flex: 1
```

**Comment by briank621** [comment]
Thanks for the response. 

I've tried doing the above, but I still have white gaps around my video.

My render returns the following: 
~~~
<View style={styles.container}>
  <View style={styles.buttonContainer}>
    <TouchableOpacity style={styles.callButton} onPress={this.pressMenu}>
      <Text> Settings </Text>
    </TouchableOpacity>
  </View>
  <View style={styles.videoContainer}>
    <RTCView streamURL={this.state.remoteURL} style={styles.video1} />
  </View>
</View>
~~~

With the following styles:

~~~
const styles = {
  container: {
    flex: 1,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#000'
  },
  videoContainer: {
    flex: 1,
    alignSelf: 'stretch'
  },
  video1: {
    flex: 1
  },
  buttonContainer: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    left: 0,
    right: 0,
    bottom: 40,
    zIndex: 5
  },
  callButton: {
    position: 'absolute',
    height: 50,
    width: 50,
    borderWidth: 3,
    borderColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DDDDDD',
    zIndex: 5
  }
};
~~~

The video is appearing with the same dimensions as the remote video. Seems like the stretching is not working.
