### ISSUE TITLE
Voice/Video call in sleep model call session will disconnect in 3 minutes

### ISSUE THREAD

**Issue by chindanai** [oney/react-native-webrtc#421]
#### Steps to reproduce the problem
1. start call on foreground mode
2. then peer user joined
3. press power button to make phone sleep
4. still can use voice call
5. in 3 minutes call session will disconnected

I've tried demo project is also happen this issue
In xcode console show

> 'oniceconnectionstatechange', 'disconnected'

#### Platform information
* **React Native version**: 0.44.3
* **Plugin version**: 1.58.3
* **OS**: iOS
* **OS version**: 9.0-11.x

**Comment by shaheem-khanzada** [comment]
remove the leave function from socket

**Comment by saghul** [comment]
You need to keep your app alive when it goes in the background. That, however, is not this plugin's job.
