### ISSUE TITLE
[Help] Local Stream broken screen on iphone8 and iphoneX

### ISSUE THREAD

**Issue by stove654** [oney/react-native-webrtc#422]
I have problem when open local stream on iphone8 and IphoneX, broken screen . How can i fix it? can you help me?
Link image: https://goo.gl/9AWRVP

#### Platform information
IOS 
* **React Native version**:
v0.51
* **Plugin version**:
lastest version
* **OS**: 
IOS11 (Iphone8 and IphoneX)
* **OS version**:

**Comment by Ulydev** [comment]
Looks like #407
