### ISSUE TITLE
Native Component for RTCVideoView does not exist.

### ISSUE THREAD

**Issue by basitsattar** [oney/react-native-webrtc#425]
Hi, I am trying to use React-native-webrtc in a project and have followed all the setup instructions but when I try to use RTCView in my javascript react component, I get error
"Native Component for RTCVideoView does not exist." 

* **React Native version**: 0.51
* **Plugin version**: latest
* **OS**: Android and IOS
* **OS version**: latest

**Comment by Rajeshbhartia** [comment]
same here

**Comment by devLaaziz** [comment]
+

**Comment by sumitnitsurat** [comment]
How did you solve it ?

**Comment by 8BallBomBom** [comment]
Easy way to solve it would be to use a newer React Native version.
0.55.4 seems pretty stable and works with this all good.

**Comment by sumitnitsurat** [comment]
@8BallBomBom  I am working on the same version. these are my packages - 
     "expo": "27.0.1",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-webrtc": "1.67.1",
    "socket.io-client": "2.1.1"

**Comment by sumitnitsurat** [comment]
For the people still stuck in this error. This problem was caused due to the project created using create-react-native-app and then ejecting the project. I created a fresh project with react-native init and updated gradle everything is working fine for me now.
