### ISSUE TITLE
I need to test webrtc at the mobile terminal, but I don't have HTTPS, what should I do

### ISSUE THREAD

**Issue by xvbo** [oney/react-native-webrtc#426]
I need to test webrtc on the mobile terminal, but I don't have a HTTPS. I just need to run in the LAN. What should I do

**Comment by zxcpoiu** [comment]
Hmm...this module `webrtc` is nothing to do with https. It just manage to get user local media and consumes sdp, perform ICE checking.

I thought you are referring to your signal part? like, websocket?
About that, we can not do anything about it. iOS seems limited all non-secure connections.

So you should search for how to use insecure connections over iOS or Android for your signaling. Not webrtc itself.
