### ISSUE TITLE
Is it possible to buffer the stream while setting up connection?

### ISSUE THREAD

**Issue by brendan-rius** [oney/react-native-webrtc#428]
Setting up a webrtc connection is slow, especially on mobile networks (the ICE candidates exchange takes time). However, I want my users to be able to press a button and start talking without having to wait for the connection to be made. 

I am streaming audio only, and it is unidirectional (I am not expecting to receive audio in exchange).

Is there a way for me to start recording what the user says as soon as he presses the button, store the audio in a buffer, and when the connection is established, replay the buffer's contents into the webrtc connection?

**Comment by zxcpoiu** [comment]
This plugin in more like a subset under chrome's webrtc. It lacks lots of API.
If I recall it correctly, there seems to have a plan to support stream from file or different media source, but not sure if it released or not.

I'm pretty sure you can not do that on this plugin currently.

**Comment by zxcpoiu** [comment]
I'm going to close this, since there is nothing we can do here.
