### ISSUE TITLE
[Question] - different result for android and ios when calling WebRTCModule.mediaStreamTrackGetSources

### ISSUE THREAD

**Issue by pmaite88** [oney/react-native-webrtc#429]
Hi,  I noticed that the implementation of `mediaStreamTrackGetSources` in the WebRTCModule  returns an `array of arrays` in `ios`, but just an `array` in `android` (links below)

https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L515

https://github.com/oney/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m#L325

Maybe I did something wrong and it's an error on my part, but I currently need to have two separate pieces of code for android and ios because of this.

If it's actually returning different things,  wouldn't it be better to have a consistent result?

Thx!

**Comment by zxcpoiu** [comment]
Agreed.

According to https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/do3t86PtHCY/discussion
`mediaStreamTrackGetSources` has been replaced by `MediaDevices.enumerateDevices()` which we have not implemented yet.

But spec of `MediaDevices.enumerateDevices()`  indicating we should return an Array(Object).
So I guess we should use `NSMutableDictionary` on objc side while `addObject` ?

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices

**Comment by saghul** [comment]
The array of arrays issue is now fixed in the latest release. As for `enumerateDevices`, I'm working on that right now.
