### ISSUE TITLE
Modifying shape of <RTCView> component

### ISSUE THREAD

**Issue by rub8n** [oney/react-native-webrtc#44]
What would be the best way to modify the shape of the RTCView stream? I tried making it round by using borderRadius but it seems the property has no effect on the component.

**Comment by m59peacemaker** [comment]
Did you try wrapping `RTCView` in a regular `View` component and applying `borderRadius` to the `View`? I think that would work.

**Comment by rub8n** [comment]
That's what I was expecting as well but seems like only the View is affected. RTCView remains unaffected.

**Comment by oney** [comment]
iOS or Android?

**Comment by rub8n** [comment]
I have only tried this on iOS so far... not sure about the Android experience.

**Comment by oney** [comment]
You're right.

Find `node_modules/react-native-webrtc/ios/RCTWebRTC/RTCVideoViewManager.m`'s `Line 39`
Replace to
```objectivec
- (UIView *)view
{
  UIView *v = [[RTCEAGLVideoView alloc] init];
  v.clipsToBounds = YES;
  return v;
}
```

And
```javascript
<RTCView streamURL={this.state.selfViewSrc} style={styles.selfView}/>
....

var styles = StyleSheet.create({
  selfView: {
    width: 200,
    height: 150,
    borderRadius: 10,
  },
...
```
It will work. I will find a time to change it in the module.

**Comment by rub8n** [comment]
Worked like a charm... Thanks for the quick reply!

Not sure if any other change is needed but made a small PR with your suggested change to hopefully save you some time.

**Comment by oney** [comment]
It is. Thanks!

**Comment by AaronVasquez** [comment]
I am trying to do this for Android with no luck (it works on iOS). Is this possible to do on Android?
