### ISSUE TITLE
Toggle Camera Functionality Not Working

### ISSUE THREAD

**Issue by vink1987** [oney/react-native-webrtc#444]
I am trying to switch camera (front/back). It works fine with local streaming but when I add the local stream to peerconnection then it doesn't appear on the remote end.
I am using removeStream and addStreaming methods on peerconnection object.

1. I remove the stream from the peer connection first
2. I get the localStream by WebRTC.getUserMedia method.
3. I add the new stream back to the same peer connection.

Please help.

**Comment by saghul** [comment]
If you are doing it that way, you need to renegotiate. Do you do that? You can use https://github.com/oney/react-native-webrtc#mediastreamtrackprototype_switchcamera, which is a lot faster.
