### ISSUE TITLE
Building Jitsi react native web rtc issue 

### ISSUE THREAD

**Issue by eawwal** [oney/react-native-webrtc#448]
Following all of the documentation but keep failing at a certain point, the error reads as this: 
When i revert back to 1.58.3 my application builds fine. Am i missing something here?

 'WebRTC/RTCMTLVideoView.h' file not found
 Could not build module 'WebRTC'

Basically its failing at one of the imports, help would be appreciated

**Comment by eawwal** [comment]
i fixed the build issue by simply commenting out the import in iOS project but am wondering if this will lead to any other issues? My full screen styling was effected slightly but iPhone X support works

**Comment by zxcpoiu** [comment]
for M63 upgrade, please continue discussion in #449
