### ISSUE TITLE
Why not use org.webrtc.SurfaceViewRenderer

### ISSUE THREAD

**Issue by richmonkey** [oney/react-native-webrtc#452]
com.oney.WebRTCModule.SurfaceViewRenderer can be replaced with org.webrtc.SurfaceViewRenderer?

**Comment by saghul** [comment]
After M63 lands yes, we already got rid of it in the jitsi fork.

For reference: we needed the custom renderer in order to make some extra checks on the EGL contexts and to deal with "black image being rendered" when switching streams. Those have since been fixed / addressed.
