### ISSUE TITLE
getSources returns an array of array on iOS

### ISSUE THREAD

**Issue by Sharcoux** [oney/react-native-webrtc#455]
#### Expected behavior

`getSources` should return an array with the devices

#### Observerd behavior

On iOS, getSources returns an array on which the only element is an array containing the devices.

#### Steps to reproduce the problem

```
import webrtc from 'react-native-webrtc';
webrtc.getSources().then(sources => console.log(sources));
```

#### Platform information

* **React Native version**:0.55.3
* **Plugin version**:1.58.3
* **OS**:  iOS
* **OS version**: 11.3

**Comment by saghul** [comment]
A PR fixing this would be most welcome!

**Comment by Sharcoux** [comment]
https://github.com/oney/react-native-webrtc/pull/446
