### ISSUE TITLE
Android getUserMedia is giving DOMException

### ISSUE THREAD

**Issue by arindam89** [oney/react-native-webrtc#457]
In Android I am always getting DOMExceoption for getUserMedia() call

More details: https://stackoverflow.com/questions/47012310/react-native-webrtc-domexception 

#### Platform information

* **React Native version**: 0.49.3
* **Plugin version**: ^1.58.3
* **OS**: Android
* **OS version**: 8.1.0

**Comment by aoarashi1988** [comment]
same Issue， and I resolve it by edit the 'android/app/src/main/AndroidManifest.xml' file
`<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus"/>

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`

Hope it help you
