### ISSUE TITLE
Crash on reload after calling `new RTCPeerConnection()` on iOS

### ISSUE THREAD

**Issue by m59peacemaker** [oney/react-native-webrtc#46]
If I call `new RTCPeerConnection()` and then change my code so that a live reload is triggered, the app crashes every time. It's a nightmare trying to develop this way. Does this happen for everyone?

**Comment by oney** [comment]
No happened on me. Can you give me logs?

**Comment by m59peacemaker** [comment]
I'm not very good with Xcode. Can you tell me how to find what you need?

**Comment by oney** [comment]
On terminal, run `open ios/<PROJECT_NAME>.xcodeproj`. Then, it will open Xcode, hit Run. When you get the crash, see logs on the bottom.

**Comment by m59peacemaker** [comment]
![screenshot 2016-04-12 23 09 11](https://cloud.githubusercontent.com/assets/4369247/14482840/9d32eee8-0106-11e6-852a-99e2ad78ed7f.png)
![screenshot 2016-04-12 23 18 53](https://cloud.githubusercontent.com/assets/4369247/14482841/9d3308ec-0106-11e6-9a56-f6da38e5a4ec.png)

**Comment by m59peacemaker** [comment]
I get the second one almost every time. That first one happens rarely.

**Comment by oney** [comment]
Does it happen on demo project? https://github.com/oney/RCTWebRTCDemo

**Comment by m59peacemaker** [comment]
It crashes while starting up. I'm on the latest Xcode (7.3)

![screenshot 2016-04-13 01 08 42](https://cloud.githubusercontent.com/assets/4369247/14484262/a7fcddc6-0114-11e6-8d8f-4473485688ad.png)

**Comment by m59peacemaker** [comment]
It does the same thing. I entered a room on my phone and joined the same room on my browser. Then, I made a change in main.js and saved it. The app tried to reload and crashed, just like it does on my app.

![screenshot 2016-04-13 01 26 37](https://cloud.githubusercontent.com/assets/4369247/14484552/f7bbb998-0116-11e6-9c66-63d9839141ed.png)

**Comment by m59peacemaker** [comment]
In my app, I narrowed it down to simply `new RTCPeerConnection()` making the difference. I commented everything out related to it so that I could be sure. If I called it, the app would crash on reload. If I commented just that line out, it would reload without crashing.

**Comment by zxcpoiu** [comment]
what is your environment?

I noticed when reload on ios, it `seems` will keep fd, said, ws connection still open.
And android `seems` closed all connections.

I don't know, if that is true, maybe should close PeerConnection and VideoView like in `onDestroy()` or something like that.

do you crash even when audio only ( not start VideoView in native ) ?

**Comment by oney** [comment]
@m59peacemaker  It won't crash when reloading(Ctrl+R), right?

**Comment by m59peacemaker** [comment]
Both the demo and my app crash just the same using the manual reload as well, both on my iPhone 5s and iPhone 6+ on 9.3.1.

**Comment by oney** [comment]
Can be reproduced in my device now, I will solve it.

**Comment by m59peacemaker** [comment]
The frustration continues - now the same crash happens when I try to switch cameras, but only for my app. I am trying to debug some things and have discovered that debugging in Chrome doesn't work (Error screen: Runtime is not ready for debugging, etc.). I tried to debug in Chrome on the latest demo 0.6.0 and the previous clone of it I had at 0.5.1. The same error screen is shown. Perhaps this is related. If not, I could open a new issue after this one is solved.

**Comment by m59peacemaker** [comment]
I have discovered that debugging in Chrome doesn't work (Error screen: Runtime is not ready for debugging, etc.). I tried to debug in Chrome on the latest demo 0.6.0 and the previous clone of it I had at 0.5.1. The same error screen is shown. Perhaps this is related. If not, I could open a new issue after this one is solved. I'll keep looking around and see if I find anything helpful.

**Comment by oney** [comment]
Should be fixed by https://github.com/oney/react-native-webrtc/pull/68 and https://github.com/oney/react-native-webrtc/commit/3405429227151e328abd182142667cae1b43d7a1
I will publish it tomorrow.
