### ISSUE TITLE
Black Screen When Switching Applications

### ISSUE THREAD

**Issue by briank621** [oney/react-native-webrtc#464]
I am calling from one device to another successfully. I can see the remote stream on both sides.
The issue arises when I switch applications on one device and then return back to the stream (after a relatively long period of time, ~1 minute). I'm left with a completely black screen for the remote stream while the local stream is still visible.

I can reset the peer connection and make the call again successfully, but I'm wondering if I can bypass that step and have it so that the video streams persists despite some inactivity.

**Comment by cristiantx** [comment]
If you're doing a calling app, make sure that you setup your app as one. This changes how the OS deals with it when in background. If not set right it can be suspended or closed. Also I would listen to app state change event and check for connection status when coming back from background.
