### ISSUE TITLE
Getting NotAllowedError using getUserMedia

### ISSUE THREAD

**Issue by shubham-srivastava-goku** [oney/react-native-webrtc#467]
import React, { Component } from 'react';
		import {
		  Platform,
		  StyleSheet,
		  Text,
		  View,
		  PermissionsAndroid
		} from 'react-native';

		var WebRTC = require('react-native-webrtc');
		var {
		  RTCPeerConnection,
		  RTCIceCandidate,
		  RTCSessionDescription,
		  RTCView,
		  MediaStream,
		  MediaStreamTrack,
		  getUserMedia,
		} = WebRTC;

		export default class App extends Component {

		  getLocalStream() {
			let isFront = true;
			return new Promise((resolve, reject) => {
			  MediaStreamTrack.getSources(async (sourceInfos) => {
				if (Platform.OS === 'android') {
				  let perCheck = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.CAMERA);
				  console.log(perCheck);
				  if(!perCheck) {
					let permission = await PermissionsAndroid.request(
					  PermissionsAndroid.PERMISSIONS.CAMERA,
					  {
						'title': 'Duo App Camera Permission',
						'message': 'Duo app wants to access camera access for video chat'
					  }
					)
					console.log(permission);
				  }

				}

				let videoSourceId;
				for (const i = 0; i < sourceInfos.length; i++) {
				  const sourceInfo = sourceInfos[i];
				  if (sourceInfo.kind == "video" && sourceInfo.facing == (isFront ? "front" : "back")) {
					videoSourceId = sourceInfo.id;
				  }
				}

				getUserMedia({
				  audio: true,
				  video: {
					mandatory: {
					  minWidth: 640, // Provide your own width, height and frame rate here
					  minHeight: 360,
					  minFrameRate: 30,
					},
					facingMode: "user",
					optional: (videoSourceId ? [{ sourceId: videoSourceId }] : []),
				  }
				}, function (stream) {
				  console.log('getUserMedia success', stream);
				  resolve(stream);
				}, reject);
			  });
			});
		  }

		  constructor() {
			super();

			this.state = {
			  selfViewSrc: null
			};
		  }

		  componentDidMount() {
			this.getLocalStream()
			  .then((stream) => {
				this.setState({
				  selfViewSrc: stream.toURL()
				});
			  })
			  .catch((e) => {
				console.log("Error : ");
				console.log(e);
			  });
		  }

		  render() {
			return (
			  <View>
				<Text>Loaded</Text>
				<RTCView streamURL={this.state.selfViewSrc} style={styles.selfView} />
			  </View>
			);
		  }
		}

		const styles = StyleSheet.create({
		  selfView: {
			width: 200,
			height: 300,
		  }
		});

#### Platform information
Running on  on 'LG-M700 - 7.1.1'
react-native-cli: 2.0.1
react-native: 0.55.4
npm: 6.1.0
react-native-webrtc: 1.63.0

**Comment by zxcpoiu** [comment]
Could you try on the demo project to reproduce it?
And be sure you did grant the required permission. see README for android installation

**Comment by davidestrela** [comment]
I had the same problem, the solution for me was fix the permissions on `AndroidManifest`

```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>


    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus"/>

    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" /> // was missing RECORD_AUDIO
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> 
```

Hope it helps
