### ISSUE TITLE
setLocalDescription success is not a function

### ISSUE THREAD

**Issue by Ahagan** [oney/react-native-webrtc#469]
When using two iPhones, the first will successfully join, the second will show an error.

#### Observerd behavior
Error message:
success is not a function. (In 'success()', 'success' is undefined.

RTCPeerConnection.js:173:8

Code causing error in RTCPeerConnection.js:

 `setLocalDescription(sessionDescription: RTCSessionDescription, success: ?Function, failure: ?Function) {
    WebRTCModule.peerConnectionSetLocalDescription(sessionDescription.toJSON(), this._peerConnectionId, (successful, data) => {
      if (successful) {
        this.localDescription = sessionDescription;
        success(); // <----- ERROR HERE
      } else {
        failure(data);
      }
    });
  }`

#### Expected behavior
Expect not to receive this error.

#### Steps to reproduce the problem
Join as User A. Then join as User B.
Using https://github.com/thoqbk/rewebrtc.  

#### Platform information

* **React Native version**:
0.55.x
* **Plugin version**:
* **OS**: IOS
* **OS version**: 
11.4 (iPhone 7 plus) / 11.2.5 (iPhone 6)

**Comment by 8BallBomBom** [comment]
How are you handling the answer function?

**Comment by saghul** [comment]
> Using https://github.com/thoqbk/rewebrtc.

This is really outdated. It uses version 1.54 of this plugin. Please update and re-test.
