### ISSUE TITLE
Datachannel Guide?

### ISSUE THREAD

**Issue by 8BallBomBom** [oney/react-native-webrtc#471]
I have been trying to get datachannels working for a while now but it would appear either i'm doing something wrong or this plugin just doesn't want to function properly.
Doesn't matter how i try getting them to work in-band or out-band they just don't seem to function without causing everything to malfunction.

I can either get a call connected and randomly datachannels work but then the connection never disconnects properly and i can't get another call connected.
Or it works flawlessly where i can get calls connected perfectly and quickly both sides but then 1 side doesn't want to transmit audio and video properly depending on who starts the call.

If i remove datachannels then calls both sides connect and disconnect perfectly each time, no problems.
No missing streams or anything, all as it should be.

I was hoping to have some of the obvious things going through datachannels instead of websockets to a backend for everything.

I can provide examples of code i'm using for creating the datachannels but could anyone provide a working example or guide?

* **React Native version**: 0.54.2
* **Plugin version**: 1.63.0
* **OS**: Android
* **OS version**: 6.0.1

**Comment by muhammadhurali** [comment]
Hi @8BallBomBom,
Did you get it working?? I need to send and receive messages using datachannel but no luck yet.

**Comment by 8BallBomBom** [comment]
Very old issue and no i never managed to fix it.
Then again with the latest plugin versions maybe this issue is resolved?
Can't say as i haven't checked yet.

**Comment by saghul** [comment]
Datachannel support was rewritten in the latest release.
