### ISSUE TITLE
setLocalDescription success is not a function -> 1.63.0

### ISSUE THREAD

**Issue by Ahagan** [oney/react-native-webrtc#472]
When using two iPhones, the first will successfully join, the second will show an error.

#Observerd behavior
Error message:
success is not a function. (In 'success()', 'success' is undefined.

RTCPeerConnection.js:173:8

Code causing error in RTCPeerConnection.js:

setLocalDescription(sessionDescription: RTCSessionDescription, success: ?Function, failure: ?Function) { WebRTCModule.peerConnectionSetLocalDescription(sessionDescription.toJSON(), this._peerConnectionId, (successful, data) => { if (successful) { this.localDescription = sessionDescription; success(); // <----- ERROR HERE } else { failure(data); } }); }

#Expected behavior
Expect not to receive this error.

Steps to reproduce the problem
Join as User A. Then join as User B.
Using https://github.com/thoqbk/rewebrtc.

Example call:
`
  private createOffer(peerConnection, socketId) {
        peerConnection.createOffer(function (desc) {
            peerConnection.setLocalDescription(desc, function () { //<--- ERROR WHEN CALLED HERE
                self.socket.emit('exchange', { 'to': socketId, 'sdp': peerConnection.localDescription });
            }, this.logError);
        }, this.logError);
    }
`

#Platform information
React Native version:
0.55.x
Plugin version: 1.63.0 of react-native-webrtc
OS: IOS
OS version:
11.4 (iPhone 7 plus) / 11.2.5 (iPhone 6)

**Comment by 8BallBomBom** [comment]
Do you have the issue if you downgrade to 1.58.3?
Seems maybe the non promise based functions are going a bit weird since the latest release.

**Comment by Ahagan** [comment]
It wasn't as issue in the previous version. I got it working though:

I changed my code to:
        peerConnection.createOffer().then(peerConnection.setLocalDescription)
            .then(() => {
                self.socket.emit('exchange', { 'to': socketId, 'sdp': peerConnection.localDescription });

            })
            .catch(this.logError);

**Comment by 8BallBomBom** [comment]
Yeah, seems the promise based changes in the latest release are being weird for non promise based functions.

**Comment by saghul** [comment]
@zxcpoiu ping

**Comment by zxcpoiu** [comment]
@Ahagan 

I don't have two iPhone so tested on both android. Can not reproduce.

My test process:

1. clone https://github.com/thoqbk/rewebrtc
2. change package.json for react-native-webrtc to 1.63.0
3. npm install
4. manually link webrtc on android ( default project does not link for you )
5. react-native run-android

I've tested all day, but nothing happened on both A or B side, no matter joined first or not.
The later joined B user will invoke `createOffer` then the first joined A user will invoke `createAnswer` 

I add some logs in https://github.com/thoqbk/rewebrtc/blob/master/src/lib/services.js#L57-L65
It's a callback based code and it works all well.

Does this only occurs on iOS?
Sorry I really can't reproduce it.

@8BallBomBom 

Are you encounter the same issue?

**Comment by zxcpoiu** [comment]
@Ahagan 

can you `rm -rf node_module` and follow my process to re-install 1.63.0 then give it another try?

**Comment by 8BallBomBom** [comment]
I'm having no issues at all, also tested the callback functions.
Everything working whether the functions are callback, promise or async.
Can't reproduce the issue :/
