### ISSUE TITLE
How to leave the room and disconnect?

### ISSUE THREAD

**Issue by bacancy-swaroopa** [oney/react-native-webrtc#473]
Hi,

I am using this module for video calling and in my screen the video is connect and have a back button in that.

So, I want  when click on back button I showed an alert like are you sure you want to leave so when user clicks leave then I want to leave the room and disconnect from socket
I kept the following code
`  Alert.alert(
    'Fanler',
    'Are you sure you want to leave the page?',
    [
      {text: 'No', onPress: () => console.log('Cancel Pressed'), style: 'cancel'},
      {text: 'Yes', onPress: () => {
            alert('socketId'+this.state.socketId);
            socket.on('leave', function(socketId){
              leave(this.state.socketId);
          });
      }},
    ],
    { cancelable: false }
  )` 
#### Expected behavior
the user has to leave the room and disconnect from socket

#### Observerd behavior
so when click on that no action is getting performed and leave method is not at all calling.
So can u tell me how to leave the room and disconnect when clicking on back button?

#### Platform information
in both iOS and android
* **React Native version**: ^0.43.3
* **Plugin version**:^1.63.0

**Comment by saghul** [comment]
I don't know what application / package you are using, but that code does not belong to this plugin.

**Comment by bacancy-swaroopa** [comment]
@saghul I have taken that leave function from the demo appilicaiton given by this module only not any other plugin

**Comment by saghul** [comment]
Then please open the issue on the demo project, this is not that.
