### ISSUE TITLE
Call from RN to Desktop Chrome: no video being sent from RN

### ISSUE THREAD

**Issue by dmneasis** [oney/react-native-webrtc#478]
Hello everyone,

I'm working on an implementation of mine. The RN based app is calling a Desktop web app. The call works fine, I have audio on both ends, I can see the video from the desktop on the mobile. However, although I can see the local video on the mobile, this video is not being sent to the Desktop. I get a stream and a track id for the video (of kind 'video'), but the track is empty and no packet data is being transmitted.

Any idea? Could it be some kind of bug from the RTCView?

**Comment by jnragu** [comment]
I'm having the same issue. I've created a peer connection and the Desktop acknowledges that the RN peer is there. However, my setRemoteDescription is never happening properly, so I can't create an answer to the sdp signal

**Comment by mrsantran** [comment]
How to resolved  this ? 

> Hello everyone,
> 
> I'm working on an implementation of mine. The RN based app is calling a Desktop web app. The call works fine, I have audio on both ends, I can see the video from the desktop on the mobile. However, although I can see the local video on the mobile, this video is not being sent to the Desktop. I get a stream and a track id for the video (of kind 'video'), but the track is empty and no packet data is being transmitted.
> 
> Any idea? Could it be some kind of bug from the RTCView?

How to resolved this?
