### ISSUE TITLE
RTCMediaStream releaseTrack or stopTrack

### ISSUE THREAD

**Issue by dguillamot** [oney/react-native-webrtc#48]
Hi, 

I was looking at adding a releaseTrack method to WebRTCModule+RTCMediaStream.m so that I can mute video/audio individually however RTCMediaStream is unavailable to edit or see the internals of. It seems that this part of the library is closed-source?

I see it has a [mediaStream addVideoTrack:videoTrack]; method..  Is there an equivalent releaseVideoTrack or stopVideoTrack method inside? Other WebRTC implementations implement stream.getVideoTracks()[0].enabled = false. However any JS changes made on the MediaStreamTracks are not passed into the objective C WebRTC implementation. 

Between releaseVideoTrack, stopVideoTrack or track.enabled = false, is there anyway for me to submit a PR for you given the limited visibility into the RTCMediaStream.m internals?

Or, if this is in development already, can you provide a status update? 

Thanks,

**Comment by oney** [comment]
If you would like to mute a audio track. `track.enabled = false` is more appropriate.

RTCMediaStream is from https://github.com/pristineio/webrtc-build-scripts
It's open source, but we wouldn't change it.

`track.enabled = false` on javascript is equivalent to 
```objectivec
RTCMediaStreamTrack *track;
[track setEnabled: NO];
```
on iOS

There are some works on bridging them.

**Comment by dguillamot** [comment]
Thank you.

track.enabled = false 

Would be great. But, this did not work for video tracks when I was testing. Is this implemented or is it the desired implementation that is coming?

**Comment by oney** [comment]
`track.enabled = false` is not implemented yet.
According to [spec](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack), it should be implemented, but I don't have time to do it.

**Comment by zxcpoiu** [comment]
I currently implementing, and almost done ( now for android ), that's why I asked a noob question to oney.

since we only pass a Map trackInfo to javascript not the track object it self, so if you set `track.enable = false` in javascript land, it just change the value itself and doesn't work at all.

and implementation maybe should use getter/setter on `enabled`. and invoke native setEnable function in setter.

I will make a PR today ( android )

@dguillamot I'm not familiar with objc, do you want to do this :)

**Comment by dguillamot** [comment]
Yes, I noticed that it has no effect since it is only in the JS side and not passed to native. That is why in my implementation I was calling a native function directly to propagate the change. However, track.enabled = true/false would be a better implementation..

**Comment by zxcpoiu** [comment]
@dguillamot 

android version is done.

use: 
`track.enabled = true`

**Comment by dguillamot** [comment]
I submitted an ios version. You can find at this PR https://github.com/oney/react-native-webrtc/pull/51

Changes made were:

- Added setEnabled to MediaStreamTrack.js (and trackSetEnabled to WebRTCModule+RTCMediaStream.m)

- Added mediaStreamRelease to WebRTCModule+RTCMediaStream.m (this is not needed for enable/disable but included it for completion).

**Comment by zxcpoiu** [comment]
nice
