### ISSUE TITLE
Empty remote video stream

### ISSUE THREAD

**Issue by dmneasis** [oney/react-native-webrtc#480]
Hello everyone.

I'm facing a serious issue while working on my own implementation based on react-native-webrtc.

I successfully implemented react-native-webrtc with a SIP library (JsSIP) and an Asterisk media server. My app allows peer to peer calls between Android phone (React Native) and Web desktop (React).

The project works like a charm when calling from Web to Web (React only).

When calling from Android to Web (react-native-webrtc involved), I get the following situation:
- Audio is working perfectly
- I see the remote video on Android (alias I can always see the video from the desktop camera)
- I get a "correct" remote video stream/track from the Android on the Web, but this video is empty: I can't see anything, no packet data seems to be transmitted.
- Local video always woks on both ends.

I am adding the Android stream to the RTCView, however, and I can see it locally.

Question: am I missing something? Where does react-native-webrtc send the stream? Does it manipulate/encode the video before sending?

**Comment by saghul** [comment]
Please don't open duplicate issues. You already opened #478 .

**Comment by awesomemarcus** [comment]
is there already a solution for this? I've encountered this issue too, when creating offer/answer, sdp has direction set to "recvonly", even though I have a camera and is working on my local. I was expecting it to be "sendrecv".
