### ISSUE TITLE
setRemote description not runnning 

### ISSUE THREAD

**Issue by jnragu** [oney/react-native-webrtc#488]
#### Expected behavior
setRemoteDescription should be running either success or fail callbacks.

#### Observerd behavior

Not running WebRTCModule.peerConnectionSetRemoteDescription ( ... ) , not getting success or failure. Prints out undefined this.remoteDescription undefined before and after. Seems to skip the function. 

  setRemoteDescription(sessionDescription: RTCSessionDescription, success: ?Function, failure: ?Function) {
    console.log('Setting Remote Description: ', sessionDescription);
    console.log('this.remoteDescription before: ', this.remoteDescription);
    console.log('sessionDescription.toJSON: ', sessionDescription.toJSON())
    WebRTCModule.peerConnectionSetRemoteDescription(sessionDescription.toJSON(), this._peerConnectionId, (successful, data) => {
      if (successful) {
        this.remoteDescription = sessionDescription;
        console.log('Success');
        success();
      } else {
        console.log('Failure');
        failure(data);
      }
    });
    console.log('this.remoteDescription after: ', this.remoteDescription);
  }

This is the console logs I'm getting:

pc RTCPeerConnection {signalingState: "stable", iceGatheringState: "new", iceConnectionState: "new", _localStreams: Array(1), _remoteStreams: Array(0), …}
index.ios.bundle?pla…e&minify=false:1403 peer {userID: "17f03b7e-4312-1da9-ed40-5a45835ac5b2", number: undefined, peerConnection: RTCPeerConnection}number: undefinedpeerConnection: RTCPeerConnection {signalingState: "stable", iceGatheringState: "new", iceConnectionState: "new", _localStreams: Array(1), _remoteStreams: Array(0), …}userID: "17f03b7e-4312-1da9-ed40-5a45835ac5b2"__proto__: Object
index.ios.bundle?pla…&minify=false:53951 Setting Remote Description:  RTCSessionDescription {sdp: "v=0
↵o=- 4809947223636492230 2 IN IP4 127.0.0.1
↵s…9585 label:3aa8ac41-1078-4e15-a029-8368d446cac5
↵", type: "offer"}
index.ios.bundle?pla…&minify=false:53952 this.remoteDescription before:  undefined
index.ios.bundle?pla…&minify=false:53953 sessionDescription.toJSON:  {sdp: "v=0
↵o=- 4809947223636492230 2 IN IP4 127.0.0.1
↵s…9585 label:3aa8ac41-1078-4e15-a029-8368d446cac5
↵", type: "offer"}
index.ios.bundle?pla…&minify=false:53964 this.remoteDescription after:  undefined
index.ios.bundle?pla…e&minify=false:1391 Got message:  {type: "ice", ice: {…}, userID: "17f03b7e-4312-1da9-ed40-5a45835ac5b2"}
index.ios.bundle?pla…e&minify=false:1422 exchange candidate {type: "ice", ice: {…}, userID: "17f03b7e-4312-1da9-ed40-5a45835ac5b2"}
index.ios.bundle?pla…e&minify=false:1391 Got message:  {type: "ice", ice: {…}, userID: "17f03b7e-4312-1da9-ed40-5a45835ac5b2"}
index.ios.bundle?pla…e&minify=false:1422 exchange candidate {type: "ice", ice: {…}, userID: "17f03b7e-4312-1da9-ed40-5a45835ac5b2"}
index.ios.bundle?pla…e&minify=false:1391 Got message:  {type: "ice", ice: {…}, userID: "17f03b7e-4312-1da9-ed40-5a45835ac5b2"}
index.ios.bundle?pla…e&minify=false:1422 exchange candidate {type: "ice", ice: {…}, userID: "17f03b7e-4312-1da9-ed40-5a45835ac5b2"}
index.ios.bundle?pla…e&minify=false:1391 Got message:  {type: "ice", ice: {…}, userID: "17f03b7e-4312-1da9-ed40-5a45835ac5b2"}
index.ios.bundle?pla…e&minify=false:1422 exchange candidate {type: "ice", ice: {…}, userID: "17f03b7e-4312-1da9-ed40-5a45835ac5b2"}

#### Steps to reproduce the problem
I took the demo code from oney and replaced it with my signaling server. Set remote description stopped working and cannot create an answer to the sdp offer. 

#### Platform information

* **React Native version**:
* **Plugin version**:
* **OS**: iOS 11
* **OS version**:
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0",
    "react-native-webrtc": "git+https://git@github.com/oney/react-native-webrtc.git",
    "socket.io-client": "^1.3.7"
  }

**Comment by saghul** [comment]
The demo hasn't been updated in almost 2 years. Please try your own code, with the latest version of the plugin.
