### ISSUE TITLE
WiFi Camera 

### ISSUE THREAD

**Issue by donei003** [oney/react-native-webrtc#489]
Hello,

I am working on a project which includes a WiFi enabled endoscope. The phone connects to the endoscope's network and gathers it's video/image feed which can be saved to the phone and sent to a remote server (from the phone). So far, I have not had any luck with establishing such a feed. With that said, the manufacturer of the endoscope, Depstech, has an app on both the Play & App Store called "WiFi View" which allows the user to see the live feed from the endoscope, record & save images. 

I am curious as to whether or not this is possible with webrtc since the endoscope is not connected to the internet. Any resources or material pointing me in the right direction would be greatly appreciated. Thanks!

**Comment by saghul** [comment]
You can probably get some sort of encoded data (probably H264) from the device by connecting to some port (this is how some drones work). 

Then you'd need to build your own capturer for the platform that you're interested in. For example, this is the interface in iOS: https://github.com/jitsi/webrtc/blob/master/sdk/objc/Framework/Headers/WebRTC/RTCVideoCapturer.h

All this, however, falls out of the scope of this plugin, alas, so you'll have to hack your way around.

Good luck!
