### ISSUE TITLE
 IOS camera is 90 degrees off of the initial position

### ISSUE THREAD

**Issue by Proxy08** [oney/react-native-webrtc#492]
When I use webrtc on Android is work perfectly, but on IOS everything on the camera is bend over, like 90 degrees off of the initial position. Any help, please ?

React Native version: 0.56.0
Plugin version: "react-native-webrtc": "^1.54.7"
OS:   iOS

**Comment by saghul** [comment]
Please update to 1.63.

**Comment by Proxy08** [comment]
I updated to 1.63 however it still did not solve my problem, it's even gotten worse, now it very slow and still 90 degrees off in my landscape mode
