### ISSUE TITLE
max dimensions are resulting in no video

### ISSUE THREAD

**Issue by Vijay-mRoads** [oney/react-native-webrtc#498]
#### Expected behavior
Video should be displayed when I set **maxWidth** and **maxHeight**

#### Observerd behavior
Video is not getting displayed unless I remove **maxWidth** and **maxHeight**

#### Steps to reproduce the problem

Pass constraints 

{
	video: {
		mandatory: {
			maxWidth: 320,
			maxHeight: 240,
			maxFrameRate: 20
		},
		facingMode: 'user',
	},
	audio: true
}

display stream on a RTCView

#### Platform information

* **React Native version**:0.56.0
* **Plugin version**:1.67.0
* **OS**: iOS 
* **OS version**:10.3.3

**Comment by saghul** [comment]
Hum, interesting. We currently ignore those constraints in the native code anyway, so I wonder what is causing this.

**Comment by Vijay-mRoads** [comment]
Do you need any more data to help you debug this?

**Comment by zxcpoiu** [comment]
@Vijay-mRoads 

Could you check and paste what are constraints look like on both js side and native side. ( before and after invoking `getUserMedia` )

**Comment by Vijay-mRoads** [comment]
I found the solution for my issue. It seems there are default values for minHeight and minWidth which are higher than maxWidth and minWidth.
Like the below
`
{
    facingMode = user;
    mandatory =     {
        maxFrameRate = 20;
        maxHeight = 240;
        maxWidth = 320;
        minFrameRate = 30;
        minHeight = 720;
        minWidth = 1280;
    };
    optional =     (
    );
}
`

setting minHeight and minWidth  to zero or value below got me rolling again. I think the library should validate these and pop errors instead of giving empty video.

Thanks @saghul  and @zxcpoiu  for your replies.
