### ISSUE TITLE
[1.67.0][Android] Error on Building, Java 8 Compat

### ISSUE THREAD

**Issue by cristiantx** [oney/react-native-webrtc#505]
I keep getting this error when trying to build the latest version.

```
Jack is required to support java 8 language features. Either enable Jack or remove sourceCompatibility JavaVersion.VERSION_1_8
```
I know Jack is deprecated on Android, but I can't get it to work.

I'm using default versions of Gradle for RN56
gradle-plugin@2.3.3, gradle@3.5.1, gradle-download-task@3.4.3,

Added the compileOptions as the docs say
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

Which should support Java 8 expressions. Any ideas?

**Comment by cristiantx** [comment]
@8BallBomBom Sorry to tag you, but you have been working with this version and might have some idea. Thanks!

**Comment by 8BallBomBom** [comment]
What i'd suggest is trying to upgrade your gradle build tools to 3.1.3 also edit /android/gradle/wrapper/gradle-wrapper.properties `distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`

Here are both my build files.
https://pastebin.com/S8CLkpBp
https://pastebin.com/5zbyEyZE

So you can get some idea as to what my config is like which is currently working without issues.
I would also say use the other react gradle file mentioned in [here](https://github.com/oney/react-native-webrtc/issues/499) but i think RN 0.56 already includes that patch.

**Comment by cristiantx** [comment]
That worked. Thanks a lot

**Comment by cristiantx** [comment]
@saghul Should we include some notes on the documentation to point this should be also done? I can help on that making some small guide using @8BallBomBom information.

**Comment by saghul** [comment]
@cristiantx Sure thing, thank would be most welcome!
