### ISSUE TITLE
RTCView：How do you get a full screen, full screen

### ISSUE THREAD

**Issue by zgh-yuanshang** [oney/react-native-webrtc#506]
How to configure：
```javascript
getUserMedia({
        audio: true,
        video: {
            mandatory: {
                minWidth: 1280, // Provide your own width, height and frame rate here
                minHeight: 720,
                minFrameRate: 30,
            },
            facingMode: (isFront ? "user" : "environment"),
            optional: (videoSourceId ? [{sourceId: videoSourceId}] : []),
        }
    }, function (stream) {
        console.log('getUserMedia success', stream);
        callback(stream);
    }, logError);
```

**Comment by saghul** [comment]
You need to use React Native style props to make the RTCView full screen, it has nothing to do with the resolution at which you open the camera.

**Comment by aoarashi1988** [comment]
@zgh-yuanshang try the 'objectFit' props, set it to cover

**Comment by rashidul-hasan** [comment]
> @zgh-yuanshang try the 'objectFit' props, set it to 'cover'

This worked for me. Thanks.

**Comment by ForevereBest** [comment]
How to set the full screen?

**Comment by webQin** [comment]
how to set the full screen, when screen rotate？

**Comment by ForevereBest** [comment]
Jump to a page in landscape mode, and then re-layout


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "react-native-webrtc/react-native-webrtc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 中午11:34
收件人:&nbsp;"react-native-webrtc/react-native-webrtc"<react-native-webrtc@noreply.github.com&gt;;
抄送:&nbsp;"Forever"<3222694807@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [react-native-webrtc/react-native-webrtc] RTCView：How do you get a full screen, full screen (#506)





 
how to set the full screen, when screen rotate？

**Comment by webQin** [comment]
> 跳转到横向模式下的页面，然后重新布局
> […](#)
> ------------------＆nbsp;原始邮件＆nbsp; ------------------发件人：“ react-native -webrtc / react-native-webrtc“ <notifications@github.com> ;; 发送时间：2021年1月21日（星期四）中午11:34收件人：“ react-native-webrtc / react-native-webrtc” <react-native-webrtc@noreply.github.com> ; 抄送：“永远” <3222694807@qq.com> ;;“评论” <comment@noreply.github.com> ;; 主题：＆nbsp; Re：[react-native-webrtc / react-native-webrtc] RTCView：如何获得全屏，全屏（[＃506](https://github.com/react-native-webrtc/react-native-webrtc/issues/506)）如何在旋转屏幕时设置全屏？？ —您收到此评论是因为您发表了评论。直接回复此电子邮件，在GitHub上查看或取消订阅。

I turn width into height and height into width，However, the final width is no problem, that is, the height, checked a little bit, about 50 up and 50 down
