### ISSUE TITLE
issue on installing webrtc

### ISSUE THREAD

**Issue by moeinrahimi** [oney/react-native-webrtc#511]
i get this error after building android
react-native run-android
```
 What went wrong:
A problem occurred configuring project ':WebRTCModule'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V
```
i used the android installation instruction .

**Comment by saghul** [comment]
Please see https://github.com/oney/react-native-webrtc/pull/508

**Comment by moeinrahimi** [comment]
@saghul 
my issue with updating gradle build tools is i get 404 from jcenter, i changed repo url by changing jcenter() to google() but it is also 404
my dependencies ,
dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
```
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
     Required by:
         project :
```

**Comment by saghul** [comment]
We just updated the instructions, please check and try again.

**Comment by moeinrahimi** [comment]
@saghul 
well the ext option is wrong in docs , it should be like this
       ext { 
  compileSdkVersion =  27
  buildToolsVersion = '27.0.3'
  
}
and now i'm getting this error .
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :WebRTCModule.
     Required by:
         project :app
      > Unable to find a matching configuration of project :WebRTCModule: None of the consumable configurations have attributes.

**Comment by moeinrahimi** [comment]
solved my issue simply by installing sdk platform 27 from sdk manager
