### ISSUE TITLE
Failed to set remote offer sdp: max-bundle is used but no bundle group found

### ISSUE THREAD

**Issue by bmp123** [oney/react-native-webrtc#515]
Hi. I have a problem with ios device. If I calling from chrome to ios I see an error:
name: 'SetRemoteDescriptionFailed'
message: 'Failed to set remote offer sdp: max-bundle is used but no bundle group found.'

My sdp: 
variable_switch_r_sdp: [v=0
o=- 5472816676170389135 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS jwEcynA4ow1uvEeVmD6b3SX4kV0qIA3obi9e
m=audio 63027 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 212.220.116.80
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:1730544014 1 udp 2122260223 192.168.88.74 63027 typ host generation 0 network-id 1 network-cost 10
a=candidate:3865970490 1 udp 1686052607 212.220.116.80 63027 typ srflx raddr 192.168.88.74 rport 63027 generation 0 network-id 1 network-cos
t 10
a=candidate:698744190 1 tcp 1518280447 192.168.88.74 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:unc9
a=ice-pwd:ZTguyDX2WsPp1ZXgkwgf/R6S
a=ice-options:trickle
a=fingerprint:sha-256 DC:B9:FC:DB:03:B3:FF:10:31:9C:79:04:E5:86:52:9A:CA:28:B5:3D:F2:4C:C5:69:5A:41:B8:E0:60:8D:FC:A8
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2434537496 cname:NyaimRoc37y/93ew
a=ssrc:2434537496 msid:jwEcynA4ow1uvEeVmD6b3SX4kV0qIA3obi9e 7cfefa32-20c4-4a43-9d31-747239e0beff
a=ssrc:2434537496 mslabel:jwEcynA4ow1uvEeVmD6b3SX4kV0qIA3obi9e
a=ssrc:2434537496 label:7cfefa32-20c4-4a43-9d31-747239e0beff
]

#### Platform information

* **React Native version**: 0.55.4
* **Plugin version**: 1.67.1
* **OS**: iOS

**Comment by bmp123** [comment]
any ideas?

**Comment by saghul** [comment]
That's weird, I don't see anything obvious, the SDP looks ok, sorry 😞

**Comment by bmp123** [comment]
@saghul error in this code : 
`pc.setRemoteDescription(new RTCSessionDescription({ type: 'offer', sdp }))`. Maybe this help to find solution

**Comment by bmp123** [comment]
What can calls this error?

**Comment by bmp123** [comment]
oh, I mistaked, this issue not resolved.. Any ideas please!

**Comment by bmp123** [comment]
how to set bundle group or how to unset max-bundle?

**Comment by 8BallBomBom** [comment]
You can set the bundlePolicy on RTCPeerConnection when you create it.
Pretty much pass it the same way you did with the IceServers.
https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration#RTCBundlePolicy_enum

**Comment by bmp123** [comment]
I tried but is does not solution...
`const pc = new RTCPeerConnection({
    iceServers,
    bundlePolicy: 'balanced',
  });
`
My solution is to add correct tags in sdp..
"v=0
o=FreeSWITCH 1537930019 1537930020 IN IP4 82.151.200.249
s=FreeSWITCH
t=0 0
a=msid-semantic: WMS TgjRI3elVCQUw1tMsIef8vmIF86xkQU4
a=end-of-candidates
a=group:BUNDLE audio
m=audio 14560 RTP/SAVPF 0 8
c=IN IP4 82.151.200.249
a=mid:audio
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=fingerprint:sha-256 C0:D8:29:A3:34:60:16:B0:AA:B9:C9:92:82:10:5F:D6:98:3A:F2:69:A7:80:1E:0F:CC:A1:BD:A8:F6:28:D5:F6
a=setup:actpass
a=rtcp-mux
a=rtcp:14560 IN IP4 82.151.200.249
a=ssrc:1692546899 cname:W4LuXQGJimuFdNiw
a=ssrc:1692546899 msid:TgjRI3elVCQUw1tMsIef8vmIF86xkQU4 a0
a=ssrc:1692546899 mslabel:TgjRI3elVCQUw1tMsIef8vmIF86xkQU4
a=ssrc:1692546899 label:TgjRI3elVCQUw1tMsIef8vmIF86xkQU4a0
a=ice-ufrag:lmBkHOSdMOBXvlRi
a=ice-pwd:ftD3a9DilXOpAWLL9cWGQEKt
a=candidate:1106224958 1 udp 659136 82.151.200.249 14560 typ host generation 0
a=candidate:1106224958 2 udp 659136 82.151.200.249 14560 typ host generation 0
a=silenceSupp:off - - - -
a=ptime:20
a=sendrecv
"

**Comment by davidestrela** [comment]
Hi there,

Can you try to switch the type from `offer` to `awswer` 
 
> `pc.setRemoteDescription(new RTCSessionDescription({ type: 'offer', sdp }))`. Maybe this help to find solution

Hope it helps

**Comment by bmp123** [comment]
pc.Offer() generate a sdp with video block always. And, I dont know why, tags in OFFER sdp in not right sequence.. In WebAPI what sequence of sdp tags we need. I tried change like in WebAPI and webrtc earned. But why this work only like this...

**Comment by bmp123** [comment]
Hi, I found solution `pc.createOffer({
          mandatory: {
            OfferToReceiveVideo: false,
            OfferToReceiveAudio: true,
          },
        }),` thank you for answers!

**Comment by saghul** [comment]
Excellent! I'm going to go ahead and close this then.

**Comment by namnm** [comment]
Hi, I'm getting this exact error.
I tried to set contrains.mandatory but it's still the same.
If I change the bundlePolicy, this error wont show up but the iceConnectionState after about 30 seconds of `checking` it becomes `failed`.

Any idea, please help.
Thanks!

**Comment by namnm** [comment]
Btw the error message on offer side and answer side is different.
- On the offer side: the message is: Failed to set remote answer sdp: Answer can not remove m= section audio from already-established BUNDLE group.
- On the answer side: Failed to set remote offer sdp: max-bundle is used but no bundle group found.

Look like the error on the answer side occur first then on the offer side.

**Comment by nsmet** [comment]
Hi guys, 

I'm experiencing the same problem and can't find a solution. In my case Device 1 calls Device 2. Device 1 only has audio, but Device 2 has audio and video. 

Offer
```
v=0
o=- 5645355810408982095 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Rnov
a=ice-pwd:ss7liTdhadxNbTOBew98/SOJ
a=ice-options:trickle renomination
a=fingerprint:sha-256 BE:7D:A4:DB:D4:C3:7F:4F:35:AB:AE:64:0E:8F:E3:9D:9B:0C:D5:3D:69:85:E7:D7:0D:9E:A4:58:F0:21:BB:DC
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 123 125 122 124
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Rnov
a=ice-pwd:ss7liTdhadxNbTOBew98/SOJ
a=ice-options:trickle renomination
a=fingerprint:sha-256 BE:7D:A4:DB:D4:C3:7F:4F:35:AB:AE:64:0E:8F:E3:9D:9B:0C:D5:3D:69:85:E7:D7:0D:9E:A4:58:F0:21:BB:DC
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c2a
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e02a
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 VP9/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=127
a=rtpmap:125 red/90000
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=125
a=rtpmap:124 ulpfec/90000
 ```

Answer 
```
v=0
 o=- 5645355810408982095 0 IN IP4 0.0.0.0
 s=-
 t=0 0
 m=audio 0 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
 c=IN IP4 0.0.0.0
 a=rtcp:9 IN IP4 0.0.0.0
 a=ice-ufrag:Rnov
 a=ice-pwd:ss7liTdhadxNbTOBew98/SOJ
 a=ice-options:trickle renomination
 a=fingerprint:sha-256 BE:7D:A4:DB:D4:C3:7F:4F:35:AB:AE:64:0E:8F:E3:9D:9B:0C:D5:3D:69:85:E7:D7:0D:9E:A4:58:F0:21:BB:DC
 a=setup:actpass
 a=mid:audio
 a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
 a=recvonly
 a=rtcp-mux
 a=rtpmap:111 opus/48000/2
 a=rtcp-fb:111 transport-cc
 a=fmtp:111 minptime=10;useinbandfec=1
 a=rtpmap:103 ISAC/16000
 a=rtpmap:104 ISAC/32000
 a=rtpmap:9 G722/8000
 a=rtpmap:102 ILBC/8000
 a=rtpmap:0 PCMU/8000
 a=rtpmap:8 PCMA/8000
 a=rtpmap:106 CN/32000
 a=rtpmap:105 CN/16000
 a=rtpmap:13 CN/8000
 a=rtpmap:110 telephone-event/48000
 a=rtpmap:112 telephone-event/32000
 a=rtpmap:113 telephone-event/16000
 a=rtpmap:126 telephone-event/8000
 m=video 0 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 123 125 122 124
 c=IN IP4 0.0.0.0
 a=rtcp:9 IN IP4 0.0.0.0
 a=ice-ufrag:Rnov
 a=ice-pwd:ss7liTdhadxNbTOBew98/SOJ
 a=ice-options:trickle renomination
 a=fingerprint:sha-256 BE:7D:A4:DB:D4:C3:7F:4F:35:AB:AE:64:0E:8F:E3:9D:9B:0C:D5:3D:69:85:E7:D7:0D:9E:A4:58:F0:21:BB:DC
 a=setup:actpass
 a=mid:video
 a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
 a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
 a=extmap:4 urn:3gpp:video-orientation
 a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
 a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
 a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
 a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
 a=recvonly
 a=rtcp-mux
 a=rtcp-rsize
 a=rtpmap:96 H264/90000
 a=rtcp-fb:96 goog-remb
 a=rtcp-fb:96 transport-cc
 a=rtcp-fb:96 ccm fir
 a=rtcp-fb:96 nack
 a=rtcp-fb:96 nack pli
 a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c2a
 a=rtpmap:97 rtx/90000
 a=fmtp:97 apt=96
 a=rtpmap:98 H264/90000
 a=rtcp-fb:98 goog-remb
 a=rtcp-fb:98 transport-cc
 a=rtcp-fb:98 ccm fir
 a=rtcp-fb:98 nack
 a=rtcp-fb:98 nack pli
 a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e02a
 a=rtpmap:99 rtx/90000
 a=fmtp:99 apt=98
 a=rtpmap:100 VP8/90000
 a=rtcp-fb:100 goog-remb
 a=rtcp-fb:100 transport-cc
 a=rtcp-fb:100 ccm fir
 a=rtcp-fb:100 nack
 a=rtcp-fb:100 nack pli
 a=rtpmap:101 rtx/90000
 a=fmtp:101 apt=100
 a=rtpmap:127 VP9/90000
 a=rtcp-fb:127 goog-remb
 a=rtcp-fb:127 transport-cc
 a=rtcp-fb:127 ccm fir
 a=rtcp-fb:127 nack
 a=rtcp-fb:127 nack pli
 a=rtpmap:123 rtx/90000
 a=fmtp:123 apt=127
 a=rtpmap:125 red/90000
 a=rtpmap:122 rtx/90000
 a=fmtp:122 apt=125
 a=rtpmap:124 ulpfec/90000
```

RN: 0.57.55
Web-rtc: 1.69.1

**Comment by hthetiot** [comment]
I also have the same problem with cordova-plugin-iosrtc using WebRTC M69, I'm looking into it.
- https://github.com/cordova-rtc/cordova-plugin-iosrtc/pull/399

**Comment by hthetiot** [comment]
I found a fix, adding "rtcConfiguration.bundlePolicy = RTCBundlePolicy.balanced;" did fix the issue.
Thank you @8BallBomBom

**Comment by hthetiot** [comment]
@saghul 
```
Specifies how to handle negotiation of candidates when the remote peer is not compatible with the SDP BUNDLE standard. This must be one of the values from the enum RTCBundlePolicy. If this value isn't included in the dictionary, "balanced" is assumed.
```
:)

**Comment by saghul** [comment]
I believe this plugin already has support for it, but at any rate, if there is a "WebRTC" device out there not supporting BUNDLE in 2019, I'd stay away from it.

**Comment by v-bianchi** [comment]
> I found a fix, adding "rtcConfiguration.bundlePolicy = RTCBundlePolicy.balanced;" did fix the issue.

Sorry for the n00b question @hthetiot , but where exactly do I add these configs?

**Comment by hthetiot** [comment]
RTFM @v-bianchi seriously or use google next time.... 

I hate when people ask questions that are not DIRECTLY related to the issue and it's even worse on a closed issue.
If you are not capache of googling how to use WebRTC you should change job or delegate to someone that does.
If it was my repository i would have banned you 30 days for you top learn the lesson.

In any case because I'm here now, here is a clue:
```
new PeerConnection({
    bundlePolicy: 'balanced'
    ....
})
```

**Comment by saghul** [comment]
@hthetiot Rather than sending these kind of replies, stay silent.

**Comment by hthetiot** [comment]
yeah i know sorry @saghul
