### ISSUE TITLE
Integrate with Openvidu

### ISSUE THREAD

**Issue by randymuhroji** [oney/react-native-webrtc#518]
Hi.
for web using openvidu but I have difficulty connecting openvidu with react-native-webrtc.

I can publish videos from mobile(react-native-webrtc) to the web (openvidu), but I failed to receive videos from the web to mobile.

can you help me to fix the code?

https://github.com/randymuhroji/react-native-webrtc-openvidu

**Comment by saghul** [comment]
Sorry, this is not what issues are for. You may have better luck at openvidu forums / mailing lists.
