### ISSUE TITLE
Failed to set remote offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answer

### ISSUE THREAD

**Issue by zuijiaoluo** [oney/react-native-webrtc#520]
#### Expected behavior
It should be able to link normally every time
#### Steps to reproduce the problem
The first link between the two sides was successful, but from the second time, there was such a problem.
#### Platform information
* **React Native version**:   0.55.3
* **Plugin version**:  1.67.1
* **OS**:   IOS
* **OS version**:   12.0

**Comment by zuijiaoluo** [comment]
Failed to set remote offer sdp: Called in wrong state: kHaveLocalOffer

**Comment by zuijiaoluo** [comment]
Sorry, I don't understand webrtc development very well. What is the correct time? Is there a reference document?

**Comment by felixSchl** [comment]
I found documentation to be a mess. Luckily the sources are quite readable. You're running into this: https://chromium.googlesource.com/external/webrtc/+/master/pc/peerconnection.cc#2189.

**Comment by felixSchl** [comment]
The sources reveal that the only valid time to apply a remote offer is when we're in the "stable" or "have-remote-offer" signaling state. So you'll have to wait for the signaling state to be right before applying the remote offer.

**Comment by zuijiaoluo** [comment]
It seems that I haven't got any particular solution yet. I'm testing the code in demo. Will you update the demo code? It doesn't seem perfect

**Comment by saghul** [comment]
The demos have not been written by those who maintain this plugin. Please ask the demo authors.

**Comment by caiseblue** [comment]
example:
   1. offer: invite   m=audio 50000 RTP/AVP 8
      answer: 200   m=audio 40000 RTP/AVP 8
   2.offer: reinvite   m=audio 50001 RTP/AVP 0 8
      The first time it was 8, the second time it was 08.The offer order does not match.
