### ISSUE TITLE
Google deprecating many terms from build.gradle at the end of this year. any plan to upgrade the project?

### ISSUE THREAD

**Issue by Shhzdmrz** [oney/react-native-webrtc#522]
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

#### Expected behavior
Should not produce any warning.
#### Observerd behavior
Returning warning for new projects.
#### Steps to reproduce the problem
Create new project with RN version 0.57.0
#### Platform information
* **React Native version**: 0.57.0
* **Plugin version**: 1.67.1
* **OS**: Android
* **OS version**: Windows

**Comment by 8BallBomBom** [comment]
Pretty much been making these changes myself.
Would be nice to see a lot of projects move this along.

**Comment by Shhzdmrz** [comment]
I think I also have to push a PR. It's on me.
