### ISSUE TITLE
Installation instruction requires to add deprecated libraries form iOS

### ISSUE THREAD

**Issue by wjelen26** [oney/react-native-webrtc#523]
Library libstdc++.tbd is deprecated, and Xcode 10 (iOS 12) does not contain it, but one step in documentation requires to link it during installation. Any workaround for that step for iOS 12?

**Comment by anagar23** [comment]
I found this https://stackoverflow.com/a/50734510/6261302.
The Library should get update using libc++.

**Comment by saghul** [comment]
A PR fining this would be most welcome.

**Comment by saghul** [comment]
Fixed in https://github.com/oney/react-native-webrtc/pull/547
