### ISSUE TITLE
Promises support

### ISSUE THREAD

**Issue by alongubkin** [oney/react-native-webrtc#53]
See here: https://blog.andyet.com/2015/11/18/modern-webrtc-js/

The callback version is now deprecated.

**Comment by zxcpoiu** [comment]
Hmm...I'm not familiar with it, in your thought, is Promise.promisify() in javascript land enough?
or should we refactoring native method like [this](https://facebook.github.io/react-native/docs/native-modules-android.html#promises)?

**Comment by oney** [comment]
I hope we can support both legacy and Promise-based version. I don't really know how to adapt it appropriately. Is the following codes okay?
```javascript
createOffer(success: ?Function, failure: ?Function, constraints) {
  if (typeof success === 'function') {
    WebRTCModule.peerConnectionCreateOffer(this._peerConnectionId, (successful, data) => {
      if (successful) {
        var sessionDescription = new RTCSessionDescription(data);
        success(sessionDescription);
      } else {
        failure(data);
      }
    });
  } else {
    return new Promise(function(resolve, reject) {
      WebRTCModule.peerConnectionCreateOffer(this._peerConnectionId, (successful, data) => {
        if (successful) {
          var sessionDescription = new RTCSessionDescription(data);
          resolve(sessionDescription);
        } else {
          reject(data);
        }
      });
    });
  }
}
```

**Comment by philikon** [comment]
In essence, yes. But that's a lot of code duplication. And there's really no reason to not return a `Promise` even in the legacy callback case.

`createOffer` and `createAnswer` are a bit of an oddball because they have arguments *after* `success` and `failure`. So let's look at that separately. For all other cases, we can make a helper that abstracts most of this away so that we don't have repeat ourselves over and over:

```js
function withLegacyCallbacks(method) {
  return function(...args) {
    if (typeof args[args.length - 1] === 'function' &&
        typeof args[args.length - 2] === 'function') {
      let failure = args.pop();
      let success = args.pop();
      return method(...args)
        .then(success)
        .catch(failure);
    }
    return method(...args);
  };
}
```
With that, we can implement `setLocalDescription` as follows:
```js
class PeerConnection {

  ...

  setLocalDescription = withLegacyCallbacks((sessionDescription) => {
    return WebRTCModule.peerConnectionSetRemoteDescription(
      sessionDescription.toJSON(),
      this._peerConnectionId
    );
  });
 
  ...

}
```

Note that this assumes `WebRTCModule.peerConnectionSetRemoteDescription` returns a Promise. For a long time, native methods have supported promise return types, and I think the WebRTC API is a good place to use this feature. Much better than passing a `successful` flag back.

**Comment by oney** [comment]
@philikon Totally agree. `withLegacyCallbacks` is a smart way.
So, `setLocalDescription, setRemoteDescription, addIceCandidate` can use `withLegacyCallbacks`, and `createOffer, createAnswer` may use another `withLegacyCallbacks`
Like
```javascript
function withLegacyCallbacks2(method) {
  return function(...args) {
    if (typeof args[0] === 'function' &&
        typeof args[1] === 'function') {
      let success = args.shift();
      let failure = args.shift();
      return method(...args)
        .then(success)
        .catch(failure);
    }
    return method(...args);
  };
}
```

On the other hand, `setLocalDescription` can accept more than 3 arguments, so below is okay.
```javascript
pc.setLocalDescription(desc, function () {}, function () {}, function () {});
```
But, `withLegacyCallbacks` will fail

**Comment by philikon** [comment]
> `function withLegacyCallbacks2(method) {`

Yep, except perhaps I'd call it `withLegacyCallbacksAndOptions` or something like that. More descriptive than `withLegacyCallbacks2` :)

> On the other hand, `setLocalDescription` can accept more than 3 arguments, ...

Ah, good point. So maybe we have two versions of `withLegacyCallbacks`, one that supports arguments like `(obj, success, failure)` and one that supports arguments like `(success, failure, options)`. `withObjectAndLegacyCallbacks` and `withLegacyCallbacksAndOptions` to make the order clear?

**Comment by maxhawkins** [comment]
How's this going? Do you need any help?

For reference, here's how WebKit does it:
https://github.com/WebKit/webkit/blob/f48d2876a4901d7eabb1c66bb5787036bee21dc8/Source/WebCore/Modules/mediastream/RTCPeerConnectionInternals.js#L102

**Comment by oney** [comment]
Yes, please help me!

**Comment by zxcpoiu** [comment]
And here's how sip.js does it.
Seems more like a combination with the discussion above.
:pray:

**Comment by maxhawkins** [comment]
I'll put together a PR today so we have some code working to talk about

**Comment by saghul** [comment]
#246 landed, closing.
