### ISSUE TITLE
AppStore reject

### ISSUE THREAD

**Issue by sagic** [oney/react-native-webrtc#533]
We tried submitting our app to app store and got the letter below. any suggestions? anyone got that?

Dear Developer,

We identified one or more issues with a recent delivery for your app, "Foo". Please correct the following issues, then upload again.

Non-public API usage:

The app references non-public selectors in FooMobile: channelId, initWithURLStrings:, setChannelId:, stringForType:
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

* 0.56
* 1.67.1
* ios

**Comment by mrsantran** [comment]
> The app references non-public selectors in FooMobile: channelId, initWithURLStrings:, setChannelId:, stringForType:
> If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

List your API: channelId, initWithURLStrings:, setChannelId:, stringForType to apple and document to apple that is your api not use private apple from apple

**Comment by saghul** [comment]
I have never seen this rejection and we have been submitting apps to Apple with this plugin for quite a while

**Comment by sagic** [comment]
yeah it's weird... thanks @mrsantran @saghul, we are trying again with a little more info and i'll post the results

**Comment by saghul** [comment]
I'm closing this. Last week we got a new version of Jitsi Meet approved, which uses this plugin.

**Comment by ex3ndr** [comment]
I am just integrated webrtc to our app and App Store rejected with very same reason
