### ISSUE TITLE
UI freezes when pc.setLocalDescription, It will be fine in about a few minutes.

### ISSUE THREAD

**Issue by zuijiaoluo** [oney/react-native-webrtc#534]
#### Expected behavior
The UI can still be executed, And the connection speed should be fast
#### Observerd behavior
when use “Debug JS Remotely”， It turned out to be good.When canceling "debug js remotely", UI freezes
#### Steps to reproduce the problem
after pc.createOffer， pc.setLocalDescription
#### Platform information

* **React Native version**:  0.55.3
* **Plugin version**:  1.67.1
* **OS**:    Android and iOS
* **OS version**:  android: 8.0   ios: 12

**Comment by saghul** [comment]
Can you show some trace / log? Also, how are you calling setLocalDescription in your code? Please show some of the surrounding lines.
