### ISSUE TITLE
RTCVideoView was not found in UIManager

### ISSUE THREAD

**Issue by rashidul-hasan** [oney/react-native-webrtc#535]
react-native-webrtc: ^1.67.1

**Comment by myhendry** [comment]
Hi @rashidul-hasan, i get a similar error. How did you manage to resolve this issue? Previously it was working ok then recently when i ran the react-native run-ios, i encounter this issue. Thanks

**Comment by rashidul-hasan** [comment]
@myhendry My problem was I didn't follow the installation instructions for Android properly. Just go through the installation instructions for iOS if you haven't already. https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md
