### ISSUE TITLE
Don't hear voice from local stream ?

### ISSUE THREAD

**Issue by haixoay96** [oney/react-native-webrtc#536]
I don't hear voice from local stream 

#### Platform information

* **React Native version**:
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by saghul** [comment]
You mean you don't hear yourself if you use the local stream in a RTCVideoView ?

**Comment by haixoay96** [comment]
Yep!exactly, I want to hear my voice.

**Comment by saghul** [comment]
That's not possible. This is a limitation of the system audio component in order to avoid echo.
