### ISSUE TITLE
How to add and connect to Remote videos?

### ISSUE THREAD

**Issue by mukulsha** [oney/react-native-webrtc#539]
Hello! I am working on react native project which includes live streaming of remote videos but I am not able to figure out how and where to add remote video url and connect to it.

**Comment by saghul** [comment]
Is you app using WebRTC? We don't use video URLs, they are just an instrument to connect the stream to the video view.

**Comment by mukulsha** [comment]
Yes, I am using webRTC in my app. Then how can i connect to remote video stream ?

**Comment by mukulsha** [comment]
Yes, I am using webRTC in my app. Then how can i connect to remote video stream ?

**Comment by xoapit** [comment]
You can see this demo:  []([https://github.com/oney/RCTWebRTCDemo])
