### ISSUE TITLE
Calling getUserMedia with width and height error occur.

### ISSUE THREAD

**Issue by karthinalliyappan** [oney/react-native-webrtc#540]
Hi, here's a error occur while running in iOS real device. 

Download the code from the github
-> npm install -> npm link -> npm start

**Comment by saghul** [comment]
What device? What OS version? What RN version? What version of this plugin?

**PLease** use the issue template.

**Comment by karthinalliyappan** [comment]
Device = iPad
OS version = 10.3.4
RN version = 0.44.0
plugin version = 
    "react-native-webrtc": "git+https://git@github.com/oney/react-native-webrtc.git",
    "socket.io-client": "^1.3.7"

Source code downloaded from  your github.

**Comment by karthinalliyappan** [comment]
Getting this error:
"[TypeError: errorCallback is non-nullable and required]"

Device = iPad mini
OS version = 10.3.2

**Comment by zxcpoiu** [comment]
@karthinalliyappan 

I think you did not pass callbacks to `getUserMedia` as code block shows below.
Please defined callback function, something like:

```js
getUserMedia(
    constraintsObject,
    successCallbackFunction,
    errorCallbackFunction
);
```

If it's not what I thought, then reopen it with your code example, thx!



https://github.com/oney/react-native-webrtc/blob/master/getUserMedia.js#L59-L68

**Comment by karthinalliyappan** [comment]
`  getUserMedia({
    audio: true,
    video: {
      mandatory: {
        minWidth: 640, // Provide your own width, height and frame rate here
        minHeight: 360,
        minFrameRate: 30,
      },
      facingMode: (isFront ? "user" : "environment"),
      optional: (videoSourceId ? [{sourceId: videoSourceId}] : []),
    }
  }, function (stream) {
    callback(stream);
  },
   logError);
}`

I'm using the getUserMedia like above.

**Comment by zxcpoiu** [comment]
Have you define your `logError` function?
The only reason is that your `logError` is not a function.

```js
  if (typeof errorCallback !== 'function') {
    throw new TypeError('errorCallback is non-nullable and required');
  }
```

**Comment by karthinalliyappan** [comment]
Yes defined the `logError` function.

`function logError(error) {
  console.log("-------- logError-------- :", error);
}
`

**Comment by zxcpoiu** [comment]
Then my advice would be print `typeof(logError)` right before each line you call `getUserMedia` then see what is the output.

This is more like coding issue and might not related to this library.
