### ISSUE TITLE
Open a single screen when call receive if app close or in background

### ISSUE THREAD

**Issue by bmp123** [oney/react-native-webrtc#542]
How can I open single screen with incoming call when app closed or in background? If anyone know solutions please answer. This help me. Thank you

**Comment by 8BallBomBom** [comment]
The way we deal with such instances is via background services called via [firebase](https://github.com/invertase/react-native-firebase) data notifications.
Along with custom modules for actually prompting the app to start with bundled data.
Only problem with that is if notifications fail to be received then calls won't be received.
So to make it more reliable you would also need other measures in place.
