### ISSUE TITLE
Invariant Violation: Invariant Violation: requireNativeComponent: "RTCVideoView" was not found in the UIManager

### ISSUE THREAD

**Issue by jessk77** [oney/react-native-webrtc#546]
Hi,

I'm having this issue on ios, hope someone could help

<img width="375" alt="image" src="https://user-images.githubusercontent.com/29874403/49262215-1c373d80-f40b-11e8-8d10-60b4f1210730.png">

#### Platform information

* **React Native version**: 0.57.1
* **Plugin version**: 1.67.1
* **OS**: iOS

**Comment by saghul** [comment]
Hum, I have never seen this myself. How are you linking the plugin?

**Comment by trilom** [comment]
I am having the same issue.

`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  View,
  Text,
  Navigator,
  TouchableHighlight,
  ToolbarAndroid,
} from 'react-native';
import {
  RTCPeerConnection,
  RTCMediaStream,
  RTCIceCandidate,
  RTCSessionDescription,
  RTCView,
  MediaStreamTrack,
  getUserMedia,
} from 'react-native-webrtc';`

**Comment by gerard-payne** [comment]
Who else is using expo?
I don't think this is compatible, needs to be ejected to regular react-native project :(
https://stackoverflow.com/questions/44270504/react-native-ios-and-android-folders-not-present#45179201

**Comment by trilom** [comment]
```
'use strict';


import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  View,
  Text,
  Navigator,
  TouchableHighlight,
  ToolbarAndroid,
} from 'react-native';
import {
  RTCPeerConnection,
  RTCMediaStream,
  RTCIceCandidate,
  RTCSessionDescription,
  RTCView,
  MediaStreamTrack,
  getUserMedia,
} from 'react-native-webrtc';

import SocketIOClient from 'socket.io-client';
console.disableYellowBox = true;

export default class CameraScreen extends Component {
  render() {
    return (
      <RTCView/>
    )
  }
}
```

Tried this and still received the same error:

![image](https://user-images.githubusercontent.com/7476973/51749155-a18e4580-207c-11e9-942e-af696eb40e59.png)

**Comment by saghul** [comment]
@trilom Good luck.

**Comment by trilom** [comment]
@saghul I'm new to react-native as well as Flutter.  I have my code stashed and ready to peal this back open if webrtc gains some traction in react-native with expo.

**Comment by saghul** [comment]
I'm personally not using Expo and if someone knows how to fix it patches will of course be welcome, until then I'm adding a note on the README.
