### ISSUE TITLE
 Multiple commands produce in iOS while generating ipa file.

### ISSUE THREAD

**Issue by karthinalliyappan** [oney/react-native-webrtc#548]
1: Multiple commands produce '/Users/iminds/Library/Developer/Xcode/DerivedData/XXXXX ekaxxelbsizytyetfctjeefplyaf/Build/Intermediates.noindex/ArchiveIntermediates/XXXXX /IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a':
1) Target 'yoga' has a command with output '/Users/iminds/Library/Developer/Xcode/DerivedData/XXXXX -ekaxxelbsizytyetfctjeefplyaf/Build/Intermediates.noindex/ArchiveIntermediates/XXXXX /IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a'
2) Target 'yoga' has a command with output '/Users/iminds/Library/Developer/Xcode/DerivedData/XXXXX -ekaxxelbsizytyetfctjeefplyaf/Build/Intermediates.noindex/ArchiveIntermediates/XXXXX /IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a'

* **React Native version**: 0.57.5
* **Plugin version**:1.67.1
* **OS**:  iOS 
* **OS version**:10.3.2 (iPad mini device)

![screen shot 2018 12 03 at 12 14 42 pm](https://user-images.githubusercontent.com/26541759/49357489-7aa73900-f6f5-11e8-882e-3e0d4e6c4ef6.png)
)

**Comment by saghul** [comment]
The error comes from your project, not this plugin, as the screenshot shows.
