### ISSUE TITLE
build-webrtc.py error

### ISSUE THREAD

**Issue by mpbunch** [oney/react-native-webrtc#549]
#### Expected behavior
for webtrc to build 

#### Observerd behavior
Syncing projects:  74% (97/130) src/third_party/boringssl/src                                                                                                                                                       

src/third_party/android_ndk (ERROR)
----------------------------------------
[0:00:07] Started.
----------------------------------------
Error: 79> 
79> ____ src/third_party/android_ndk at 4e2cea441bfd43f0863d14f57b1e1844260b9884
79> 	You have unstaged changes.
79> 	Please commit, stash, or reset.

#### Steps to reproduce the problem
git clone repo
mkdir ~/src
cd react-native-webrtc/tools
python build-webrtc.py --setup --android ~/src/

#### Platform information
* **React-native-cli**: 2.0.1
* **React-native**: 0.57.7
* **Plugin version**: 1.67.1
* **OS**: 
* **OS version**: osx 10.14.1

**Comment by ruddell** [comment]
WebRTC for Android can only be built on Linux at the moment. https://github.com/oney/react-native-webrtc/blob/master/Documentation/BuildingWebRTC.md#android-1
