### ISSUE TITLE
TURN support/help?

### ISSUE THREAD

**Issue by mgreer** [oney/react-native-webrtc#55]
Thank you for this wonderful code, by the way!

I'm trying to pass STUN and TURN servers, but WebRTCModule throws an exception about the TURN format, which is typically:
```
{
credential:"ivZhTedeY+XEMHZeB+ZayL70aoY=",
urls:["turn:my.turn.server:3478"],
username:"1461261865"
}
```

WebRTCModule borks on line 120, saying it can't find key "url" in dynamic object.
```
iceServers.add(new PeerConnection.IceServer(iceServerMap.getString("url")));
```
I think my TURN server format is right, but please correct me.

I've also tried reformatting it to add the URL key, but it isn't authenticating as it isn't passing username and password.

Thank you!
-Mike

**Comment by zxcpoiu** [comment]
this is because:

1. we are using `url` which is deprecated instead `urls`.

2. we only accept string instead array (we should accept both)

should fix it according to [spec](http://w3c.github.io/webrtc-pc/#idl-def-RTCIceServer)

now for your workaround, you should changed to:

`url:"turn:my.turn.server:3478",`

**Comment by zxcpoiu** [comment]
seems it doesn't support TURN authentication though. it just ignores all except URL.

**Comment by mgreer** [comment]
@zxcpoiu agreed, it is only passing the url in, skipping username and credentials. This is seen on the TURN server as well: no credentials.

I'm going to look into a TURN support PR, but I'm having a bit of a time understanding PeerConnection.

**Comment by oney** [comment]
What a terrible mistake! I will fix it instantly.

**Comment by mgreer** [comment]
Looks like PeerConnection will happily accept all in its constructor:
```
public IceServer(String uri, String username, String password) 
```
The URI only is a convenience function for STUN

**Comment by oney** [comment]
@zxcpoiu @mgreer 
Please help take a look this PR https://github.com/oney/react-native-webrtc/pull/56 to check if it's correct. Thanks.

**Comment by mgreer** [comment]
Looks good!

**Comment by mgreer** [comment]
Tested, working. Thank you!
