### ISSUE TITLE
webrtc ios build failed: mac osx sdk is incompatible

### ISSUE THREAD

**Issue by mpbunch** [oney/react-native-webrtc#551]
Does the webrtc build script not work on Mojave (10.14.1)?
```
python build-webrtc.py --setup --ios ~/src/
cd ~/src/build_webrtc/webrtc/ios/src/
git checkout -b build-M57 refs/remotes/branch-heads/57
git cherry-pick 0e22a4cfd3790d80ad1ae699891341fe322cb418
python build-webrtc.py --build --ios ~/src/
```
#### Observerd behavior
********************************************************************************
 WARNING: The Mac OS X SDK is incompatible with the version of Xcode. To fix,
          either upgrade Xcode to the latest version or install the Mac OS X
          10.11 SDK. For more information, see https://crbug.com/620127.

 Current SDK Version:   10.14
 Current Xcode Version: 0101 (10B61)
********************************************************************************
ERROR at //build/config/mac/mac_sdk.gni:104:3: Assertion failed.
  assert(false, "SDK is incompatible with Xcode")
  ^-----
SDK is incompatible with Xcode
See //build/toolchain/mac/BUILD.gn:14:1: whence it was imported.
import("//build/config/mac/mac_sdk.gni")
^--------------------------------------
See //BUILD.gn:11:1: which caused the file to be included.
group("default") {
^-----------------
#### Steps to reproduce the problem
Follow the documentation for ios webrtc build.

#### Platform information
* **React Native version**:
* **Plugin version**: master
* **OS**: OSX 10.14

**Comment by saghul** [comment]
Have you tried a newer branch? 57 is ancient.

**Comment by mpbunch** [comment]
Build-57 is specified in the docs, I will have to give a newer branch a shot.
https://github.com/oney/react-native-webrtc/blob/master/Documentation/BuildingWebRTC.md

**Comment by saghul** [comment]
Well, that's an example. You need to pick the branch you want. Why are you building WebRTC yoursef BTW?

**Comment by mpbunch** [comment]
Right, I should have understood it was an example, but I was following it as instructions, my mistake.
I was trying to build webrtc myself, because I was unable to get any app, no matter how basic, to successfully build/run.

I wasn't sure if there was something specific with my setup that was preventing react-native + webrtc to work, so I was going to build it on my machine to see if it made a difference. Since this post I have uninstalled and reinstalled react-native, and now things are working. So, there must have been something wrong with my install.

**Comment by saghul** [comment]
Good to hear! If you think the docs need some clarification, a PR would be most welcome.
