### ISSUE TITLE
h264 video streaming is not working on ios and android- Failed to set local answer sdp: Failed to set local video description recv parameters.

### ISSUE THREAD

**Issue by maheshnrk** [oney/react-native-webrtc#553]
We are trying to stream video from an ip camera. 
When we transcode the stream from h264 to VP8 then the streaming is successfully happening.
But when we try to stream the video in h264 without transcoding we get error "Failed to set local answer sdp: Failed to set local video description recv parameters."

SDP that is working as expected after transcoded to VP8
> {“type":"offer",
"sdp":"v=0o=- 6879933684578820951 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:n8b7xTkLOl5xm8VSEVReWaXkaNmFqtmp
a=ice-pwd:yuXJxi+rUtDS4HjtTZyh5u5vOsA0m73f
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=mid:video0
a=fingerprint:sha-256 E2:34:A2:BC:13:82:B8:B7:39:FD:3F:38:32:B6:65:82:33:1B:1B:FA:6B:40:FE:C5:F8:EB:B4:4B:41:C8:12:61"}

SDP giving error when offer sent in H264 format.
Android offer
> {"type":"offer","sdp":"
v=0  
o=- 3951288648198276198 0 IN IP4 0.0.0.0  
s=-  
t=0 0  
a=ice-options:trickle  
m=video 9 UDP/TLS/RTP/SAVPF 96  
c=IN IP4 0.0.0.0  
a=setup:actpass  
a=ice-ufrag:AeuQpGRie8id0pBjj4vRjI9TvhDV4tH3  
a=ice-pwd:ahwysgkyyoNZTFie5wUh9oFA4txEPlfc  
a=sendrecv  
a=rtcp-mux  
a=rtcp-rsize  
a=rtpmap:96 H264/-1696155160  
a=rtcp-fb:96 nack  
a=rtcp-fb:96 nack pli  
a=mid:video0  
a=fingerprint:sha-256 8A:80:F8:0D:0D:54:0A:20:3B:45:13:32:95:63:D1:CA:EC:9F:E2:D7:7A:B7:AD:DF:B3:8E:DC:A0:94:D8:B1:E7  "}

Android Local Description / answer

> {"sdp":"
v=0  
o=- 416596035360039236 2 IN IP4 127.0.0.1  
s=-  
t=0 0  
a=msid-semantic: WMS  
m=video 9 UDP/TLS/RTP/SAVPF 0  
c=IN IP4 0.0.0.0  
a=rtcp:9 IN IP4 0.0.0.0  
a=ice-ufrag:W33r  
a=ice-pwd:y57g4clZDIuK8AtmQ7YCmfTO  
a=ice-options:trickle renomination  
a=fingerprint:sha-256 25:55:95:EB:C8:C7:95:F3:70:94:92:91:15:FA:57:74:88:CD:AA:E9:F5:AD:D0:D6:1B:14:26:BE:E0:27:40:CF  
a=setup:active  
a=mid:video0 
a=recvonly  
a=rtcp-mux  
a=rtcp-rsize  
","type":"answer"}

Error 

> Failed to set local answer sdp: Failed to set local video description recv parameters.

 iOS offer SDP
>{"type":"offer","sdp":"
v=0  
o=- 7886923958798912853 0 IN IP4 0.0.0.0  
s=-  
t=0 0  
a=ice-options:trickle  
m=video 9 UDP/TLS/RTP/SAVPF 96  
c=IN IP4 0.0.0.0  
a=setup:actpass  
a=ice-ufrag:8DHvfe5vupl2NkCWZ8++mkGBnK1nWT3V  
a=ice-pwd:5wDFHZD0MCuEV9O+LEE170MyBljRt3a5  
a=sendrecv  
a=rtcp-mux  
a=rtcp-rsize  
a=rtpmap:96 H264/-1283435976  
a=rtcp-fb:96 nack  
a=rtcp-fb:96 nack pli  
a=mid:video0  
a=fingerprint:sha-256 55:74:E8:0E:9B:B8:35:FC:78:C3:5A:F7:BB:B4:CB:A4:A6:B6:CC:B6:7D:FB:26:74:4D:37:A0:D4:61:E1:26:21  "}

iOS Local Description

> {"sdp":"
v=0  
o=- 6467658633751753588 2 IN IP4 127.0.0.1  
s=-  
t=0 0  
a=msid-semantic: WMS  
m=video 9 UDP/TLS/RTP/SAVPF 0  
c=IN IP4 0.0.0.0  
a=rtcp:9 IN IP4 0.0.0.0  
a=ice-ufrag:wqSR  
a=ice-pwd:0cYuVjuEOk6yJRQVceBRa+PF  
a=ice-options:trickle renomination  
a=fingerprint:sha-256 7F:5D:1F:5E:07:F9:18:22:A3:B1:B6:9A:13:B3:A4:02:DF:8C:DD:B1:69:AF:A7:A6:51:68:F3:2E:8C:19:EA:47  
a=setup:active  
a=mid:video0  
a=recvonly  
a=rtcp-mux  
a=rtcp-rsize  
","type":"answer"}

Error

> {name:"SetLocalDescriptionFailed", message: "Failed to set local answer sdp: Failed to set local video description recv parameters."}

#### Expected behavior
We should be able to stream H264 stream
#### Observed behavior
Only stream transcoded to VP8 plays

#### Steps to reproduce the problem
NA
#### Platform information

* **React Native version**: react-native: 0.57.4
react-native-cli: 2.0.1 
* **Plugin version**: 1.67.1
* **OS**:  iOS 12, Android 9
* **GStreamer version**: 1.14.1
* **OS version**:

Are we missing any thing in the offer?
If so why are we able to stream the VP8 transcoded steam successfully

**Comment by maheshnrk** [comment]
I have made the bundle policy as balanced in both iOS and Android so that sdp works without max bundle

**Comment by saghul** [comment]
> a=rtpmap:96 H264/-1283435976

I suspect this is the problem. I haven't seen those values myself though.

**Comment by maheshnrk** [comment]
Hi @saghul  Thanks for the response. Yes also noticed the negative value here.
But we are not munging the SDP value from our side. It is coming from the camera.  We are using the GStreamer version: 1.14.1.

**Comment by saghul** [comment]
Yes, those are needed. You should report this to GStreamer. That SDP is not very correct...
