### ISSUE TITLE
[QUESTION] Create Offer and Answer always generate a SDP containing C line as c=IN IP4 0.0.0.0

### ISSUE THREAD

**Issue by mariouzae** [oney/react-native-webrtc#556]
When I create an answer or offer to hand over to another peer, I'm seeing the SDP line C always as c=IN IP4 0.0.0.0, I know this is a default IP and WebRTC doesn't consider it because of ICE, but as I'm using a SIP Server it does consider this line and when the call establishes with the server, it keeps the call on hold.

There is some workaround to update this SDP line?

#### Expected behavior
SDP Offer/Answer containing IP gathered from STUN and not c=IN IP4 0.0.0.0
#### Observerd behavior
All SDP Offer/Answer are beining generated with c=IN IP4 0.0.0.0

#### Steps to reproduce the problem
Create a RTCPeerConnection.createOffer() or even an Answer.

```
RTCPeerConnection.createOffer()
    .then(sdp => {
        console.log(sdp);
    })
```
#### Platform information

* **React Native version**: 0.57.7
* **Plugin version**: 1.67.1
* **OS**: Android
* **OS version**: 8.1

**Comment by saghul** [comment]
You can modify the SDP yourself once you get it in the promise result, before you send it to your server. Note however, that if your server doesn't already support this, chances of it properly working with a WebRTC endpoint are pretty slim.
