### ISSUE TITLE
[HELP NEEDED] Is there any working example of this repository?

### ISSUE THREAD

**Issue by emech-en** [oney/react-native-webrtc#557]
I can't find any working sample and any corresponding documentation on this repository. 

I have a sample work flow which works correctly on browsers, but using this repository in react-native application, IceConnectionState goes from 'checking' to 'failed' and remote video is not rendered correctly.

**Comment by davidestrela** [comment]
https://github.com/oney/RCTWebRTCDemo

**Comment by saghul** [comment]
Note that that repo is old and unmaintained. It will probably not work with the current version of this plugin.

**Comment by emech-en** [comment]
@saghul Yes, that repo is old and not working. 
Fortunately I found a solution for audio only calls (my problem), which working and maybe I publish a working demo based on current version of the module in future.

**Comment by saghul** [comment]
That would be appreciated.
