### ISSUE TITLE
Crop Remote stream to Aspect Ratio Size

### ISSUE THREAD

**Issue by pohsiu** [oney/react-native-webrtc#559]
Is any way to accomplish this goal of RTCView ?

I want to figure this out to take care diff device remote stream to expected stream size

**Comment by davidestrela** [comment]
One of the ways you can accomplish this is by setting the desired aspect ratio on the remote peer constraints

**Comment by pohsiu** [comment]
@davidestrela would you mind describe in detail ?

**Comment by enaluz** [comment]
@pohsiu How did you solve this?
