### ISSUE TITLE
Unsupported Architectures   x86_64,i386]

### ISSUE THREAD

**Issue by Proxy08** [oney/react-native-webrtc#561]
Apple Store keeps rejecting my even after striping it #141. I follow these before submitting to Apple store 

> 1. go to react-native-webrtc/tools folder
2. extract all archs first: node ios_arch.js --extract
3. re-package device related archs only: node ios_arch.js --device
4. delete files generated from step 2
5. you can check current arch use this command: file 
node_modules/react-native-webrtc/ios/WebRTC.framework/WebRTC

after the step 5 I got this as architectures:
[https://res.cloudinary.com/hu5ylidzk/image/upload/v1546156382/issues/Screen_Shot_2018-12-30_at_8.46.49_AM.png](url)
What should I do ?

 "react-native": "0.57.1",
 "react-native-webrtc": "^1.67.1",
* **OS**:  iOS 
* **OS version**:

**Comment by HasnainAD** [comment]
Hi, were you able to solve it?

**Comment by Proxy08** [comment]
Hi, there are in node_modules/react-native-webrtc/ios/WeRTC.framework

**Comment by Proxy08** [comment]
Yes did solve it!
