### ISSUE TITLE
React Native Scalable Broadcast

### ISSUE THREAD

**Issue by ConquerDeveloper** [oney/react-native-webrtc#562]
Greetings everyone.

First of all, i wanted to thank you guys for creating this awesome component, i've used it in many of my RN projects!

I wanted to ask if there is any possibility of creating a Scalable Broadcast app using this component for RN, i have seen some examples but using cordova mostly. I would like to do something like this:

[https://rtcmulticonnection.herokuapp.com/demos/Scalable-Broadcast.html](url)

The above is an example using a plugin for cordova apps. I need to do that but using RN.

If any of you could help me out with this or tell me if there is any other way to accomplish this, i would be very grateful.

Thanks in advance.

**Comment by YuePing1104** [comment]
Hi, I want to know how you run the project. I have been working on it for more than a week, and I still have a lot of reports of mistakes.I hope god can guide me.WeChat, 15579729780)

**Comment by saghul** [comment]
I believe it should be possible using this project. You ay even be able to reuse some of that code, but you'll need to adapt it to the React Native environment.

**Comment by YuePing1104** [comment]
I want to know how you did it, because I have been working on it for some time, and I want to use React-native. Can you give me some guidance?



| |
15579729780
|
|
15579729780@163.com
|
签名由网易邮箱大师定制
On 1/8/2019 16:10，Saúl Ibarra Corretgé<notifications@github.com> wrote：

Closed #562.
