### ISSUE TITLE
React/RCTBridge.h - File Not Found

### ISSUE THREAD

**Issue by p8952** [oney/react-native-webrtc#563]
# Steps Taken:

Create Project:

```
$ npx react-native-cli init webrtctest

$ cd webrtctest/

$ npm install --save react-native-webrtc
```

Create Podfile:

```
project "ios/webrtctest.xcodeproj/"
platform :ios, "9.0"

target "webrtctest" do
  pod "react-native-webrtc", :path => "./node_modules/react-native-webrtc"
end
```

Install Dependencies & Launch XCode:

```
$ pod install

$ open webrtctest.xcworkspace/
```

Clean Project & Build:

* XCode -> Product -> Clean Build Folder
* XCode -> Product -> Build

#### Expected behaviour
The project compiles & runs!

#### Observed behaviour
<img width="265" alt="screenshot 2019-01-03 at 13 06 10" src="https://user-images.githubusercontent.com/2962587/50639288-e1b84780-0f58-11e9-8798-addd42327652.png">
<img width="1392" alt="screenshot 2019-01-03 at 13 06 38" src="https://user-images.githubusercontent.com/2962587/50639291-e3820b00-0f58-11e9-9ff2-e0b714977bc6.png">
<img width="1392" alt="screenshot 2019-01-03 at 13 06 44" src="https://user-images.githubusercontent.com/2962587/50639292-e4b33800-0f58-11e9-929f-83525045bf70.png">

**Comment by saghul** [comment]
You need to add the react-native dependencies to your podfile: https://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies
