### ISSUE TITLE
Front camera is black for Android

### ISSUE THREAD

**Issue by Proxy08** [oney/react-native-webrtc#567]
Expected behavior
By clicking switch it should front to back and back to front without any problem 
Observerd behavior
front camera for android always gives me a black screen whenever I try to flip it or when I start initial by that. It works fine in Ios though. It's like i cannot access to front camera. Any

> let isFront = true;
> MediaStreamTrack.getSources(sourceInfos => {
>   console.log(sourceInfos);
>   let videoSourceId;
>   for (let i = 0; i < sourceInfos.length; i++) {
>     const sourceInfo = sourceInfos[i];
>     if(sourceInfo.kind == "video" && sourceInfo.facing == (isFront ? "front" : "back")) {
>       videoSourceId = sourceInfo.id;
>     }
>   }
>   getUserMedia({
>     audio: true,
>     video: {
>       mandatory: {
>         minWidth: 500, // Provide your own width, height and frame rate here
>         minHeight: 300,
>         minFrameRate: 30
>       },
>       facingMode: (isFront ? "user" : "environment"),
>       optional: (videoSourceId ? [{sourceId: videoSourceId}] : [])
>     }
>   }, function (stream) {
>     console.log('dddd', stream);
>     callback(stream);
>   }, logError);
> });

Any ideas??
Thank you..

#### Platform inform

* **React Native version*0.57.1*:
* **Plugin version*1.67.1*:
* **OS**: Android 
* **OS version**:

**Comment by shaheem-khanzada** [comment]
_switchVideoType() {
    localStream.getVideoTracks().forEach(track => { track._switchCamera(); });
  }

**Comment by shaheem-khanzada** [comment]
does it help ?
