### ISSUE TITLE
Record audio from local stream or remote stream

### ISSUE THREAD

**Issue by xoapit** [oney/react-native-webrtc#568]
Hi all,

I am trying to record the audio from webrtc. Does anyone have any ideas for that?

Thanks in advance.

**Comment by Frekansapp** [comment]
> 
> 
> Hi all,
> 
> I am trying to record the audio from webrtc. Does anyone have any ideas for that?
> 
> Thanks in advance.

try this https://github.com/zxcpoiu/react-native-incall-manager
