### ISSUE TITLE
[Android] Crash on arm64 device.

### ISSUE THREAD

**Issue by mbloody** [oney/react-native-webrtc#572]
Please add arm64 arch support for Android.

#### Platform information

* **React Native version**: 0.58
* **Plugin version**: 1.67.1
* **OS**: Android
* **OS version**: Debian 9

**Comment by saghul** [comment]
React Native itself doesn't support it.

**Comment by mbloody** [comment]
It start support it from 0.58 version.

**Comment by mbloody** [comment]
01-25 15:12:57.762 30398 30426 I org.webrtc.Logging: NativeLibrary: Loading native library.
01-25 15:12:57.762 30398 30426 I org.webrtc.Logging: NativeLibrary: Loading library: jingle_peerconnection_so
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: NativeLibrary: Failed to load native library: jingle_peerconnection_so
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.cvaluemobile-keY0EhYhR-zgBcCleVk2dQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.cvaluemobile-keY0EhYhR-zgBcCleVk2dQ==/lib/arm64, /data/app/com.cvaluemobile-keY0EhYhR-zgBcCleVk2dQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libjingle_peerconnection_so.so"
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.cvaluemobile-keY0EhYhR-zgBcCleVk2dQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.cvaluemobile-keY0EhYhR-zgBcCleVk2dQ==/lib/arm64, /data/app/com.cvaluemobile-keY0EhYhR-zgBcCleVk2dQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libjingle_peerconnection_so.so"
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at java.lang.System.loadLibrary(System.java:1657)
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at org.webrtc.NativeLibrary$DefaultLoader.load(NativeLibrary.java:21)
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at org.webrtc.NativeLibrary.initialize(NativeLibrary.java:44)
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:197)
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at com.oney.WebRTCModule.WebRTCModule.initAsync(WebRTCModule.java:58)
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at com.oney.WebRTCModule.WebRTCModule.lambda$new$0(WebRTCModule.java:46)
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$T9WIHBBwOXq3znC0jdgs3RSomME.run(Unknown Source:2)
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-25 15:12:57.763 30398 30426 E org.webrtc.Logging: 	at java.lang.Thread.run(Thread.java:764)
01-25 15:12:57.764 30398 30426 E zygote64: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(boolean) (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__Z)
01-25 15:12:57.765 30398 30418 D ReactNative: Initializing React Xplat Bridge.
01-25 15:12:57.765 30398 30426 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
01-25 15:12:57.765 30398 30426 E AndroidRuntime: Process: com.cvaluemobile, PID: 30398
01-25 15:12:57.765 30398 30426 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(boolean) (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__Z)
01-25 15:12:57.765 30398 30426 E AndroidRuntime: 	at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
01-25 15:12:57.765 30398 30426 E AndroidRuntime: 	at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:198)
01-25 15:12:57.765 30398 30426 E AndroidRuntime: 	at com.oney.WebRTCModule.WebRTCModule.initAsync(WebRTCModule.java:58)
01-25 15:12:57.765 30398 30426 E AndroidRuntime: 	at com.oney.WebRTCModule.WebRTCModule.lambda$new$0(WebRTCModule.java:46)
01-25 15:12:57.765 30398 30426 E AndroidRuntime: 	at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$T9WIHBBwOXq3znC0jdgs3RSomME.run(Unknown Source:2)
01-25 15:12:57.765 30398 30426 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-25 15:12:57.765 30398 30426 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-25 15:12:57.765 30398 30426 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
01-25 15:12:57.766 30398 30426 E AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
01-25 15:12:57.766 30398 30426 D OSTracker: OS Event: crash
01-25 15:12:57.768 30398 30426 E AbstractTracker: mTrackerAsyncQueryHandler is null
01-25 15:12:57.768 30398 30418 D ReactNative: Initializing React Xplat Bridge before initializeBridge
01-25 15:12:57.770  1352  2144 W ActivityManager:   Force finishing activity com.cvaluemobile/.MainActivity
01-25 15:12:57.774  1352  1439 I ActivityManager: Showing crash dialog for package com.cvaluemobile u0
