### ISSUE TITLE
[BOUNTY] IOS no sound

### ISSUE THREAD

**Issue by fuqiangleon** [oney/react-native-webrtc#574]
we integrated jisti-meet to our ios app, but after hangup, there is a red bar at the top.

we tried below disableAudio to remove red bar after handup and enableAudio before rejoining a meeting.
the issue is after rejoin, the participants can not hear each other.

-(void) disableAudio {
    //[[RTCAudioSession sharedInstance] setIsAudioEnabled:NO];
    //[[RTCAudioSession sharedInstance] setUseManualAudio:NO];
    [[AVAudioSession sharedInstance] setActive:NO withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation error:nil];
}

-(void) enableAudio {
    [[AVAudioSession sharedInstance] setActive:YES error:nil];
    //[[RTCAudioSession sharedInstance] setUseManualAudio:YES];
    //[[RTCAudioSession sharedInstance] setIsAudioEnabled:YES];
}

**Comment by saghul** [comment]
Please port this in the community forum: https://react-native-webrtc.discourse.group/

**Comment by sagark1510** [comment]
@fuqiangleon did you find any solution on this?
