### ISSUE TITLE
Could not find @ReactModule annotation in com.oney.WebRTCModule.WebRTCModule

### ISSUE THREAD

**Issue by mbloody** [oney/react-native-webrtc#575]
![screenshot](https://user-images.githubusercontent.com/1745865/51846116-a293d100-2321-11e9-89fd-09d016851133.png)

#### Platform information

* **React Native version**: 0.58.1
* **Plugin version**: 1.67.1
* **OS**:  Android
* **OS version**: all

**Comment by mbloody** [comment]
On real device:

01-28 17:53:55.856 25351 25351 W ResourceType: No known package when getting name for resource number 0xffffffff
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: Error while updating prop streamURL
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: java.lang.reflect.InvocationTargetException
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:269)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:911)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:110)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:778)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at android.view.Choreographer.doFrame(Choreographer.java:710)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:789)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:164)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at android.app.ActivityThread.main(ActivityThread.java:6798)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: Caused by: java.lang.IllegalArgumentException: Could not find @ReactModule annotation in com.oney.WebRTCModule.WebRTCModule
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNameFromAnnotation(CatalystInstanceImpl.java:444)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:433)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:119)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.oney.WebRTCModule.WebRTCView.getVideoTrackForStreamURL(WebRTCView.java:214)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.oney.WebRTCModule.WebRTCView.setStreamURL(WebRTCView.java:510)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	at com.oney.WebRTCModule.RTCVideoViewManager.setStreamURL(RTCVideoViewManager.java:59)
01-28 17:53:55.860 25351 25351 E unknown:ViewManager: 	... 25 more
01-28 17:53:55.860 25351 25351 D AndroidRuntime: Shutting down VM

**Comment by saghul** [comment]
Are you using Expo?

**Comment by mbloody** [comment]
No

**Comment by mbloody** [comment]
It's happened on react native 0.58.
On react native 0.57 everything work.

**Comment by saghul** [comment]
Gotcha. We haven't tested on RN 0.58 yet, there might be some fixes necesary.

**Comment by mbloody** [comment]
https://github.com/oney/react-native-webrtc/pull/576 fix this issue.
