### ISSUE TITLE
examples of usage method mediaDevices

### ISSUE THREAD

**Issue by tienviip** [oney/react-native-webrtc#580]
Can you give me a code example of how to use mediaDevices method? please

**Comment by saghul** [comment]
Please ask in our community forum.

**Comment by tienviip** [comment]
I am new member of github so I don't know the forum, you can help me? when I update library react-native-webrtc new version, I don't know use method mediaDevices.

**Comment by tienviip** [comment]
thank you support me, I knew how to use it.
