### ISSUE TITLE
[1.69.0] MediaStreamTrack.getSources() - undefined promise rejection?

### ISSUE THREAD

**Issue by 8BallBomBom** [oney/react-native-webrtc#581]
I've been using this function to count how many cameras the device has to then be able to determine if i should show the camera flipping button on screen and also whether the device in question can actually send out a video stream.
But seems after the latest update the function no longer works without giving a warning.

#### Expected behavior
Run the function without any errors/warnings.
#### Observerd behavior
Since the latest update there is now a warning.
```
Possible Unhandled Promise Rejection (id: 0):
    TypeError: undefined is not a function (evaluating 'WebRTCModule.mediaStreamTrackGetSources(success)')
```
Having a try/catch doesn't seem to fix the issue.
#### Steps to reproduce the problem
```
let cameraCount: number = 0;

( async () => {
	let mediaSources = await MediaStreamTrack.getSources();

	for ( const source of mediaSources ) {
		if ( source.kind != 'video' ) { continue; };

		cameraCount = cameraCount + 1;
	};
} )();
```
#### Platform information

* **React Native version**: 0.57.8
* **Plugin version**: 1.69.0
* **OS**: Android
* **OS version**: 8

**Comment by saghul** [comment]
Do, I forgot to remove that. Youc an now use `mediaDevices.enumerateDevices()` which returns a promise.

**Comment by 8BallBomBom** [comment]
Ahhh didn't really look to see if the functions were changed over, double doh.
Thanks @saghul as always :)
All working.

```
let cameraCount: number = 0;

( async () => {
	let devices = await mediaDevices.enumerateDevices();

	for ( const device of devices ) {
		if ( device.kind != 'videoinput' ) { continue; };

		cameraCount = cameraCount + 1;
	};
} )();
```
