### ISSUE TITLE
Crashes on start in release build

### ISSUE THREAD

**Issue by yuensunn** [oney/react-native-webrtc#590]
Used to work perfectly fine (both debug & release build ) in the past. Not sure what I did to trigger this problem.

#### ADB logcat result

> 02-18 17:13:28.746 21624 21646 E rtc     : #
02-18 17:13:28.746 21624 21646 E rtc     : # Fatal error in: ../../sdk/android/src/jni/jni_generator_helper.cc, line 32
02-18 17:13:28.746 21624 21646 E rtc     : # last system error: 88
02-18 17:13:28.746 21624 21646 E rtc     : # Check failed: !clazz.is_null()
02-18 17:13:28.746 21624 21646 E rtc     : # org/webrtc/WebRtcClassLoader
02-18 17:13:28.747 21624 21646 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 21646 (pool-1-thread-1)

#### Platform information

* **React Native version**: 0.57.7
* **Plugin version**: ^1.69.0
* **OS**:  Android
* **OS version**: 8.0.0

**Comment by yuensunn** [comment]
Update: Everything seems to work fine after clearing npm caches and reinstalling all node modules.

**Comment by epurban** [comment]
I'm having this problem as well. @yuensunn , can you detail any other steps you took to fix this?

**Comment by yuensunn** [comment]
@epurban I can't remember exactly but here are some of the steps that I did

- cleaning the gradle `./gradlew clean`
- deleting the entire `node_modules` folder and `npm install` again
- `npm clean cache`

or maybe you could try upgrading your webrtc package?

**Comment by epurban** [comment]
I'll try those steps now. I'm the latest version 1.69.1. Actually as I write this I notice they released 1.69.2, so I'll try upgrading and see if that fixes anything. You said it came out of seemingly nowhere? How long did you tussle with this issue before you finally resolved it?

**Comment by epurban** [comment]
After upgrading, cleaning the build folder, removing node modules and reinstalling, and clearing npm cache, I still get this same error. it's a bit different from yours, but here it is:

`JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "org.webrtc.WebRtcClassLoader" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.socialrealm.myomma-3xgFVSJ41s0wq0iYBSsTJw==/base.apk", zip file "/data/app/com.socialrealm.myomma-3xgFVSJ41s0wq0iYBSsTJw==/split_config.en.apk", zip file "/data/app/com.socialrealm.myomma-3xgFVSJ41s0wq0iYBSsTJw==/split_config.x86.apk", zip file "/data/app/com.socialrealm.myomma-3xgFVSJ41s0wq0iYBSsTJw==/split_config.xxxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.socialrealm.myomma-3xgFVSJ41s0wq0iYBSsTJw==/lib/x86, /data/app/com.socialrealm.myomma-3xgFVSJ41s0wq0iYBSsTJw==/base.apk!/lib/x86, /data/app/com.socialrealm.myomma-3xgFVSJ41s0wq0iYBSsTJw==/split_config.en.apk!/lib/x86, /data/app/com.socialrealm.myomma-3xgFVSJ41s0wq0iYBSsTJw==/split_config.x86.apk!/lib/x86, /data/app/com.socialrealm.myomma-3xgFVSJ41s0wq0iYBSs`

**Comment by epurban** [comment]
Anyone having this problem in the future, I fixed it by adding

`-keep class org.webrtc.**  { *; }`

to my Proguard file

**Comment by adamsythe** [comment]
im facing this problem, @epurban did you just put that inside the poguard-rules.pro file?  My file is currently empty so i just added that line but its still not working

**Comment by adamsythe** [comment]
this is my error

 java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.va.vipertest-1/base.apk:classes2.dex)
        at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
        at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
        at com.oney.WebRTCModule.WebRTCModule.initAsync(WebRTCModule.java:98)
        at com.oney.WebRTCModule.WebRTCModule.lambda$new$0$WebRTCModule(WebRTCModule.java:73)
        at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$CnyHZvkjDxq52UReGHUZlY0JsVw.run(lambda)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by epurban** [comment]
Yes, thats correct. Try everything else above as well. Also look up what a
proguard file is for if you didn’t know like myself.

**Comment by brunsy** [comment]
@adamsythe that's not the same issue. Have a look at #761

**Comment by pankajnegi1893** [comment]
I am also facing this isssue. 
`"react": "16.9.0",
 "react-native": "0.62.2",
 "react-native-webrtc": "^1.84.0"
`
-keep class org.webrtc.** { *; } this is not working and clearing npm caches and reinstalling all node modules still not working.

Can someone help?

**Comment by harishgupta01** [comment]
I am also facing a similar issue. I tried all solutions mentioned above. Did anyone find the solution?

**Comment by whenmoon** [comment]
> Anyone having this problem in the future, I fixed it by adding
> 
> `-keep class org.webrtc.** { *; }`
> 
> to my Proguard file

omg this worked!!

**Comment by nihar1990** [comment]
Hi All, I added  -keep class org.webrtc.** { *; } in my proguard but it is still not working. It is not working in signed apk otherwise in the normal build it is working. Any idea how to resolve.
