### ISSUE TITLE
Voice disappears when the app is in the background

### ISSUE THREAD

**Issue by Frekansapp** [oney/react-native-webrtc#594]
After a while the connection is disconnecting while the application is in the background. I’m testing on Android how can i prevent disconnect problem. Please check out this discussion  [`React native discourse group`](https://react-native-webrtc.discourse.group/t/app-in-background-sound-disappears/43?u=eren).

#### What have I tried so far
I tried to use react-native-backgroundjob for keep app alive but it’s work only short time period like 5-10 minute. I’m really stuck this point. 

https://github.com/evollu/react-native-fcm/pull/496 1 i use this and it’s show ongoing notification, but still sound disappears after 20 seconds. I installed the react-native-callkeep library and tried to implement the codes according to the example here https://github.com/wazo-pbx/wazo-react-native-demo but did not work. I’m having trouble understanding this structure because it’s not exactly the same with this sample https://github.com/oney/RCTWebRTCDemo

i think android kills the services we call with ThreadUtils.java .

showLocalNotification(notif) {
FCM.presentLocalNotification({
id: new Date().valueOf().toString(), // (optional for instant notification)
title:notif.title, // as FCM payload
body: notif.body, // as FCM payload (required)
show_in_foreground: true ,
ongoing: true

});

}

pc.onaddstream = function (event) {
/…/
RNCallKeep.startCall(this.getCurrentCallId(), null); //Rn callkeep
showLocalNotification(notif)
/…/
}
function leave(socketId)
{
/…/
RNCallKeep.endCall(this.getCurrentCallId());
this.currentCallId = null;
/…/
}

#### Expected behavior
Sound shouldn't disappears when the application gets into the background.

#### Observerd behavior
Sound disappears when the application gets into the background.

#### Steps to reproduce the problem
[Create an app with React-native-webrtc](https://github.com/oney/RCTWebRTCDemo) and
connect some room after connected get the app to the background 

#### Platform information

* **React Native version**:0.58.5
* **Plugin version**:1.69.0
* **OS**:  Android / iOS 
* **OS version**: 6.0.0

**Comment by 8BallBomBom** [comment]
Have you tried using this https://github.com/zxcpoiu/react-native-incall-manager?
Then run the start and stop functions as specified.
We have been using that for a while without issues with Android 4.4.4 all the way up to recent Android versions.

**Comment by Frekansapp** [comment]
> 
> 
> Have you tried using this https://github.com/zxcpoiu/react-native-incall-manager?
> Then run the start and stop functions as specified.
> 
> We have been using that for a while without issues with Android 4.4.4 all the way up to recent Android versions without issues.
> 
> Never really tried adding an ongoing notification but that was on our todo list as we also use https://github.com/invertase/react-native-firebase

yes i am using react-native-incall-manager but still sound disappears after a while. Could you please connect me with the remote desktop and examine my code? I'm going crazy. I tried everything I could.

**Comment by 8BallBomBom** [comment]
Not really a service i can offer.

We use react-native-incall-manager like this for the call initiator.
```
InCallManager.start( {
	media: isVoiceOnly ? 'audio' : 'video',
	ringback: '_BUNDLE_'
} );
```
Then the person being called, once they accept the call they use it like this.
```
InCallManager.start( {
	media: isVoiceOnly ? 'audio' : 'video'
} );
```
isVoiceOnly is just a var set both ends for whether it will be a voice or video+voice call.
Not really sure if that part matters really as i haven't looked.

Are you having this issue just on Android?

**Comment by Frekansapp** [comment]
Yes i am testing on android. I am not tested on ios but if you configure iOS VoIP there is no problem. This is how i am using incall manager. Could you provide an apk from your app for testing.

 pc.onaddstream = function (event) {

    StatusBar.setBackgroundColor('green');
    Vibration.vibrate(150);
    container.setState({ color: true, callingbuttoncolor: '#5cb85c', stopcallingbuttonvisible: true });
    InCallManager.start({ media: 'audio' });

    }

**Comment by 8BallBomBom** [comment]
Can't really provide anything as such as the project is currently private.

What i can say though is we are running the functions a little bit earlier.
When the call is started as in the initial request is sent, not when it is actually connected and when the call is accepted and about to be connected.

The only other thing we have is a custom module on the Android side of things which allows us to acquire wakelocks but we only use that as an extra for incoming calls generated from a real time connection or notification for the call when the app was in the background.

But i can say we have never had this issue even before that was added.

**Comment by redexp** [comment]
Same for android, when app goes to sleep - microphone stop working, but I can hear voice from speaker, trying to downgrade to 1.67.1

**Comment by saghul** [comment]
Downgrading won't help. An ongoing notification should fix that.

I'm going to close this since it's not something we can fix in the plugin.

**Comment by flyinghawker** [comment]
I encountered the same issue when testing with iphone device and xcode simulator. 
Even though with code:
`InCallManager.start({ media: callType });`
Hope someone could help this, because I also see some similar issues posted and many people have this issue.
Thanks.

**Comment by chevonc** [comment]
Same issue here if anyone has suggestions

**Comment by redexp** [comment]
only foreground service fixes this problem for me. Try to install `@voximplant/react-native-foreground-service` and check. Be sure that your gradle is not lower than `3.2.1` (in `android/build.gradle` file)

**Comment by Frekansapp** [comment]
> 
> 
> only foreground service fixes this problem for me. Try to install `@voximplant/react-native-foreground-service` and check. Be sure that your gradle is not lower than `3.2.1` (in `android/build.gradle` file)

Thank you i will try it

**Comment by callmemonky** [comment]
@redexp any idea about the iOS? I am losing audio and connection in iphone. I am connected in the meeting (I implemented that), but audio and video stop transmitting.

**Comment by kkureli** [comment]
any solution ?
