### ISSUE TITLE
[QUESTION] Are Android setup docs up to date?

### ISSUE THREAD

**Issue by renefs** [oney/react-native-webrtc#595]
I'm trying to setup the project using React Native 0.58 to setup a new project, but I am not sure if the documentation to setup an Android project is relevant since many of the libraries used are pretty old.

Should we still use the versions displayed on those docs?

**Comment by saghul** [comment]
You should able to skip sections 5b and 5c.

**Comment by KuanHanrong** [comment]
Getting a bunch of "Program type already present: com.oney.WebRTCModule.BuildConfig" error messages during build.

Just checking if steps 2 and 4 are required?
I noticed that after installing/linking, MainApplication.java already has the
```
import com.oney.WebRTCModule.WebRTCModulePackage;
new WebRTCModulePackage()
```
lines added. And in _android/settings.gradle_

```
include ':react-native-webrtc'
project(':react-native-webrtc').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webrtc/android')
```

**Comment by saghul** [comment]
So you used react-native link? In that case I think you don't need to do that.

**Comment by renefs** [comment]
If you run `react-native link` some other steps are not needed? I can confirm that skipping 5b and 5c sections work fine.

**Comment by saghul** [comment]
@renefs Correct. Do you feel like sending a PR to update the docs?

**Comment by sheshashayan** [comment]
I am getting this issue please help me in resolving the same
ERROR: The modules ['WebRTCModule', 'react-native-webrtc'] point to the same directory in the file system.
Each module must have a unique path

**Comment by eldareini** [comment]
@sheshashayan did you find a solution? I'm having the same error
