### ISSUE TITLE
getUserMedia not firing.

### ISSUE THREAD

**Issue by LukeDeBeneducci** [oney/react-native-webrtc#596]
#### Expected behavior
streamURL should be set when getLocalStream is Called.
#### Observerd behavior
getLocalStream is being called but mediaDevices.enumeratedDevices() and mediaDevices.getUserMedia() are not being called. I made a post on the discourse as well.
<img width="722" alt="screenshot 2019-03-02 at 13 14 36" src="https://user-images.githubusercontent.com/13799285/53698248-e458e100-3dd1-11e9-8a98-37d442f5a43a.png">
<img width="522" alt="screenshot 2019-03-02 at 13 15 32" src="https://user-images.githubusercontent.com/13799285/53698249-e458e100-3dd1-11e9-9498-f8c0649a8856.png">

#### Platform information

* **React Native version**:0.58.5
* **Plugin version**:1.69.0
* **OS**: Android - 4.1.1 - Real Device

**Comment by saghul** [comment]
Please, don't open issues if you already posted on discourse.
