### ISSUE TITLE
How to change Signaling server

### ISSUE THREAD

**Issue by alexrozrio** [oney/react-native-webrtc#60]
Hi Oney the genius, 

We have used your react-native-webrtc and successfully running the app in mobiles.
And we have downloaded the signaling server you have provided (https://github.com/oney/react-native-webrtc-server) and started it successfully. 
Both are working fine.

Now how to integrate our signaling server in the app.
We have tried changing io.connect('http://react-native-webrtc.herokuapp.com', {transports: ['websocket']}); with io.connect('https://ourip:outport', {transports: ['websocket']});
But it is not working. 

Do we need to change anything else.
Do you have any documentation or steps to do that

Thanks in advance.

**Comment by oney** [comment]
Your server is using code from https://github.com/oney/react-native-webrtc-server, right?
Can you check socket connection of the app?
```javascript
var socket = io.connect('http://react-native-webrtc.herokuapp.com', {transports: ['websocket']});
socket.on('connect', (data) => {
  console.log('connect');
});
socket.on('disconnect', (data) => {
  console.log('disconnect');
});
socket.on('reconnect', (data) => {
  console.log('reconnect');
});
socket.on('reconnectAttempt', (data) => {
  console.log('reconnectAttempt');
});
socket.on('error', (data) => {
  console.log('error', data);
});
```
Give some logs to me.
Make sure your https is working.

**Comment by alexrozrio** [comment]
Thank you for your quick response.

Yes i have used the same code. And it is working in https. And i have tested it in browser using my local url (https://10.10.180.88:4443) as well. It is working fine.

And in (Android) App If i use var socket = io.connect('http://react-native-webrtc.herokuapp.com', {transports: ['websocket']}); in my app it is working fine.
But if i change it to var socket = io.connect('https://10.10.180.88:4443', {transports: ['websocket']}); it shows only 'Initializing' with black video screen in the App.

I debug the code and put some logs and i found that in connect method of socket.io.js gives 
'Error: websocket error' in line no 4564

**Comment by oney** [comment]
Please just use
```javascript
var socket = io.connect('https://10.10.180.88:4443');
```

**Comment by alexrozrio** [comment]
Thank you very much for your support.
But if i try like that. It gives different error  `Error: xhr poll error`

And i googled it and seen people are suggesting to set process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; OR rejectUnauthorized: false. But i dont know where to set.
Is that right?
Can you please help me to fix this xhr poll error

**Comment by oney** [comment]
I believe this is about socket.io rather than react-native-webrtc.
Please go https://github.com/oney/react-native-webrtc-server/issues to open new issue, I am pleased to give some helps.
