### ISSUE TITLE
ios client set offer and add stream ,only support 3-way travel

### ISSUE THREAD

**Issue by iamadk** [oney/react-native-webrtc#600]
I made a ios client, ios client send offer and addstream to others,but only support 3-way up travel,but down travel  can support more。If I  send answer,it can support more way.Does anyone know why?

**Comment by iamadk** [comment]
Does anyone know how to make more way to up travel  when send offer.

**Comment by saghul** [comment]
Please ask in our community: https://react-native-webrtc.discourse.group/
