### ISSUE TITLE
Error Can't find variable: Comment

### ISSUE THREAD

**Issue by samuelrvg** [oney/react-native-webrtc#607]
![Screenshot_20190324-231528](https://user-images.githubusercontent.com/14062631/54893354-1e2e7c00-4e94-11e9-9053-e9e54f517463.png)

#### Steps to reproduce the problem

Code:

`import React, { Component } from "react";
import { Platform, StyleSheet } from "react-native";
import {
  RTCPeerConnection,
  RTCIceCandidate,
  RTCSessionDeion,
  RTCView,
  MediaStream,
  MediaStreamTrack,
  mediaDevices
} from "react-native-webrtc";

class Main extends Comment {
  state = {
    videoUrl: "",
    isFront: false
  };

  componentDidMount = () => {
    const configuration = {
      iceServers: [{ url: "stun:stun.l.google.com:19302" }]
    };
    const pc = new RTCPeerConnection(configuration);

    // let isFront = true;
    const {isFront} = this.state;
    mediaDevices.enumerateDevices().then(sourceInfos => {
      console.log("mediaDevices.enumerateDevices", sourceInfos);
      let videoSourceId;
      for (let i = 0; i < sourceInfos.length; i++) {
        const sourceInfo = sourceInfos[i];
        if (
          sourceInfo.kind === "video" &&
          sourceInfo.facing == (isFront ? "front" : "back")
        ) {
          videoSourceId = sourceInfo.id;
        }
      }
      mediaDevices
        .getUserMedia({
          audio: true,
          video:
            Platform.OS === "ios"
              ? false
              : {
                  mandatory: {
                    minWidth: 500, // Provide your own width, height and frame rate here
                    minHeight: 300,
                    minFrameRate: 30
                  },
                  facingMode: isFront ? "user" : "environment",
                  optional: videoSourceId ? [{ sourceId: videoSourceId }] : []
                }
        })
        .then(stream => {
          // Got stream!
          console.log("stream ok");
          this.setState({
            videoUrl: stream.toUrl()
          });
          pc.addStream(stream);
        })
        .catch(error => {
          console.log("error => ", error);
          // Log error
        });
    });

    pc.createOffer().then(desc => {
      pc.setLocalDeion(desc).then(() => {
        // Send pc.localDeion to peer
        console.log("setLocalDeion");
      });
    });

    pc.onicecandidate = event => {
      // send event.candidate to peer
      console.log("onicecandidate");
    };
  };

  render() {
    return (
      <RTCView streamURL={this.state.videoUrl} styles={styles.container} />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ccc"
  }
});

export default Main;
`

#### Platform information

* **React Native version**: 58.0.3
* **Plugin version**:
* **OS**: 
* **OS version**: 
        buildToolsVersion = "28.0.2"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"

**Comment by ruddell** [comment]
`class Main extends Comment {`

Maybe you meant `Component`?  There's nothing in this package called `Comment`

**Comment by zxcpoiu** [comment]
This seems is a typo and not related with this plugin as @ruddell stated.
