### ISSUE TITLE
undefined is not a function (evaluating 'WebRTCModule.mediaStreamTrackGetSources(success)')

### ISSUE THREAD

**Issue by emall2018** [oney/react-native-webrtc#613]
i'am trying to run my react-native project on my motorela e(4) plus android version 7.1.0 but the above error keeps showing
![Capture du 2019-03-27 14-00-20](https://user-images.githubusercontent.com/47556898/55235824-b929ac00-522e-11e9-99f9-0ecff9a82bd7.png)

**Comment by saghul** [comment]
Please check the README, thast function was replaces with `mediaDevices.enumerateDevices`.

**Comment by emall2018** [comment]
i'am using janus server with the react-native-webrtc 
          Janus.listDevices = function(callback) {
              callback = (typeof callback == "function") ? callback : Janus.noop;
              if(navigator.mediaDevices) {
                  getUserMedia({ audio: true, video: true }, function(stream) {
                      navigator.mediaDevices.enumerateDevices().then(function(devices) {
                          Janus.debug(devices);
                          callback(devices);
                          // Get rid of the now useless stream
                          try {
                              stream.stop();
                          } catch(e) {}
                          try {
                              var tracks = stream.getTracks();
                              for(var i in tracks) {
                                  var mst = tracks[i];
                                  if(mst !== null && mst !== undefined)
                                      mst.stop();
                              }
                          } catch(e) {}
                      });
                  }, function(err) {
                      Janus.error(err);
                      callback([]);
                  });
              } else {
                  Janus.warn("navigator.mediaDevices unavailable");
                  callback([]);
              }
I read something about issues in running the lib on some phones .. is it the problem?
