### ISSUE TITLE
PeerConnectionFactory  no implementation found error at runtiime

### ISSUE THREAD

**Issue by saikatdutta1991** [oney/react-native-webrtc#614]
Java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals()

**Comment by saikatdutta1991** [comment]
sorry.. i need your help.. why just closed this issue ?

**Comment by saghul** [comment]
Well, there is an issue template which you chose to ignore. We have it for a reason. Give as many details in advance, for instance how about mentioning what versions of both React Native and react-native-webrtc you are using, and so on. Help us help you.

**Comment by remigijusbalc** [comment]
Hi, I am facing the same issue, this error appears when app loads. RN version - 0.59.2, rn-webrtc version 1.69.0. Setting ndk abi filters and packagingOptions to exclude 64 bit version seems like do the trick, but that means it still doesn't work on 64 bit arch devices yet :/

**Comment by saghul** [comment]
You can update to 1.69.1, it has 64bits support.
