### ISSUE TITLE
cant resolve RCTDeviceEventEmitter

### ISSUE THREAD

**Issue by jcgertig** [oney/react-native-webrtc#7]
uncaught error Error: UnableToResolveError: Unable to resolve module RCTDeviceEventEmitter from /Users/jonathangertig/sidework/stuffwithsteve/peep/node_modules/react-native-webrtc/RTCPeerConnection.js: Invalid directory /Users/node_modules/RCTDeviceEventEmitter

**Comment by jcgertig** [comment]
<img width="847" alt="screen shot 2015-12-12 at 12 36 48 pm" src="https://cloud.githubusercontent.com/assets/455355/11763141/13106cca-a0cd-11e5-8bdd-31131bfd101e.png">

**Comment by jcgertig** [comment]
any ideas @oney

**Comment by oney** [comment]
Just update new version on NPM. Please try to see if it's fixed.

**Comment by jcgertig** [comment]
That did fix it thanks
