### ISSUE TITLE
Has anyone implemented this with simpleWebRTC's Signalmaster?

### ISSUE THREAD

**Issue by Emilios1995** [oney/react-native-webrtc#70]
&yet provides a simple signaling server called [SignalMaster](https://github.com/andyet/signalmaster) 
I''m having trouble making this client work with that server.
Has anyone done it?
Thanks

**Comment by songyen** [comment]
Did you end up figuring this out? If so, could you write what you did?
Thanks

**Comment by oarsoy** [comment]
I'm looking for same thing.
