### ISSUE TITLE
iOS Build Error

### ISSUE THREAD

**Issue by Partysun** [oney/react-native-webrtc#72]
Hi, I try to build sample iOS app and I have got this error message. Android no problem) 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RTCAudioTrack", referenced from:
      l_OBJC_$_CATEGORY_RTCAudioTrack_$_React in libRCTWebRTC.a(WebRTCModule+RTCMediaStream.o)
  "_OBJC_CLASS_$_RTCDataBuffer", referenced from:
      objc-class-ref in libRCTWebRTC.a(WebRTCModule+RTCDataChannel.o)
  "_OBJC_CLASS_$_RTCDataChannel", referenced from:
      l_OBJC_$_CATEGORY_RTCDataChannel_$_React in libRCTWebRTC.a(WebRTCModule+RTCDataChannel.o)
  "_OBJC_CLASS_$_RTCDataChannelInit", referenced from:
      objc-class-ref in libRCTWebRTC.a(RCTConvert+WebRTC.o)
  "_OBJC_CLASS_$_RTCEAGLVideoView", referenced from:
      objc-class-ref in libRCTWebRTC.a(RTCVideoViewManager.o)
  "_OBJC_CLASS_$_RTCICECandidate", referenced from:
      objc-class-ref in libRCTWebRTC.a(WebRTCModule+RTCPeerConnection.o)
  "_OBJC_CLASS_$_RTCICEServer", referenced from:
      objc-class-ref in libRCTWebRTC.a(WebRTCModule+RTCPeerConnection.o)
  "_OBJC_CLASS_$_RTCMediaConstraints", referenced from:
      objc-class-ref in libRCTWebRTC.a(WebRTCModule+RTCPeerConnection.o)
      objc-class-ref in libRCTWebRTC.a(WebRTCModule+RTCMediaStream.o)
  "_OBJC_CLASS_$_RTCMediaStream", referenced from:
      l_OBJC_$_CATEGORY_RTCMediaStream_$_React in libRCTWebRTC.a(WebRTCModule+RTCMediaStream.o)
  "_OBJC_CLASS_$_RTCPair", referenced from:
      objc-class-ref in libRCTWebRTC.a(WebRTCModule+RTCPeerConnection.o)
  "_OBJC_CLASS_$_RTCPeerConnection", referenced from:
      l_OBJC_$_CATEGORY_RTCPeerConnection_$_React in libRCTWebRTC.a(WebRTCModule+RTCPeerConnection.o)
      l_OBJC_$_CATEGORY_RTCPeerConnection_$_Block in libRCTWebRTC.a(RTCPeerConnection+Block.o)
     (maybe you meant: _OBJC_CLASS_$_RTCPeerConnectionDelegator)
  "_OBJC_CLASS_$_RTCPeerConnectionFactory", referenced from:
      objc-class-ref in libRCTWebRTC.a(WebRTCModule.o)
  "_OBJC_CLASS_$_RTCSessionDescription", referenced from:
      objc-class-ref in libRCTWebRTC.a(WebRTCModule+RTCPeerConnection.o)
  "_OBJC_CLASS_$_RTCVideoCapturer", referenced from:
      objc-class-ref in libRCTWebRTC.a(WebRTCModule+RTCMediaStream.o)
  "_OBJC_CLASS_$_RTCVideoTrack", referenced from:
      l_OBJC_$_CATEGORY_RTCVideoTrack_$_React in libRCTWebRTC.a(WebRTCModule+RTCMediaStream.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zxcpoiu** [comment]
when you are importing files into your xcode, make sure you choose the same options described at:

https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md

**Comment by Partysun** [comment]
Op, Yeah. I did\nt open options. It works great. Thank you, for your work.

**Comment by m59peacemaker** [comment]
@zxcpoiu I tried updating and got this error. Installing the version I had before 0.6.2 is doing this as well. Is the documentation definitely right? I followed it perfectly. I've checked and tried again multiple times.

**Comment by m59peacemaker** [comment]
I got it to build, but I'm not sure how. I did roughly the same things I have been doing. I think it has something to do with removing libRCTWebRTC.a and adding it back in the right order with adding the webrtc libraries.

**Comment by zxcpoiu** [comment]
Hmm... when I encounter similar problems, I would try:

1. unlink all webrtc library on xcode
2. delete all `react-native-webrtc` folder in `node_module`
3. fellow instructions to get webrtc lib via npm install and git lfs
4. a `Product` -> `Clean` in xcode may help.

**Comment by ignivahermenpreet** [comment]
When i tried to run in simulator it shown me error. In device it is working fine. How i can handle it

**Comment by RevanScript** [comment]
The same issue here. I ran `pod install` and got this error now
