### ISSUE TITLE
WebRTC library version 

### ISSUE THREAD

**Issue by zxcpoiu** [oney/react-native-webrtc#79]
**Last Update: 2016-09-10 +0**

**This thread is for discussion about upgrade/maintain webrtc version**

The webrtc library of this repository is based on [webrtc-build-script](https://github.com/pristineio/webrtc-build-scripts) opensourced and maintained by [pristine](http://tech.pristine.io/) and it seems pristine is no longer maintain the [auto-build](http://tech.pristine.io/automated-webrtc-building/) but [webrtc-build-script](https://github.com/pristineio/webrtc-build-scripts)
## WebRTC Library git revision build Info

**webRTC git branch mapping revision:**

[wertc git repo](https://chromium.googlesource.com/external/webrtc)
[chrome release history wiki](https://en.wikipedia.org/wiki/Google_Chrome_release_history)

45 -> #9565
46 -> #9745
47 -> #10155
48 -> #10622
49 -> #11252
50 -> #11765
51 -> #12279
52 -> #12798
53 -> #13317 ( Stable )
54 -> #13869 ( Beta )
## Latest pre-build binary from pristine

The version of webrtc we use in this repository currently is likely between chrome 47-rc and 47-stable.  

**ANDROID:**

```
webRTC svn version: 11139
GIT COMMIT: 0c7e9f540b282d60b94081f601a1694054d8646e
maven: http://mvnrepository.com/artifact/io.pristine/libjingle
download: https://repo1.maven.org/maven2/io/pristine/libjingle/
```

**IOS:**

```
webRTC svn version: 11177
GIT COMMIT: 893505d0fb41a840be5e4a44a1250dba83d79bf5
cocoapods: https://cocoapods.org/pods/libjingle_peerconnection/
cocoapos: https://github.com/CocoaPods/Specs/blob/master/Specs/libjingle_peerconnection/
download: https://s3.amazonaws.com/libjingle/11177/Release/0/libWebRTC.tar.bz2
```

**Comment by zxcpoiu** [comment]
**Side Note:**

iOS will generate crash report such as

```
Exception Type:  EXC_RESOURCE
Exception Subtype: WAKEUPS
Exception Message: (Limit 150/sec) Observed 202/sec over 300 secs
Exception Note:  NON-FATAL CONDITION (this is NOT a crash)
```

it will be treated as a crash on iOS8 and be treated as a warning on iOS9

see:
https://bugs.chromium.org/p/webrtc/issues/detail?id=4212

fix at webrtc revision 12186:
https://chromium.googlesource.com/external/webrtc.git/+/89717aad5099d7cf5ff55dd5eace6df6651de3c7

**Comment by zxcpoiu** [comment]
has anyone successfully build latest stable version of webrtc on android or ios?

**Comment by bryaneaton13** [comment]
We've got a pretty recent build working on a RN app. It's in a PR on a fork by @lyubomir https://github.com/lyubomir/react-native-webrtc/pull/1 (version 12832)
We didn't update Android (having some other issues on Android where it's super slow, even on the demo app), just the iOS build.

**Comment by zxcpoiu** [comment]
@bryaneaton13 

cool, thanks for share!

It would be great if we build and test webrtc along with every stable version.

I was trying to build by myself using webrtc-build-script but without lucks :(
I'll keep studying.

by the way, about android, are you own a maven repo or just put actual `aar` file into this repo directly?

**Comment by tiensonqin** [comment]
@zxcpoiu @bryaneaton13 I've upgraded to version 12832, but still hit the `EXC_RESOURCE` problem,
only tested in iphone 5s.

**Comment by zxcpoiu** [comment]
thanks for the information, although it's a bad news :disappointed: 
I will do some experiments with latest versions and those compile stuffs soon.

**Comment by zxcpoiu** [comment]
folks, I created a branch `upgrade-webrtc-51` which upgraded webrtc core library to correspond release version 51 branch.

I only tested simple audio part and it looks fine without any slow problems on android.

Since I don't have enough time to test whole stuffs like video or data channel yet, I wish someone whi have problems on the old library can git it a try to see if it solves your problem or makes PR to that branch.

once the branch have been fully tested, we can merge it into the master branch.

cheers

**Comment by zxcpoiu** [comment]
51 branch revision is 12700 btw

**Comment by zxcpoiu** [comment]
52 branch revision is 13039

**Comment by zxcpoiu** [comment]
about library control here goes 2 ways:

1. maintained in this repository
  * store library in github large file, and upload by ourself.
  * use latest stable release build in master along with debug build branch

2. maintained in CocoaPods and Maven
  it's like what [pristineio](https://github.com/pristineio/webrtc-build-scripts) does it.
  but currently, it seems no longer be maintained 

option 2 is more agile and convenient, but at this stage I prefer option 1.


because using `maven` with `aar` files are fine in `react-native android`, just a few line changes in `build.gradle`. But if you goes with `CocoaPods`, I'm not sure, you would force users to change xcode structure for it.

I guess that's the reason that @oney use `aar` files on `android` but including library into repository on `ios` at the beginning.

option 2 still needs someone to create repo on `CocoaPods`/`Maven` and maintain/compile/upload it.

Does anyone know is there anyway to use CocoaPods without change xcode project?
said, would you use `react-native init` with `pod install react-native-webrtc` with out change your xcode project structure?
or they can exist at the same time by just adding pod files?

I totally have no ideas with xcode environment :disappointed: 
@jeremyong any thoughts?

**Comment by jeremyong** [comment]
Personally, I think for using native code with react-native on ios anyways, cocoa pods is the way to go. The install instructions here of manually linking a library and changing link directory paths is honestly just as complicated as integrating cocoapods with xcode, and most serious react native projects would likely already have done this. It also makes updating this repository potentially easier. You can migrate plugin versions independently of webrtc itself. Also, to update the library version, instead of building, manually extracting the library here, pushing a new branch and committing, one could just update the cocoa pod. If the ios cocoa pod for libjingle_peerconnection really isn't maintained, I'm sure the original maintainers of the build scripts would be interested in having it up to date.

My two cents.

**Comment by zxcpoiu** [comment]
I totally agree with you that using pod is easier to install than manually link it on library such as this.
The only problem I guess in this moment is, we can not find a maintained neither on `cocoapods` nor `maven`.

as noted in first comment, the maintainer of `libjingle-peerconnection` on both `cocoapods` and `maven` is the same team of `webrtc-build-script`, and both stop updated version roughly at 11139~11177 since Jan, 2016.

**to get things work, it would be:**

1. find the hosting repo ( both `cocoapods` and `maven` ) :
    * ask them for update.
    * create another one maintained by ourselves. ( is it necessary? )

2. compile native library into `pod`/`aar` format
3. provide documents for how to apply it.

obviously, we all have our own full time shits to do,
would you mind take care `cocoapods` part and I would dealing with android aar?

or someone has interest in it?

I would happy to see it happens :smile:

**Comment by zxcpoiu** [comment]
could we make PR on `cocoapods` or `maven` like we did on github?

**Comment by inspiraluna** [comment]
I am not (yet) working on ReactNative at the moment, but would need an updated libjingle on cocopod or anywhere else too! Since I think the cocopod version from January has  a bug with IPv6. [issue 5871](https://bugs.chromium.org/p/webrtc/issues/detail?id=5871 )
I don't know the current status of that problem, but need to investigate it now.  

I just know, I can(!) connect iOS to any browser or android (using stun/turn) if they are in the same network or the calling network supports "Reflexive connectivity" (Test at http://test.webrtc.org)  

I can't (!) cannot iOS with any browser or android as soon as the network-router (e.g. café) does not show a working "reflexive connectivity". The problem, as I understood it, is that the whole procedure of discovering candidates fails because of a IPv6 bug in the webrtc lib.

**Comment by zxcpoiu** [comment]
@inspiraluna 
sorry but I don't understand.
Do you mean that you are going to create `CocoaPod` repo ?

btw, you can get latest 53 branch library from master.

**Comment by inspiraluna** [comment]
nope. I don't plan it. Thanks! I will check the libjingle from you guys!

**Comment by zxcpoiu** [comment]
cool, hope it works for you

**Comment by ianholing** [comment]
@inspiraluna I have exactly the same issue you talked about.. And I am stuck here trying to switch that library with updates with no luck, How did you solve it? I need to get it working

**Comment by inspiraluna** [comment]
Hey, I finally moved to a new pod! https://cocoapods.org/pods/WebRTC <https://cocoapods.org/pods/WebRTC> which seems pretty cool.
But beware the pod uses the latest WebRTC lib from google, it caused me a complete weekend and a bit more to rewrite the whole client!

To make it a bit quicker for you you can check for code snips here: https://github.com/inspiraluna/AppRTC-iOS <https://github.com/inspiraluna/AppRTC-iOS>

The interesting part is, to test it from networks without proper reflexive connectivity. https://test.webrtc.org/ <https://test.webrtc.org/>  (check here!)
e.g. some company networks don’t support stun or even some cafés. many home router support stun. (reflexive connectivity)

Some claim they could establish connections from networks without the reflexive connectivity with Android. But I can’t confirm that.

https://test.webrtc.org/ <https://test.webrtc.org/>

Kind Regards,

Nico

**Comment by inspiraluna** [comment]
Sorry again to make it more clear. Some networks don’t support stun, if thats the case works everything should or must work over turn. so you need a TURN server. please test both environments. TURN in my case is a bit slower in performance wich is natural. but still seems as fluent as in android. (at least it seems like that in most of the cases) I do not have any worries as long as reflexive connectivity works. Please check environments with turn only possibilities on ALL peers (not just on one)!

Let me know!

N.

**Comment by saghul** [comment]
Closing since it looks like this no longer applies. Feel free to reopen if I'm wrong @zxcpoiu.
