### ISSUE TITLE
RTCDataChannel example?

### ISSUE THREAD

**Issue by chadobado** [oney/react-native-webrtc#8]
Learning a lot from this library, really helpful.  Thank you for writing it.

I'd like to send non-video/audio data across the peer connection as described [on the bottom of the RTCPeerConnection docs here] (https://developer.mozilla.org/zh-TW/docs/Web/API/RTCPeerConnection).

For example:

```javascript
var pc = new PeerConnection();
var channel = pc.createDataChannel("Mydata");
channel.onopen = function(event) {
  channel.send('sending a message');
}
channel.onmessage = function(event) { console.log(event.data); }
```

I see some ```didOpenDataChannel``` stubbed out in WebRTCModule+RTCPeerConnection.m and references to dataChannel elsewhere.. any advice where to focus/how to implement this?

Thank you in advance

**Comment by oney** [comment]
This module hasn't supported RTCDataChannel yet.
On iOS, I use this pod https://cocoapods.org/pods/libjingle_peerconnection to do it.
Do you want to help implement bridge of iOS and React Native?

**Comment by chadobado** [comment]
Thanks for getting back to me @oney.

Was excited to figure it out but after taking a look at libjingle, it looks over my head. 

Although the dataChannel looks like the right way to do it - considering you're already using socket.io, would it be easier/possible to just broadcast events between peers?  

My use case is fairly simple, just want all peers in a room to receive data emitted from any other peer in that room (such as a simple TouchableHighlight onPress event).  

Thanks again for the help.

**Comment by oney** [comment]
Yes, if you want to do text chatting feature, using socket.io would be easier.

**Comment by chadobado** [comment]
Thanks for the feedback @oney

**Comment by pbojinov** [comment]
@chadobado Looks like the PR for RTCDataChannel was just [merged](https://github.com/oney/react-native-webrtc/pull/52) and [added to the demo app](https://github.com/oney/RCTWebRTCDemo/commit/81914b3f694018337ae3a1bf2f4987b4741105d1)

**Comment by chadobado** [comment]
Awesome thanks for tagging me @pbojinov - looking forward to trying it out.
