### ISSUE TITLE
Camera switching or Orientation Changes not working on android (Galaxy S6)

### ISSUE THREAD

**Issue by faireroquen** [oney/react-native-webrtc#80]
Just discover this great project :+1: 
But i tried the demo app project and when i change the orientation of my phone , the RtcView freeze.
And when i try to switch camera RtcView turn black.

Nothing particular on Debug Console.
Logcat is too verbose , don't know where find meaningful information

**Comment by zxcpoiu** [comment]
android will destroy and recreate views when orientation occurs.
my guess is we should listen to some events and change props of `RTCView`, resume media source accordingly after orientation.
 
If  you got any solution, please submit a PR.

about logcat, you can use:
`adb logcat *:E ReactNative:V ReactNativeJS:V com.oney.WebRTCModule.WebRTCModule:V`
to filter out only logs generate from react-native and webrtc module plus system errors.

**Comment by zxcpoiu** [comment]
merged into #89
