### ISSUE TITLE
TURN & STUN servers

### ISSUE THREAD

**Issue by Partysun** [oney/react-native-webrtc#82]
How to setup config for turn server?

In example we have one public ice server.
`var configuration = {"iceServers": [{"url": "stun:stun.l.google.com:19302"}]};`

If I try to add in this array several turn servers, I get the error on Android.
```
couldn\t find key iceServers in dynamic object
getArray
ReadableNativeMap.java: -2
```
It works on iOS, but I don't know it works or doesn't.

**Comment by brikendr** [comment]
@Partysun  how did you fix it ? I am having the same problem here :/.
