### ISSUE TITLE
Build ipa failed

### ISSUE THREAD

**Issue by Partysun** [oney/react-native-webrtc#83]
When I try to build ipa file, I get the next message from xcode

> libWebRTC.a(libjingle_peerconnection_objc.RTCICECandidate.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

In simulator's build everything is ok.

**Comment by zxcpoiu** [comment]
Is it related to step 6 in following instructions?

https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md

**Comment by Partysun** [comment]
> Dead Code Stripping to No and Enable Bitcode to No.

Yeah. It works. Thank you.

**Comment by ua24** [comment]
sorry somebody changed instructions provided by this link there is no step 6 now @Partysun  can help?

**Comment by Partysun** [comment]
Current version of instruction works. Do you have any problem?

**Comment by zxcpoiu** [comment]
@ua24 

it's now step 4-(5)

**Comment by GuleriaAshish** [comment]
I am facing the same issue. Please suggest what to do.
Reactnative: 0.63.2
WebRTC: 1.84.0
