### ISSUE TITLE
New NPM release and Question about Speaker vs Headphones

### ISSUE THREAD

**Issue by dguillamot** [oney/react-native-webrtc#84]
Hello, would it be possible to have a new release pushed to NPM this week?

Also, I've noticed that if headphones/earphones are plugged into an IOS device, ~50% of the time audio will go to the headphone correctly, but 50% of the time it will come out on speaker - even with the headphones plugged in. I notice that RTCSetting has also been removed in the last couple of days. 

1) How can we control speaker vs earphones setting without RTCSetting and

2) Has the issue with audio coming out on speaker instead of earphones been resolved?

Thank you,

**Comment by zxcpoiu** [comment]
@dguillamot 

audio routing is yet another complex stuff to handle and not totally related to webrtc itself.
so we move those into a separate but working closely project called [react-native-incall-manager](https://github.com/zxcpoiu/react-native-incall-manager) 

you can try it out and track issues there.

**Comment by oney** [comment]
Just release 0.8.0

**Comment by reformer** [comment]
Is this issue resolved? After removing RTCSetting, its hard to swapping sound route by headphone and speaker. 😞

**Comment by zxcpoiu** [comment]
nope, see [here](https://github.com/oney/react-native-webrtc/issues/125#issuecomment-249577200)

**Comment by davidperrenoud** [comment]
To fix your app crashing when connecting headphone, add the following:
```javascript
InCallManager.start({
  media: 'video',
  auto: true,
});
```

**Comment by seb0zz** [comment]
@davidperrenoud passing `auto:true` doesn't fix the crash for me :-(
