### ISSUE TITLE
'onicecandidate' not fired on ICE gathering completion

### ISSUE THREAD

**Issue by maxhawkins** [oney/react-native-webrtc#87]
According to the spec, `onicecandidate` should be fired with `newCandidate == null` when the ICE gathering process is done. Currently, `onicecandidate` is not fired when gathering is completed.

https://w3c.github.io/webrtc-pc/#h-operation
```
When a new ICE candidate is available or when the ICE gathering process is done , the user agent must queue a task to run the following steps:
 (...)
3. If the gathering process is done: Update connection's ICE gathering state to completed and let newCandidate be null.
4. Fire an event named icecandidate with newCandidate at connection.
```

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onicecandidate
```
If the event's candidate property is null, ICE gathering has finished.
```

**Comment by zxcpoiu** [comment]
agreed
