### ISSUE TITLE
Orientation releated issue in Android and IOS

### ISSUE THREAD

**Issue by alexrozrio** [oney/react-native-webrtc#89]
Hi,
The example app is working well in both the devices.

Now we have made some UI changes.
We have used navigator to make it as a 2 page app.
First page will ask the room id and in the second page the actual videos will load.
It is working fine if we are not changing the orientation.

But while we are in call (after connected with remote video), if we change the orientation (by rotating the mobile), In Android it moves to the first page and we can not able to see the video. And in IOS video is getting stretched. 

Can you please help us to fix this issue?
Do you have any idea to fix this issue?

Regards,
Alex.

**Comment by zxcpoiu** [comment]
android will destroy and recreate views when orientation occurs.

my guess is we should listen to some events and change props of RTCView, resume media source accordingly after orientation.

this library doesn't support orientation handling yet.

help wanted

**Comment by sbaar** [comment]
Does anyone know of a way to constrain ios to portrait only or landscape only at least? So that when you rotate the phone the video and rtcview does not start capturing in landscape? it doesn't seem like this is a well defined behavior as far as web rtc goes.

**Comment by saghul** [comment]
@sbaar I haven't tried it yet, but I was planning on using https://github.com/yamill/react-native-orientation

**Comment by sbaar** [comment]
@saghul Forgive me if I'm mistaken, but that would affect the entirety of the app. What I'm dealing with is that even when my app is always set as portrait only the rtcview or perhaps the backing renderer changes the orientation of the camera when the iphone is rotated while the rest of the ui stays the same. I just want it to respect the app's orientation, but so far it looks like i'd need access to the avcaptureconnection or the render layer to enforce this, which the webrtc lib does not expose. I should probably just make this a separate issue.

**Comment by saghul** [comment]
Closing since there is nothing we can do in this plugin for the original report.
