### ISSUE TITLE
Have you planned to give any support for codec ?

### ISSUE THREAD

**Issue by RD1991** [oney/react-native-webrtc#93]
Hi Oney,
This is very exciting library for react native , and easy to install. 
I was able to use this pretty easily, just wanted to give my thoughts or ask you if you are going to support codec in future releases ? 

This question appears because when I tried the library over 2G/3G there was NOT as expected support.  Need to have good feasibility of network. 

Regards,
RD.

**Comment by zxcpoiu** [comment]
codecs are included in webrtc native library itself at compile time.
we can track this issue in #79.

once we came out a way to handle those version issue, then we can discuss about what codecs should we included in this repo. ( to have a balance between library size and compatibility )

**FYI, codecs I saw on android currently are:**

a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:127 red/8000
a=rtpmap:126 telephone-event/8000
