### ISSUE TITLE
Error while updating property 'streamURL' of a view managed by:RTCVideoView

### ISSUE THREAD

**Issue by llgoer** [oney/react-native-webrtc#94]
I check out the sample:https://github.com/oney/RCTWebRTCDemo.git ,and run in android system.
But in my mobile phone,it shows:Error while updating property 'streamURL' of a view managed by:RTCVideoView.
![c6e9aa6d70496f4710ac078db9be2bd3](https://cloud.githubusercontent.com/assets/1004110/16185406/2412cf08-36f6-11e6-9be9-7ac22d4ec434.jpg)

**Comment by alexlbr** [comment]
Same problem. Though I had to update this file "android/gradle/wrapper/gradle-wrapper.properties" due the following error:
Error:(1, 1) A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Gradle version 2.10 is required. Current version is 2.4. If using the gradle wrapper, try editing the distributionUrl i RCTWebRTCDemo/android/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip

Once I add gradle-2.10-all.zip the app builds, but it just works for a second and then I get the error "Error while updating property 'streamURL' of a view managed by:RTCVideoView"
<img width="269" alt="webrtc1" src="https://cloud.githubusercontent.com/assets/1273037/16356415/ac8dba38-3ace-11e6-8743-c7a76a81cae2.png">
<img width="372" alt="webrtc2" src="https://cloud.githubusercontent.com/assets/1273037/16356416/b0699e6a-3ace-11e6-80ca-dadca459257d.png">

**Comment by myrace31** [comment]
I used latest demo , still facing above screen when enter room Id and click on Enter room button.

Please help me to solve out this issue.

Thanks

**Comment by mjsisley** [comment]
I have the same problem on Android 4.2 (Andy OS Emulator) with the latest demo. Works great on iOS.

**Comment by atyenoria** [comment]
Same problem on Android 5.0.2. iOS is good.

**Comment by anhtuank7c** [comment]
Same problem to me.

**Comment by anhtuank7c** [comment]
Here is my own guide: [https://youtu.be/1Bm6qoYp8qQ](https://youtu.be/1Bm6qoYp8qQ)
Not to resolve this issue, the issue does not happen when you all test on real devices

**Comment by saghul** [comment]
Lots has changed since the original report. Tentatively closing, please reopen if you see this again.
