### ISSUE TITLE
Image sending

### ISSUE THREAD

**Issue by mobileDevNativeCross** [oney/react-native-webrtc#98]
Does this lib supports Image,audio,docs sending?
Could you advise how to do this?

**Comment by mavenave** [comment]
The best way to send an image is by sending data through the RTCDataChannel then displaying the image by converting it to a base64 uri

**Comment by oney** [comment]
[react-native-fs](https://github.com/johanneslumpe/react-native-fs) is a awesome project.
You can use `readFile(filepath: string, encoding?: string)` to encode any file(image, audio, docs) to string, then use `writeFile(filepath: string, contents: string, encoding?: string, options?: WriteFileOptions)` to write strings into the file.
I never try this. If you accomplish it, please share the codes. It will be very useful.

**Comment by mobileDevNativeCross** [comment]
yep. Thanks.
I will do this.

**Comment by snsekar** [comment]
@oney I am trying this. However i am not able to send more than 20kb(approx). If i send more than 20kb receiver simply not receiving anything. Can you please advise is there any data size limits?
