### ISSUE TITLE
Recording the call

### ISSUE THREAD

**Issue by bcalik** [oney/react-native-webrtc#99]
Is it possible to record and save the streamed video call?
Thank you.

**Comment by zxcpoiu** [comment]
there is a [MediaStream Recording](https://w3c.github.io/mediacapture-record/MediaRecorder.html) draft API Spec.

But I think there is a long way to go to support it.

**Comment by alongubkin** [comment]
I implemented recording for react-native-webrtc by patching Google's webrtc library to write all PCM frames to external buffers, and then encode them using [LAME](http://lame.sourceforge.net/) to mp3 files on the SD card. 

This is a pretty quick n' dirty solution, but it works great in both Android and iOS - the quality is high and the final mp3 file size is small. 

Is there any interest in this? I can maybe open source, but TBH I'm not really sure how to, since it contains some patches to the core WebRTC library.

**Comment by zxcpoiu** [comment]
sounds interesting!

but maybe it is not a good idea to included into this library by default.
maybe till we have regular builds and more control on webRTC library (#74)
we can include it as a branch along with every version of master.

is your modifications all written in c++?

maybe you can open source it as a patch file into your own repo and specified a corresponds webRTC version?

**Comment by alongubkin** [comment]
All my modifications were Java and Objective C. 

About the patched repo - Sounds like the best solution atm

**Comment by zxcpoiu** [comment]
so your modifications needs patched at compile time, right?

If this is the case, maybe you can try to rewrite it to patch codes in this module instead patch webRTC core library directly, therefore, we can create a branch for that and keep the API correspond to spec as possible. Some folks might be interesting in improves it to fit the spec.

**Comment by dariocravero** [comment]
@zxcpoiu have you already gotten around open sourcing that somewhere? It would be amazing to try it out! Thanks :)

**Comment by zxcpoiu** [comment]
@dariocravero
Oh, the implementation's credit belongs to @alongubkin , not mine.
maybe you can contact with him to see if and how it can be open sourced/patched.
it would be awesome for sure :smile:

**Comment by dariocravero** [comment]
Thanks @zxcpoiu, read it too fast :P. @alongubkin, what are your thoughts on that? would it be possible to check it out somewhere? thanks! :)

**Comment by Partysun** [comment]
@alongubkin 👍  for share your recording patch.

**Comment by rohitgupta87410** [comment]
@alongubkin  please share your recording patch.

**Comment by sagivo** [comment]
+1 for recording

**Comment by minhtc** [comment]
any update for webrtc recording?

**Comment by juanpiterson** [comment]
any update for webrtc recording?

**Comment by SaniokUA** [comment]
any update for webrtc recording?

**Comment by zxcpoiu** [comment]
AFAIK, no one has a plan to implement recording feature anytime soon.
Feel free to send a PR if you familiar with it :+1:

**Comment by ztl8702** [comment]
I am new to this discussion and just want to share a few thoughts:

Are we talking about recording the entire call (all participants)? What if I only want to record the _local_ audio? Will that be easier to achieve?

I was looking at [`org.webrtc.audio.AudioDeviceModule.SamplesReadyCallback`](https://webrtc.googlesource.com/src/+/master/sdk/android/api/org/webrtc/audio/AudioDeviceModule.java#86).  It seems to allow getting the raw audio bytes?
  
It is also used in one of the sample apps to save audio to files: https://webrtc.googlesource.com/src/+/master/examples/androidapp/src/org/appspot/apprtc/RecordedAudioToFileController.java

Alternatively, can we instead record audio using [react-native-audio](https://github.com/jsierles/react-native-audio)? Seems a dirty hack, but would it work? Need to test it out.

**Comment by sagivo** [comment]
@ztl8702 i would love to see if you have an update on it.

**Comment by gut4** [comment]
I think we need to investigate recording on js side via https://github.com/muaz-khan/RecordRTC

**Comment by saghul** [comment]
I'm closing this. This has been open for 2 years and nobody has written a patch. If anyone wants to take a stab at this, please open a PR and let's continue the discussion there.
